"""Build Grade 5 Geometry map JSON from a single source of truth.

Run: python3 scripts/_build_grade5_geometry.py

Pedagogical spine (课标/人教脉络风格，自撰短描述，非教材页原文):
  多边形面积（平行四边形、三角形、梯形复习与组合、不规则估面积）
  → 圆的认识、周长与面积
  → 轴对称、旋转、平移深入。
扇形初步与观察物体还原为软锁支线。
圆放在五年级本图（人教常见在六年级上；按本仓库几何线规划前移），六年级图做圆柱圆锥等收束。
本图自洽，不引用低年级或数与运算节点 id。
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _geo_common import (
    MASTERY_CONCEPT,
    MASTERY_GATE,
    ROOT,
    SOFT,
    node as _node,
    quest,
    write_map,
)

OUT = ROOT / "maps" / "primary-math" / "grade-5-geometry"
G = 5


def node(nid, title, difficulty, prereqs, tags, description, *, unlock=None, mastery=None):
    return _node(
        nid, title, G, difficulty, prereqs, tags, description, unlock=unlock, mastery=mastery
    )


NODES = [
    node(
        "pm-g5-geo-n001",
        "面积从转化来",
        1,
        [],
        ["area", "ch-poly"],
        "能说出：不会算的图形，常常先割补、拼成已经会算的图形，面积在转化前后不变。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-geo-n002",
        "平行四边形面积再练",
        2,
        ["pm-g5-geo-n001"],
        ["area", "ch-poly", "parallelogram"],
        "能熟练用底×高求平行四边形面积，并在图中排除斜边干扰，标出垂直的高。",
    ),
    node(
        "pm-g5-geo-n003",
        "三角形面积再练",
        2,
        ["pm-g5-geo-n002"],
        ["area", "ch-poly", "triangle"],
        "能熟练用底×高÷2 求三角形面积，同一三角形可以选不同的底和高配对。",
    ),
    node(
        "pm-g5-geo-n004",
        "梯形面积",
        3,
        ["pm-g5-geo-n003"],
        ["area", "ch-poly", "trapezoid"],
        "能用（上底+下底）×高÷2 求梯形面积，并说明公式来自转化成平行四边形。",
    ),
    node(
        "pm-g5-geo-n005",
        "等底等高的面积",
        3,
        ["pm-g5-geo-n004"],
        ["area", "ch-poly", "equal-base"],
        "能判断等底等高的三角形或平行四边形面积相等，并用来比较组合图中的块。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-geo-n006",
        "组合图形面积",
        4,
        ["pm-g5-geo-n005"],
        ["area", "ch-poly", "composite"],
        "能把多边形组合图形分割或补形，用加减求出面积。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g5-geo-n007",
        "不规则图形估面积",
        3,
        ["pm-g5-geo-n006"],
        ["area", "ch-poly", "estimate"],
        "能在方格纸上用数格（满格、半格）估计树叶、脚印等不规则图形的面积。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-geo-n008",
        "多边形面积综合",
        4,
        ["pm-g5-geo-n007"],
        ["area", "ch-poly", "boss-gate"],
        "能选择合适公式或割补策略，完成多边形面积章节收束检查。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g5-geo-n009",
        "圆的初步认识",
        2,
        ["pm-g5-geo-n001"],
        ["circle", "ch-circle"],
        "能辨认圆，知道圆是平面图形，周围是一条封闭的曲线。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-geo-n010",
        "圆心半径直径",
        2,
        ["pm-g5-geo-n009"],
        ["circle", "ch-circle", "parts"],
        "能指出圆心、半径、直径：半径连圆心与圆上一点，直径过圆心且两端在圆上。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-geo-n011",
        "半径与直径关系",
        2,
        ["pm-g5-geo-n010"],
        ["circle", "ch-circle", "parts"],
        "知道同一圆中直径是半径的 2 倍，所有半径相等、所有直径相等。",
    ),
    node(
        "pm-g5-geo-n012",
        "圆的对称",
        3,
        ["pm-g5-geo-n011"],
        ["circle", "ch-circle", "symmetry"],
        "能说明圆是轴对称图形，任意一条直径所在直线都是对称轴；也具有旋转对称的直观。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-geo-n013",
        "用圆规画圆",
        2,
        ["pm-g5-geo-n011"],
        ["circle", "ch-circle", "draw"],
        "能用圆规按指定半径或直径画圆，并标出圆心。",
    ),
    node(
        "pm-g5-geo-n014",
        "周长与直径",
        3,
        ["pm-g5-geo-n013"],
        ["circle", "ch-circle", "circumference"],
        "能通过滚动或绳子测量，感受圆的周长大约是直径的三倍多一点。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-geo-n015",
        "圆周率π",
        3,
        ["pm-g5-geo-n014"],
        ["circle", "ch-circle", "pi"],
        "知道圆周率 π 表示周长与直径的比值，计算时常用 3.14，它是一个无限不循环小数。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-geo-n016",
        "圆周长公式",
        3,
        ["pm-g5-geo-n015"],
        ["circle", "ch-circle", "circumference"],
        "能用 C = πd 或 C = 2πr 求圆周长，并说明两个公式其实是一回事。",
    ),
    node(
        "pm-g5-geo-n017",
        "圆面积的转化",
        4,
        ["pm-g5-geo-n016", "pm-g5-geo-n008"],
        ["circle", "ch-circle", "area"],
        "能把圆等分成若干扇形拼成近似长方形，直观理解圆面积公式从哪来。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-geo-n018",
        "圆面积公式",
        4,
        ["pm-g5-geo-n017"],
        ["circle", "ch-circle", "area"],
        "能用 S = πr² 求圆面积，已知直径时先求出半径再代入。",
    ),
    node(
        "pm-g5-geo-n019",
        "圆环的面积",
        4,
        ["pm-g5-geo-n018"],
        ["circle", "ch-circle", "ring"],
        "能用两个圆的面积相减求圆环面积，注意两个半径不要用错。",
    ),
    node(
        "pm-g5-geo-n020",
        "圆的实际问题",
        4,
        ["pm-g5-geo-n019"],
        ["circle", "ch-circle", "application"],
        "能解决车轮滚一圈、圆形花坛周长或面积、环形跑道等短故事，先判断问周长还是面积。",
    ),
    node(
        "pm-g5-geo-n021",
        "圆的周长面积综合",
        4,
        ["pm-g5-geo-n020"],
        ["circle", "ch-circle", "boss-gate"],
        "能综合半径直径、周长面积公式和圆环，完成圆的章节收束检查。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g5-geo-n022",
        "轴对称的性质",
        3,
        ["pm-g5-geo-n012"],
        ["motion", "ch-motion", "symmetry"],
        "能说明对应点到对称轴距离相等、连线被对称轴垂直平分，并用来检查作图。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-geo-n023",
        "画轴对称图形",
        3,
        ["pm-g5-geo-n022"],
        ["motion", "ch-motion", "symmetry"],
        "能在方格纸上画出较复杂图形（如五边形、简单图案）关于给定直线的轴对称图形。",
    ),
    node(
        "pm-g5-geo-n024",
        "旋转的性质",
        3,
        ["pm-g5-geo-n022"],
        ["motion", "ch-motion", "rotation"],
        "能说明旋转时对应点到旋转中心距离相等、旋转角相同，形状大小不变。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-geo-n025",
        "按要求旋转图形",
        4,
        ["pm-g5-geo-n024"],
        ["motion", "ch-motion", "rotation"],
        "能把图形绕指定点顺时针或逆时针旋转 90°、180°，画出旋转后的图形。",
    ),
    node(
        "pm-g5-geo-n026",
        "平移的性质",
        2,
        ["pm-g5-geo-n001"],
        ["motion", "ch-motion", "translation"],
        "能说明平移时各点移动方向相同、距离相等，对应线段平行且相等。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-geo-n027",
        "三种运动一起看",
        4,
        ["pm-g5-geo-n023", "pm-g5-geo-n025", "pm-g5-geo-n026"],
        ["motion", "ch-motion"],
        "能根据对应点的关系判断图形经过了平移、轴对称还是旋转，或它们的组合。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g5-geo-n028",
        "用运动设计图案",
        3,
        ["pm-g5-geo-n027"],
        ["motion", "ch-motion", "application"],
        "能用平移、轴对称或旋转，由一个基本图案设计出简单花边或风车图案。",
    ),
    node(
        "pm-g5-geo-n029",
        "扇形是圆的一部分",
        3,
        ["pm-g5-geo-n018"],
        ["circle", "ch-circle", "sector"],
        "能指出扇形由两条半径和一段圆弧围成；知道圆心角越大，扇形占圆的份儿越大。",
        unlock=SOFT,
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-geo-n030",
        "观察物体与还原",
        3,
        ["pm-g5-geo-n008"],
        ["view", "ch-poly"],
        "能根据三个方向的视图想象简单立体的块数与摆法，为六年级展开图做铺垫。",
        unlock=SOFT,
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-geo-n031",
        "多边形与圆合练",
        4,
        ["pm-g5-geo-n021", "pm-g5-geo-n028"],
        ["mixed", "ch-end"],
        "能在同一张综合练习里完成组合图形面积、圆的周长或面积，以及一种图形运动作图。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g5-geo-n032",
        "五年级图形通关",
        5,
        ["pm-g5-geo-n031"],
        ["mixed", "ch-end", "boss-gate"],
        "综合多边形面积、圆的周长面积与图形运动深入，完成本图收束检查。",
        mastery=MASTERY_GATE,
    ),
]


EXTRA_EDGES = [
    {
        "from": "pm-g5-geo-n002",
        "to": "pm-g5-geo-n003",
        "type": "related",
        "note": "三角形面积是等底等高平行四边形的一半。",
    },
    {
        "from": "pm-g5-geo-n003",
        "to": "pm-g5-geo-n005",
        "type": "application",
        "note": "同一条底上的等高三角形，面积一定相等。",
    },
    {
        "from": "pm-g5-geo-n006",
        "to": "pm-g5-geo-n007",
        "type": "related",
        "note": "规则图形用公式，不规则图形先估再数格。",
    },
    {
        "from": "pm-g5-geo-n010",
        "to": "pm-g5-geo-n011",
        "type": "easily_confused",
        "note": "半径是一半，直径过圆心；不要把弦都叫做直径。",
    },
    {
        "from": "pm-g5-geo-n016",
        "to": "pm-g5-geo-n018",
        "type": "easily_confused",
        "note": "周长用 2πr，面积用 πr²：一个与半径一次方有关，一个与平方有关。",
    },
    {
        "from": "pm-g5-geo-n018",
        "to": "pm-g5-geo-n019",
        "type": "related",
        "note": "圆环是大圆面积减去小圆面积。",
    },
    {
        "from": "pm-g5-geo-n016",
        "to": "pm-g5-geo-n020",
        "type": "application",
        "note": "车轮滚一圈走的路，就是圆周长。",
    },
    {
        "from": "pm-g5-geo-n022",
        "to": "pm-g5-geo-n024",
        "type": "easily_confused",
        "note": "轴对称对应点关于直线对称；旋转对应点绕点转过相同角。",
    },
    {
        "from": "pm-g5-geo-n026",
        "to": "pm-g5-geo-n024",
        "type": "related",
        "note": "平移、旋转、轴对称都能保持形状和大小，但对应点规则不同。",
    },
    {
        "from": "pm-g5-geo-n012",
        "to": "pm-g5-geo-n022",
        "type": "related",
        "note": "圆有无数条对称轴，是理解轴对称性质的好例子。",
    },
    {
        "from": "pm-g5-geo-n017",
        "to": "pm-g5-geo-n001",
        "type": "related",
        "note": "圆面积同样用「转化」：拼成近似长方形。",
    },
    {
        "from": "pm-g5-geo-n029",
        "to": "pm-g5-geo-n019",
        "type": "related",
        "note": "圆环和扇形都是圆的一部分，但一块是中间挖空，一块是切西瓜。",
    },
    {
        "from": "pm-g5-geo-n008",
        "to": "pm-g5-geo-n017",
        "type": "related",
        "note": "多边形面积综合过关后，再用同样的转化思想看圆。",
    },
]


QUESTS = [
    quest(
        "pm-g5-geo-n001-explain",
        "pm-g5-geo-n001",
        "割补面积不变",
        "explain",
        10,
        "把一张平行四边形纸沿高剪开，拼成长方形。说明面积为什么没变。",
        "只是改形状，没有丢掉或添上纸。",
    ),
    quest(
        "pm-g5-geo-n002-practice",
        "pm-g5-geo-n002",
        "别量斜边当高",
        "practice",
        20,
        "求 4 个平行四边形面积，图中斜边、邻边都标了数，必须选用垂直的高。",
        "高是垂直线段，不是斜腰。",
        4,
    ),
    quest(
        "pm-g5-geo-n003-practice",
        "pm-g5-geo-n003",
        "换底换高",
        "practice",
        20,
        "对同一个三角形用两组不同的底和高各算一次面积，核对得数。",
        "底和高必须配对垂直。",
        4,
    ),
    quest(
        "pm-g5-geo-n004-practice",
        "pm-g5-geo-n004",
        "上底下底加起来",
        "practice",
        20,
        "求 4 个梯形面积，先标上底、下底、高，再代入公式。",
        "高夹在两底之间，要垂直。",
        4,
    ),
    quest(
        "pm-g5-geo-n005-explain",
        "pm-g5-geo-n005",
        "形状不同面积同",
        "explain",
        10,
        "指出图中几个等底等高的三角形，说明它们面积相等的理由。",
        "公式只看底和高两个数。",
    ),
    quest(
        "pm-g5-geo-n006-practice",
        "pm-g5-geo-n006",
        "分割或补形",
        "practice",
        20,
        "求 3 个组合多边形面积：至少一次分割、一次补成大矩形再减。",
        "辅助线要让每一块都变成会算的图形。",
        3,
    ),
    quest(
        "pm-g5-geo-n007-practice",
        "pm-g5-geo-n007",
        "数格估树叶",
        "practice",
        20,
        "在方格纸上估计两片叶子的面积：满格算 1，超过半格算 1，不到半格算 0。",
        "估面积允许有一两格出入，方法要对。",
        2,
    ),
    quest(
        "pm-g5-geo-n008-practice",
        "pm-g5-geo-n008",
        "多边形闯关练",
        "practice",
        20,
        "混合：平行四边形、三角形、梯形、组合图形。每题先写公式再算。",
        "先点名图形，再找底和高。",
        8,
    ),
    quest(
        "pm-g5-geo-n008-quiz",
        "pm-g5-geo-n008",
        "多边形面积小测",
        "mini_quiz",
        30,
        "公式选择、组合图形、等底等高判断。夹一道把斜边当高的改错。",
        "垂直才是高。",
        8,
    ),
    quest(
        "pm-g5-geo-boss-polygon",
        "pm-g5-geo-n008",
        "关主：多边形面积工程师",
        "boss",
        80,
        "击败关主：①平行四边形或三角形面积（标底高）②梯形面积 ③一个组合图形 ④说明转化前后面积为什么不变。",
        "转化是本关的钥匙。",
        12,
    ),
    quest(
        "pm-g5-geo-n009-explain",
        "pm-g5-geo-n009",
        "圆是一个面",
        "explain",
        10,
        "指出钟面、杯口轮廓是圆，并说明圆和球不是同一种图形。",
        "圆在平面上，球是立体。",
    ),
    quest(
        "pm-g5-geo-n010-explain",
        "pm-g5-geo-n010",
        "指出半径直径",
        "explain",
        10,
        "在一个圆里画出半径、直径和一条不过圆心的弦，说明直径的两个条件。",
        "过圆心、两端在圆上，缺一不可。",
    ),
    quest(
        "pm-g5-geo-n011-practice",
        "pm-g5-geo-n011",
        "r和d换算",
        "practice",
        20,
        "已知半径求直径、已知直径求半径各 4 题，单位保持一致。",
        "直径 = 2 × 半径。",
        8,
    ),
    quest(
        "pm-g5-geo-n012-explain",
        "pm-g5-geo-n012",
        "无数条对称轴",
        "explain",
        10,
        "把圆形纸对折多次，说明每一条折痕（直径）都可以当对称轴。",
        "圆对任何一条直径两侧都重合。",
    ),
    quest(
        "pm-g5-geo-n013-practice",
        "pm-g5-geo-n013",
        "圆规开口是半径",
        "practice",
        20,
        "画出半径 3 厘米和直径 8 厘米的圆各一个，标出圆心。直径题要先想开口多大。",
        "圆规两脚的距离是半径。",
        2,
    ),
    quest(
        "pm-g5-geo-n014-explain",
        "pm-g5-geo-n014",
        "滚一圈比直径",
        "explain",
        10,
        "用圆形学具滚一圈，把滚过的线与直径比，说出大约是几倍。",
        "会得到三倍多一点，为 π 做准备。",
    ),
    quest(
        "pm-g5-geo-n015-explain",
        "pm-g5-geo-n015",
        "π是一个比值",
        "explain",
        10,
        "用自己的话说：π 不是圆的周长，而是周长除以直径得到的那个倍数，计算常用 3.14。",
        "不同圆的这个比值都一样。",
    ),
    quest(
        "pm-g5-geo-n016-practice",
        "pm-g5-geo-n016",
        "2πr或πd",
        "practice",
        20,
        "已知半径或直径求周长各 3 题，π 取 3.14，并说明为什么两个公式相等。",
        "d = 2r，所以 πd = 2πr。",
        6,
    ),
    quest(
        "pm-g5-geo-n017-explain",
        "pm-g5-geo-n017",
        "拼成近似长方形",
        "explain",
        10,
        "看圆被切成许多小扇形再拼：长大约是半个周长，宽是半径。由此说出面积公式。",
        "长 × 宽 ≈ πr × r = πr²。",
    ),
    quest(
        "pm-g5-geo-n018-practice",
        "pm-g5-geo-n018",
        "πr²求面积",
        "practice",
        20,
        "已知半径或直径求圆面积，π 取 3.14。直径题必须先求 r。",
        "面积公式用的是半径的平方。",
        6,
    ),
    quest(
        "pm-g5-geo-n019-practice",
        "pm-g5-geo-n019",
        "大圆减小圆",
        "practice",
        20,
        "求 3 个圆环面积，图中有的给两个半径，有的给外径和环宽。",
        "先求出两个半径，再两个面积相减。",
        3,
    ),
    quest(
        "pm-g5-geo-n020-practice",
        "pm-g5-geo-n020",
        "车轮和花坛",
        "practice",
        20,
        "三则短故事：车轮滚一圈走多远；圆形花坛占地；环形跑道面积。先判断周长还是面积。",
        "滚一圈走周长，铺满问面积。",
        3,
    ),
    quest(
        "pm-g5-geo-n021-practice",
        "pm-g5-geo-n021",
        "圆周长面积闯关",
        "practice",
        20,
        "混合：r 与 d、周长、面积、圆环、易混判断。",
        "看到平方想面积，看到 2πr 想周长。",
        8,
    ),
    quest(
        "pm-g5-geo-n021-quiz",
        "pm-g5-geo-n021",
        "圆的小测",
        "mini_quiz",
        30,
        "公式选择、已知直径求面积、圆环、实际问题。夹一道用 πd² 求面积的改错。",
        "面积是 πr²，不是 πd²。",
        8,
    ),
    quest(
        "pm-g5-geo-boss-circle",
        "pm-g5-geo-n021",
        "关主：圆的度量师",
        "boss",
        80,
        "击败关主：①指出半径直径并换算 ②求周长 ③求面积（已知直径）④求一个圆环或判断一题问周长还是面积。",
        "先找 r，再决定用 2πr 还是 πr²。",
        12,
    ),
    quest(
        "pm-g5-geo-n022-explain",
        "pm-g5-geo-n022",
        "对应点到轴等距",
        "explain",
        10,
        "在轴对称图形上连对应点，说明连线被对称轴垂直平分。",
        "到轴的格数相等、左右各一。",
    ),
    quest(
        "pm-g5-geo-n023-practice",
        "pm-g5-geo-n023",
        "画出另一半",
        "practice",
        20,
        "在方格纸上完成 2 个轴对称作图：一个对称轴竖直，一个倾斜 45°（用格点）。",
        "逐个点找对称点再连线。",
        2,
    ),
    quest(
        "pm-g5-geo-n024-explain",
        "pm-g5-geo-n024",
        "到中心的距离不变",
        "explain",
        10,
        "把一个小旗绕点旋转 90°，说明每个点走的是圆弧，半径不变、转过的角相同。",
        "旋转中心到对应点的距离相等。",
    ),
    quest(
        "pm-g5-geo-n025-practice",
        "pm-g5-geo-n025",
        "顺时针逆时针",
        "practice",
        20,
        "将「L」形绕格点顺时针 90°、逆时针 90°、旋转 180° 各画一次。",
        "先标旋转中心，再转每一个关键点。",
        3,
    ),
    quest(
        "pm-g5-geo-n026-explain",
        "pm-g5-geo-n026",
        "方向相同格数相同",
        "explain",
        10,
        "说明平移时每个点都向同一方向移动同样格数，对应边平行。",
        "平移没有翻转，也没有绕点转。",
    ),
    quest(
        "pm-g5-geo-n027-practice",
        "pm-g5-geo-n027",
        "这是哪种运动",
        "practice",
        20,
        "给 6 组运动前后图形，判断平移、轴对称、旋转或需要两步组合。",
        "看对应点：同向等距是平移；到直线等距是对称；绕点转是旋转。",
        6,
    ),
    quest(
        "pm-g5-geo-n028-practice",
        "pm-g5-geo-n028",
        "设计一条花边",
        "practice",
        20,
        "用一个基本图案，通过平移或轴对称设计一段花边，或用旋转设计一个风车。",
        "先规定运动规则，再重复。",
        2,
    ),
    quest(
        "pm-g5-geo-n029-explain",
        "pm-g5-geo-n029",
        "像切西瓜",
        "explain",
        10,
        "指出扇形的两条半径和弧。比较圆心角 90° 与 180° 的扇形，谁占的圆更大。软锁节点。",
        "圆心角决定这块西瓜有多厚。",
    ),
    quest(
        "pm-g5-geo-n030-practice",
        "pm-g5-geo-n030",
        "看图想块数",
        "practice",
        15,
        "根据三视图估计小立体用了几块正方体，并试着摆出来。软锁节点。",
        "上面看占地，前面看高度。",
        3,
    ),
    quest(
        "pm-g5-geo-n031-practice",
        "pm-g5-geo-n031",
        "多边形与圆合练",
        "practice",
        25,
        "混合：组合图形面积、圆的周长或面积、一种轴对称或旋转作图。",
        "多边形用底高，圆先找半径。",
        8,
    ),
    quest(
        "pm-g5-geo-n031-quiz",
        "pm-g5-geo-n031",
        "合练小测",
        "mini_quiz",
        30,
        "覆盖梯形或组合面积、圆周长面积易混、一种运动判断。",
        "2πr 与 πr² 不要对调。",
        8,
    ),
    quest(
        "pm-g5-geo-n032-practice",
        "pm-g5-geo-n032",
        "五年级图形综合练",
        "practice",
        25,
        "题型混合：组合面积、已知直径求圆面积、圆环、旋转 90°、判断运动类型。",
        "对回已点亮的灯。",
        12,
    ),
    quest(
        "pm-g5-geo-boss-map",
        "pm-g5-geo-n032",
        "关主：五年级图形通关试炼",
        "boss",
        100,
        "最终关主：①组合或梯形面积 ②圆的周长 ③圆的面积（已知直径）④判断或完成一种图形运动。全部通过即通关。",
        "通关后记入已通关列表；圆的周长与面积公式是最常回生的一对。",
        16,
    ),
]


META = {
    "id": "pm-g5-geometry",
    "title": "五年级 · 图形与几何",
    "subject": "数学",
    "stage": "小学",
    "grade": 5,
    "strand": "图形与几何",
    "version": "0.1.0",
    "locale": "zh-CN",
    "start_node_ids": ["pm-g5-geo-n001"],
    "recommended_path_note": "从「面积从转化来」进入：先打通多边形面积，圆的认识可与多边形主线并行，在圆面积转化处汇合；再轴对称与旋转深入。平移性质可从起点并行。扇形初步（n029）与观察物体还原（n030）为软锁支线，不挡终章关主，通关前仍须点亮。",
    "win_condition": {
        "type": "light_all_nodes_and_bosses",
        "required_node_ids": "all",
        "required_boss_quest_ids": [
            "pm-g5-geo-boss-polygon",
            "pm-g5-geo-boss-circle",
            "pm-g5-geo-boss-map",
        ],
        "summary": "点亮全部知识点，并击败三名关主：多边形面积工程师、圆的度量师、地图通关试炼。",
    },
    "content_disclaimer": "知识点与任务为课标/教材目录风格的原创教学大纲与自编提示语，不是任何版本教科书正文或习题的摘录。",
    "description": "小学五年级「图形与几何」地图：多边形面积 → 圆的认识与周长面积 → 轴对称与旋转深入。圆在本图系统学习；长方体圆柱等立体收束见六年级图。与四年级面积公式扩展概念衔接，但各自独立通关。",
}


SAMPLE_PROGRESS = {
    "player_id": "demo-learner",
    "display_name": "小明",
    "xp_total": 20,
    "current_map_id": "pm-g5-geometry",
    "cleared_map_ids": [],
    "nodes": {
        "pm-g5-geo-n001": {
            "state": "lit",
            "xp_earned": 10,
            "cleared_quest_ids": ["pm-g5-geo-n001-explain"],
            "updated_at": "2026-09-17T10:00:00Z",
        },
        "pm-g5-geo-n002": {
            "state": "learning",
            "xp_earned": 0,
            "cleared_quest_ids": [],
            "updated_at": "2026-09-17T10:08:00Z",
        },
    },
}


def main() -> None:
    write_map(OUT, META, NODES, EXTRA_EDGES, QUESTS, SAMPLE_PROGRESS)


if __name__ == "__main__":
    main()
