"""Build Grade 6 Numbers map JSON from a single source of truth.

Run: python3 scripts/_build_grade6_numbers.py
The generated JSON under maps/primary-math/grade-6-numbers/ is the published content.

Pedagogical spine (人教版/课标风格脉络，自撰短描述，非教材页原文):
  分数乘除（本图自洽，不引用五年级节点 id）
  → 比与化简比、按比分配
  → 百分数及其应用
  → 比例、正比例与反比例入门
  → 方程巩固（列方程解决分数/百分数问题）
  → 负数初步（软锁支线，不挡终章关主）。
圆、圆柱圆锥、扇形统计图等几何与统计大块留给以后的领域地图。
与五年级地图概念衔接（分数加减、简易方程），但节点 id 不跨图引用。
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "maps" / "primary-math" / "grade-6-numbers"

HARD = {"type": "hard_all_prereqs", "allow_teacher_override": False}
SOFT = {"type": "soft_recommended", "allow_teacher_override": True}

MASTERY_CONCEPT = {
    "min_quests_cleared": 1,
    "require_quest_types": ["explain"],
    "review_after_days": 10,
}
MASTERY_SKILL = {
    "min_quests_cleared": 1,
    "min_quiz_accuracy": 0.8,
    "require_quest_types": ["practice"],
    "review_after_days": 7,
}
MASTERY_GATE = {
    "min_quests_cleared": 2,
    "min_quiz_accuracy": 0.85,
    "require_quest_types": ["practice"],
    "review_after_days": 5,
}


def node(
    nid: str,
    title: str,
    difficulty: int,
    prereqs: list[str],
    tags: list[str],
    description: str,
    *,
    unlock: dict | None = None,
    mastery: dict | None = None,
) -> dict:
    return {
        "id": nid,
        "title": title,
        "subject": "数学",
        "stage": "小学",
        "grade": 6,
        "strand": "数与代数",
        "difficulty": difficulty,
        "prerequisites": prereqs,
        "tags": tags,
        "unlock_rule": unlock or HARD,
        "mastery_criteria": mastery or MASTERY_SKILL,
        "description": description,
    }


# --- 38 nodes, teaching order ---
NODES = [
    # A. 分数乘除（本图自洽）
    node(
        "pm-g6-n001",
        "分数乘法的意义",
        2,
        [],
        ["fraction", "ch-frac-mul", "concept"],
        "知道分数乘分数可以表示「求一个数的几分之几」，也能看成「几份里的几份」。本图从这里系统学习分数乘除。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-n002",
        "分数乘整数",
        2,
        ["pm-g6-n001"],
        ["fraction", "ch-frac-mul", "multiply"],
        "会计算分数乘整数：分子与整数相乘、分母不变，能约分的先约再乘或乘完再约。",
    ),
    node(
        "pm-g6-n003",
        "分数乘分数",
        3,
        ["pm-g6-n002"],
        ["fraction", "ch-frac-mul", "multiply"],
        "会计算分数乘分数：分子相乘作分子、分母相乘作分母；能交叉约分的先约再乘。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g6-n004",
        "求一个数的几分之几",
        3,
        ["pm-g6-n003"],
        ["fraction", "ch-frac-mul", "of"],
        "已知一个数，求它的几分之几是多少，会用乘法计算，并能在线段图上指出对应的一份。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-n005",
        "分数乘法解决问题",
        3,
        ["pm-g6-n004"],
        ["word-problem", "ch-frac-mul", "application"],
        "在「求一个数的几分之几」的短故事里列出乘法算式，注意单位 1 是哪一个量。",
    ),
    node(
        "pm-g6-n006",
        "倒数的认识",
        2,
        ["pm-g6-n003"],
        ["fraction", "ch-frac-div", "reciprocal"],
        "知道乘积是 1 的两个数互为倒数；会求整数、分数、小数的倒数（0 没有倒数）。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-n007",
        "分数除以整数",
        3,
        ["pm-g6-n006"],
        ["fraction", "ch-frac-div", "divide"],
        "分数除以整数，等于乘这个整数的倒数；平均分时也能看成分母乘整数。",
    ),
    node(
        "pm-g6-n008",
        "一个数除以分数",
        4,
        ["pm-g6-n007"],
        ["fraction", "ch-frac-div", "divide"],
        "一个数除以分数，等于乘这个分数的倒数。能说明「里面有几个这样的几分之几」。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g6-n009",
        "已知几分之几求这个数",
        4,
        ["pm-g6-n004", "pm-g6-n008"],
        ["fraction", "ch-frac-div", "of"],
        "已知一个数的几分之几是多少，求这个数，会用除法（或乘倒数）计算。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g6-n010",
        "分数四则混合运算",
        4,
        ["pm-g6-n005", "pm-g6-n008"],
        ["fraction", "ch-frac-div", "mixed"],
        "能按先乘除后加减、有括号先算括号的顺序，完成含分数的四则混合运算，得数要约分。",
    ),
    node(
        "pm-g6-n011",
        "分数乘除解决问题",
        4,
        ["pm-g6-n009"],
        ["word-problem", "ch-frac-div", "application"],
        "能区分「求一个数的几分之几」和「已知几分之几求原数」，列出乘或除的算式。",
    ),
    node(
        "pm-g6-n012",
        "分数乘除综合",
        4,
        ["pm-g6-n010", "pm-g6-n011"],
        ["fluency", "ch-frac-div", "boss-gate"],
        "综合分数乘分数、倒数、除以分数、求原数、混合运算和应用题。",
        mastery=MASTERY_GATE,
    ),
    # B. 比
    node(
        "pm-g6-n013",
        "比的意义",
        2,
        ["pm-g6-n012"],
        ["ratio", "ch-ratio", "concept"],
        "知道两个数相除又可以写成比，读作「比」；比的后项不能是 0。本图只谈数的比。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-n014",
        "比的基本性质",
        3,
        ["pm-g6-n013"],
        ["ratio", "ch-ratio", "property"],
        "知道比的前项和后项同时乘或除以一个不为 0 的数，比值不变。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-n015",
        "化简比",
        3,
        ["pm-g6-n014"],
        ["ratio", "ch-ratio", "simplify"],
        "能把整数比、小数比、分数比化成最简整数比。",
    ),
    node(
        "pm-g6-n016",
        "求比值",
        2,
        ["pm-g6-n014"],
        ["ratio", "ch-ratio", "value"],
        "能用前项除以后项求出比值，并用分数或小数表示。",
    ),
    node(
        "pm-g6-n017",
        "按比分配",
        4,
        ["pm-g6-n015"],
        ["ratio", "ch-ratio", "application"],
        "能把一个数量按照给定的比分成几部分，先求总份数再求每一部分。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g6-n018",
        "比例尺入门",
        3,
        ["pm-g6-n016"],
        ["ratio", "ch-ratio", "scale"],
        "知道图上距离∶实际距离＝比例尺，能在数值比例尺和简单换算之间来回（几何作图留给以后）。",
        mastery=MASTERY_CONCEPT,
    ),
    # C. 百分数
    node(
        "pm-g6-n019",
        "百分数的意义",
        2,
        ["pm-g6-n013"],
        ["percent", "ch-percent", "concept"],
        "知道百分数表示一个数是另一个数的百分之几，用百分号「%」书写，便于比较。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-n020",
        "百分数与分数小数互化",
        3,
        ["pm-g6-n019"],
        ["percent", "ch-percent", "convert"],
        "能在百分数、分数、小数之间互相改写，如 1/4＝0.25＝25%。",
    ),
    node(
        "pm-g6-n021",
        "求一个数的百分之几",
        3,
        ["pm-g6-n020"],
        ["percent", "ch-percent", "of"],
        "已知一个数，求它的百分之几是多少，会把百分数化成分数或小数再乘。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g6-n022",
        "已知百分之几求这个数",
        4,
        ["pm-g6-n021"],
        ["percent", "ch-percent", "of"],
        "已知一个数的百分之几是多少，求这个数，会用除法计算。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g6-n023",
        "百分率",
        3,
        ["pm-g6-n021"],
        ["percent", "ch-percent", "rate"],
        "能求发芽率、合格率、出勤率等：这部分数量÷总数量，再写成百分数。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-n024",
        "折扣税率利率入门",
        3,
        ["pm-g6-n021"],
        ["percent", "ch-percent", "life"],
        "能在折扣、税率、利率的简单情境里，把「几折、百分之几」转化成求一个数的百分之几。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-n025",
        "百分数解决问题",
        4,
        ["pm-g6-n022", "pm-g6-n023", "pm-g6-n024"],
        ["word-problem", "ch-percent", "application"],
        "能在百分数短故事里分清单位 1，选择「求百分之几是多少」或「已知百分之几求原数」。",
        mastery=MASTERY_GATE,
    ),
    # D. 比例、正比例与反比例
    node(
        "pm-g6-n026",
        "比例的意义",
        3,
        ["pm-g6-n015", "pm-g6-n016"],
        ["proportion", "ch-prop", "concept"],
        "知道表示两个比相等的式子叫做比例，能判断四个数能不能组成比例。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-n027",
        "解比例",
        3,
        ["pm-g6-n026"],
        ["proportion", "ch-prop", "solve"],
        "知道比例的基本性质（内项之积等于外项之积），并能据此求出比例中的未知项。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g6-n028",
        "正比例的意义",
        3,
        ["pm-g6-n027"],
        ["proportion", "ch-prop", "direct"],
        "知道两种相关联的量，一种量扩大（缩小）若干倍，另一种量也扩大（缩小）相同倍数，比值一定，成正比例。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-n029",
        "反比例的意义",
        3,
        ["pm-g6-n027"],
        ["proportion", "ch-prop", "inverse"],
        "知道两种相关联的量，一种量扩大（缩小）若干倍，另一种量反而缩小（扩大）相同倍数，积一定，成反比例。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-n030",
        "成正比例与成反比例",
        4,
        ["pm-g6-n028", "pm-g6-n029"],
        ["proportion", "ch-prop", "judge"],
        "能根据「比值一定」或「积一定」判断两种量成正比例、成反比例，还是不成比例。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g6-n031",
        "正反比例解决问题",
        4,
        ["pm-g6-n030"],
        ["word-problem", "ch-prop", "application"],
        "能在简单生活量里列出正比例或反比例关系，并用解比例的办法求未知量。",
    ),
    node(
        "pm-g6-n032",
        "比百分数比例综合",
        4,
        ["pm-g6-n017", "pm-g6-n018", "pm-g6-n025", "pm-g6-n031"],
        ["fluency", "ch-prop", "boss-gate"],
        "综合化简比、按比分配、百分数应用、解比例和正反比例判断。",
        mastery=MASTERY_GATE,
    ),
    # E. 负数初步（软锁支线，不挡终章关主）
    node(
        "pm-g6-n033",
        "认识负数",
        2,
        ["pm-g6-n012"],
        ["negative", "ch-neg", "concept"],
        "能在气温、收支、海拔等情境里认识负数，知道正号、负号表示相反意义的量。",
        unlock=SOFT,
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-n034",
        "正数负数和0",
        2,
        ["pm-g6-n033"],
        ["negative", "ch-neg", "concept"],
        "知道正数、负数和 0：0 既不是正数也不是负数，是正负数的分界。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-n035",
        "负数的大小比较",
        3,
        ["pm-g6-n034"],
        ["negative", "ch-neg", "compare"],
        "能比较两个负数、负数与 0、负数与正数的大小：负得越多反而越小。",
    ),
    # F. 方程巩固（本图自洽，不引用五年级节点）
    node(
        "pm-g6-n036",
        "列方程解决分数问题",
        3,
        ["pm-g6-n012"],
        ["algebra", "ch-eq", "application"],
        "能在分数乘除故事里设未知数、列方程。方程是含未知数的等式；本图从这里巩固，不依赖其他地图。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-n037",
        "列方程解决百分数问题",
        4,
        ["pm-g6-n025", "pm-g6-n036"],
        ["algebra", "ch-eq", "application"],
        "能在百分数故事里设单位 1 为未知数，列出方程并求解、检验。",
    ),
    # G. 地图综合（负数为软锁，不挡终章关主，通关前仍须点亮）
    node(
        "pm-g6-n038",
        "六年级数与运算综合",
        5,
        ["pm-g6-n012", "pm-g6-n032", "pm-g6-n037"],
        ["synthesis", "ch-final", "boss-gate"],
        "综合分数乘除、比与按比分配、百分数、比例与正反比例、列方程。负数支线不挡本关，通关前仍须点亮。",
        mastery=MASTERY_GATE,
    ),
]


EXTRA_EDGES = [
    {
        "from": "pm-g6-n001",
        "to": "pm-g6-n004",
        "type": "related",
        "note": "分数乘法的意义，核心就是「求一个数的几分之几」。",
    },
    {
        "from": "pm-g6-n003",
        "to": "pm-g6-n006",
        "type": "related",
        "note": "会乘分数之后，倒数就是「乘谁得 1」。",
    },
    {
        "from": "pm-g6-n004",
        "to": "pm-g6-n009",
        "type": "easily_confused",
        "note": "求几分之几用乘；已知几分之几求原数用除。单位 1 不要找错。",
    },
    {
        "from": "pm-g6-n006",
        "to": "pm-g6-n008",
        "type": "application",
        "note": "除以一个分数，就是乘它的倒数。",
    },
    {
        "from": "pm-g6-n007",
        "to": "pm-g6-n008",
        "type": "easily_confused",
        "note": "除以整数：乘 1/整数；除以分数：乘这个分数的倒数。不要分子分母颠倒除数以外的数。",
    },
    {
        "from": "pm-g6-n005",
        "to": "pm-g6-n011",
        "type": "easily_confused",
        "note": "同样说「几分之几」，有的是已知单位 1 求部分，有的是已知部分求单位 1。",
    },
    {
        "from": "pm-g6-n013",
        "to": "pm-g6-n016",
        "type": "related",
        "note": "比值就是前项除以后项的商，和除法、分数是一家。",
    },
    {
        "from": "pm-g6-n014",
        "to": "pm-g6-n015",
        "type": "easily_confused",
        "note": "基本性质保证比值不变；化简比是用它把前后项化成互质整数。",
    },
    {
        "from": "pm-g6-n015",
        "to": "pm-g6-n017",
        "type": "application",
        "note": "按比分配前，常常先把比化成最简整数比，再数总份数。",
    },
    {
        "from": "pm-g6-n013",
        "to": "pm-g6-n019",
        "type": "related",
        "note": "百分数可以看成后项是 100 的比，专门用来比较。",
    },
    {
        "from": "pm-g6-n016",
        "to": "pm-g6-n018",
        "type": "application",
        "note": "比例尺就是图上距离与实际距离的比，比值写成分数或 1∶n。",
    },
    {
        "from": "pm-g6-n004",
        "to": "pm-g6-n021",
        "type": "related",
        "note": "求一个数的百分之几，和求一个数的几分之几是同一类乘法。",
    },
    {
        "from": "pm-g6-n009",
        "to": "pm-g6-n022",
        "type": "related",
        "note": "已知百分之几求原数，和已知几分之几求原数是同一类除法。",
    },
    {
        "from": "pm-g6-n021",
        "to": "pm-g6-n022",
        "type": "easily_confused",
        "note": "求百分之几是多少用乘；已知百分之几求单位 1 用除。",
    },
    {
        "from": "pm-g6-n023",
        "to": "pm-g6-n025",
        "type": "application",
        "note": "百分率是「部分÷总数」，再写成百分数去比较。",
    },
    {
        "from": "pm-g6-n020",
        "to": "pm-g6-n024",
        "type": "related",
        "note": "几折、税率、利率都要先化成百分数或小数再算。",
    },
    {
        "from": "pm-g6-n015",
        "to": "pm-g6-n026",
        "type": "related",
        "note": "两个最简比的比值相等，就可以写成比例。",
    },
    {
        "from": "pm-g6-n026",
        "to": "pm-g6-n027",
        "type": "easily_confused",
        "note": "比例是两个比相等；解比例是求其中一项未知数。",
    },
    {
        "from": "pm-g6-n028",
        "to": "pm-g6-n029",
        "type": "easily_confused",
        "note": "正比例看比值一定；反比例看积一定。不要只看「一个变大一个也变大」。",
    },
    {
        "from": "pm-g6-n030",
        "to": "pm-g6-n031",
        "type": "application",
        "note": "判断成正比例还是反比例之后，才能列比例求未知量。",
    },
    {
        "from": "pm-g6-n033",
        "to": "pm-g6-n034",
        "type": "related",
        "note": "负号表示相反意义；0 是正负数中间的分界，本身不带正负。",
    },
    {
        "from": "pm-g6-n034",
        "to": "pm-g6-n035",
        "type": "easily_confused",
        "note": "−8 比 −3 小，因为更靠「负」的一侧；不要看成 8 比 3 大就判定 −8 更大。",
    },
    {
        "from": "pm-g6-n011",
        "to": "pm-g6-n036",
        "type": "application",
        "note": "分数乘除故事也可以改用设未知数、列方程来解。",
    },
    {
        "from": "pm-g6-n025",
        "to": "pm-g6-n037",
        "type": "application",
        "note": "百分数里单位 1 未知时，设方程往往更清楚。",
    },
    {
        "from": "pm-g6-n032",
        "to": "pm-g6-n038",
        "type": "application",
        "note": "比、百分数、比例进入终章综合。",
    },
]


def quest(
    qid: str,
    node_id: str,
    title: str,
    qtype: str,
    xp: int,
    prompt: str,
    hint: str,
    items: int | None = None,
) -> dict:
    q = {
        "id": qid,
        "node_id": node_id,
        "title": title,
        "type": qtype,
        "xp": xp,
        "prompt": prompt,
        "success_hint": hint,
    }
    if items is not None:
        q["items_suggested"] = items
    return q


QUESTS = [
    # A
    quest(
        "pm-g6-n001-explain",
        "pm-g6-n001",
        "几份里再取几份",
        "explain",
        10,
        "把一张长方形看成单位 1，先取 1/2，再取其中的 1/3。说明这是 1/2×1/3，也是「求 1/2 的 1/3」。本图从这里系统学习，不依赖其他地图节点。",
        "分数乘分数：求一个数的几分之几。",
    ),
    quest(
        "pm-g6-n001-practice",
        "pm-g6-n001",
        "画出几分之几",
        "practice",
        15,
        "在纸条或圆上先表示一个分数，再表示它的几分之几，并写出对应的乘法算式。",
        "先确定单位 1，再看「取了其中的几分之几」。",
        6,
    ),
    quest(
        "pm-g6-n002-explain",
        "pm-g6-n002",
        "几个几分之几",
        "explain",
        10,
        "把 2/5×3 看成 3 个 2/5 相加，或分子 2 乘 3、分母不变。说明能和 3 约分时可以先约。",
        "整数与分子相乘；能和分母约分的先约，计算更简单。",
    ),
    quest(
        "pm-g6-n002-practice",
        "pm-g6-n002",
        "分数乘整数练",
        "practice",
        20,
        "计算分数乘整数，含可以先约分的题，得数写成最简分数或带分数。",
        "先看整数和分母有没有公因数。",
        8,
    ),
    quest(
        "pm-g6-n003-explain",
        "pm-g6-n003",
        "分子乘分子分母乘分母",
        "explain",
        10,
        "用 2/3×3/4 说明：分子 2×3、分母 3×4，其中 3 可以交叉约分，得 1/2。指出约分要在不同分数的分子分母之间做。",
        "能约分先约，积的分子分母会更小。",
    ),
    quest(
        "pm-g6-n003-practice",
        "pm-g6-n003",
        "分数乘分数练",
        "practice",
        25,
        "计算分数乘分数，含带分数先化假分数、能交叉约分的情况。",
        "带分数先化成假分数再乘。",
        8,
    ),
    quest(
        "pm-g6-n003-quiz",
        "pm-g6-n003",
        "分数乘法小测",
        "mini_quiz",
        30,
        "混合分数乘整数、分数乘分数，夹先约分和带分数，正确率达到掌握标准才过关。",
        "得数要约成最简；大于 1 可写成带分数。",
        8,
    ),
    quest(
        "pm-g6-n004-explain",
        "pm-g6-n004",
        "单位1的几分之几",
        "explain",
        10,
        "一瓶水 12 升，喝了 1/4。说明「12 的 1/4」用 12×1/4，并在线段图上标出单位 1 和 1/4。",
        "求一个数的几分之几，用乘法。",
    ),
    quest(
        "pm-g6-n004-practice",
        "pm-g6-n004",
        "求几分之几是多少",
        "practice",
        20,
        "已知总量，求它的几分之几；数量可以是整数或分数。",
        "先找到单位 1，再乘对应的分数。",
        8,
    ),
    quest(
        "pm-g6-n005-explain",
        "pm-g6-n005",
        "谁是单位1",
        "explain",
        10,
        "一本书 80 页，已经看了 3/5。说明单位 1 是这本书的页数，求看了多少页用乘法。再改口「还剩几分之几」该怎样想。",
        "单位 1 通常是「谁的几分之几」里的「谁」。",
    ),
    quest(
        "pm-g6-n005-practice",
        "pm-g6-n005",
        "分数乘法故事",
        "practice",
        20,
        "完成「求一个数的几分之几」短故事，夹一则「先求几分之几再求剩下」。",
        "剩下的几分之几＝1−已经取的几分之几。",
        4,
    ),
    quest(
        "pm-g6-n006-explain",
        "pm-g6-n006",
        "乘积是1的两个数",
        "explain",
        10,
        "因为 2/3×3/2＝1，所以 2/3 和 3/2 互为倒数。说出 5、1/8、0.25 的倒数，并说明 0 为什么没有倒数。",
        "整数 a 的倒数是 1/a；分数 a/b 的倒数是 b/a（a、b 都不为 0）。",
    ),
    quest(
        "pm-g6-n006-practice",
        "pm-g6-n006",
        "求倒数",
        "practice",
        20,
        "求整数、真分数、假分数、带分数和一位小数的倒数；判断 0 有没有倒数。",
        "小数可先写成分数再颠倒分子分母。",
        8,
    ),
    quest(
        "pm-g6-n007-explain",
        "pm-g6-n007",
        "平均分成几份",
        "explain",
        10,
        "把 3/4 平均分成 2 份，是 3/4÷2＝3/4×1/2。说明除以整数等于乘它的倒数。",
        "平均分几份，就是乘 1/几。",
    ),
    quest(
        "pm-g6-n007-practice",
        "pm-g6-n007",
        "分数除以整数练",
        "practice",
        20,
        "计算分数除以整数，得数写成最简分数。",
        "整数和分子能约分时可以先约。",
        8,
    ),
    quest(
        "pm-g6-n008-explain",
        "pm-g6-n008",
        "里面有几个几分之几",
        "explain",
        10,
        "1 里面有几个 1/4？1÷1/4＝1×4＝4。再用 2/3÷1/6＝2/3×6＝4 说明「除以分数＝乘倒数」。",
        "问「有几个这样的几分之几」，就是除法。",
    ),
    quest(
        "pm-g6-n008-practice",
        "pm-g6-n008",
        "除以分数练",
        "practice",
        25,
        "计算整数或分数除以分数，含带分数先化假分数；得数要约分。",
        "除号后面的那个分数，分子分母颠倒后改成乘。",
        8,
    ),
    quest(
        "pm-g6-n008-quiz",
        "pm-g6-n008",
        "分数除法小测",
        "mini_quiz",
        30,
        "混合除以整数、除以分数、求倒数，正确率达到掌握标准才过关。",
        "先写出倒数再乘，不要只颠倒被除数。",
        8,
    ),
    quest(
        "pm-g6-n009-explain",
        "pm-g6-n009",
        "已知部分求单位1",
        "explain",
        10,
        "一瓶水喝了 1/4，正好是 3 升。说明 3 升是单位 1 的 1/4，求这瓶水用 3÷1/4，或设 x 满足 x×1/4＝3。",
        "已知一个数的几分之几是多少，求这个数，用除法。",
    ),
    quest(
        "pm-g6-n009-practice",
        "pm-g6-n009",
        "求原数练",
        "practice",
        20,
        "已知一个数的几分之几是多少，求这个数；夹两道「求几分之几是多少」作对比。",
        "先问：单位 1 已知还是未知？",
        6,
    ),
    quest(
        "pm-g6-n010-practice",
        "pm-g6-n010",
        "分数混合运算练",
        "practice",
        25,
        "计算含分数加减乘除、小括号的混合运算，写出中间得数，最后约分。",
        "没有括号先乘除后加减；同级从左往右。",
        6,
    ),
    quest(
        "pm-g6-n011-explain",
        "pm-g6-n011",
        "乘还是除先看单位1",
        "explain",
        10,
        "对比两则短故事：①已知总量求几分之几 ②已知几分之几对应的数量求总量。说明一个用乘、一个用除。",
        "单位 1 已知用乘，单位 1 未知用除。",
    ),
    quest(
        "pm-g6-n011-practice",
        "pm-g6-n011",
        "分数乘除故事",
        "practice",
        20,
        "完成乘、除方向各两则短故事，其中一则先求剩下的几分之几。",
        "可以用线段图标出单位 1 和已知的那一段。",
        4,
    ),
    quest(
        "pm-g6-n012-practice",
        "pm-g6-n012",
        "分数乘除综合练",
        "practice",
        25,
        "混合分数乘分数、倒数、除以分数、求原数、一则混合运算和一则应用题。",
        "先判断单位 1 在不在，再决定乘还是除。",
        12,
    ),
    quest(
        "pm-g6-n012-quiz",
        "pm-g6-n012",
        "分数乘除小测",
        "mini_quiz",
        30,
        "乘、除、求倒数、求原数、混合运算各至少一题，正确率达到掌握标准才过关。",
        "除以分数先写成乘倒数；得数要约分。",
        10,
    ),
    quest(
        "pm-g6-boss-fracops",
        "pm-g6-n012",
        "关主：分数乘除大闯关",
        "boss",
        90,
        "击败关主条件：①分数乘分数 1 题 ②求一个数的几分之几 1 题 ③求倒数 1 题 ④一个数除以分数 1 题 ⑤已知几分之几求原数 1 题 ⑥一道分数四则混合。",
        "乘是「取其中几份」，除是「有几个这样的几份」或「求单位 1」。",
        12,
    ),
    # B
    quest(
        "pm-g6-n013-explain",
        "pm-g6-n013",
        "两个数相除也可以说比",
        "explain",
        10,
        "班级里男生 18 人、女生 16 人，男生人数比女生人数是 18∶16。指出前项、后项，并说明后项不能是 0。",
        "比号写成「∶」，读作「比」；顺序不能随便换。",
    ),
    quest(
        "pm-g6-n013-practice",
        "pm-g6-n013",
        "写出两个量的比",
        "practice",
        15,
        "根据数量写出比，并指出前项、后项；夹一道「后项是 0 能不能写比」的判断。",
        "谁比谁，谁就是前项。",
        6,
    ),
    quest(
        "pm-g6-n014-explain",
        "pm-g6-n014",
        "同时乘除比值不变",
        "explain",
        10,
        "说明 2∶4 和 1∶2 的比值相同：前项后项同时除以 2。再说明不能乘 0 或除以 0。",
        "和分数的基本性质同一种想法：上下同时乘除同一个不为 0 的数。",
    ),
    quest(
        "pm-g6-n014-practice",
        "pm-g6-n014",
        "写出相等的比",
        "practice",
        20,
        "根据比的基本性质填空，写出与 3∶5、2∶8 相等的比；判断哪一步乘错。",
        "前项后项必须乘（或除以）同一个不为 0 的数。",
        8,
    ),
    quest(
        "pm-g6-n015-explain",
        "pm-g6-n015",
        "化成最简整数比",
        "explain",
        10,
        "把 0.4∶0.6 先写成 4∶6 再化成 2∶3；把 1/2∶1/3 先通分再化简。说明最简整数比的前后项互质。",
        "有小数先化整数，有分数先化同分母或先求比值再写。",
    ),
    quest(
        "pm-g6-n015-practice",
        "pm-g6-n015",
        "化简比练",
        "practice",
        20,
        "化简整数比、小数比、分数比，写成最简整数比。",
        "最后前后项的最大公因数应是 1。",
        8,
    ),
    quest(
        "pm-g6-n016-explain",
        "pm-g6-n016",
        "前项除以后项",
        "explain",
        10,
        "求 3∶4 的比值：3÷4＝3/4＝0.75。说明比值是一个数，比是一种关系。",
        "比值可以是分数、小数或整数。",
    ),
    quest(
        "pm-g6-n016-practice",
        "pm-g6-n016",
        "求比值练",
        "practice",
        20,
        "求若干比的比值，用分数或小数表示；夹两道化简比（不是求比值）作对比。",
        "题目问比值，就要算出那个商；问化简比，要写成 a∶b。",
        8,
    ),
    quest(
        "pm-g6-n017-explain",
        "pm-g6-n017",
        "先求总份数再分配",
        "explain",
        10,
        "把 30 枝铅笔按 2∶3 分给甲、乙。说明总份数是 5 份，每份 6 枝，甲 12 枝、乙 18 枝。",
        "按比分配：总数量÷总份数＝每份，再乘各自分数。",
    ),
    quest(
        "pm-g6-n017-practice",
        "pm-g6-n017",
        "按比分配练",
        "practice",
        25,
        "把一个数量按给定的比分成两部分或三部分；夹一道比未化简的题。",
        "先化简比，再算总份数。",
        6,
    ),
    quest(
        "pm-g6-n017-quiz",
        "pm-g6-n017",
        "比与分配小测",
        "mini_quiz",
        30,
        "化简比、求比值、按比分配各至少一题，正确率达到掌握标准才过关。",
        "分清题目要的是 a∶b，还是那个商，还是分得的数量。",
        8,
    ),
    quest(
        "pm-g6-n018-explain",
        "pm-g6-n018",
        "图上1厘米代表实际多少",
        "explain",
        10,
        "比例尺 1∶5000 表示图上 1 厘米相当于实际 5000 厘米。说明已知图上距离求实际距离用乘法，反过来用除法。画圆、作图留给图形地图。",
        "图上距离∶实际距离＝比例尺，单位要先统一。",
    ),
    quest(
        "pm-g6-n018-practice",
        "pm-g6-n018",
        "比例尺换算练",
        "practice",
        20,
        "根据数值比例尺，在图上距离和实际距离之间换算；单位先化成同样的。",
        "实际距离＝图上距离÷比例尺的比值，或按 1∶n 乘 n。",
        6,
    ),
    # C
    quest(
        "pm-g6-n019-explain",
        "pm-g6-n019",
        "百分之几便于比较",
        "explain",
        10,
        "两班及格人数不同、总人数也不同时，用及格率（百分之几）来比。说明 37% 读作百分之三十七，百分数后面一般不带单位。",
        "百分数表示两个数量的倍比关系，不是一个具体的数量。",
    ),
    quest(
        "pm-g6-n019-practice",
        "pm-g6-n019",
        "读百分数说意义",
        "practice",
        15,
        "读、写百分数，并说出「合格率 96%」表示合格数量是总数量的百分之九十六。",
        "百分号前面的数表示有百分之几。",
        8,
    ),
    quest(
        "pm-g6-n020-explain",
        "pm-g6-n020",
        "百分之几就是百分之几",
        "explain",
        10,
        "说明 25%＝25/100＝1/4＝0.25；1/5＝0.2＝20%。百分数改分数要约分，改小数看百分号相当于除以 100。",
        "百分号往左移两位小数点（除以 100）就变成小数。",
    ),
    quest(
        "pm-g6-n020-practice",
        "pm-g6-n020",
        "百分数分数小数互化",
        "practice",
        20,
        "在百分数、分数、小数之间来回改写，含 1/8、0.07、125%。",
        "大于 100% 的百分数对应大于 1 的分数或小数。",
        10,
    ),
    quest(
        "pm-g6-n021-explain",
        "pm-g6-n021",
        "求百分之几是多少",
        "explain",
        10,
        "一本书 80 页，看了 30%。说明 80×30%＝80×0.3。指出这和「求一个数的几分之几」同类。",
        "把百分数化成小数或分数，再与单位 1 相乘。",
    ),
    quest(
        "pm-g6-n021-practice",
        "pm-g6-n021",
        "求百分之几是多少练",
        "practice",
        20,
        "已知总量，求它的百分之几是多少；夹一道百分数大于 100% 的题。",
        "超过 100% 表示比单位 1 还多。",
        8,
    ),
    quest(
        "pm-g6-n021-quiz",
        "pm-g6-n021",
        "百分数乘法小测",
        "mini_quiz",
        30,
        "互化与「求一个数的百分之几」混合，正确率达到掌握标准才过关。",
        "先改写成小数或分数，再乘。",
        8,
    ),
    quest(
        "pm-g6-n022-explain",
        "pm-g6-n022",
        "已知百分之几求单位1",
        "explain",
        10,
        "一本书看了 30%，正好是 24 页。说明 24 是单位 1 的 30%，求全书页数用 24÷30%。",
        "已知一个数的百分之几是多少，求这个数，用除法。",
    ),
    quest(
        "pm-g6-n022-practice",
        "pm-g6-n022",
        "求原数（百分数）",
        "practice",
        25,
        "已知一个数的百分之几是多少，求这个数；夹两道「求百分之几是多少」作对比。",
        "先问：单位 1 已知还是未知？",
        6,
    ),
    quest(
        "pm-g6-n023-explain",
        "pm-g6-n023",
        "部分除以总数",
        "explain",
        10,
        "播种 200 粒，发芽 186 粒。发芽率＝186÷200＝93%。说明百分率要先除再写成百分数。",
        "百分率＝这部分数量÷总数量。",
    ),
    quest(
        "pm-g6-n023-practice",
        "pm-g6-n023",
        "求百分率",
        "practice",
        20,
        "根据部分和总数求发芽率、合格率或出勤率，写成百分数；可保留到百分号前一位小数。",
        "除不尽时按题目要求保留近似百分数。",
        6,
    ),
    quest(
        "pm-g6-n024-explain",
        "pm-g6-n024",
        "几折就是百分之几十",
        "explain",
        10,
        "说明 8 折是现价为原价的 80%；税率 5% 是纳税额为营业额的 5%。本图只练把它们化成「求一个数的百分之几」。",
        "几折＝百分之几十；不要把「减价百分之几」和「现价是原价的百分之几」混在一起。",
    ),
    quest(
        "pm-g6-n024-practice",
        "pm-g6-n024",
        "折扣税率利率练",
        "practice",
        20,
        "完成折扣、税率或利率的简单计算各一则：已知原价求现价，或已知本金求利息。",
        "现价＝原价×折扣对应的百分数；利息＝本金×利率。",
        4,
    ),
    quest(
        "pm-g6-n025-practice",
        "pm-g6-n025",
        "百分数故事综合",
        "practice",
        25,
        "混合：求百分之几是多少、已知百分之几求原数、求百分率、一则折扣或税率。先标出单位 1。",
        "单位 1 已知用乘，未知用除；百分率是部分÷总数。",
        6,
    ),
    quest(
        "pm-g6-n025-quiz",
        "pm-g6-n025",
        "百分数应用小测",
        "mini_quiz",
        30,
        "四类百分数问题混排，正确率达到掌握标准才过关。",
        "先用一句话写出「谁是谁的百分之几」。",
        8,
    ),
    # D
    quest(
        "pm-g6-n026-explain",
        "pm-g6-n026",
        "两个比相等就是比例",
        "explain",
        10,
        "因为 2∶3 的比值和 4∶6 的比值相等，所以 2∶3＝4∶6 是比例。判断 1、2、3、6 四个数能不能组成比例。",
        "比例必须是两个比用等号连起来。",
    ),
    quest(
        "pm-g6-n026-practice",
        "pm-g6-n026",
        "哪些能组成比例",
        "practice",
        20,
        "判断几组比或四个数能不能组成比例，能组成的写出一种比例。",
        "比值相等就能组成比例；也可以看交叉相乘是否相等。",
        6,
    ),
    quest(
        "pm-g6-n027-explain",
        "pm-g6-n027",
        "内项之积等于外项之积",
        "explain",
        10,
        "在 2∶3＝4∶6 里，3 和 4 是内项，2 和 6 是外项，3×4＝2×6。用这个性质求 x∶5＝6∶10 里的 x。",
        "未知项＝另外两个已知项的积 ÷ 剩下那个已知项。",
    ),
    quest(
        "pm-g6-n027-practice",
        "pm-g6-n027",
        "解比例练",
        "practice",
        25,
        "解若干比例，未知项在前项、后项、内项、外项都要见到；解完用交叉相乘检验。",
        "先写出内项积＝外项积，再求未知项。",
        8,
    ),
    quest(
        "pm-g6-n027-quiz",
        "pm-g6-n027",
        "解比例小测",
        "mini_quiz",
        30,
        "判断能否组成比例、解比例各若干题，正确率达到掌握标准才过关。",
        "检验：两个内项的积要等于两个外项的积。",
        8,
    ),
    quest(
        "pm-g6-n028-explain",
        "pm-g6-n028",
        "比值一定成正比例",
        "explain",
        10,
        "路程＝速度×时间，速度一定时，路程和时间的比值（就是速度）一定，所以路程和时间成正比例。指出两种量要相关联。",
        "一种量变，另一种量跟着变，比值一定，才成正比例。",
    ),
    quest(
        "pm-g6-n028-practice",
        "pm-g6-n028",
        "判断正比例",
        "practice",
        20,
        "判断几组相关联的量是否成正比例，并说明比值是什么；夹一组不成比例的。",
        "先写出对应的比，看比值变不变。",
        6,
    ),
    quest(
        "pm-g6-n029-explain",
        "pm-g6-n029",
        "积一定成反比例",
        "explain",
        10,
        "总价一定，单价和数量的积一定，单价扩大几倍数量就缩小几倍，成反比例。再举「每天做的页数与天数」。",
        "一种量变，另一种量反而变，积一定，才成反比例。",
    ),
    quest(
        "pm-g6-n029-practice",
        "pm-g6-n029",
        "判断反比例",
        "practice",
        20,
        "判断几组量是否成反比例，并说明积是什么；夹一组成正比例的作对比。",
        "先写出对应的积，看积变不变。",
        6,
    ),
    quest(
        "pm-g6-n030-explain",
        "pm-g6-n030",
        "正、反还是不成比例",
        "explain",
        10,
        "对比三组量：正方形边长与周长（正比例）、边长与面积（不成比例）、工作总量一定时工作效率与时间（反比例）。说明判断步骤。",
        "先问相不相关，再问是比值一定还是积一定，还是都不定。",
    ),
    quest(
        "pm-g6-n030-practice",
        "pm-g6-n030",
        "正反比例辨析",
        "practice",
        25,
        "判断若干组量成正比例、成反比例还是不成比例，各写一句理由。",
        "边长与面积：边长扩大 2 倍，面积扩大 4 倍，比值、积都不定。",
        8,
    ),
    quest(
        "pm-g6-n031-explain",
        "pm-g6-n031",
        "列出比例求未知量",
        "explain",
        10,
        "一辆车 3 小时走 180 千米，照这样 5 小时走多少千米？说明路程和时间成正比例，列出 180∶3＝x∶5 再解。",
        "先判断正还是反，再按对应量列出比例。",
    ),
    quest(
        "pm-g6-n031-practice",
        "pm-g6-n031",
        "正反比例故事",
        "practice",
        20,
        "完成正比例、反比例短故事各一则，列出比例并求出未知量。",
        "反比例时，对应项的位置要让积保持相等。",
        4,
    ),
    quest(
        "pm-g6-n032-practice",
        "pm-g6-n032",
        "比百分数比例综合练",
        "practice",
        25,
        "混合：化简比或按比分配、百分数应用、解比例、判断正反比例、一则比例尺换算。",
        "先判断这题在考比、百分数还是比例。",
        12,
    ),
    quest(
        "pm-g6-n032-quiz",
        "pm-g6-n032",
        "比与比例百分数小测",
        "mini_quiz",
        30,
        "按比分配、百分数、解比例、正反比例判断各至少一题，正确率达到掌握标准才过关。",
        "百分数看单位 1；比例看比值或积是否一定。",
        10,
    ),
    quest(
        "pm-g6-boss-ratio",
        "pm-g6-n032",
        "关主：比百分数比例大闯关",
        "boss",
        90,
        "击败关主条件：①化简比或求比值 1 题 ②按比分配 1 题 ③百分数应用 2 题（含一题求原数或百分率）④解比例 1 题 ⑤判断正比例或反比例 1 题。",
        "比要化最简；百分数先找单位 1；比例用内项积等于外项积。",
        12,
    ),
    # E
    quest(
        "pm-g6-n033-explain",
        "pm-g6-n033",
        "相反意义的量",
        "explain",
        10,
        "零上 5 摄氏度和零下 3 摄氏度，写成 +5℃ 和 −3℃。说明负号表示与正方向相反的量。本支线为软锁，不挡终章关主。",
        "先约定哪个方向为正，相反方向就用负号。",
    ),
    quest(
        "pm-g6-n033-practice",
        "pm-g6-n033",
        "用正负数记录",
        "practice",
        15,
        "在气温、收入与支出、高于或低于海平面等情境里，用正数或负数记录数量。",
        "收入、高于、零上常用正；支出、低于、零下常用负。",
        6,
    ),
    quest(
        "pm-g6-n034-explain",
        "pm-g6-n034",
        "0是分界",
        "explain",
        10,
        "说明正数都大于 0，负数都小于 0，0 既不是正数也不是负数。+5 和 5 表示同一个数。",
        "正号可以省略，负号不能省略。",
    ),
    quest(
        "pm-g6-n034-practice",
        "pm-g6-n034",
        "分一分正负数和0",
        "practice",
        15,
        "把一组数分成正数、负数和 0；指出哪些写法表示同一个数。",
        "0 单独一类，不要放进正数或负数。",
        8,
    ),
    quest(
        "pm-g6-n035-explain",
        "pm-g6-n035",
        "负得越多越小",
        "explain",
        10,
        "比较 −3 和 −8、−2 和 0、−1 和 4。说明在一条向右增大的线上，越往左越小。",
        "两个负数，绝对值大的反而小；负数一定小于 0，小于任何正数。",
    ),
    quest(
        "pm-g6-n035-practice",
        "pm-g6-n035",
        "正负数比大小",
        "practice",
        20,
        "比较正数、负数和 0 的大小，填＞＜＝；能按从小到大排列几个数。",
        "先看符号，再看离 0 有多远。",
        8,
    ),
    # F
    quest(
        "pm-g6-n036-explain",
        "pm-g6-n036",
        "分数故事也可以列方程",
        "explain",
        10,
        "一瓶水喝了 1/4 正好 3 升。设这瓶水是 x 升，列出 x×1/4＝3。说明方程是含未知数的等式，本图自己巩固，不引用其他地图节点。",
        "设单位 1 为 x，再按「一个数的几分之几」列等式。",
    ),
    quest(
        "pm-g6-n036-practice",
        "pm-g6-n036",
        "列方程解分数故事",
        "practice",
        20,
        "用方程解「求一个数的几分之几」或「已知几分之几求原数」短故事各一则，并检验。",
        "解方程：两边同时除以（或乘）同一个不为 0 的数。",
        4,
    ),
    quest(
        "pm-g6-n037-explain",
        "pm-g6-n037",
        "百分数里设单位1",
        "explain",
        10,
        "看了 30% 正好 24 页。设全书是 x 页，列出 x×30%＝24。解出后再用「是不是 30%」检查。",
        "单位 1 未知时，设它为 x 往往比先想「用除法」更清楚。",
    ),
    quest(
        "pm-g6-n037-practice",
        "pm-g6-n037",
        "列方程解百分数故事",
        "practice",
        20,
        "用方程解百分数短故事：含求百分之几是多少、已知百分之几求原数各一则。",
        "百分数先化成小数或分数，再与 x 相乘。",
        4,
    ),
    # G
    quest(
        "pm-g6-n038-practice",
        "pm-g6-n038",
        "地图综合练",
        "practice",
        25,
        "题型混合：分数乘除、已知几分之几求原数、化简比或按比分配、百分数、解比例或正反比例、一则列方程。",
        "先判断这题在考哪一盏已点亮的灯。",
        12,
    ),
    quest(
        "pm-g6-boss-map",
        "pm-g6-n038",
        "关主：六年级数与运算通关试炼",
        "boss",
        100,
        "最终关主：①分数乘或除 1 题 ②已知几分之几或百分之几求原数 1 题 ③化简比或按比分配 1 题 ④百分数应用 1 题 ⑤解比例或判断正反比例 1 题 ⑥列一道方程。全部通过即通关本地图。",
        "通关后这张地图记入已通关列表。五年级的分数加减与简易方程和本地图起点、方程巩固在概念上衔接，但存档仍按图分别计算，暂无跨地图引擎。",
        16,
    ),
]


META = {
    "id": "pm-g6-numbers",
    "title": "六年级 · 数与运算",
    "subject": "数学",
    "stage": "小学",
    "grade": 6,
    "strand": "数与代数",
    "version": "0.1.0",
    "locale": "zh-CN",
    "start_node_ids": ["pm-g6-n001"],
    "recommended_path_note": "从「分数乘法的意义」进入：先打通分数乘除，再比与按比分配、百分数，然后比例与正反比例入门，并用方程巩固分数/百分数问题。认识负数（n033）为软锁支线，不挡终章关主，通关前仍须点亮。圆与几何大块不在本图。",
    "win_condition": {
        "type": "light_all_nodes_and_bosses",
        "required_node_ids": "all",
        "required_boss_quest_ids": [
            "pm-g6-boss-fracops",
            "pm-g6-boss-ratio",
            "pm-g6-boss-map",
        ],
        "summary": "点亮全部知识点，并击败三名关主：分数乘除、比百分数比例、地图通关试炼。",
    },
    "content_disclaimer": "知识点与任务为课标/教材目录风格的原创教学大纲与自编提示语，不是任何版本教科书正文或习题的摘录。",
    "description": "小学六年级「数与代数」地图：分数乘除 → 比 → 百分数 → 比例与正反比例；负数初步为软锁支线。与五年级地图概念衔接，但各自独立通关。",
}


SAMPLE_PROGRESS = {
    "player_id": "demo-learner",
    "display_name": "小明",
    "xp_total": 20,
    "current_map_id": "pm-g6-numbers",
    "cleared_map_ids": [],
    "nodes": {
        "pm-g6-n001": {
            "state": "lit",
            "xp_earned": 10,
            "cleared_quest_ids": ["pm-g6-n001-explain"],
            "updated_at": "2026-09-17T10:00:00Z",
        },
        "pm-g6-n002": {
            "state": "learning",
            "xp_earned": 10,
            "cleared_quest_ids": ["pm-g6-n002-explain"],
            "updated_at": "2026-09-17T10:08:00Z",
        },
    },
}


def prereq_edges(nodes: list[dict]) -> list[dict]:
    edges = []
    for n in nodes:
        for src in n["prerequisites"]:
            edges.append(
                {
                    "from": src,
                    "to": n["id"],
                    "type": "prerequisite",
                    "note": f"{src} 需先于 {n['id']}",
                }
            )
    return edges


def dump(path: Path, data) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")


def _assert_field_limits() -> None:
    """Fail fast if learner-facing strings exceed schema limits."""
    for n in NODES:
        assert 1 <= len(n["title"]) <= 40, n["title"]
        assert 8 <= len(n["description"]) <= 160, (n["id"], len(n["description"]), n["description"])
    for q in QUESTS:
        assert 1 <= len(q["title"]) <= 40, q["title"]
        assert 4 <= len(q["prompt"]) <= 400, (q["id"], len(q["prompt"]))
        hint = q.get("success_hint") or ""
        assert len(hint) <= 200, (q["id"], len(hint))
    for e in EXTRA_EDGES:
        note = e.get("note") or ""
        assert len(note) <= 120, (e["from"], e["to"], len(note), note)
    covered = {q["node_id"] for q in QUESTS}
    missing = [n["id"] for n in NODES if n["id"] not in covered]
    assert not missing, f"nodes without quests: {missing}"


def main() -> None:
    _assert_field_limits()
    OUT.mkdir(parents=True, exist_ok=True)
    edges = prereq_edges(NODES) + EXTRA_EDGES
    dump(OUT / "nodes.json", {"map_id": META["id"], "nodes": NODES})
    dump(OUT / "edges.json", {"map_id": META["id"], "edges": edges})
    dump(OUT / "quests.json", {"map_id": META["id"], "quests": QUESTS})
    dump(OUT / "map.meta.json", META)
    dump(OUT / "player-progress.sample.json", SAMPLE_PROGRESS)


if __name__ == "__main__":
    main()
