"""Build Grade 1 Geometry map JSON from a single source of truth.

Run: python3 scripts/_build_grade1_geometry.py
The generated JSON under maps/primary-math/grade-1-geometry/ is the published content.

Pedagogical spine (课标/人教脉络风格，自撰短描述，非教材页原文):
  位置（上下、前后、左右与相对位置）
  → 立体图形初步（长方体、正方体、圆柱、球）
  → 平面图形初步（长方形、正方形、三角形、圆）
  → 拼组与生活中找图形。
七巧板与对折看对称为软锁支线。本图自洽，不引用数与运算节点 id。
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _geo_common import (
    MASTERY_CONCEPT,
    MASTERY_GATE,
    ROOT,
    SOFT,
    node as _node,
    quest,
    write_map,
)

OUT = ROOT / "maps" / "primary-math" / "grade-1-geometry"
G = 1


def node(nid, title, difficulty, prereqs, tags, description, *, unlock=None, mastery=None):
    return _node(
        nid, title, G, difficulty, prereqs, tags, description, unlock=unlock, mastery=mastery
    )


NODES = [
    # A. 位置
    node(
        "pm-g1-geo-n001",
        "上和下",
        1,
        [],
        ["position", "ch-pos", "up-down"],
        "能指着两件叠放的物品，说出谁在上面、谁在下面，并在自己身上指出头在上、脚在下。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-geo-n002",
        "前和后",
        1,
        ["pm-g1-geo-n001"],
        ["position", "ch-pos", "front-back"],
        "能根据自己面向的方向，说出谁在前面、谁在后面，不把「前」说成「上」。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-geo-n003",
        "左和右",
        1,
        ["pm-g1-geo-n001"],
        ["position", "ch-pos", "left-right"],
        "会用自己的左手、右手当标准，说出左边、右边，并指出旁边同学在自己的哪一侧。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-geo-n004",
        "上下前后左右",
        2,
        ["pm-g1-geo-n002", "pm-g1-geo-n003"],
        ["position", "ch-pos"],
        "能在同一场景里同时使用上、下、前、后、左、右，把一件物品的位置说完整。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-geo-n005",
        "相对位置",
        2,
        ["pm-g1-geo-n004"],
        ["position", "ch-pos", "relative"],
        "知道「在谁的左边」要以那个人为标准；换一个标准，左右可能对调。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-geo-n006",
        "用位置说一说",
        2,
        ["pm-g1-geo-n005"],
        ["position", "ch-pos", "application"],
        "能用上下前后左右，描述教室或桌面上几件物品彼此的位置。",
    ),
    node(
        "pm-g1-geo-n007",
        "位置综合",
        3,
        ["pm-g1-geo-n006"],
        ["position", "ch-pos", "boss-gate"],
        "能在图上或教室里连续回答「谁在谁的哪一边」，不把上下和前后说混。",
        mastery=MASTERY_GATE,
    ),
    # B. 立体图形
    node(
        "pm-g1-geo-n008",
        "摸一摸物体",
        1,
        ["pm-g1-geo-n007"],
        ["solid", "ch-solid", "sense"],
        "能用手摸学具，说出它是平平的面、直直的棱，还是圆滚滚的，为认立体图形做准备。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-geo-n009",
        "认识长方体",
        2,
        ["pm-g1-geo-n008"],
        ["solid", "ch-solid", "cuboid"],
        "能从实物中指出长方体，并说出它有平平的面，看起来有的面长一些、有的面正一些。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-geo-n010",
        "认识正方体",
        2,
        ["pm-g1-geo-n008"],
        ["solid", "ch-solid", "cube"],
        "能指出正方体，并发现它的每个面看起来都一样方，像骰子或小魔方。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-geo-n011",
        "长方体和正方体",
        2,
        ["pm-g1-geo-n009", "pm-g1-geo-n010"],
        ["solid", "ch-solid", "compare"],
        "能比较长方体和正方体：都有平平的面，正方体更「方」，长方体常常有的面更长。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-geo-n012",
        "认识圆柱",
        2,
        ["pm-g1-geo-n008"],
        ["solid", "ch-solid", "cylinder"],
        "能指出圆柱，发现上下两个面是圆的、旁边可以滚动，像易拉罐或一段短柱。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-geo-n013",
        "认识球",
        2,
        ["pm-g1-geo-n008"],
        ["solid", "ch-solid", "sphere"],
        "能指出球，发现它处处圆滚滚、没有平平的面，会向各个方向滚。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-geo-n014",
        "滚一滚堆一堆",
        2,
        ["pm-g1-geo-n012", "pm-g1-geo-n013"],
        ["solid", "ch-solid", "motion"],
        "能通过滚和堆：圆柱有时能立住、有时能滚；球很难堆稳，长方体、正方体容易叠高。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-geo-n015",
        "立体图形分类",
        3,
        ["pm-g1-geo-n011", "pm-g1-geo-n014"],
        ["solid", "ch-solid", "classify"],
        "能把一堆实物分成长方体、正方体、圆柱、球，并说出分类的理由。",
    ),
    # C. 平面图形
    node(
        "pm-g1-geo-n016",
        "从物体上找面",
        2,
        ["pm-g1-geo-n015"],
        ["plane", "ch-plane", "face"],
        "能把立体图形的一个面描在纸上，知道纸上得到的是平面图形。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-geo-n017",
        "认识长方形",
        2,
        ["pm-g1-geo-n016"],
        ["plane", "ch-plane", "rectangle"],
        "能辨认长方形：有四条边、四个角，看起来对边一样长，像门牌或书的封面。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-geo-n018",
        "认识正方形",
        2,
        ["pm-g1-geo-n016"],
        ["plane", "ch-plane", "square"],
        "能辨认正方形：四条边看起来一样长，四个角都是直直的，像方手帕。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-geo-n019",
        "长方形和正方形",
        2,
        ["pm-g1-geo-n017", "pm-g1-geo-n018"],
        ["plane", "ch-plane", "compare"],
        "能比较长方形和正方形：都有四条边四个直角；正方形四边一样长，长方形常常有两边更长。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-geo-n020",
        "认识三角形",
        2,
        ["pm-g1-geo-n016"],
        ["plane", "ch-plane", "triangle"],
        "能辨认三角形：有三条边、三个角，三条边可以一样长也可以不一样长。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-geo-n021",
        "认识圆",
        2,
        ["pm-g1-geo-n016"],
        ["plane", "ch-plane", "circle"],
        "能辨认圆：周围是弯弯的一圈，没有角，像杯口印下来的痕迹。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-geo-n022",
        "平面图形分类",
        3,
        ["pm-g1-geo-n019", "pm-g1-geo-n020", "pm-g1-geo-n021"],
        ["plane", "ch-plane", "classify"],
        "能把纸片分成长方形、正方形、三角形和圆，不把圆和球、正方形和正方体说成同一种。",
    ),
    node(
        "pm-g1-geo-n023",
        "立体和平面对照",
        4,
        ["pm-g1-geo-n015", "pm-g1-geo-n022"],
        ["solid", "plane", "ch-plane", "boss-gate"],
        "能说明立体图形是「可以拿在手里的块」，平面图形是「一个面」；球不是圆，正方体不是正方形。",
        mastery=MASTERY_GATE,
    ),
    # D. 拼组
    node(
        "pm-g1-geo-n024",
        "平面图形拼组",
        3,
        ["pm-g1-geo-n022"],
        ["compose", "ch-compose", "plane"],
        "能用几个平面图形拼出房子、小鱼等简单图案，并说出用了哪些图形。",
    ),
    node(
        "pm-g1-geo-n025",
        "积木搭一搭",
        3,
        ["pm-g1-geo-n015"],
        ["compose", "ch-compose", "solid"],
        "能用长方体、正方体和圆柱积木搭出小塔或小车，并说说谁在上、谁在下。",
    ),
    node(
        "pm-g1-geo-n026",
        "图形的分与合",
        3,
        ["pm-g1-geo-n024", "pm-g1-geo-n025"],
        ["compose", "ch-compose"],
        "知道一个图形可以拆成几块再拼回去，拼法不同，看起来就不一样。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-geo-n027",
        "七巧板试试看",
        3,
        ["pm-g1-geo-n024"],
        ["compose", "ch-compose", "tangram"],
        "能用七巧板的几块拼出一个指定轮廓（如三角形或小房子），不要求拼出复杂图案。",
        unlock=SOFT,
    ),
    node(
        "pm-g1-geo-n028",
        "生活中找图形",
        2,
        ["pm-g1-geo-n023"],
        ["application", "ch-compose"],
        "能在教室和家里指出长方体、圆柱、球、长方形、圆等，并说明是立体还是平面。",
    ),
    node(
        "pm-g1-geo-n029",
        "对折看对称",
        2,
        ["pm-g1-geo-n022"],
        ["symmetry", "ch-compose"],
        "能把剪纸对折，欣赏两边重合的现象；不要求说出「轴对称」这个词的定义。",
        unlock=SOFT,
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-geo-n030",
        "图形与位置合练",
        4,
        ["pm-g1-geo-n007", "pm-g1-geo-n026", "pm-g1-geo-n028"],
        ["mixed", "ch-end"],
        "能一边指出图形名称，一边用上下左右说明它们摆在哪里。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g1-geo-n031",
        "一年级图形通关",
        4,
        ["pm-g1-geo-n030"],
        ["mixed", "ch-end", "boss-gate"],
        "综合位置、立体与平面辨认、简单拼组，能独立完成一张入门地图的收束检查。",
        mastery=MASTERY_GATE,
    ),
]


EXTRA_EDGES = [
    {
        "from": "pm-g1-geo-n002",
        "to": "pm-g1-geo-n003",
        "type": "related",
        "note": "前后和左右都是水平方向上的位置，宜对照着说。",
    },
    {
        "from": "pm-g1-geo-n001",
        "to": "pm-g1-geo-n002",
        "type": "easily_confused",
        "note": "「上」不是「前」：上是头顶方向，前是脸朝的方向。",
    },
    {
        "from": "pm-g1-geo-n003",
        "to": "pm-g1-geo-n005",
        "type": "easily_confused",
        "note": "自己的左和「在小明左边」不是同一句话，标准不同。",
    },
    {
        "from": "pm-g1-geo-n009",
        "to": "pm-g1-geo-n010",
        "type": "related",
        "note": "长方体和正方体都有平平的面，先一起摸再比较。",
    },
    {
        "from": "pm-g1-geo-n012",
        "to": "pm-g1-geo-n013",
        "type": "related",
        "note": "圆柱和球都能滚，但球没有平平的底面。",
    },
    {
        "from": "pm-g1-geo-n009",
        "to": "pm-g1-geo-n017",
        "type": "related",
        "note": "长方形常常是长方体的一个面描下来的。",
    },
    {
        "from": "pm-g1-geo-n010",
        "to": "pm-g1-geo-n018",
        "type": "related",
        "note": "正方形常常是正方体的一个面描下来的。",
    },
    {
        "from": "pm-g1-geo-n013",
        "to": "pm-g1-geo-n021",
        "type": "easily_confused",
        "note": "球是立体，圆是平面；球的影子或杯口才更像圆。",
    },
    {
        "from": "pm-g1-geo-n010",
        "to": "pm-g1-geo-n018",
        "type": "easily_confused",
        "note": "正方体是一块，正方形是一个面，名字很像但不是同一种。",
    },
    {
        "from": "pm-g1-geo-n017",
        "to": "pm-g1-geo-n018",
        "type": "easily_confused",
        "note": "正方形四边一样长；长方形常常有一组对边更长。",
    },
    {
        "from": "pm-g1-geo-n006",
        "to": "pm-g1-geo-n025",
        "type": "application",
        "note": "搭积木时正好要用上、下、前、后来说位置。",
    },
    {
        "from": "pm-g1-geo-n024",
        "to": "pm-g1-geo-n028",
        "type": "application",
        "note": "生活里的图案也是平面图形拼出来的。",
    },
    {
        "from": "pm-g1-geo-n021",
        "to": "pm-g1-geo-n012",
        "type": "related",
        "note": "圆柱的底面看起来是圆。",
    },
    {
        "from": "pm-g1-geo-n029",
        "to": "pm-g1-geo-n024",
        "type": "related",
        "note": "对折剪纸和拼组都是在玩图形的合与分。",
    },
]


QUESTS = [
    quest(
        "pm-g1-geo-n001-explain",
        "pm-g1-geo-n001",
        "谁在上面",
        "explain",
        10,
        "把书放在桌上、橡皮放在书上。指着说谁在上面、谁在下面，再摸摸自己的头和脚。",
        "上面靠近天花板或头顶，下面靠近地板或脚。",
    ),
    quest(
        "pm-g1-geo-n002-explain",
        "pm-g1-geo-n002",
        "谁在前面",
        "explain",
        10,
        "面向黑板站好。说出谁在你前面、谁在你后面，并解释为什么不说「上面」。",
        "脸朝的方向是前，背对的方向是后。",
    ),
    quest(
        "pm-g1-geo-n003-explain",
        "pm-g1-geo-n003",
        "左手右手",
        "explain",
        10,
        "举起左手和右手，再说出铅笔在你的左边还是右边。转过身后再说一次。",
        "先认自己的左手右手，再说旁边的东西。",
    ),
    quest(
        "pm-g1-geo-n003-practice",
        "pm-g1-geo-n003",
        "指一指左右",
        "practice",
        15,
        "听口令指出：左耳、右口袋、左边的窗户。至少正确完成 6 次。",
        "弄不清时先看哪只手。",
        8,
    ),
    quest(
        "pm-g1-geo-n004-explain",
        "pm-g1-geo-n004",
        "六个方向一起说",
        "explain",
        10,
        "看一张课桌图，用上、下、前、后、左、右各说一句，把橡皮、铅笔、书的位置说清。",
        "一次只说一个方向，说完六个方向再检查有没有说反。",
    ),
    quest(
        "pm-g1-geo-n005-explain",
        "pm-g1-geo-n005",
        "以谁为标准",
        "explain",
        10,
        "两位同学面对面站。说明「小明的左边」和「我的左边」为什么可能不是同一侧。",
        "先想清楚这句话是以谁的身体当标准。",
    ),
    quest(
        "pm-g1-geo-n006-practice",
        "pm-g1-geo-n006",
        "教室位置说一说",
        "practice",
        20,
        "描述教室里黑板、门、自己的座位、邻座：至少用上四个不同的位置词。",
        "先选定一件物品当「家」，再说别人在它的哪一边。",
        6,
    ),
    quest(
        "pm-g1-geo-n007-practice",
        "pm-g1-geo-n007",
        "位置闯关练",
        "practice",
        20,
        "看图回答：谁在树上、谁在房子前面、小猫在小狗的左边还是右边。共 8 问。",
        "上下看高低，前后看面向，左右先找标准。",
        8,
    ),
    quest(
        "pm-g1-geo-n007-quiz",
        "pm-g1-geo-n007",
        "位置小测",
        "mini_quiz",
        30,
        "混合题：听口令做动作 + 看图填位置词。正确率达到掌握标准才过关。",
        "容易错的是「前」和「上」、「左」和「以谁为标准」。",
        10,
    ),
    quest(
        "pm-g1-geo-boss-position",
        "pm-g1-geo-n007",
        "关主：位置小侦探",
        "boss",
        80,
        "击败关主要过三关：①用上下前后左右描述一张图 ②指出面对面时左右会怎样 ③在教室里按口令站到正确位置。",
        "说位置时先想「以谁为标准」。",
        12,
    ),
    quest(
        "pm-g1-geo-n008-explain",
        "pm-g1-geo-n008",
        "摸摸面和棱",
        "explain",
        10,
        "闭眼摸一块积木和一只皮球，说出哪个有平平的面、哪个圆滚滚、哪个有直直的棱。",
        "用手当眼睛：平、直、圆滚滚是三种不同的感觉。",
    ),
    quest(
        "pm-g1-geo-n009-explain",
        "pm-g1-geo-n009",
        "找出长方体",
        "explain",
        10,
        "从牙膏盒、魔方、易拉罐、皮球里指出长方体，并说出你是凭什么判断的。",
        "长方体有平平的面，看起来有的面比较长。",
    ),
    quest(
        "pm-g1-geo-n010-explain",
        "pm-g1-geo-n010",
        "找出正方体",
        "explain",
        10,
        "指出正方体学具或骰子，转一转，看看每个面是不是都一样方。",
        "正方体每个面都是方方的，像小方块。",
    ),
    quest(
        "pm-g1-geo-n011-explain",
        "pm-g1-geo-n011",
        "方块比一比",
        "explain",
        10,
        "把长方体和正方体放在一起，说两句相同的、两句不同的。",
        "都有平的面；正方体更「匀称」，长方体常常一边更长。",
    ),
    quest(
        "pm-g1-geo-n011-practice",
        "pm-g1-geo-n011",
        "分一分方块",
        "practice",
        15,
        "给 8 件盒子类物品，分成「更像长方体」和「更像正方体」两组。",
        "看各个面是不是差不多一样方。",
        8,
    ),
    quest(
        "pm-g1-geo-n012-explain",
        "pm-g1-geo-n012",
        "找出圆柱",
        "explain",
        10,
        "指出易拉罐、一段短蜡烛或茶叶桶，说明上下面圆圆的、侧面可以滚动。",
        "圆柱能立在圆底上，侧面一滚就走。",
    ),
    quest(
        "pm-g1-geo-n013-explain",
        "pm-g1-geo-n013",
        "找出球",
        "explain",
        10,
        "指出皮球或玻璃球，试着让它停在桌面上，说说为什么它总想滚走。",
        "球没有平平的面可以「坐稳」。",
    ),
    quest(
        "pm-g1-geo-n014-explain",
        "pm-g1-geo-n014",
        "滚一滚堆一堆",
        "explain",
        10,
        "分别滚和堆长方体、圆柱、球，记录谁容易叠高、谁容易滚走。",
        "有平面更容易堆，处处圆的最会滚。",
    ),
    quest(
        "pm-g1-geo-n015-practice",
        "pm-g1-geo-n015",
        "立体分家",
        "practice",
        20,
        "把 12 件实物分成长方体、正方体、圆柱、球四类，说一类分错了会怎样。",
        "先看能不能滚，再看有没有方方的面。",
        12,
    ),
    quest(
        "pm-g1-geo-n016-explain",
        "pm-g1-geo-n016",
        "描一个面",
        "explain",
        10,
        "选一块积木，沿一个面在纸上描一圈。说明纸上得到的是「面」，手里拿的是「块」。",
        "描下来的没有厚度，是平面图形。",
    ),
    quest(
        "pm-g1-geo-n017-explain",
        "pm-g1-geo-n017",
        "找出长方形",
        "explain",
        10,
        "从门、书本封面、三角板、杯口中指出长方形，并数一数它有几条边、几个角。",
        "长方形有四条边、四个直直的角。",
    ),
    quest(
        "pm-g1-geo-n018-explain",
        "pm-g1-geo-n018",
        "找出正方形",
        "explain",
        10,
        "指出手帕或方瓷砖，比一比四条边是不是一样长。",
        "正方形四边一样长，角都是直的。",
    ),
    quest(
        "pm-g1-geo-n019-explain",
        "pm-g1-geo-n019",
        "长方和正方",
        "explain",
        10,
        "用纸条摆一个长方形和一个正方形，说它们哪里像、哪里不像。",
        "都是四边形；正方形四边相等，长方形常有两边更长。",
    ),
    quest(
        "pm-g1-geo-n019-practice",
        "pm-g1-geo-n019",
        "纸片分一分",
        "practice",
        15,
        "给一批四边形纸片，分成长方形和正方形。有一张接近正方形但有两边更长，说明该进哪一组。",
        "先看四边是不是一样长。",
        8,
    ),
    quest(
        "pm-g1-geo-n020-explain",
        "pm-g1-geo-n020",
        "找出三角形",
        "explain",
        10,
        "指出三角板或屋顶的轮廓，数三条边和三个角，再说一说三角形可以瘦、可以胖。",
        "三条边围起来就是三角形。",
    ),
    quest(
        "pm-g1-geo-n021-explain",
        "pm-g1-geo-n021",
        "找出圆",
        "explain",
        10,
        "指出钟面、杯口或硬币的轮廓，说明圆没有角、周围是弯的。",
        "圆是平面上的一圈，不是可以拿起来的球。",
    ),
    quest(
        "pm-g1-geo-n022-practice",
        "pm-g1-geo-n022",
        "平面图形分家",
        "practice",
        20,
        "给 12 张纸片，分成长方形、正方形、三角形、圆。夹两张故意画歪的干扰图。",
        "先数边和角，再看是不是弯弯的一圈。",
        12,
    ),
    quest(
        "pm-g1-geo-n023-explain",
        "pm-g1-geo-n023",
        "块和面不一样",
        "explain",
        10,
        "拿起正方体和一张正方形纸，再说球和圆。用自己的话说明「块」和「面」的不同。",
        "立体占地方、能拿在手里；平面像贴纸，是一个面。",
    ),
    quest(
        "pm-g1-geo-n023-practice",
        "pm-g1-geo-n023",
        "对对碰：块和面",
        "practice",
        20,
        "连线：长方体—长方形，正方体—正方形，圆柱底—圆；再指出两对容易叫错的名字。",
        "名字像不等于是同一种图形。",
        8,
    ),
    quest(
        "pm-g1-geo-n023-quiz",
        "pm-g1-geo-n023",
        "立体平面小测",
        "mini_quiz",
        30,
        "既要给实物命名，也要从照片里指出平面图形。夹「球/圆」「正方体/正方形」对照题。",
        "先问自己：这是一块还是一个面？",
        10,
    ),
    quest(
        "pm-g1-geo-boss-shape",
        "pm-g1-geo-n023",
        "关主：图形分拣员",
        "boss",
        80,
        "击败关主：①把立体实物分成四类 ②把纸片分成四类 ③说出两对「名字很像但不是同一种」的图形。",
        "分拣时先分立体和平面，再分具体形状。",
        12,
    ),
    quest(
        "pm-g1-geo-n024-practice",
        "pm-g1-geo-n024",
        "拼一个小房子",
        "practice",
        20,
        "用三角形和长方形拼一座小房子，再用圆和长方形拼一辆小车。说出每座用了哪些图形。",
        "先想屋顶、车轮分别像什么图形。",
        4,
    ),
    quest(
        "pm-g1-geo-n025-practice",
        "pm-g1-geo-n025",
        "搭一座小塔",
        "practice",
        20,
        "用积木搭一座至少三层的小塔，用上、下说出谁在谁的上面，并尽量用到圆柱。",
        "下面用容易站稳的长方体或正方体。",
        3,
    ),
    quest(
        "pm-g1-geo-n026-explain",
        "pm-g1-geo-n026",
        "拆开再拼回去",
        "explain",
        10,
        "把拼好的房子拆开，再用同样几块拼成另一种图案。说明图形可以分、也可以合。",
        "块还是那些块，拼法变了，样子就变了。",
    ),
    quest(
        "pm-g1-geo-n027-practice",
        "pm-g1-geo-n027",
        "七巧板小试",
        "practice",
        15,
        "用七巧板中的两到四块，拼出一个大三角形或一个小房子轮廓。",
        "先把最大的三角形放好，再补角落。",
        3,
    ),
    quest(
        "pm-g1-geo-n028-practice",
        "pm-g1-geo-n028",
        "找图形小猎人",
        "practice",
        20,
        "在教室里找到立体图形和平面图形各三种，登记名称，并注明是块还是面。",
        "钟面、黑板是面；粉笔盒、地球仪更像块。",
        6,
    ),
    quest(
        "pm-g1-geo-n029-explain",
        "pm-g1-geo-n029",
        "对折看一看",
        "explain",
        10,
        "把一张剪纸对折，看看两边能不能基本重合。说一说你觉得「两边一样」是什么感觉。",
        "对折能合上，就说明两边很像。",
    ),
    quest(
        "pm-g1-geo-n030-practice",
        "pm-g1-geo-n030",
        "边认图形边说位置",
        "practice",
        25,
        "看一张拼贴画：说出图中有哪些图形，再用上下左右说明太阳、房子、小车的位置。",
        "先点名图形，再选一个当标准说位置。",
        8,
    ),
    quest(
        "pm-g1-geo-n030-quiz",
        "pm-g1-geo-n030",
        "合练小测",
        "mini_quiz",
        30,
        "混合：位置词、立体分类、平面分类、看图说拼组。",
        "每一题先判断是在考位置还是在考图形名字。",
        10,
    ),
    quest(
        "pm-g1-geo-n031-practice",
        "pm-g1-geo-n031",
        "入门地图综合练",
        "practice",
        25,
        "题型混合：听口令做位置动作、给实物命名、给纸片分类、用三块图形拼一个指定轮廓。",
        "不会时回到对应的那盏灯再看一眼。",
        12,
    ),
    quest(
        "pm-g1-geo-boss-map",
        "pm-g1-geo-n031",
        "关主：一年级图形通关试炼",
        "boss",
        100,
        "最终关主：①位置图 6 问 ②立体与平面各分一类 ③说出一对容易混的名字 ④用图形拼一个小图案并说明位置。全部通过即通关本地图。",
        "通关后记入已通关列表；位置和「块/面」是本图最容易回生的两处。",
        16,
    ),
]


META = {
    "id": "pm-g1-geometry",
    "title": "一年级 · 图形与几何",
    "subject": "数学",
    "stage": "小学",
    "grade": 1,
    "strand": "图形与几何",
    "version": "0.1.0",
    "locale": "zh-CN",
    "start_node_ids": ["pm-g1-geo-n001"],
    "recommended_path_note": "从「上和下」进入：先打通位置（上下前后左右），再认识立体与平面图形，最后拼组。七巧板（n027）与对折看对称（n029）为软锁支线，不挡终章关主，通关前仍须点亮。",
    "win_condition": {
        "type": "light_all_nodes_and_bosses",
        "required_node_ids": "all",
        "required_boss_quest_ids": [
            "pm-g1-geo-boss-position",
            "pm-g1-geo-boss-shape",
            "pm-g1-geo-boss-map",
        ],
        "summary": "点亮全部知识点，并击败三名关主：位置小侦探、图形分拣员、地图通关试炼。",
    },
    "content_disclaimer": "知识点与任务为课标/教材目录风格的原创教学大纲与自编提示语，不是任何版本教科书正文或习题的摘录。",
    "description": "小学一年级「图形与几何」地图：位置 → 立体图形初步 → 平面图形初步 → 拼组。与数与运算地图概念上可对照生活情境，但各自独立通关，不引用跨图节点。",
}


SAMPLE_PROGRESS = {
    "player_id": "demo-learner",
    "display_name": "小明",
    "xp_total": 20,
    "current_map_id": "pm-g1-geometry",
    "cleared_map_ids": [],
    "nodes": {
        "pm-g1-geo-n001": {
            "state": "lit",
            "xp_earned": 10,
            "cleared_quest_ids": ["pm-g1-geo-n001-explain"],
            "updated_at": "2026-09-17T10:00:00Z",
        },
        "pm-g1-geo-n002": {
            "state": "available",
            "xp_earned": 0,
            "cleared_quest_ids": [],
            "updated_at": "2026-09-17T10:00:00Z",
        },
        "pm-g1-geo-n003": {
            "state": "learning",
            "xp_earned": 10,
            "cleared_quest_ids": ["pm-g1-geo-n003-explain"],
            "updated_at": "2026-09-17T10:08:00Z",
        },
    },
}


def main() -> None:
    write_map(OUT, META, NODES, EXTRA_EDGES, QUESTS, SAMPLE_PROGRESS)


if __name__ == "__main__":
    main()
