"""Build Grade 2 Geometry map JSON from a single source of truth.

Run: python3 scripts/_build_grade2_geometry.py

Pedagogical spine (课标/人教脉络风格，自撰短描述，非教材页原文):
  长度（厘米、米，兼及分米、毫米、千米）
  → 角的初步认识
  → 长方形与正方形的边和角
  → 轴对称欣赏、观察物体。
东南西北与简单路线图、平移现象欣赏为软锁支线。
本图自洽：长度与角从「比长短」「线段」重新铺垫，不引用一年级或数与运算节点 id。
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _geo_common import (
    MASTERY_CONCEPT,
    MASTERY_GATE,
    ROOT,
    SOFT,
    node as _node,
    quest,
    write_map,
)

OUT = ROOT / "maps" / "primary-math" / "grade-2-geometry"
G = 2


def node(nid, title, difficulty, prereqs, tags, description, *, unlock=None, mastery=None):
    return _node(
        nid, title, G, difficulty, prereqs, tags, description, unlock=unlock, mastery=mastery
    )


NODES = [
    node(
        "pm-g2-geo-n001",
        "比长短",
        1,
        [],
        ["length", "ch-len", "compare"],
        "能用一端对齐的方法比较两根小棒或两条线谁更长，知道比较要有同一个起点。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g2-geo-n002",
        "认识厘米",
        1,
        ["pm-g2-geo-n001"],
        ["length", "ch-len", "cm"],
        "认识长度单位厘米，能在直尺上指出 1 厘米，并知道它大约是一节手指的宽度。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g2-geo-n003",
        "用厘米量",
        2,
        ["pm-g2-geo-n002"],
        ["length", "ch-len", "measure"],
        "会把物体一端对准直尺的 0 刻度，读另一端对着的数，得到大约几厘米。",
    ),
    node(
        "pm-g2-geo-n004",
        "认识米",
        2,
        ["pm-g2-geo-n002"],
        ["length", "ch-len", "m"],
        "认识长度单位米，能用双臂大约比划 1 米，知道米比厘米大得多。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g2-geo-n005",
        "米和厘米",
        2,
        ["pm-g2-geo-n003", "pm-g2-geo-n004"],
        ["length", "ch-len", "convert"],
        "知道 1 米 = 100 厘米，能判断量课桌多用厘米、量教室长多用米。",
    ),
    node(
        "pm-g2-geo-n006",
        "估一估有多长",
        3,
        ["pm-g2-geo-n005"],
        ["length", "ch-len", "estimate"],
        "能先估再量：橡皮、铅笔、一步大约几厘米或几米，估得太离谱要重新感受单位。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g2-geo-n007",
        "认识分米",
        2,
        ["pm-g2-geo-n005"],
        ["length", "ch-len", "dm"],
        "认识分米：1 分米 = 10 厘米，大约是手掌的宽度，常常夹在厘米和米中间用。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g2-geo-n008",
        "认识毫米",
        3,
        ["pm-g2-geo-n007"],
        ["length", "ch-len", "mm"],
        "认识毫米：1 厘米 = 10 毫米，用来量很短或要更精确的长度，如一枚硬币的厚度。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g2-geo-n009",
        "认识千米",
        3,
        ["pm-g2-geo-n005"],
        ["length", "ch-len", "km"],
        "认识千米：1 千米 = 1000 米，用来量路程，如从家到学校大约几千米。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g2-geo-n010",
        "长度单位综合",
        4,
        ["pm-g2-geo-n006", "pm-g2-geo-n008", "pm-g2-geo-n009"],
        ["length", "ch-len", "boss-gate"],
        "能选择合适的单位去量、去估，并完成米、分米、厘米、毫米之间简单的相邻换算。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g2-geo-n011",
        "认识线段",
        2,
        ["pm-g2-geo-n003"],
        ["angle", "ch-angle", "segment"],
        "知道线段是直直的、有两个端点，能量出它的长度，并与弯弯的线区分开。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g2-geo-n012",
        "角是什么样",
        2,
        ["pm-g2-geo-n011"],
        ["angle", "ch-angle"],
        "知道角由一个顶点和两条边组成，能从时钟指针、张开的圆规里指出角。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g2-geo-n013",
        "认识直角",
        2,
        ["pm-g2-geo-n012"],
        ["angle", "ch-angle", "right"],
        "能用三角板上的直角去比，判断一个角是不是直角，并在教室里找出直角。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g2-geo-n014",
        "锐角和钝角",
        3,
        ["pm-g2-geo-n013"],
        ["angle", "ch-angle", "acute-obtuse"],
        "能把比直角小的角叫锐角、比直角大（但还没翻成一条直线）的角叫钝角。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g2-geo-n015",
        "角的分类",
        3,
        ["pm-g2-geo-n014"],
        ["angle", "ch-angle", "classify"],
        "能在一组角里分出直角、锐角、钝角，不把「张得大」和「边画得长」混为一谈。",
    ),
    node(
        "pm-g2-geo-n016",
        "长方形的边和角",
        3,
        ["pm-g2-geo-n010", "pm-g2-geo-n013"],
        ["rect", "ch-rect", "rectangle"],
        "能说明长方形有四个直角，对边相等；能量出长和宽。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g2-geo-n017",
        "正方形的边和角",
        3,
        ["pm-g2-geo-n016"],
        ["rect", "ch-rect", "square"],
        "能说明正方形四个角都是直角、四条边都相等；它是特殊的长方形。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g2-geo-n018",
        "长方形正方形初步",
        3,
        ["pm-g2-geo-n017"],
        ["rect", "ch-rect"],
        "能根据边和角判断一张纸是长方形、正方形还是普通四边形。",
    ),
    node(
        "pm-g2-geo-n019",
        "画长方形正方形",
        3,
        ["pm-g2-geo-n018"],
        ["rect", "ch-rect", "draw"],
        "能在方格纸或用直尺、三角板画出指定长和宽的长方形，以及指定边长的正方形。",
    ),
    node(
        "pm-g2-geo-n020",
        "用长度解决问题",
        3,
        ["pm-g2-geo-n018"],
        ["length", "ch-rect", "application"],
        "能在「绳子够不够围一圈」「两支铅笔一共多长」这类短故事里选用厘米或米来算。",
    ),
    node(
        "pm-g2-geo-n021",
        "轴对称现象",
        2,
        ["pm-g2-geo-n018"],
        ["symmetry", "ch-sym"],
        "能从蝴蝶、脸谱、窗花里感受到「两边一样」，知道这是轴对称现象。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g2-geo-n022",
        "对折找对称轴",
        3,
        ["pm-g2-geo-n021"],
        ["symmetry", "ch-sym", "axis"],
        "能通过对折找出简单图形的对称轴，并说明对折后两边基本重合。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g2-geo-n023",
        "生活中的对称",
        2,
        ["pm-g2-geo-n022"],
        ["symmetry", "ch-sym", "application"],
        "能在叶子、建筑物、字母里找出轴对称的例子，并指出大概在哪里对折。",
    ),
    node(
        "pm-g2-geo-n024",
        "从正面看",
        2,
        ["pm-g2-geo-n015"],
        ["view", "ch-view"],
        "知道从正面看物体，只能看到朝向自己的那一面，形状可能和从旁边看不一样。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g2-geo-n025",
        "从侧面和上面看",
        3,
        ["pm-g2-geo-n024"],
        ["view", "ch-view"],
        "能辨认简单积木组合从侧面、从上面看到的形状，不把三个方向的图弄混。",
    ),
    node(
        "pm-g2-geo-n026",
        "观察物体综合",
        4,
        ["pm-g2-geo-n025"],
        ["view", "ch-view", "boss-gate"],
        "能根据「从哪边看」选出正确的视图，并说明换一个方向为什么会变样。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g2-geo-n027",
        "东、南、西、北",
        2,
        ["pm-g2-geo-n001"],
        ["direction", "ch-dir"],
        "能在给出一个方向（如北方）时辨认其余三个方向，并在教室里指出大概的东、南、西、北。",
        unlock=SOFT,
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g2-geo-n028",
        "看简单路线图",
        3,
        ["pm-g2-geo-n027"],
        ["direction", "ch-dir", "map"],
        "能在简单平面图上按「向东走、再向北」描述从家到学校的路线。",
        unlock=SOFT,
    ),
    node(
        "pm-g2-geo-n029",
        "平移现象欣赏",
        2,
        ["pm-g2-geo-n021"],
        ["translation", "ch-sym"],
        "能从电梯、推拉窗里感受图形整体移动、方向不变的现象；不要求在方格纸上作图。",
        unlock=SOFT,
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g2-geo-n030",
        "长度角与图形合练",
        4,
        ["pm-g2-geo-n010", "pm-g2-geo-n020", "pm-g2-geo-n023", "pm-g2-geo-n026"],
        ["mixed", "ch-end"],
        "能把量长度、认角、认长方形正方形、看视图放在同一张综合练习里完成。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g2-geo-n031",
        "二年级图形通关",
        4,
        ["pm-g2-geo-n030"],
        ["mixed", "ch-end", "boss-gate"],
        "综合长度单位、角的分类、长方形正方形初步和观察物体，完成本图收束检查。",
        mastery=MASTERY_GATE,
    ),
]


EXTRA_EDGES = [
    {
        "from": "pm-g2-geo-n002",
        "to": "pm-g2-geo-n004",
        "type": "related",
        "note": "厘米量短的，米量长的，先建立大小感觉再换算。",
    },
    {
        "from": "pm-g2-geo-n007",
        "to": "pm-g2-geo-n009",
        "type": "related",
        "note": "分米夹在厘米和米中间；千米比米大得多，用来量路程。",
    },
    {
        "from": "pm-g2-geo-n002",
        "to": "pm-g2-geo-n008",
        "type": "easily_confused",
        "note": "厘米看直尺上的大格，毫米是大格里的小格，不要数错。",
    },
    {
        "from": "pm-g2-geo-n004",
        "to": "pm-g2-geo-n009",
        "type": "easily_confused",
        "note": "米量教室，千米量马路，不要把课桌长说成几千米。",
    },
    {
        "from": "pm-g2-geo-n012",
        "to": "pm-g2-geo-n015",
        "type": "easily_confused",
        "note": "角的大小看张开的程度，不看边画得长不长。",
    },
    {
        "from": "pm-g2-geo-n013",
        "to": "pm-g2-geo-n014",
        "type": "related",
        "note": "先钉住直角这个「标准角」，再分出更小的锐角和更大的钝角。",
    },
    {
        "from": "pm-g2-geo-n016",
        "to": "pm-g2-geo-n017",
        "type": "easily_confused",
        "note": "正方形四边相等；长方形对边相等，邻边可以不相等。",
    },
    {
        "from": "pm-g2-geo-n011",
        "to": "pm-g2-geo-n019",
        "type": "application",
        "note": "画长方形正方形时，边都是线段，要用直尺。",
    },
    {
        "from": "pm-g2-geo-n021",
        "to": "pm-g2-geo-n029",
        "type": "related",
        "note": "轴对称是对折重合，平移是整体滑动，两种运动不一样。",
    },
    {
        "from": "pm-g2-geo-n024",
        "to": "pm-g2-geo-n025",
        "type": "easily_confused",
        "note": "正面、侧面、上面看到的轮廓常常不同，不能只用一个方向猜。",
    },
    {
        "from": "pm-g2-geo-n027",
        "to": "pm-g2-geo-n003",
        "type": "related",
        "note": "方向和长度都是在空间里给物体定位：一个说朝哪，一个说有多长。",
    },
    {
        "from": "pm-g2-geo-n006",
        "to": "pm-g2-geo-n020",
        "type": "application",
        "note": "解决问题前先估一估用哪个单位更合适。",
    },
    {
        "from": "pm-g2-geo-n015",
        "to": "pm-g2-geo-n016",
        "type": "related",
        "note": "长方形四个角都是直角，认角是认长方形的基础。",
    },
]


QUESTS = [
    quest(
        "pm-g2-geo-n001-explain",
        "pm-g2-geo-n001",
        "一端对齐再比",
        "explain",
        10,
        "拿两支铅笔，先随便比一次，再把一端对齐比一次。说明为什么要对齐。",
        "起点不同，谁长谁短会看走眼。",
    ),
    quest(
        "pm-g2-geo-n002-explain",
        "pm-g2-geo-n002",
        "1厘米有多长",
        "explain",
        10,
        "在直尺上指出 0 到 1 的一大格，用手指比一比，再说出还有哪些东西大约是 1 厘米。",
        "1 厘米是一小段，不要把整把尺子当成 1 厘米。",
    ),
    quest(
        "pm-g2-geo-n003-practice",
        "pm-g2-geo-n003",
        "对准0再读数",
        "practice",
        20,
        "量橡皮、卡片、铅笔的长，每样写「约几厘米」。故意把一次起点对在 1 上，说说读数该怎么改。",
        "左端对 0，右端对着几就是几厘米。",
        6,
    ),
    quest(
        "pm-g2-geo-n004-explain",
        "pm-g2-geo-n004",
        "1米有多长",
        "explain",
        10,
        "用米尺或绳子比出大约 1 米，和自己的身高、一步比一比。",
        "1 米大约是大人的一大步，比铅笔长得多。",
    ),
    quest(
        "pm-g2-geo-n005-explain",
        "pm-g2-geo-n005",
        "1米等于100厘米",
        "explain",
        10,
        "说明量课桌面多用厘米、量教室长多用米的理由，并说出 1 米里有多少厘米。",
        "单位要和物体的长短匹配。",
    ),
    quest(
        "pm-g2-geo-n005-practice",
        "pm-g2-geo-n005",
        "选单位填一填",
        "practice",
        20,
        "给「铅笔长、操场长、指甲宽、教室门高」选择厘米或米，并完成 2 米 = □ 厘米。",
        "先想物体大概有多长，再选单位。",
        8,
    ),
    quest(
        "pm-g2-geo-n006-practice",
        "pm-g2-geo-n006",
        "先估再量",
        "practice",
        20,
        "先估橡皮、课本、一步的长度，再量出来，比一比估得偏大还是偏小。",
        "估完必须真的量一次，才能校准感觉。",
        6,
    ),
    quest(
        "pm-g2-geo-n007-explain",
        "pm-g2-geo-n007",
        "手掌大约一分米",
        "explain",
        10,
        "在直尺上指出 10 厘米，说明这就是 1 分米，并用手掌比一比。",
        "10 个 1 厘米连起来是 1 分米。",
    ),
    quest(
        "pm-g2-geo-n008-explain",
        "pm-g2-geo-n008",
        "毫米在小格里",
        "explain",
        10,
        "指出直尺上 1 厘米里的小格，数一数是 10 格，说明 1 厘米 = 10 毫米。",
        "毫米用来量很短或要更准的东西。",
    ),
    quest(
        "pm-g2-geo-n008-practice",
        "pm-g2-geo-n008",
        "厘米毫米换算",
        "practice",
        20,
        "完成 3 厘米 = □ 毫米、40 毫米 = □ 厘米，并量一枚硬币的厚度大约几毫米。",
        "向毫米换要 ×10，向厘米换要 ÷10。",
        8,
    ),
    quest(
        "pm-g2-geo-n009-explain",
        "pm-g2-geo-n009",
        "千米是路程",
        "explain",
        10,
        "说明从家到公园如果要走很久，用千米更合适，并说出 1 千米 = 1000 米。",
        "千米很大，不要用来量橡皮。",
    ),
    quest(
        "pm-g2-geo-n010-practice",
        "pm-g2-geo-n010",
        "单位全家福",
        "practice",
        20,
        "给 8 个情境选毫米、厘米、分米、米或千米，并完成相邻单位换算 4 题。",
        "先问「这个有多长」，再选最顺口的单位。",
        12,
    ),
    quest(
        "pm-g2-geo-n010-quiz",
        "pm-g2-geo-n010",
        "长度小测",
        "mini_quiz",
        30,
        "混合：读尺、选单位、换算、先估再量。夹一道把课桌说成 2 千米的改错。",
        "单位错了，数字再对也没有意义。",
        10,
    ),
    quest(
        "pm-g2-geo-boss-length",
        "pm-g2-geo-n010",
        "关主：长度测量员",
        "boss",
        80,
        "击败关主：①正确量两件物品 ②选对 4 个情境的单位 ③完成米—厘米、厘米—毫米换算各 2 题。",
        "量的时候左端一定要记住对 0。",
        12,
    ),
    quest(
        "pm-g2-geo-n011-explain",
        "pm-g2-geo-n011",
        "线段有两个头",
        "explain",
        10,
        "画一条直直的线，点上两个端点，说明它和弯线、可以无限延长的线有什么不同。",
        "线段直、有两个端点，长度可以量。",
    ),
    quest(
        "pm-g2-geo-n012-explain",
        "pm-g2-geo-n012",
        "指出角的顶点",
        "explain",
        10,
        "看时钟 3 点和张开的书，指出角的顶点在哪、两条边在哪。",
        "顶点是两条边的交点，边是从顶点出发的两条射线。",
    ),
    quest(
        "pm-g2-geo-n013-practice",
        "pm-g2-geo-n013",
        "用直角比一比",
        "practice",
        20,
        "用三角板的直角去比门角、书角、任意画的角，分成「是直角」和「不是直角」。",
        "三角板的直角要贴紧顶点和一条边再看另一条边。",
        8,
    ),
    quest(
        "pm-g2-geo-n014-explain",
        "pm-g2-geo-n014",
        "比直角小还是大",
        "explain",
        10,
        "画一个比直角小的角和一个比直角大的角，分别叫出锐角、钝角。",
        "先用直角当尺子，再决定小还是大。",
    ),
    quest(
        "pm-g2-geo-n015-practice",
        "pm-g2-geo-n015",
        "角的三分类",
        "practice",
        20,
        "给 10 个角贴标签：直角、锐角、钝角。其中两个边画得很长但张口很小。",
        "只看张开的程度，不看边的长短。",
        10,
    ),
    quest(
        "pm-g2-geo-n015-quiz",
        "pm-g2-geo-n015",
        "认角小测",
        "mini_quiz",
        25,
        "判断并分类一组角，再回答「边越长角越大吗」。",
        "角的大小与边长无关。",
        8,
    ),
    quest(
        "pm-g2-geo-n016-explain",
        "pm-g2-geo-n016",
        "长方形量一量",
        "explain",
        10,
        "量一张长方形纸的四条边、用三角板比四个角，总结长方形的边和角有什么特点。",
        "四个直角，对边相等。",
    ),
    quest(
        "pm-g2-geo-n017-explain",
        "pm-g2-geo-n017",
        "正方形量一量",
        "explain",
        10,
        "量正方形纸的四边、比四角，说明它和长方形哪里一样、哪里更「特殊」。",
        "正方形是四边都相等的长方形。",
    ),
    quest(
        "pm-g2-geo-n018-practice",
        "pm-g2-geo-n018",
        "这是什么四边形",
        "practice",
        20,
        "给 8 张四边形，判断长方形、正方形或都不是，并写出判断依据（边或角）。",
        "先看是不是四个直角，再看边是否都相等。",
        8,
    ),
    quest(
        "pm-g2-geo-n019-practice",
        "pm-g2-geo-n019",
        "画指定的长方形",
        "practice",
        20,
        "在方格纸上画长 6 厘米、宽 4 厘米的长方形，再画边长 3 厘米的正方形。",
        "先画一条边，再用直角把邻边画垂直。",
        4,
    ),
    quest(
        "pm-g2-geo-n020-practice",
        "pm-g2-geo-n020",
        "绳子和铅笔",
        "practice",
        20,
        "解决两则短故事：两支铅笔接起来够不够 20 厘米；围一块手帕一圈大约需要多长的线。",
        "围一圈要把四条边加起来。",
        4,
    ),
    quest(
        "pm-g2-geo-n021-explain",
        "pm-g2-geo-n021",
        "两边一样的美",
        "explain",
        10,
        "看蝴蝶或脸谱图片，说一说左右两边哪里一样，你觉得对折后会怎样。",
        "轴对称先建立「两边一样」的感觉，先不急着下定义。",
    ),
    quest(
        "pm-g2-geo-n022-practice",
        "pm-g2-geo-n022",
        "对折找中线",
        "practice",
        20,
        "把长方形、正方形、等腰三角形纸对折，画出折痕，并判断圆形对折会怎样。",
        "折痕就是对称轴所在的位置。",
        4,
    ),
    quest(
        "pm-g2-geo-n023-practice",
        "pm-g2-geo-n023",
        "找对称小猎人",
        "practice",
        15,
        "在教室或字母卡片里找出 4 个轴对称的例子，指出大约沿哪条线对折。",
        "对折能基本重合才算。",
        4,
    ),
    quest(
        "pm-g2-geo-n024-explain",
        "pm-g2-geo-n024",
        "换个方向看",
        "explain",
        10,
        "拿一个茶杯，先从正面看再说从侧面看，说明为什么看到的形状会变。",
        "眼睛换位置，被挡住的面就不同。",
    ),
    quest(
        "pm-g2-geo-n025-practice",
        "pm-g2-geo-n025",
        "三张视图选一选",
        "practice",
        20,
        "看两层积木，从三张图里选出正面、侧面、上面各是哪一张。",
        "上面看的是「屋顶」轮廓，不要和正面搞混。",
        6,
    ),
    quest(
        "pm-g2-geo-n026-practice",
        "pm-g2-geo-n026",
        "观察闯关练",
        "practice",
        20,
        "完成 6 组「从哪边看」匹配，并说明其中一组为什么另外两张图不对。",
        "先确定观察方向，再看露出了几个面。",
        6,
    ),
    quest(
        "pm-g2-geo-n026-quiz",
        "pm-g2-geo-n026",
        "观察小测",
        "mini_quiz",
        30,
        "给出积木照片和三视图，判断观察方向；夹一道把上面看成正面的改错。",
        "方向说错，图就会选错。",
        8,
    ),
    quest(
        "pm-g2-geo-boss-angle",
        "pm-g2-geo-n026",
        "关主：角与观察小能手",
        "boss",
        80,
        "击败关主：①把 6 个角分成直角锐角钝角 ②判断 2 个四边形 ③为积木选出正确的上面视图。",
        "角看张口，视图看方向，不要互相干扰。",
        12,
    ),
    quest(
        "pm-g2-geo-n027-explain",
        "pm-g2-geo-n027",
        "指出北方",
        "explain",
        10,
        "如果老师告诉你窗那边是北，请指出南、东、西，并说明南北相对、东西相对。",
        "面朝北时，右手边大约是东。",
    ),
    quest(
        "pm-g2-geo-n028-practice",
        "pm-g2-geo-n028",
        "走一段路线",
        "practice",
        20,
        "在简单方格图上从学校走到邮局：先向东 2 格，再向北 3 格。用方向词说一遍。",
        "每走一段只改一个方向。",
        4,
    ),
    quest(
        "pm-g2-geo-n029-explain",
        "pm-g2-geo-n029",
        "整体滑过去",
        "explain",
        10,
        "看推拉窗或电梯门，说明格子图案是怎样整体移动的，形状有没有转动。",
        "平移时图形不翻转、不转动，只是换了位置。",
    ),
    quest(
        "pm-g2-geo-n030-practice",
        "pm-g2-geo-n030",
        "长度角图形合练",
        "practice",
        25,
        "混合：选单位、量一条边、判断角、辨认长方形正方形、选视图。",
        "先看题目在问「多长」「什么角」还是「从哪看」。",
        10,
    ),
    quest(
        "pm-g2-geo-n030-quiz",
        "pm-g2-geo-n030",
        "合练小测",
        "mini_quiz",
        30,
        "覆盖长度换算、角的分类、长方形正方形特征和一题三视图。",
        "易错：单位、边长与角的大小、视图方向。",
        10,
    ),
    quest(
        "pm-g2-geo-n031-practice",
        "pm-g2-geo-n031",
        "二年级图形综合练",
        "practice",
        25,
        "题型混合：读尺、换算、画一个正方形、对折找对称轴、看图选观察方向。",
        "每一题对回本图已经点亮的那一盏灯。",
        12,
    ),
    quest(
        "pm-g2-geo-boss-map",
        "pm-g2-geo-n031",
        "关主：二年级图形通关试炼",
        "boss",
        100,
        "最终关主：①长度单位与换算 ②角的三分类 ③长方形正方形边角特征 ④一题观察物体。全部通过即通关。",
        "通关后记入已通关列表；量长度对 0 和认直角是最常回生的两处。",
        16,
    ),
]


META = {
    "id": "pm-g2-geometry",
    "title": "二年级 · 图形与几何",
    "subject": "数学",
    "stage": "小学",
    "grade": 2,
    "strand": "图形与几何",
    "version": "0.1.0",
    "locale": "zh-CN",
    "start_node_ids": ["pm-g2-geo-n001"],
    "recommended_path_note": "从「比长短」进入：先打通厘米米及分毫米千米，再角的初步认识、长方形正方形边和角，然后轴对称欣赏与观察物体。东南西北与路线图（n027–n028）、平移欣赏（n029）为软锁支线，不挡终章关主，通关前仍须点亮。",
    "win_condition": {
        "type": "light_all_nodes_and_bosses",
        "required_node_ids": "all",
        "required_boss_quest_ids": [
            "pm-g2-geo-boss-length",
            "pm-g2-geo-boss-angle",
            "pm-g2-geo-boss-map",
        ],
        "summary": "点亮全部知识点，并击败三名关主：长度测量员、角与观察小能手、地图通关试炼。",
    },
    "content_disclaimer": "知识点与任务为课标/教材目录风格的原创教学大纲与自编提示语，不是任何版本教科书正文或习题的摘录。",
    "description": "小学二年级「图形与几何」地图：长度单位 → 角的初步认识 → 长方形正方形初步 → 轴对称欣赏与观察物体。与一年级地图概念衔接，但各自独立通关。",
}


SAMPLE_PROGRESS = {
    "player_id": "demo-learner",
    "display_name": "小明",
    "xp_total": 20,
    "current_map_id": "pm-g2-geometry",
    "cleared_map_ids": [],
    "nodes": {
        "pm-g2-geo-n001": {
            "state": "lit",
            "xp_earned": 10,
            "cleared_quest_ids": ["pm-g2-geo-n001-explain"],
            "updated_at": "2026-09-17T10:00:00Z",
        },
        "pm-g2-geo-n002": {
            "state": "learning",
            "xp_earned": 10,
            "cleared_quest_ids": ["pm-g2-geo-n002-explain"],
            "updated_at": "2026-09-17T10:08:00Z",
        },
    },
}


def main() -> None:
    write_map(OUT, META, NODES, EXTRA_EDGES, QUESTS, SAMPLE_PROGRESS)


if __name__ == "__main__":
    main()
