"""Build Grade 4 Numbers map JSON from a single source of truth.

Run: python3 scripts/_build_grade4_numbers.py
The generated JSON under maps/primary-math/grade-4-numbers/ is the published content.

Pedagogical spine (人教版/课标风格脉络，自撰短描述，非教材页原文):
  大数认识（亿以内读写改写、亿以上）→ 三位数乘两位数
  → 除数是两位数的除法（含调商）与乘除综合
  → 四则运算与运算律、简便运算入门
  → 小数的意义和性质、小数加减
  → 小数乘除入门（软锁支线，四年级下/五年级衔接）。
与三年级地图概念衔接（万以内数位、一位小数初步软锁），但节点 id 不跨图引用。
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "maps" / "primary-math" / "grade-4-numbers"

HARD = {"type": "hard_all_prereqs", "allow_teacher_override": False}
SOFT = {"type": "soft_recommended", "allow_teacher_override": True}

MASTERY_CONCEPT = {
    "min_quests_cleared": 1,
    "require_quest_types": ["explain"],
    "review_after_days": 10,
}
MASTERY_SKILL = {
    "min_quests_cleared": 1,
    "min_quiz_accuracy": 0.8,
    "require_quest_types": ["practice"],
    "review_after_days": 7,
}
MASTERY_GATE = {
    "min_quests_cleared": 2,
    "min_quiz_accuracy": 0.85,
    "require_quest_types": ["practice"],
    "review_after_days": 5,
}


def node(
    nid: str,
    title: str,
    difficulty: int,
    prereqs: list[str],
    tags: list[str],
    description: str,
    *,
    unlock: dict | None = None,
    mastery: dict | None = None,
) -> dict:
    return {
        "id": nid,
        "title": title,
        "subject": "数学",
        "stage": "小学",
        "grade": 4,
        "strand": "数与代数",
        "difficulty": difficulty,
        "prerequisites": prereqs,
        "tags": tags,
        "unlock_rule": unlock or HARD,
        "mastery_criteria": mastery or MASTERY_SKILL,
        "description": description,
    }


# --- 40 nodes, teaching order ---
NODES = [
    # A. 大数的认识
    node(
        "pm-g4-n001",
        "计数单位：从万到亿",
        1,
        [],
        ["place-value", "ch-large", "review"],
        "能说出个、十、百、千、万、十万、百万、千万、亿，并说明相邻两个单位之间是十进关系。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g4-n002",
        "亿以内数的读法",
        2,
        ["pm-g4-n001"],
        ["read", "ch-large"],
        "会按级（个级、万级）读亿以内的数，连续的 0 只读一个零，某级末尾的 0 常常不读。",
    ),
    node(
        "pm-g4-n003",
        "亿以内数的写法",
        2,
        ["pm-g4-n002"],
        ["write", "ch-large"],
        "听到或看到中文读法后，能按数位写出亿以内的数，某一位一个单位也没有时要写 0 占位。",
    ),
    node(
        "pm-g4-n004",
        "亿以内数的组成",
        2,
        ["pm-g4-n003"],
        ["compose", "ch-large"],
        "能说出一个亿以内的数含有几个亿、几个万、几个一，并用计数单位说明它的组成。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g4-n005",
        "用万作单位改写",
        3,
        ["pm-g4-n004"],
        ["rewrite", "ch-large", "wan"],
        "能把整万的数改写成用「万」作单位的数，改写后与原数相等，只是计数单位变了。",
    ),
    node(
        "pm-g4-n006",
        "近似数与四舍五入",
        3,
        ["pm-g4-n005"],
        ["round", "ch-large", "estimate"],
        "会按「四舍五入」省略万后面的尾数，求出以万作单位的近似数，并说明它只是接近原数。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g4-n007",
        "亿以上数与用亿改写",
        3,
        ["pm-g4-n004"],
        ["rewrite", "ch-large", "yi"],
        "认识十亿、百亿、千亿，会读写亿以上的数，并能把整亿的数改写成用「亿」作单位。",
    ),
    node(
        "pm-g4-n008",
        "大数比较与综合",
        4,
        ["pm-g4-n006", "pm-g4-n007"],
        ["compare", "ch-large", "boss-gate"],
        "会比较亿以内及更大数的大小，并综合读写、组成、改写和求近似数。",
        mastery=MASTERY_GATE,
    ),
    # B. 三位数乘两位数
    node(
        "pm-g4-n009",
        "口算乘数是整十",
        2,
        ["pm-g4-n008"],
        ["multiply", "ch-mul3x2", "mental"],
        "能口算两位数或三位数乘 10、20、30 等，体会「先乘前面的数字，再按整十补 0」。",
    ),
    node(
        "pm-g4-n010",
        "三位数乘两位数（不进位）",
        2,
        ["pm-g4-n009"],
        ["multiply", "ch-mul3x2", "no-carry"],
        "会分两层竖式：用个位乘一遍、用十位乘一遍（积向左错一位），再把两次积加起来。",
    ),
    node(
        "pm-g4-n011",
        "三位数乘两位数（进位）",
        4,
        ["pm-g4-n010"],
        ["multiply", "ch-mul3x2", "carry"],
        "每一层相乘若满十会进位，进上去的数只加在这一层里；因数中间有 0 时积里的 0 不写丢。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g4-n012",
        "积的变化规律",
        3,
        ["pm-g4-n011"],
        ["multiply", "ch-mul3x2", "pattern"],
        "知道一个因数扩大（或缩小）若干倍、另一个不变，积也扩大（或缩小）相同的倍数。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g4-n013",
        "乘法估算",
        3,
        ["pm-g4-n009"],
        ["estimate", "ch-mul3x2"],
        "能把三位数或两位数看成接近的整百、整十再相乘，判断积大概落在哪一带。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g4-n014",
        "用乘法解决问题",
        3,
        ["pm-g4-n011"],
        ["word-problem", "ch-mul3x2", "application"],
        "在「每份同样多、求一共」或「求几倍」的短故事里，列出三位数乘两位数的算式。",
    ),
    # C. 除数是两位数的除法
    node(
        "pm-g4-n015",
        "口算除数是整十",
        2,
        ["pm-g4-n009"],
        ["divide", "ch-div2", "mental"],
        "能口算整百、整千除以 10、20、30 等，并用乘法想一想是否合理。",
    ),
    node(
        "pm-g4-n016",
        "用整十数除",
        3,
        ["pm-g4-n015", "pm-g4-n011"],
        ["divide", "ch-div2"],
        "会用竖式计算除数是 20、30、40 这类整十数的除法，商写在正确的数位上。",
    ),
    node(
        "pm-g4-n017",
        "除数是两位数（试商）",
        3,
        ["pm-g4-n016"],
        ["divide", "ch-div2", "try-quotient"],
        "除数不是整十时，能把它看成接近的整十来试商，并把商写在被除数相应数位的上面。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g4-n018",
        "调商",
        4,
        ["pm-g4-n017"],
        ["divide", "ch-div2", "adjust"],
        "初商偏大（乘积比余下的数大）或偏小（余数比除数还大）时，会把商调小或调大再算。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g4-n019",
        "商中间或末尾有0",
        4,
        ["pm-g4-n018"],
        ["divide", "ch-div2", "zero"],
        "某一位不够商 1 时会在商的这一位写 0，不把 0 漏掉或挪到别的数位上。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g4-n020",
        "商的变化规律",
        3,
        ["pm-g4-n012", "pm-g4-n017"],
        ["divide", "ch-div2", "pattern"],
        "知道被除数扩大（或缩小）若干倍、除数不变，商也扩大（或缩小）相同倍数；两者同时扩大相同倍数，商不变。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g4-n021",
        "除法估算",
        3,
        ["pm-g4-n013", "pm-g4-n016"],
        ["estimate", "ch-div2"],
        "能把被除数、除数看成接近的整百、整十再除，判断商大概是几十还是几百。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g4-n022",
        "乘除综合",
        4,
        ["pm-g4-n014", "pm-g4-n019", "pm-g4-n020", "pm-g4-n021"],
        ["fluency", "ch-div2", "boss-gate"],
        "综合三位数乘两位数、除数是两位数的除法、调商、商里的 0、估算和应用题。",
        mastery=MASTERY_GATE,
    ),
    # D. 四则运算与运算律
    node(
        "pm-g4-n023",
        "四则混合运算顺序",
        3,
        ["pm-g4-n022"],
        ["order", "ch-laws"],
        "没有括号时先乘除后加减、从左往右算；有小括号先算括号里，再认识中括号从里往外算。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g4-n024",
        "加法交换律与结合律",
        2,
        ["pm-g4-n023"],
        ["add", "ch-laws", "commutative"],
        "知道两个数相加交换位置和不变，三个数相加可以先把其中两个结合起来加，和也不变。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g4-n025",
        "乘法交换律与结合律",
        2,
        ["pm-g4-n023"],
        ["multiply", "ch-laws", "commutative"],
        "知道两个数相乘交换位置积不变，三个数相乘可以先把其中两个结合起来乘，积也不变。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g4-n026",
        "乘法分配律",
        3,
        ["pm-g4-n025"],
        ["multiply", "ch-laws", "distributive"],
        "知道两个数的和乘一个数，等于把两个加数分别与这个数相乘，再把积加起来。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g4-n027",
        "简便运算入门",
        4,
        ["pm-g4-n024", "pm-g4-n026"],
        ["mental", "ch-laws", "simplify"],
        "能根据运算律把算式变得更好算，如凑整、先乘能得整百的数、或把接近整百的数拆开再乘。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g4-n028",
        "运算律综合应用",
        4,
        ["pm-g4-n027"],
        ["fluency", "ch-laws", "application"],
        "在混合运算和短故事里选择合适的运算律或运算顺序，把计算变得清楚、简便。",
    ),
    # E. 小数的意义和性质、小数加减（本图自洽，不引用三年级节点 id）
    node(
        "pm-g4-n029",
        "小数的意义",
        2,
        ["pm-g4-n028"],
        ["decimal", "ch-dec", "concept"],
        "知道把「1」平均分成 10 份、100 份，十分之几、百分之几可以写成小数，小数点右边第一、二位是十分位、百分位。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g4-n030",
        "小数的读写与数位",
        2,
        ["pm-g4-n029"],
        ["decimal", "ch-dec", "place-value"],
        "会读、写一位和两位小数，能指出整数部分、十分位、百分位，并对照米与分米、厘米说一说。",
    ),
    node(
        "pm-g4-n031",
        "小数的性质",
        3,
        ["pm-g4-n030"],
        ["decimal", "ch-dec", "property"],
        "知道小数的末尾添上 0 或去掉 0，小数的大小不变，并能用来把两个小数变得数位同样多。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g4-n032",
        "小数大小比较",
        3,
        ["pm-g4-n031"],
        ["decimal", "ch-dec", "compare"],
        "比较小数时先看整数部分，再从十分位往右一位一位看；数位不同时可先补 0 再比。",
    ),
    node(
        "pm-g4-n033",
        "小数点移动与大小变化",
        3,
        ["pm-g4-n031"],
        ["decimal", "ch-dec", "point-shift"],
        "小数点向右移动一位、两位，原数就扩大 10 倍、100 倍；向左移动则缩小相同倍数。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g4-n034",
        "小数加减（对齐小数点）",
        3,
        ["pm-g4-n032"],
        ["decimal", "ch-dec", "add-sub"],
        "小数加减要把小数点对齐（相同数位对齐），再按整数加减的办法计算，得数里也要点上小数点。",
    ),
    node(
        "pm-g4-n035",
        "小数加减（位数不同）",
        4,
        ["pm-g4-n034"],
        ["decimal", "ch-dec", "add-sub"],
        "两个小数位数不同时，能先对齐小数点（需要时末尾补 0），完成进位加法或退位减法。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g4-n036",
        "小数加减应用",
        3,
        ["pm-g4-n035", "pm-g4-n033"],
        ["word-problem", "ch-dec", "application"],
        "在购物、测量等短情境里列出小数加减算式，并能先估一估得数是否合理。",
    ),
    # F. 小数乘除入门（软锁支线：系统学习多在五年级）
    node(
        "pm-g4-n037",
        "小数乘整数入门",
        3,
        ["pm-g4-n035"],
        ["decimal", "ch-dec-mul", "multiply"],
        "能把小数乘整数看成几个相同小数相加，或先按整数相乘再点上小数点，体会积的小数位数。",
        unlock=SOFT,
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g4-n038",
        "小数除以整数入门",
        3,
        ["pm-g4-n037"],
        ["decimal", "ch-dec-mul", "divide"],
        "能计算小数除以一位整数（商是小数）的入门题，除的过程中小数点要与被除数对齐。",
    ),
    node(
        "pm-g4-n039",
        "积与商里的小数点",
        4,
        ["pm-g4-n038"],
        ["decimal", "ch-dec-mul", "point"],
        "能根据因数或被除数的小数位数，说出积、商的小数点应点在哪里，并检查是否差了十倍。",
        mastery=MASTERY_CONCEPT,
    ),
    # G. 地图综合（小数乘除为软锁，不挡终章关主，通关前仍须点亮）
    node(
        "pm-g4-n040",
        "四年级数与运算综合",
        5,
        ["pm-g4-n008", "pm-g4-n022", "pm-g4-n028", "pm-g4-n036"],
        ["synthesis", "ch-final", "boss-gate"],
        "综合大数读写改写、三位数乘两位数、除数是两位数的除法、运算律简便运算和小数加减。",
        mastery=MASTERY_GATE,
    ),
]


EXTRA_EDGES = [
    {
        "from": "pm-g4-n002",
        "to": "pm-g4-n003",
        "type": "easily_confused",
        "note": "读的时候连续 0 只读一个零；写的时候每一个空位都要写 0。",
    },
    {
        "from": "pm-g4-n005",
        "to": "pm-g4-n006",
        "type": "easily_confused",
        "note": "用万改写是相等的；四舍五入得到的是近似数，和原数不一定相等。",
    },
    {
        "from": "pm-g4-n005",
        "to": "pm-g4-n007",
        "type": "related",
        "note": "用「万」作单位和用「亿」作单位，都是改计数单位、不改变相等关系。",
    },
    {
        "from": "pm-g4-n001",
        "to": "pm-g4-n007",
        "type": "related",
        "note": "万级数位排完之后，下一级是亿级：十亿、百亿、千亿。",
    },
    {
        "from": "pm-g4-n006",
        "to": "pm-g4-n013",
        "type": "application",
        "note": "四舍五入求近似数，正是乘法估算里「看成整十整百」的办法。",
    },
    {
        "from": "pm-g4-n010",
        "to": "pm-g4-n011",
        "type": "easily_confused",
        "note": "两层相乘时，每一层自己也可能进位，不要只加不进。",
    },
    {
        "from": "pm-g4-n009",
        "to": "pm-g4-n015",
        "type": "related",
        "note": "乘整十与除以整十互为口算伙伴，都可以先算前面的数字再处理 0。",
    },
    {
        "from": "pm-g4-n012",
        "to": "pm-g4-n020",
        "type": "easily_confused",
        "note": "积随一个因数变；商在除数不变时随被除数变，两者同时扩大则商不变。",
    },
    {
        "from": "pm-g4-n017",
        "to": "pm-g4-n018",
        "type": "easily_confused",
        "note": "试商是先估；乘完发现偏了，才需要调商。",
    },
    {
        "from": "pm-g4-n018",
        "to": "pm-g4-n019",
        "type": "related",
        "note": "调完商之后，还要检查这一位够不够商 1，不够就要写 0。",
    },
    {
        "from": "pm-g4-n011",
        "to": "pm-g4-n019",
        "type": "easily_confused",
        "note": "积里的 0 常来自因数有 0；商里的 0 常来自这一位不够商 1。",
    },
    {
        "from": "pm-g4-n013",
        "to": "pm-g4-n021",
        "type": "related",
        "note": "乘法估算和除法估算都是先看成整十整百，用来判断得数是否离谱。",
    },
    {
        "from": "pm-g4-n014",
        "to": "pm-g4-n022",
        "type": "easily_confused",
        "note": "「求一共、几倍」用乘；「求每份、份数」用除，故事里不要看错方向。",
    },
    {
        "from": "pm-g4-n024",
        "to": "pm-g4-n025",
        "type": "related",
        "note": "加法和乘法都有交换律、结合律；减法和除法一般不能随便换位置。",
    },
    {
        "from": "pm-g4-n025",
        "to": "pm-g4-n026",
        "type": "easily_confused",
        "note": "结合律是三个因数先乘哪两个；分配律是「和」去乘一个数，要拆开分别乘。",
    },
    {
        "from": "pm-g4-n023",
        "to": "pm-g4-n027",
        "type": "related",
        "note": "运算顺序保证算对；运算律用来把算式变得更好算。",
    },
    {
        "from": "pm-g4-n001",
        "to": "pm-g4-n029",
        "type": "related",
        "note": "整数相邻单位是十进；小数点右边继续十进，就是十分位、百分位。",
    },
    {
        "from": "pm-g4-n031",
        "to": "pm-g4-n033",
        "type": "easily_confused",
        "note": "末尾添 0 去 0，大小不变；小数点左右移动，大小会扩大或缩小。",
    },
    {
        "from": "pm-g4-n032",
        "to": "pm-g4-n033",
        "type": "related",
        "note": "比大小从高位看起；移动小数点改变的也是每一位的计数单位。",
    },
    {
        "from": "pm-g4-n034",
        "to": "pm-g4-n035",
        "type": "easily_confused",
        "note": "位数不同时仍应对齐小数点，不能改成把末尾数字上下对齐。",
    },
    {
        "from": "pm-g4-n029",
        "to": "pm-g4-n037",
        "type": "related",
        "note": "小数表示十分之几、百分之几，乘整数就是在求几个这样的小数。",
    },
    {
        "from": "pm-g4-n037",
        "to": "pm-g4-n038",
        "type": "easily_confused",
        "note": "乘整数时积的小数位数常跟因数走；除以整数时商的小数点要与被除数对齐。",
    },
    {
        "from": "pm-g4-n011",
        "to": "pm-g4-n014",
        "type": "application",
        "note": "三位数乘两位数服务于「每份同样多、求一共」的实际问题。",
    },
    {
        "from": "pm-g4-n018",
        "to": "pm-g4-n022",
        "type": "application",
        "note": "调商后的除法用来解决平均分与求份数。",
    },
    {
        "from": "pm-g4-n027",
        "to": "pm-g4-n028",
        "type": "application",
        "note": "简便运算用到需要选择运算律的综合题。",
    },
    {
        "from": "pm-g4-n034",
        "to": "pm-g4-n036",
        "type": "application",
        "note": "小数点对齐的加减用到购物、测量等短情境。",
    },
    {
        "from": "pm-g4-n036",
        "to": "pm-g4-n040",
        "type": "application",
        "note": "小数加减进入终章综合。",
    },
]


def quest(
    qid: str,
    node_id: str,
    title: str,
    qtype: str,
    xp: int,
    prompt: str,
    hint: str,
    items: int | None = None,
) -> dict:
    q = {
        "id": qid,
        "node_id": node_id,
        "title": title,
        "type": qtype,
        "xp": xp,
        "prompt": prompt,
        "success_hint": hint,
    }
    if items is not None:
        q["items_suggested"] = items
    return q


QUESTS = [
    # A
    quest(
        "pm-g4-n001-explain",
        "pm-g4-n001",
        "相邻单位是十进",
        "explain",
        10,
        "从个位说到亿：每相邻两个计数单位之间是什么关系？举「10 个万是 1 个十万」说明十进。",
        "从右边起每四位是一级：个级、万级，再往左是亿级。",
    ),
    quest(
        "pm-g4-n001-practice",
        "pm-g4-n001",
        "数位顺序表填空",
        "practice",
        15,
        "在数位顺序表里填出个、十、百、千、万、十万、百万、千万、亿，并指出万级包括哪几位。",
        "万级是：万、十万、百万、千万。",
        8,
    ),
    quest(
        "pm-g4-n002-explain",
        "pm-g4-n002",
        "按级来读",
        "explain",
        10,
        "读 30507000：先看万级是 3050 万，个级是 7000。说明连续的 0 怎样读，万级末尾的 0 读不读。",
        "先分级，再读每一级；连续的 0 只读一个零。",
    ),
    quest(
        "pm-g4-n002-practice",
        "pm-g4-n002",
        "亿以内数读一读",
        "practice",
        20,
        "读出若干亿以内的数，夹带中间有 0、末尾有 0、万级和个级都有 0 的情况。",
        "哪一级一个计数单位也没有，这一级就不必读。",
        8,
    ),
    quest(
        "pm-g4-n003-practice",
        "pm-g4-n003",
        "听到读法写下来",
        "practice",
        20,
        "根据读法写出亿以内的数，如「三千零六万零四十」「二百零八万」。空位用 0 占住。",
        "先想好有几位，再从高级写起，空位补 0。",
        8,
    ),
    quest(
        "pm-g4-n004-explain",
        "pm-g4-n004",
        "几个亿几个万几个一",
        "explain",
        10,
        "说出 40608000 由 4 个千万、6 个十万和 8 个千组成，并换一种方式用「万」来说明组成。",
        "同一级里也可以改用较大的计数单位来说组成。",
    ),
    quest(
        "pm-g4-n004-practice",
        "pm-g4-n004",
        "组成填空",
        "practice",
        20,
        "完成如 25060000＝□个万□个一；也能根据「3 个千万和 5 个百」写出这个数。",
        "哪一位上是 0，就表示这一位一个单位也没有。",
        8,
    ),
    quest(
        "pm-g4-n005-explain",
        "pm-g4-n005",
        "改写成多少万",
        "explain",
        10,
        "把 380000 改写成 38 万，说明「万」是新的计数单位，这个数和原来一样大。",
        "整万的数，末尾四个 0 可以收成「万」。",
    ),
    quest(
        "pm-g4-n005-practice",
        "pm-g4-n005",
        "用万作单位练",
        "practice",
        20,
        "把整万的数改写成用「万」作单位；也能把「72 万」改回原来的数。",
        "改写是相等的，不要四舍五入。",
        8,
    ),
    quest(
        "pm-g4-n006-explain",
        "pm-g4-n006",
        "四舍五入省略尾数",
        "explain",
        10,
        "把 384600 看成约多少万：看万后面第一位是 4，不到 5 就舍去，约是 38 万。说明近似数和原数的差别。",
        "看要省略的那一位的前一位（从右边数），满 5 向前入，不满 5 舍去。",
    ),
    quest(
        "pm-g4-n006-practice",
        "pm-g4-n006",
        "求近似数",
        "practice",
        20,
        "把若干数省略万后面的尾数，求出以万作单位的近似数；夹两道改写（不是近似）作对比。",
        "题目若说「约是多少万」，才用四舍五入。",
        8,
    ),
    quest(
        "pm-g4-n007-practice",
        "pm-g4-n007",
        "亿以上读写与改写",
        "practice",
        20,
        "读写含十亿、百亿的数，并把整亿的数改写成用「亿」作单位，如 300000000＝3 亿。",
        "亿级也按四位一级来读；整亿末尾八个 0 可收成「亿」。",
        8,
    ),
    quest(
        "pm-g4-n008-practice",
        "pm-g4-n008",
        "大数综合练",
        "practice",
        25,
        "混合：读法写法、组成、用万或亿改写、求近似数、比较两个大数的大小。",
        "比较大小时先看数位多少，数位同样多再从最高位比起。",
        12,
    ),
    quest(
        "pm-g4-n008-quiz",
        "pm-g4-n008",
        "大数认识小测",
        "mini_quiz",
        30,
        "限时混合检测：读、写、改写、近似数、比大小各至少一题，正确率达到掌握标准才过关。",
        "先分清题目要的是相等改写，还是大约多少。",
        10,
    ),
    quest(
        "pm-g4-boss-large",
        "pm-g4-n008",
        "关主：大数认识大闯关",
        "boss",
        80,
        "击败关主条件：①按级正确读、写一个含 0 的大数 ②说出组成 ③用万或亿作单位改写一题 ④四舍五入求一个以万作单位的近似数 ⑤比较两个大数的大小并说明理由。",
        "这一关之后，亿以内和亿以上的读写改写就打通了。",
        10,
    ),
    # B
    quest(
        "pm-g4-n009-explain",
        "pm-g4-n009",
        "乘整十先乘再补0",
        "explain",
        10,
        "把 24×30 看成 24×3 再在末尾补一个 0，把 120×40 看成 12×4 再补两个 0，说明 0 从哪里来。",
        "先乘没有 0 的那几位，原来有几个 0 积的末尾就先记下几个 0。",
    ),
    quest(
        "pm-g4-n009-practice",
        "pm-g4-n009",
        "整十口算乘",
        "practice",
        20,
        "口算 15×20、36×40、120×30、250×20 等，写出分步或补 0 的过程。",
        "可以先把整十看成几个十，再乘。",
        8,
    ),
    quest(
        "pm-g4-n010-practice",
        "pm-g4-n010",
        "两层相乘不进位",
        "practice",
        20,
        "竖式计算三位数乘两位数（两层暂不进位），检查第二层是否从十位写起。",
        "个位乘的积从个位写起，十位乘的积从十位写起。",
        6,
    ),
    quest(
        "pm-g4-n011-explain",
        "pm-g4-n011",
        "每一层自己进位",
        "explain",
        10,
        "用 216×34 说明：先用 4 去乘 216，再用 3 去乘 216；每一层满十只进在这一层，最后两层再相加。",
        "不要把第一层进上去的数加到第二层里。",
    ),
    quest(
        "pm-g4-n011-practice",
        "pm-g4-n011",
        "三位数乘两位数进位练",
        "practice",
        25,
        "竖式计算三位数乘两位数（含进位），夹一题因数中间有 0，积里的 0 不要写丢。",
        "两层分别进位，最后再把两层积相加。",
        8,
    ),
    quest(
        "pm-g4-n011-quiz",
        "pm-g4-n011",
        "乘两位数进位小测",
        "mini_quiz",
        30,
        "混合不进位与进位、因数有 0 的三位数乘两位数，先标出两层再计算。",
        "第二层末尾空出个位（或写 0），表示这是若干个十。",
        8,
    ),
    quest(
        "pm-g4-n012-explain",
        "pm-g4-n012",
        "一个因数变积也变",
        "explain",
        10,
        "比较 12×4 和 12×40：乘数扩大 10 倍，积也扩大 10 倍。再说说如果乘数缩小 10 倍，积怎样变。",
        "另一个因数不变时，积和变化的那个因数「同步」扩大或缩小。",
    ),
    quest(
        "pm-g4-n012-practice",
        "pm-g4-n012",
        "积怎样变",
        "practice",
        20,
        "已知一题乘法，说出一个因数扩大或缩小 10 倍、100 倍后积是多少，不必每次都重算竖式。",
        "积末尾的 0 会跟着增多或减少。",
        8,
    ),
    quest(
        "pm-g4-n013-explain",
        "pm-g4-n013",
        "先看成整十整百再乘",
        "explain",
        10,
        "把 198×32 看成 200×30，说明积大约是 6000，用来判断精确计算有没有算飞。",
        "估算先看高位，两边都可以看成接近的整十或整百。",
    ),
    quest(
        "pm-g4-n013-practice",
        "pm-g4-n013",
        "乘法估一估",
        "practice",
        20,
        "给几道三位数乘两位数，先估后算，或判断别人的积是否合理（如 210×48 不可能只有 800）。",
        "210×50＝10500，得数应在一万左右。",
        6,
    ),
    quest(
        "pm-g4-n014-explain",
        "pm-g4-n014",
        "每份同样多求一共",
        "explain",
        10,
        "每箱 125 本练习本，有 36 箱。用「几个几」说明为什么用乘法，并列出算式。",
        "每份同样多，求一共，就用乘法。",
    ),
    quest(
        "pm-g4-n014-practice",
        "pm-g4-n014",
        "乘法故事练习",
        "practice",
        20,
        "完成「每份同样多求一共」和「求几倍」短故事，数量需要三位数乘两位数。",
        "先找出「每份几个」和「有几份」。",
        4,
    ),
    # C
    quest(
        "pm-g4-n015-explain",
        "pm-g4-n015",
        "除以整十可以先除再看0",
        "explain",
        10,
        "把 800÷20 说成 80 个十除以 2 个十，或看成 800÷2÷10。说明两种想法人一样。",
        "先算前面的数字，0 再跟上；可用乘法验算。",
    ),
    quest(
        "pm-g4-n015-practice",
        "pm-g4-n015",
        "整十口算除",
        "practice",
        20,
        "口算 600÷30、900÷30、1200÷40、2400÷20 等，并用乘法验算两题。",
        "商乘除数应当回到被除数。",
        8,
    ),
    quest(
        "pm-g4-n016-explain",
        "pm-g4-n016",
        "除数是整十时怎样试商",
        "explain",
        10,
        "用竖式说明 96÷30：把 30 看成 3 个十，看 9 个十里面有几个 3 个十，商写在个位上。",
        "除到哪一位，商就写在哪一位的上面。",
    ),
    quest(
        "pm-g4-n016-practice",
        "pm-g4-n016",
        "用整十数除练",
        "practice",
        20,
        "竖式计算除数是整十的除法，商的数位要对齐，有余数时余数必须比除数小。",
        "不够除就看下一位，不要把商写错位。",
        8,
    ),
    quest(
        "pm-g4-n017-explain",
        "pm-g4-n017",
        "看成接近的整十来试",
        "explain",
        10,
        "计算 192÷32：把 32 看成 30 来试商，用 19 个十里面有几个 30 想初商，再乘一乘看准不准。",
        "试商是「先估一个」，乘完再检查。",
    ),
    quest(
        "pm-g4-n017-practice",
        "pm-g4-n017",
        "两位数除法试商练",
        "practice",
        20,
        "竖式计算除数是两位数（先选初商比较顺利）的除法，写出看成哪个整十。",
        "除数的个位是 1、2、3、4，常看成小一些的整十；是 5 到 9，常看成大一些的整十。",
        8,
    ),
    quest(
        "pm-g4-n018-explain",
        "pm-g4-n018",
        "偏了就把商调一调",
        "explain",
        10,
        "说明初商偏大：乘积比余下的数还大，要调小；初商偏小：余数比除数还大，还能再商 1，要调大。",
        "乘完立刻比一比：太大就减商，太小就加商。",
    ),
    quest(
        "pm-g4-n018-practice",
        "pm-g4-n018",
        "调商练习",
        "practice",
        25,
        "计算需要调商的两位数除法，至少各有一题偏大和偏小；用「商×除数+余数」验算。",
        "余数一定要比除数小，否则初商偏小。",
        8,
    ),
    quest(
        "pm-g4-n018-quiz",
        "pm-g4-n018",
        "试商与调商小测",
        "mini_quiz",
        30,
        "混合一次试准、需要调大、需要调小的题，正确率达到掌握标准才过关。",
        "先看成整十试，乘完再决定调不调。",
        8,
    ),
    quest(
        "pm-g4-n019-explain",
        "pm-g4-n019",
        "这一位不够商就写0",
        "explain",
        10,
        "说明 8120÷4 的伙伴题 2412÷12：某一位余下的数不够商 1 时，这一位必须写 0，再落下一位继续除。",
        "不够商 1 的那一位必须写 0，占住数位。",
    ),
    quest(
        "pm-g4-n019-practice",
        "pm-g4-n019",
        "商里的0",
        "practice",
        20,
        "计算商的中间或末尾有 0 的两位数除法，检查 0 有没有写丢。",
        "商少写一个 0，得数会差十倍。",
        8,
    ),
    quest(
        "pm-g4-n020-explain",
        "pm-g4-n020",
        "商什么时候变、什么时候不变",
        "explain",
        10,
        "比较 24÷8、240÷8 和 240÷80：被除数扩大 10 倍商怎样变；被除数和除数同时扩大 10 倍，商为什么不变。",
        "只动被除数，商跟着变；两个一起扩大同样倍数，商不变。",
    ),
    quest(
        "pm-g4-n020-practice",
        "pm-g4-n020",
        "商怎样变",
        "practice",
        20,
        "根据一道除法，说出被除数或除数扩大、缩小 10 倍后商是多少；夹两道「两个同时变」的题。",
        "想一想：是只变一边，还是两边一起变。",
        8,
    ),
    quest(
        "pm-g4-n021-explain",
        "pm-g4-n021",
        "先看成整十再除",
        "explain",
        10,
        "把 594÷28 看成 600÷30，说明商大约是 20，用来判断精确计算有没有算飞。",
        "估算先看高位，除数、被除数都可以看成接近的整十、整百。",
    ),
    quest(
        "pm-g4-n021-practice",
        "pm-g4-n021",
        "除法估一估",
        "practice",
        20,
        "给几道除数是两位数的除法，先估后算，或判断别人的商是否合理。",
        "594÷28 接近 600÷30＝20，不可能商 2，也不可能商 200。",
        6,
    ),
    quest(
        "pm-g4-n022-practice",
        "pm-g4-n022",
        "乘除综合练",
        "practice",
        25,
        "混合三位数乘两位数、除数是两位数、调商、商里有 0、估算和一则应用题。",
        "先判断是求一共、求每份，还是分不完。",
        12,
    ),
    quest(
        "pm-g4-n022-quiz",
        "pm-g4-n022",
        "乘除综合小测",
        "mini_quiz",
        30,
        "乘除混排加 1 道调商、1 道商有 0、1 道估算、1 则应用题，正确率达到掌握标准才过关。",
        "可以用乘除互逆当场验算。",
        12,
    ),
    quest(
        "pm-g4-boss-muldiv",
        "pm-g4-n022",
        "关主：乘除大闯关",
        "boss",
        90,
        "击败关主条件：①三位数乘两位数 2 题（含一题进位）②除数是两位数 2 题（含一题调商）③一道商中间或末尾有 0 ④先估再算或判断一题是否合理 ⑤一则用乘或除的短故事。",
        "竖式对齐数位，调商和商里的 0 最容易出错。",
        14,
    ),
    # D
    quest(
        "pm-g4-n023-explain",
        "pm-g4-n023",
        "先乘除后加减",
        "explain",
        10,
        "用 12+8×5 和 (12+8)×5 说明：没有括号时先算乘，有小括号先算括号里。再指出中括号要从里面一层算起。",
        "有括号先算括号；同级运算从左往右。",
    ),
    quest(
        "pm-g4-n023-practice",
        "pm-g4-n023",
        "混合运算顺序练",
        "practice",
        20,
        "计算含乘除加减、小括号，以及一题带中括号的四则混合运算，写出每一步的中间得数。",
        "可以在第一步下面标出小得数，避免跳步。",
        8,
    ),
    quest(
        "pm-g4-n024-explain",
        "pm-g4-n024",
        "加数换位置和不变",
        "explain",
        10,
        "用 25+37+75 说明：可以把 25 和 75 先加得 100，再加 37。指出这是结合律，交换位置则是交换律。",
        "交换是换两个加数的位置；结合是先加其中两个。",
    ),
    quest(
        "pm-g4-n024-practice",
        "pm-g4-n024",
        "加法运算律练",
        "practice",
        20,
        "判断或填写交换律、结合律，并用它们把几道连加变得更好算。",
        "看看哪两个加数凑在一起能得到整十、整百。",
        8,
    ),
    quest(
        "pm-g4-n025-explain",
        "pm-g4-n025",
        "因数换位置积不变",
        "explain",
        10,
        "用 25×17×4 说明：可以把 25 和 4 先乘得 100，再乘 17。指出交换律和结合律在乘法里同样成立。",
        "先乘能得到整百的那两个因数。",
    ),
    quest(
        "pm-g4-n025-practice",
        "pm-g4-n025",
        "乘法交换结合练",
        "practice",
        20,
        "判断或填写乘法交换律、结合律，并用它们计算 125×8×125 一类可以凑整的题（自编同类即可）。",
        "125×8＝1000，常常是凑整的好帮手。",
        8,
    ),
    quest(
        "pm-g4-n026-explain",
        "pm-g4-n026",
        "和乘一个数可以拆开乘",
        "explain",
        10,
        "用 102×7＝(100+2)×7＝100×7+2×7 说明分配律：把接近整百的数拆开，分别乘再加起来。",
        "两个数的和乘一个数＝两个加数分别乘这个数，再相加。",
    ),
    quest(
        "pm-g4-n026-practice",
        "pm-g4-n026",
        "分配律练",
        "practice",
        20,
        "用分配律计算如 101×23、98×6（看成 100×6−2×6）等，并指出哪一步在拆、哪一步在合。",
        "接近整十、整百时，拆成「整的加减差一点」。",
        8,
    ),
    quest(
        "pm-g4-n027-explain",
        "pm-g4-n027",
        "怎样变得更好算",
        "explain",
        10,
        "各举一道用结合律凑整、一道用分配律拆开的题，说出为什么这样算更快，而不是乱换运算顺序。",
        "简便运算仍然要遵守四则顺序，只是用定律换一种写法。",
    ),
    quest(
        "pm-g4-n027-practice",
        "pm-g4-n027",
        "简便运算入门练",
        "practice",
        25,
        "混合使用交换、结合、分配使计算简便；夹一道不能乱换顺序的干扰题（如 12÷3×2）。",
        "除法、减法一般不能随便换位置。",
        8,
    ),
    quest(
        "pm-g4-n027-quiz",
        "pm-g4-n027",
        "运算律小测",
        "mini_quiz",
        30,
        "判断该用哪一条运算律，并完成简便计算，正确率达到掌握标准才过关。",
        "先看能不能凑成整十、整百，再决定用结合还是分配。",
        8,
    ),
    quest(
        "pm-g4-n028-practice",
        "pm-g4-n028",
        "运算律综合练",
        "practice",
        20,
        "在混合运算和一则短故事里选择运算顺序或运算律，列出算式并算对。",
        "先问：这题是在考顺序，还是在考怎样凑整。",
        6,
    ),
    # E
    quest(
        "pm-g4-n029-explain",
        "pm-g4-n029",
        "十分之几写成小数",
        "explain",
        10,
        "把 1 平均分成 10 份，3 份是 3/10，写成 0.3；再分成 100 份，说明 0.07 是百分之七。指出十分位、百分位。",
        "小数点右边第一位是十分位，第二位是百分位。本图从这里系统学习小数，不依赖其他地图的节点。",
    ),
    quest(
        "pm-g4-n029-practice",
        "pm-g4-n029",
        "分数和小数互相对照",
        "practice",
        15,
        "在 1/10 与 0.1、7/100 与 0.07、3/10 与 0.3 之间来回改写，并指出各位上的数表示什么。",
        "十分位上是几就是十分之几；百分位上是几就是百分之几。",
        8,
    ),
    quest(
        "pm-g4-n030-practice",
        "pm-g4-n030",
        "小数读读写写",
        "practice",
        20,
        "读、写一位和两位小数，夹「3.05」「0.4」「10.08」；对照 3 米 5 分米写成 3.5 米。",
        "整数部分是 0 时，小数点左边仍要写 0。",
        10,
    ),
    quest(
        "pm-g4-n031-explain",
        "pm-g4-n031",
        "末尾的0可以添也可以去掉",
        "explain",
        10,
        "说明 0.5＝0.50：十分之五和百分之五十同样大。添 0 或去 0 只发生在小数末尾，不能删中间的 0。",
        "3.05 中间的 0 表示十分位一个也没有，不能去掉。",
    ),
    quest(
        "pm-g4-n031-practice",
        "pm-g4-n031",
        "小数性质练",
        "practice",
        20,
        "判断哪些小数相等（末尾添 0 去 0），哪些不相等；把 0.7 和 0.70、0.07 放在一起比较。",
        "只有末尾的 0 可以添或去；位置不同，大小就不同。",
        8,
    ),
    quest(
        "pm-g4-n032-explain",
        "pm-g4-n032",
        "谁更大先看整数部分",
        "explain",
        10,
        "比较 1.2 和 0.98、0.36 和 0.4。说明先比整数部分，再比十分位；位数不同时可以先补 0。",
        "0.4＝0.40，再和 0.36 比十分位、百分位。",
    ),
    quest(
        "pm-g4-n032-practice",
        "pm-g4-n032",
        "小数比大小",
        "practice",
        20,
        "比较一位、两位小数的大小，填＞＜＝，夹两道位数不同的题。",
        "不要只看「谁的数字多」，要按数位对齐来比。",
        8,
    ),
    quest(
        "pm-g4-n033-explain",
        "pm-g4-n033",
        "小数点一移大小就变",
        "explain",
        10,
        "把 3.6 的小数点向右移一位变成 36，说明扩大 10 倍；向左移一位变成 0.36，说明缩小 10 倍。",
        "向右移扩大，向左移缩小；移几位就是 10 的几次方倍。",
    ),
    quest(
        "pm-g4-n033-practice",
        "pm-g4-n033",
        "移动小数点",
        "practice",
        20,
        "按要求把小数点向左或向右移动，写出新的数，并说出扩大或缩小了多少倍。",
        "整数部分不够时，要在小数点左边补 0，如 3.6 向左移两位是 0.036。",
        8,
    ),
    quest(
        "pm-g4-n034-explain",
        "pm-g4-n034",
        "小数点对齐再加减",
        "explain",
        10,
        "用 3.5+1.2、4.8−1.3 说明：小数点对齐就是十分位对十分位，再按整数加减的办法算。",
        "小数点对齐后，从最低位算起；得数的小数点也要对齐。",
    ),
    quest(
        "pm-g4-n034-practice",
        "pm-g4-n034",
        "小数加减对齐练",
        "practice",
        20,
        "计算位数相同的小数加减，检查小数点有没有对齐、得数的小数点有没有丢。",
        "得数末尾的 0 可以按性质去掉，但小数点不能丢。",
        8,
    ),
    quest(
        "pm-g4-n035-practice",
        "pm-g4-n035",
        "位数不同的小数加减",
        "practice",
        25,
        "计算位数不同的小数加减，含进位和退位，如 3.6+0.85、5−1.28。需要对齐小数点。",
        "整数加减小数时，整数可以看成小数点在末尾。",
        8,
    ),
    quest(
        "pm-g4-n035-quiz",
        "pm-g4-n035",
        "小数加减小测",
        "mini_quiz",
        30,
        "混合位数相同、位数不同、进位、退位的小数加减，正确率达到掌握标准才过关。",
        "先点齐小数点，再决定要不要末尾补 0。",
        8,
    ),
    quest(
        "pm-g4-n036-explain",
        "pm-g4-n036",
        "故事里的小数加减",
        "explain",
        10,
        "一本书 12.5 元，一枝笔 3.8 元。说明「一共」和「还差多少」各用加还是减，并先估一估大约多少元。",
        "先找到已知的那个数，再看是合起来还是去掉、比较。",
    ),
    quest(
        "pm-g4-n036-practice",
        "pm-g4-n036",
        "小数加减故事",
        "practice",
        20,
        "完成「一共、还剩、比多」的小数短情境各一则，并列式计算；其中一则先估再算。",
        "估算时可以把小数看成接近的整数或一位小数。",
        4,
    ),
    # F
    quest(
        "pm-g4-n037-explain",
        "pm-g4-n037",
        "几个相同的小数",
        "explain",
        10,
        "把 1.2×3 看成 1.2+1.2+1.2，或先算 12×3 再点上小数点。说明积里为什么有一位小数。",
        "小数乘整数：可以先当整数乘，再看因数一共有几位小数。这是入门，系统学习多在五年级。",
    ),
    quest(
        "pm-g4-n037-practice",
        "pm-g4-n037",
        "小数乘整数入门练",
        "practice",
        20,
        "计算一位小数乘一位整数，如 0.4×5、1.3×4、2.5×6，并说出积的小数点点在哪里。",
        "因数里一共有几位小数，积里通常也先点几位，末尾的 0 可以再去掉。",
        8,
    ),
    quest(
        "pm-g4-n038-explain",
        "pm-g4-n038",
        "平均分成几份",
        "explain",
        10,
        "把 1.2 平均分成 3 份，说明 1.2÷3＝0.4。竖式里商的小数点要和被除数的小数点对齐。",
        "除到小数部分，先在商上点好小数点，再继续往下除。",
    ),
    quest(
        "pm-g4-n038-practice",
        "pm-g4-n038",
        "小数除以整数入门练",
        "practice",
        20,
        "计算小数除以一位整数的入门题，如 2.8÷4、0.9÷3、6.4÷2，检查商的小数点。",
        "整数部分不够除时，商的整数部分写 0，再除小数部分。",
        6,
    ),
    quest(
        "pm-g4-n039-practice",
        "pm-g4-n039",
        "小数点点在哪里",
        "practice",
        20,
        "给几道小数乘整数、小数除以整数，先说出积或商的小数点应在哪，再计算并检查是否差了十倍。",
        "点错一位，得数就会差十倍；可以用估算先看数量级。",
        6,
    ),
    # G
    quest(
        "pm-g4-n040-practice",
        "pm-g4-n040",
        "地图综合练",
        "practice",
        25,
        "题型混合：大数读写或改写、三位数乘两位数、除数是两位数（可含调商）、简便运算、小数加减、一则估算。",
        "先判断这题在考哪一盏已点亮的灯。",
        12,
    ),
    quest(
        "pm-g4-boss-map",
        "pm-g4-n040",
        "关主：四年级数与运算通关试炼",
        "boss",
        100,
        "最终关主：①读或改写一个大数 ②三位数乘两位数 1 题 ③除数是两位数 1 题（可含调商）④用运算律做一道简便运算 ⑤小数加减 1 题 ⑥用估算判断一道计算是否合理。全部通过即通关本地图。",
        "通关后这张地图记入已通关列表。三年级地图的万以内数位与一位小数初步，和本地图起点、小数意义在概念上衔接，但存档仍按图分别计算，暂无跨地图引擎。",
        18,
    ),
]


META = {
    "id": "pm-g4-numbers",
    "title": "四年级 · 数与运算",
    "subject": "数学",
    "stage": "小学",
    "grade": 4,
    "strand": "数与代数",
    "version": "0.1.0",
    "locale": "zh-CN",
    "start_node_ids": ["pm-g4-n001"],
    "recommended_path_note": "从「计数单位：从万到亿」进入：先打通大数读写改写与近似数，再三位数乘两位数、除数是两位数的除法（含调商），然后四则运算与运算律、简便运算，最后小数意义与加减。小数乘除入门（n037）为软锁支线（四年级下/五年级衔接），不挡终章关主，通关前仍须点亮。",
    "win_condition": {
        "type": "light_all_nodes_and_bosses",
        "required_node_ids": "all",
        "required_boss_quest_ids": [
            "pm-g4-boss-large",
            "pm-g4-boss-muldiv",
            "pm-g4-boss-map",
        ],
        "summary": "点亮全部知识点，并击败三名关主：大数认识、乘除大闯关、地图通关试炼。",
    },
    "content_disclaimer": "知识点与任务为课标/教材目录风格的原创教学大纲与自编提示语，不是任何版本教科书正文或习题的摘录。",
    "description": "小学四年级「数与代数」地图：大数认识 → 三位数乘两位数 → 除数是两位数的除法 → 运算律与简便运算 → 小数意义与加减；小数乘除入门为软锁支线。与三年级地图概念衔接，但各自独立通关。",
}


SAMPLE_PROGRESS = {
    "player_id": "demo-learner",
    "display_name": "小明",
    "xp_total": 20,
    "current_map_id": "pm-g4-numbers",
    "cleared_map_ids": [],
    "nodes": {
        "pm-g4-n001": {
            "state": "lit",
            "xp_earned": 10,
            "cleared_quest_ids": ["pm-g4-n001-explain"],
            "updated_at": "2026-09-17T10:00:00Z",
        },
        "pm-g4-n002": {
            "state": "learning",
            "xp_earned": 10,
            "cleared_quest_ids": ["pm-g4-n002-explain"],
            "updated_at": "2026-09-17T10:08:00Z",
        },
    },
}


def prereq_edges(nodes: list[dict]) -> list[dict]:
    edges = []
    for n in nodes:
        for src in n["prerequisites"]:
            edges.append(
                {
                    "from": src,
                    "to": n["id"],
                    "type": "prerequisite",
                    "note": f"{src} 需先于 {n['id']}",
                }
            )
    return edges


def dump(path: Path, data) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")


def _assert_field_limits() -> None:
    """Fail fast if learner-facing strings exceed schema limits."""
    for n in NODES:
        assert 1 <= len(n["title"]) <= 40, n["title"]
        assert 8 <= len(n["description"]) <= 160, (n["id"], len(n["description"]), n["description"])
    for q in QUESTS:
        assert 1 <= len(q["title"]) <= 40, q["title"]
        assert 4 <= len(q["prompt"]) <= 400, (q["id"], len(q["prompt"]))
        hint = q.get("success_hint") or ""
        assert len(hint) <= 200, (q["id"], len(hint))
    for e in EXTRA_EDGES:
        note = e.get("note") or ""
        assert len(note) <= 120, (e["from"], e["to"], len(note), note)
    covered = {q["node_id"] for q in QUESTS}
    missing = [n["id"] for n in NODES if n["id"] not in covered]
    assert not missing, f"nodes without quests: {missing}"


def main() -> None:
    _assert_field_limits()
    OUT.mkdir(parents=True, exist_ok=True)
    edges = prereq_edges(NODES) + EXTRA_EDGES
    dump(OUT / "nodes.json", {"map_id": META["id"], "nodes": NODES})
    dump(OUT / "edges.json", {"map_id": META["id"], "edges": edges})
    dump(OUT / "quests.json", {"map_id": META["id"], "quests": QUESTS})
    dump(OUT / "map.meta.json", META)
    dump(OUT / "player-progress.sample.json", SAMPLE_PROGRESS)


if __name__ == "__main__":
    main()
