"""Build Grade 6 Geometry map JSON from a single source of truth.

Run: python3 scripts/_build_grade6_geometry.py

Pedagogical spine (课标/人教脉络风格，自撰短描述，非教材页原文):
  长方体与正方体（认识、展开图、表面积、体积容积）
  → 圆柱与圆锥
  → 比例尺、图形放大与缩小
  → 观察物体与小学图形收束。
简单路线图与方向为软锁支线。
本图自洽：立体从长方体重新铺垫，不引用五年级圆或数与运算节点 id。
圆的周长面积已在五年级几何图；本图用「底面是圆」直观认识圆柱，不把圆公式节点当前置。
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _geo_common import (
    MASTERY_CONCEPT,
    MASTERY_GATE,
    ROOT,
    SOFT,
    node as _node,
    quest,
    write_map,
)

OUT = ROOT / "maps" / "primary-math" / "grade-6-geometry"
G = 6


def node(nid, title, difficulty, prereqs, tags, description, *, unlock=None, mastery=None):
    return _node(
        nid, title, G, difficulty, prereqs, tags, description, unlock=unlock, mastery=mastery
    )


NODES = [
    node(
        "pm-g6-geo-n001",
        "长方体的认识",
        1,
        [],
        ["prism", "ch-box"],
        "能指出长方体的面、棱、顶点，说出相对的面大小相等，相交于一个顶点的三条棱可以当作长、宽、高。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-geo-n002",
        "正方体的认识",
        2,
        ["pm-g6-geo-n001"],
        ["prism", "ch-box", "cube"],
        "能说明正方体是特殊的长方体：六个面都是正方形，十二条棱都相等。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-geo-n003",
        "长方体的展开图",
        3,
        ["pm-g6-geo-n001"],
        ["prism", "ch-box", "net"],
        "能辨认长方体的展开图：六个长方形怎样排才折得拢，相对的面不要重叠在错误位置。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-geo-n004",
        "正方体的展开图",
        3,
        ["pm-g6-geo-n002", "pm-g6-geo-n003"],
        ["prism", "ch-box", "net"],
        "能辨认正方体常见展开图（如「一」字四连、土字形），排除折起来会重叠或缺面的排法。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-geo-n005",
        "长方体的表面积",
        3,
        ["pm-g6-geo-n003"],
        ["prism", "ch-box", "surface"],
        "能把六个面的面积加起来求长方体表面积：2×（长×宽 + 长×高 + 宽×高）。",
    ),
    node(
        "pm-g6-geo-n006",
        "正方体的表面积",
        3,
        ["pm-g6-geo-n004", "pm-g6-geo-n005"],
        ["prism", "ch-box", "surface"],
        "能用 6×棱长×棱长 求正方体表面积，并与长方体公式对照。",
    ),
    node(
        "pm-g6-geo-n007",
        "体积表示什么",
        2,
        ["pm-g6-geo-n002"],
        ["volume", "ch-box"],
        "知道体积表示物体所占空间的大小，能用小正方体摆一摆感受「占了几块」。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-geo-n008",
        "体积单位",
        2,
        ["pm-g6-geo-n007"],
        ["volume", "ch-box", "unit"],
        "认识立方厘米、立方分米、立方米，能选择量橡皮、纸箱、房间各用哪个单位。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-geo-n009",
        "长方体的体积",
        3,
        ["pm-g6-geo-n008", "pm-g6-geo-n001"],
        ["volume", "ch-box"],
        "能用长×宽×高求长方体体积，并理解它等于底面积×高。",
    ),
    node(
        "pm-g6-geo-n010",
        "正方体的体积",
        3,
        ["pm-g6-geo-n009", "pm-g6-geo-n002"],
        ["volume", "ch-box"],
        "能用棱长×棱长×棱长求正方体体积。",
    ),
    node(
        "pm-g6-geo-n011",
        "容积与体积",
        3,
        ["pm-g6-geo-n010"],
        ["volume", "ch-box", "capacity"],
        "知道容积是容器里面能装多少，常用升、毫升；1 立方分米 = 1 升，1 立方厘米 = 1 毫升。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-geo-n012",
        "长方体正方体综合",
        4,
        ["pm-g6-geo-n006", "pm-g6-geo-n011"],
        ["prism", "ch-box", "boss-gate"],
        "能区分表面积和体积，完成展开图、求面积或体积、容积换算的章节收束。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g6-geo-n013",
        "圆柱的认识",
        2,
        ["pm-g6-geo-n001"],
        ["cylinder", "ch-cyl"],
        "能指出圆柱的两个圆形底面和一个侧面，高是两底之间的垂直距离。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-geo-n014",
        "圆柱的展开图",
        3,
        ["pm-g6-geo-n013", "pm-g6-geo-n003"],
        ["cylinder", "ch-cyl", "net"],
        "能说明圆柱侧面展开是长方形：长等于底面周长，宽等于圆柱的高。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-geo-n015",
        "圆柱的表面积",
        4,
        ["pm-g6-geo-n014", "pm-g6-geo-n005"],
        ["cylinder", "ch-cyl", "surface"],
        "能求圆柱表面积：两个底面积加侧面积。侧面积 = 底面周长 × 高。",
    ),
    node(
        "pm-g6-geo-n016",
        "圆柱的体积",
        4,
        ["pm-g6-geo-n015", "pm-g6-geo-n009"],
        ["cylinder", "ch-cyl", "volume"],
        "能用底面积×高求圆柱体积，底面积是圆面积；已知直径时先求半径。",
    ),
    node(
        "pm-g6-geo-n017",
        "圆锥的认识",
        2,
        ["pm-g6-geo-n013"],
        ["cone", "ch-cyl"],
        "能指出圆锥有一个圆形底面和一个顶点，高是顶点到底面圆心的垂直距离。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-geo-n018",
        "圆锥的体积",
        4,
        ["pm-g6-geo-n017", "pm-g6-geo-n016"],
        ["cone", "ch-cyl", "volume"],
        "知道等底等高时圆锥体积是圆柱的三分之一：V = (1/3) × 底面积 × 高。",
    ),
    node(
        "pm-g6-geo-n019",
        "圆柱圆锥综合",
        4,
        ["pm-g6-geo-n018"],
        ["cylinder", "ch-cyl", "boss-gate"],
        "能区分侧面积、表面积和体积，完成圆柱圆锥章节收束检查。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g6-geo-n020",
        "比例尺",
        3,
        ["pm-g6-geo-n001"],
        ["scale", "ch-scale"],
        "知道比例尺 = 图上距离 : 实际距离，能读懂 1:10000 这类数值比例尺。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-geo-n021",
        "求图上或实际距离",
        3,
        ["pm-g6-geo-n020"],
        ["scale", "ch-scale"],
        "能根据比例尺在图上距离和实际距离之间换算，注意单位要先统一。",
    ),
    node(
        "pm-g6-geo-n022",
        "图形的放大",
        3,
        ["pm-g6-geo-n021"],
        ["scale", "ch-scale", "enlarge"],
        "能在方格纸上按指定倍数放大简单图形，对应角不变、对应边成比例。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-geo-n023",
        "图形的缩小",
        3,
        ["pm-g6-geo-n022"],
        ["scale", "ch-scale", "reduce"],
        "能按指定倍数缩小图形，并说明缩小后形状不变、面积不是按同样倍数减少。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-geo-n024",
        "放大缩小与比例尺",
        3,
        ["pm-g6-geo-n023"],
        ["scale", "ch-scale"],
        "能把地图、图纸上的放大缩小与比例尺联系起来：图上 1 厘米代表实际多少。",
    ),
    node(
        "pm-g6-geo-n025",
        "从上面前面左面看",
        3,
        ["pm-g6-geo-n012"],
        ["view", "ch-end"],
        "能综合长方体、圆柱等，辨认从上面、前面、左面看到的轮廓。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-geo-n026",
        "立体图形关系",
        4,
        ["pm-g6-geo-n019", "pm-g6-geo-n012"],
        ["solid", "ch-end"],
        "能用自己的话串起长方体、正方体、圆柱、圆锥：谁是谁的特例，体积怎样比。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g6-geo-n027",
        "展开图易混专练",
        4,
        ["pm-g6-geo-n014", "pm-g6-geo-n004"],
        ["net", "ch-end"],
        "能在长方体、正方体、圆柱展开图里指出哪一张折不拢，哪一张侧面不是长方形。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g6-geo-n028",
        "测量与图纸",
        3,
        ["pm-g6-geo-n024", "pm-g6-geo-n011"],
        ["scale", "ch-end", "application"],
        "能在「水箱容积」和「图纸上的房间」两类问题里选择体积或比例尺。",
    ),
    node(
        "pm-g6-geo-n029",
        "小学图形总复习",
        4,
        ["pm-g6-geo-n026", "pm-g6-geo-n024", "pm-g6-geo-n025"],
        ["mixed", "ch-end"],
        "能回顾平面与立体、周长面积体积、运动与比例尺，知道遇到问题先判断在考哪一块。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g6-geo-n030",
        "六年级图形通关",
        5,
        ["pm-g6-geo-n029"],
        ["mixed", "ch-end", "boss-gate"],
        "综合长方体圆柱圆锥、比例尺与放大缩小、展开图，完成本图及小学图形线收束检查。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g6-geo-n031",
        "路线图与方向",
        2,
        ["pm-g6-geo-n025"],
        ["direction", "ch-end"],
        "能在简单平面图上用东南西北描述路线，作为位置与方向的小学收束。",
        unlock=SOFT,
        mastery=MASTERY_CONCEPT,
    ),
]


EXTRA_EDGES = [
    {
        "from": "pm-g6-geo-n001",
        "to": "pm-g6-geo-n002",
        "type": "related",
        "note": "正方体是长、宽、高都相等的长方体。",
    },
    {
        "from": "pm-g6-geo-n003",
        "to": "pm-g6-geo-n005",
        "type": "application",
        "note": "展开图六个面铺平，正好帮助理解和计算表面积。",
    },
    {
        "from": "pm-g6-geo-n005",
        "to": "pm-g6-geo-n009",
        "type": "easily_confused",
        "note": "表面积是六个面的总面积，体积是所占空间；单位一个是平方，一个是立方。",
    },
    {
        "from": "pm-g6-geo-n011",
        "to": "pm-g6-geo-n009",
        "type": "easily_confused",
        "note": "容积看容器里面，体积看物体本身；数字上常能换算，意思不同。",
    },
    {
        "from": "pm-g6-geo-n014",
        "to": "pm-g6-geo-n015",
        "type": "related",
        "note": "侧面展开成长方形，长是底面周长，所以侧面积 = 底面周长 × 高。",
    },
    {
        "from": "pm-g6-geo-n015",
        "to": "pm-g6-geo-n016",
        "type": "easily_confused",
        "note": "侧面积只包一圈，表面积还要加两个底；体积是底面积乘高。",
    },
    {
        "from": "pm-g6-geo-n016",
        "to": "pm-g6-geo-n018",
        "type": "easily_confused",
        "note": "等底等高时圆锥是圆柱的三分之一，不要漏乘 1/3，也不要除以 2。",
    },
    {
        "from": "pm-g6-geo-n009",
        "to": "pm-g6-geo-n016",
        "type": "related",
        "note": "柱体体积都可以看成底面积乘高，底从长方形换成圆。",
    },
    {
        "from": "pm-g6-geo-n022",
        "to": "pm-g6-geo-n023",
        "type": "related",
        "note": "放大与缩小都是相似变化：角不变，边成比例。",
    },
    {
        "from": "pm-g6-geo-n023",
        "to": "pm-g6-geo-n020",
        "type": "easily_confused",
        "note": "边长缩小到 1/2，面积缩小到 1/4，不要按同一倍数去估面积。",
    },
    {
        "from": "pm-g6-geo-n020",
        "to": "pm-g6-geo-n024",
        "type": "application",
        "note": "比例尺就是图纸把实际图形按倍数缩小后的记录方式。",
    },
    {
        "from": "pm-g6-geo-n004",
        "to": "pm-g6-geo-n014",
        "type": "related",
        "note": "展开图都是把立体的面铺到平面上，只是面的形状不同。",
    },
    {
        "from": "pm-g6-geo-n025",
        "to": "pm-g6-geo-n031",
        "type": "related",
        "note": "观察物体和路线图都是在用不同方向描述空间。",
    },
    {
        "from": "pm-g6-geo-n027",
        "to": "pm-g6-geo-n015",
        "type": "application",
        "note": "展开图看错，侧面积就会把底面周长用错。",
    },
]


QUESTS = [
    quest(
        "pm-g6-geo-n001-explain",
        "pm-g6-geo-n001",
        "面棱顶点",
        "explain",
        10,
        "拿一个纸盒，数面、棱、顶点的个数，指出相交于一个顶点的三条棱。",
        "6 个面、12 条棱、8 个顶点是长方体的基本数。",
    ),
    quest(
        "pm-g6-geo-n002-explain",
        "pm-g6-geo-n002",
        "特殊的长方体",
        "explain",
        10,
        "说明正方体为什么可以算长方体，并指出六个面都是正方形。",
        "长、宽、高都相等时就是正方体。",
    ),
    quest(
        "pm-g6-geo-n003-practice",
        "pm-g6-geo-n003",
        "哪张能折成盒子",
        "practice",
        20,
        "给 6 张长方体展开图，判断哪些能折成盒子，指出失败的原因（重叠或缺面）。",
        "相对的面在展开图上不能靠得「隔一张就叠上」。",
        6,
    ),
    quest(
        "pm-g6-geo-n004-practice",
        "pm-g6-geo-n004",
        "正方体展开图辨认",
        "practice",
        20,
        "给 8 张六个正方形的排法，选出能折成正方体的，排除「一」字六个连在一起等。",
        "一排超过四个，或出现「凹」得太散，常常折不拢。",
        8,
    ),
    quest(
        "pm-g6-geo-n005-practice",
        "pm-g6-geo-n005",
        "六个面加起来",
        "practice",
        20,
        "求 4 个长方体表面积；其中一题缺一个面（无盖纸箱），不要乘 2 次那个面。",
        "先想有几个面露在外面。",
        4,
    ),
    quest(
        "pm-g6-geo-n006-practice",
        "pm-g6-geo-n006",
        "六个正方形",
        "practice",
        20,
        "求棱长 5 厘米、2 分米的正方体表面积，注意单位。",
        "6 个相同的正方形面积相加。",
        4,
    ),
    quest(
        "pm-g6-geo-n007-explain",
        "pm-g6-geo-n007",
        "占了多少空间",
        "explain",
        10,
        "用 1 立方厘米的小正方体摆一个小长方体，数一数占了几块，说明这就是体积。",
        "体积是「占地方」，不是「包外面」。",
    ),
    quest(
        "pm-g6-geo-n008-practice",
        "pm-g6-geo-n008",
        "选体积单位",
        "practice",
        20,
        "给橡皮、词典、纸箱、教室选择立方厘米、立方分米或立方米，并完成 1 立方分米 = □ 立方厘米。",
        "边长单位连乘三次，体积单位就是立方。",
        6,
    ),
    quest(
        "pm-g6-geo-n009-practice",
        "pm-g6-geo-n009",
        "长乘宽乘高",
        "practice",
        20,
        "求 4 个长方体体积，其中一题给出底面积和高，用底面积×高。",
        "三个长度相乘，单位是立方。",
        4,
    ),
    quest(
        "pm-g6-geo-n010-practice",
        "pm-g6-geo-n010",
        "棱长的三次方",
        "practice",
        20,
        "求棱长 4 厘米、1 分米的正方体体积，并与同棱长的表面积对照，说出单位不同。",
        "体积是棱长×棱长×棱长。",
        4,
    ),
    quest(
        "pm-g6-geo-n011-explain",
        "pm-g6-geo-n011",
        "瓶子能装多少",
        "explain",
        10,
        "说明容积是容器里面的空间，1 升等于 1 立方分米。拿水瓶比划大约 500 毫升。",
        "容积常用升、毫升来写。",
    ),
    quest(
        "pm-g6-geo-n011-practice",
        "pm-g6-geo-n011",
        "升和毫升",
        "practice",
        15,
        "完成 2 升 = □ 毫升、500 毫升 = □ 立方厘米，并求一个无盖长方体水箱能装多少升。",
        "1 立方厘米对应 1 毫升。",
        4,
    ),
    quest(
        "pm-g6-geo-n012-practice",
        "pm-g6-geo-n012",
        "表面积还是体积",
        "practice",
        20,
        "10 道短题先判断表面积/体积/容积，再计算其中 6 道。含无盖纸箱。",
        "刷油漆、包包装纸多半是表面积；装东西是体积或容积。",
        10,
    ),
    quest(
        "pm-g6-geo-n012-quiz",
        "pm-g6-geo-n012",
        "长方体小测",
        "mini_quiz",
        30,
        "展开图判断、表面积、体积、容积换算。夹一道单位写成平方的改错。",
        "体积单位必须是立方。",
        8,
    ),
    quest(
        "pm-g6-geo-boss-box",
        "pm-g6-geo-n012",
        "关主：长方体工匠",
        "boss",
        80,
        "击败关主：①辨认一张展开图 ②求长方体或正方体表面积 ③求体积 ④完成一题容积换算。",
        "先问包外面还是占里面。",
        12,
    ),
    quest(
        "pm-g6-geo-n013-explain",
        "pm-g6-geo-n013",
        "两个圆底一个侧面",
        "explain",
        10,
        "指出茶叶罐的两个底面和一个侧面，用直尺说明高是两底之间的垂直距离。",
        "高不要沿着侧面斜着量。",
    ),
    quest(
        "pm-g6-geo-n014-explain",
        "pm-g6-geo-n014",
        "侧面展开成长方形",
        "explain",
        10,
        "把圆柱学具的侧面标签撕开（或想象），说明展开后的长为什么等于底面周长。",
        "围一圈的那条线，拉开就是长方形的长。",
    ),
    quest(
        "pm-g6-geo-n015-practice",
        "pm-g6-geo-n015",
        "侧面积加两个底",
        "practice",
        20,
        "求 3 个圆柱表面积；另有一题只求侧面积（一圈商标纸）。π 取 3.14。",
        "商标纸常常只要侧面积，不要加底。",
        4,
    ),
    quest(
        "pm-g6-geo-n016-practice",
        "pm-g6-geo-n016",
        "底面积乘高",
        "practice",
        20,
        "求 4 个圆柱体积，已知条件有的是半径、有的是直径。π 取 3.14。",
        "先求底面半径，再 πr²，再乘高。",
        4,
    ),
    quest(
        "pm-g6-geo-n017-explain",
        "pm-g6-geo-n017",
        "一个顶点一个圆底",
        "explain",
        10,
        "指出圆锥的底面和顶点，说明高要垂直到底面圆心，不能沿着斜面量。",
        "斜面的长度不是高。",
    ),
    quest(
        "pm-g6-geo-n018-explain",
        "pm-g6-geo-n018",
        "三分之一",
        "explain",
        10,
        "用等底等高的圆柱和圆锥学具做装沙实验（或看图），说明圆锥体积是圆柱的三分之一。",
        "公式里的 1/3 不要丢掉。",
    ),
    quest(
        "pm-g6-geo-n018-practice",
        "pm-g6-geo-n018",
        "圆锥体积计算",
        "practice",
        20,
        "求 3 个圆锥体积；再给等底等高的圆柱体积，求对应圆锥体积。π 取 3.14。",
        "V = (1/3)πr²h。",
        4,
    ),
    quest(
        "pm-g6-geo-n019-practice",
        "pm-g6-geo-n019",
        "圆柱圆锥闯关",
        "practice",
        20,
        "混合：展开图、侧面积、表面积、圆柱体积、圆锥体积。夹一道漏乘 1/3 的改错。",
        "先认是柱还是锥，再决定要不要 1/3。",
        8,
    ),
    quest(
        "pm-g6-geo-n019-quiz",
        "pm-g6-geo-n019",
        "圆柱圆锥小测",
        "mini_quiz",
        30,
        "侧面积与表面积、体积公式选择、等底等高比较。",
        "圆锥体积是圆柱的三分之一，不是一半。",
        8,
    ),
    quest(
        "pm-g6-geo-boss-cylinder",
        "pm-g6-geo-n019",
        "关主：圆柱圆锥工匠",
        "boss",
        80,
        "击败关主：①说明侧面展开 ②求圆柱侧面积或表面积 ③求圆柱体积 ④求圆锥体积（含 1/3）。",
        "底面是圆，先找半径；锥体记得三分之一。",
        12,
    ),
    quest(
        "pm-g6-geo-n020-explain",
        "pm-g6-geo-n020",
        "图上1厘米代表什么",
        "explain",
        10,
        "读 1:10000 的比例尺，说明图上 1 厘米代表实际 10000 厘米（合多少米）。",
        "比例尺是图上比实际，单位要先相同。",
    ),
    quest(
        "pm-g6-geo-n021-practice",
        "pm-g6-geo-n021",
        "图上实际互求",
        "practice",
        20,
        "已知比例尺，由图上距离求实际、由实际求图上各 3 题，统一单位。",
        "实际 = 图上 ÷ 比例尺前项 × 后项（先化成同一单位）。",
        6,
    ),
    quest(
        "pm-g6-geo-n022-practice",
        "pm-g6-geo-n022",
        "按格放大",
        "practice",
        20,
        "在方格纸上把一个直角三角形各边放大到 2 倍，检查角有没有变。",
        "对应边乘同一倍数，角保持不变。",
        2,
    ),
    quest(
        "pm-g6-geo-n023-explain",
        "pm-g6-geo-n023",
        "边缩一半面积呢",
        "explain",
        10,
        "把边长 4 格的正方形缩成边长 2 格，比较面积变成几分之几。",
        "边长比是 1/2，面积比是 1/4。",
    ),
    quest(
        "pm-g6-geo-n024-practice",
        "pm-g6-geo-n024",
        "图纸上的房间",
        "practice",
        20,
        "根据比例尺和房间平面图，求实际长和宽；再说这相当于把实际图形缩小了多少倍。",
        "比例尺后项越大，图画得越小。",
        4,
    ),
    quest(
        "pm-g6-geo-n025-practice",
        "pm-g6-geo-n025",
        "柱和锥的三视图",
        "practice",
        20,
        "为长方体、圆柱选出上面和前面的轮廓（圆柱上面是圆，前面常常是长方形）。",
        "从上面看圆柱是圆，从侧面看是长方形。",
        4,
    ),
    quest(
        "pm-g6-geo-n026-explain",
        "pm-g6-geo-n026",
        "立体家族说一说",
        "explain",
        10,
        "用一段话串起：正方体是特殊长方体；圆柱体积用底面积×高；圆锥再乘 1/3。",
        "先认形状，再选公式。",
    ),
    quest(
        "pm-g6-geo-n027-practice",
        "pm-g6-geo-n027",
        "展开图改错",
        "practice",
        20,
        "在 6 张展开图里找出折不拢的，并指出圆柱展开图中哪一张把侧面画成了平行四边形却边长不对。",
        "侧面展开的长必须等于底面周长。",
        6,
    ),
    quest(
        "pm-g6-geo-n028-practice",
        "pm-g6-geo-n028",
        "水箱还是图纸",
        "practice",
        20,
        "两则问题：水箱能装多少升；图纸上两村距离。先选体积还是比例尺，再计算。",
        "装水想容积，看地图想比例尺。",
        2,
    ),
    quest(
        "pm-g6-geo-n029-practice",
        "pm-g6-geo-n029",
        "先判断再下手",
        "practice",
        25,
        "8 道综合题先圈：表面积 / 体积 / 比例尺 / 视图，再做其中 5 道。",
        "小学图形收束：先点名这块知识，再选公式。",
        8,
    ),
    quest(
        "pm-g6-geo-n029-quiz",
        "pm-g6-geo-n029",
        "总复习小测",
        "mini_quiz",
        30,
        "覆盖展开图、圆柱或圆锥体积、比例尺、放大缩小面积比。",
        "锥体 1/3、面积比是边长比的平方。",
        8,
    ),
    quest(
        "pm-g6-geo-n030-practice",
        "pm-g6-geo-n030",
        "六年级图形综合练",
        "practice",
        25,
        "题型混合：长方体表面积与体积、圆柱侧面积、圆锥体积、比例尺换算、一张展开图判断。",
        "对回本图已点亮的灯。",
        12,
    ),
    quest(
        "pm-g6-geo-boss-map",
        "pm-g6-geo-n030",
        "关主：六年级图形通关试炼",
        "boss",
        100,
        "最终关主：①长方体或正方体表面积与体积各一 ②圆柱侧面积或体积 ③圆锥体积 ④比例尺或放大缩小 ⑤一张展开图。全部通过即通关本地图。",
        "通关后记入已通关列表；表面积与体积、圆柱与圆锥体积是最常回生的两对。",
        16,
    ),
    quest(
        "pm-g6-geo-n031-practice",
        "pm-g6-geo-n031",
        "向东再向北",
        "practice",
        15,
        "在简单平面图上按比例尺走一段「向东再向北」的路线，说出两个地点的方向关系。软锁节点。",
        "方向词和比例尺可以同时用。",
        3,
    ),
]


META = {
    "id": "pm-g6-geometry",
    "title": "六年级 · 图形与几何",
    "subject": "数学",
    "stage": "小学",
    "grade": 6,
    "strand": "图形与几何",
    "version": "0.1.0",
    "locale": "zh-CN",
    "start_node_ids": ["pm-g6-geo-n001"],
    "recommended_path_note": "从「长方体的认识」进入：先打通展开图、表面积、体积容积，圆柱圆锥可与长方体主线在展开图和体积处汇合；比例尺与放大缩小从起点并行。路线图与方向（n031）为软锁支线，不挡终章关主，通关前仍须点亮。",
    "win_condition": {
        "type": "light_all_nodes_and_bosses",
        "required_node_ids": "all",
        "required_boss_quest_ids": [
            "pm-g6-geo-boss-box",
            "pm-g6-geo-boss-cylinder",
            "pm-g6-geo-boss-map",
        ],
        "summary": "点亮全部知识点，并击败三名关主：长方体工匠、圆柱圆锥工匠、地图通关试炼。",
    },
    "content_disclaimer": "知识点与任务为课标/教材目录风格的原创教学大纲与自编提示语，不是任何版本教科书正文或习题的摘录。",
    "description": "小学六年级「图形与几何」地图：长方体正方体 → 圆柱圆锥 → 比例尺与图形放大缩小 → 展开图与观察收束。圆的周长面积在五年级几何图；本图独立通关，不引用跨图节点。",
}


SAMPLE_PROGRESS = {
    "player_id": "demo-learner",
    "display_name": "小明",
    "xp_total": 20,
    "current_map_id": "pm-g6-geometry",
    "cleared_map_ids": [],
    "nodes": {
        "pm-g6-geo-n001": {
            "state": "lit",
            "xp_earned": 10,
            "cleared_quest_ids": ["pm-g6-geo-n001-explain"],
            "updated_at": "2026-09-17T10:00:00Z",
        },
        "pm-g6-geo-n002": {
            "state": "learning",
            "xp_earned": 10,
            "cleared_quest_ids": ["pm-g6-geo-n002-explain"],
            "updated_at": "2026-09-17T10:08:00Z",
        },
    },
}


def main() -> None:
    write_map(OUT, META, NODES, EXTRA_EDGES, QUESTS, SAMPLE_PROGRESS)


if __name__ == "__main__":
    main()
