"""Build Grade 4 Geometry map JSON from a single source of truth.

Run: python3 scripts/_build_grade4_geometry.py

Pedagogical spine (课标/人教脉络风格，自撰短描述，非教材页原文):
  直线射线线段 → 角的度量（量角器、平角周角）→ 垂直与平行
  → 平行四边形与梯形 → 三角形（三边关系、分类、内角和）
  → 面积公式扩展（平行四边形、三角形、梯形）。
轴对称作图与旋转作图为软锁支线。
本图自洽，不引用低年级或数与运算节点 id。
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _geo_common import (
    MASTERY_CONCEPT,
    MASTERY_GATE,
    ROOT,
    SOFT,
    node as _node,
    quest,
    write_map,
)

OUT = ROOT / "maps" / "primary-math" / "grade-4-geometry"
G = 4


def node(nid, title, difficulty, prereqs, tags, description, *, unlock=None, mastery=None):
    return _node(
        nid, title, G, difficulty, prereqs, tags, description, unlock=unlock, mastery=mastery
    )


NODES = [
    node(
        "pm-g4-geo-n001",
        "直线射线线段",
        1,
        [],
        ["line", "ch-angle"],
        "能区分直线（两边无限延长）、射线（一个端点，向一边延长）和线段（两个端点）。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g4-geo-n002",
        "角的顶点和边",
        2,
        ["pm-g4-geo-n001"],
        ["angle", "ch-angle"],
        "知道角由顶点与两条射线组成，能在图上标出顶点和边。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g4-geo-n003",
        "用量角器量角",
        3,
        ["pm-g4-geo-n002"],
        ["angle", "ch-angle", "measure"],
        "能把量角器中心对顶点、0 刻度线对一条边，读另一条边对着的刻度，得到角的度数。",
    ),
    node(
        "pm-g4-geo-n004",
        "画指定度数的角",
        3,
        ["pm-g4-geo-n003"],
        ["angle", "ch-angle", "draw"],
        "能用直尺和量角器画出指定度数的角，如 60°、90°、135°。",
    ),
    node(
        "pm-g4-geo-n005",
        "平角和周角",
        3,
        ["pm-g4-geo-n004"],
        ["angle", "ch-angle", "straight-round"],
        "知道平角是 180°（一条直线）、周角是 360°（转一圈），直角是平角的一半。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g4-geo-n006",
        "角的分类总表",
        3,
        ["pm-g4-geo-n005"],
        ["angle", "ch-angle", "classify"],
        "能按度数把角分成锐角、直角、钝角、平角、周角，并举例说明。",
    ),
    node(
        "pm-g4-geo-n007",
        "垂直",
        3,
        ["pm-g4-geo-n006"],
        ["line", "ch-angle", "perpendicular"],
        "知道两条直线相交成直角就互相垂直，会用直角三角板画垂线、认垂足。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g4-geo-n008",
        "平行",
        3,
        ["pm-g4-geo-n007"],
        ["line", "ch-angle", "parallel"],
        "知道在同一平面内不相交的两条直线互相平行，会用三角板和直尺画平行线。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g4-geo-n009",
        "画垂线平行线",
        3,
        ["pm-g4-geo-n008"],
        ["line", "ch-angle", "draw"],
        "能过直线外一点画已知直线的垂线和平行线，并说明工具怎么摆。",
    ),
    node(
        "pm-g4-geo-n010",
        "角与线综合",
        4,
        ["pm-g4-geo-n009"],
        ["angle", "ch-angle", "boss-gate"],
        "能综合量角、画角、垂直与平行，完成章节收束检查。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g4-geo-n011",
        "平行四边形的特征",
        3,
        ["pm-g4-geo-n008"],
        ["quad", "ch-quad", "parallelogram"],
        "能说明平行四边形两组对边分别平行且相等，对角相等；用拉一拉感受它容易变形。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g4-geo-n012",
        "梯形的特征",
        3,
        ["pm-g4-geo-n011"],
        ["quad", "ch-quad", "trapezoid"],
        "能说明梯形只有一组对边平行（上底和下底），另两边是腰；认识等腰梯形。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g4-geo-n013",
        "平行四边形和梯形",
        3,
        ["pm-g4-geo-n012"],
        ["quad", "ch-quad", "compare"],
        "能比较平行四边形和梯形：平行边的组数不同，不要把「有一组平行」说成平行四边形。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g4-geo-n014",
        "四边形分类",
        3,
        ["pm-g4-geo-n013"],
        ["quad", "ch-quad", "classify"],
        "能整理四边形家族：平行四边形、长方形、正方形、梯形各满足哪些边角条件。",
    ),
    node(
        "pm-g4-geo-n015",
        "三角形的稳定性",
        2,
        ["pm-g4-geo-n001"],
        ["triangle", "ch-tri"],
        "能通过拉动对比：三角形不易变形，四边形容易变形，体会三角形的稳定性。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g4-geo-n016",
        "三角形三边关系",
        3,
        ["pm-g4-geo-n015"],
        ["triangle", "ch-tri", "sides"],
        "知道任意两边之和大于第三边，才能围成三角形；能判断三条线段行不行。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g4-geo-n017",
        "按边分类三角形",
        3,
        ["pm-g4-geo-n016"],
        ["triangle", "ch-tri", "classify"],
        "能按边分成不等边、等腰、等边三角形，并说明等边是特殊的等腰。",
    ),
    node(
        "pm-g4-geo-n018",
        "按角分类三角形",
        3,
        ["pm-g4-geo-n017", "pm-g4-geo-n006"],
        ["triangle", "ch-tri", "classify"],
        "能按角分成锐角、直角、钝角三角形，一个三角形只能按「最大的那个角」归一类。",
    ),
    node(
        "pm-g4-geo-n019",
        "三角形内角和",
        4,
        ["pm-g4-geo-n018"],
        ["triangle", "ch-tri", "angle-sum"],
        "能通过撕拼或测量发现三角形三个内角加起来是 180°，并用来求未知角。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g4-geo-n020",
        "三角形综合",
        4,
        ["pm-g4-geo-n019", "pm-g4-geo-n014"],
        ["triangle", "ch-tri", "boss-gate"],
        "能综合三边关系、按边按角分类和内角和，完成章节收束检查。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g4-geo-n021",
        "平行四边形面积",
        4,
        ["pm-g4-geo-n014", "pm-g4-geo-n010"],
        ["area", "ch-area", "parallelogram"],
        "能把平行四边形割补成长方形，理解面积 = 底 × 高，高要垂直于底。",
    ),
    node(
        "pm-g4-geo-n022",
        "三角形面积",
        4,
        ["pm-g4-geo-n021", "pm-g4-geo-n020"],
        ["area", "ch-area", "triangle"],
        "能把两个完全一样的三角形拼成平行四边形，理解面积 = 底 × 高 ÷ 2。",
    ),
    node(
        "pm-g4-geo-n023",
        "梯形面积",
        4,
        ["pm-g4-geo-n022"],
        ["area", "ch-area", "trapezoid"],
        "能把梯形转化成平行四边形或三角形来理解：面积 =（上底+下底）× 高 ÷ 2。",
    ),
    node(
        "pm-g4-geo-n024",
        "等底等高",
        3,
        ["pm-g4-geo-n022"],
        ["area", "ch-area", "equal-base"],
        "知道等底等高的平行四边形（或三角形）面积相等，形状可以不同。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g4-geo-n025",
        "组合图形面积",
        4,
        ["pm-g4-geo-n023", "pm-g4-geo-n024"],
        ["area", "ch-area", "composite"],
        "能把组合图形分割或补成已学图形，再加减面积。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g4-geo-n026",
        "面积公式扩展综合",
        4,
        ["pm-g4-geo-n025"],
        ["area", "ch-area"],
        "能根据图形选择平行四边形、三角形或梯形公式，并标出对应的底和高。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g4-geo-n027",
        "三个方向观察",
        3,
        ["pm-g4-geo-n014"],
        ["view", "ch-view"],
        "能辨认由几个正方体搭成的立体从前面、上面、左面看到的形状。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g4-geo-n028",
        "根据三视图搭",
        4,
        ["pm-g4-geo-n027"],
        ["view", "ch-view"],
        "能根据前面、上面、左面三张图，用积木搭出符合要求的立体（块数不太多）。",
    ),
    node(
        "pm-g4-geo-n029",
        "轴对称作图",
        3,
        ["pm-g4-geo-n007"],
        ["symmetry", "ch-view"],
        "能在方格纸上画出简单图形关于给定直线的轴对称图形。",
        unlock=SOFT,
    ),
    node(
        "pm-g4-geo-n030",
        "旋转作图",
        4,
        ["pm-g4-geo-n029"],
        ["rotation", "ch-view"],
        "能在方格纸上把简单图形绕一点旋转 90° 或 180°，画出旋转后的图形。",
        unlock=SOFT,
    ),
    node(
        "pm-g4-geo-n031",
        "图形与测量合练",
        4,
        ["pm-g4-geo-n010", "pm-g4-geo-n026", "pm-g4-geo-n028"],
        ["mixed", "ch-end"],
        "能在同一张综合练习里完成量角、四边形三角形辨认、面积公式和简单三视图。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g4-geo-n032",
        "四年级图形通关",
        5,
        ["pm-g4-geo-n031"],
        ["mixed", "ch-end", "boss-gate"],
        "综合角的度量、平行四边形梯形、三角形和面积公式扩展，完成本图收束检查。",
        mastery=MASTERY_GATE,
    ),
]


EXTRA_EDGES = [
    {
        "from": "pm-g4-geo-n001",
        "to": "pm-g4-geo-n002",
        "type": "related",
        "note": "角的边是射线，先分清直线射线线段再画角。",
    },
    {
        "from": "pm-g4-geo-n003",
        "to": "pm-g4-geo-n004",
        "type": "related",
        "note": "会量才会画：画角其实是把量的过程反过来做。",
    },
    {
        "from": "pm-g4-geo-n003",
        "to": "pm-g4-geo-n006",
        "type": "easily_confused",
        "note": "量角器内外两圈刻度，要从 0 那一圈开始读，不要读成互补的那个数。",
    },
    {
        "from": "pm-g4-geo-n007",
        "to": "pm-g4-geo-n008",
        "type": "easily_confused",
        "note": "垂直一定相交成直角；平行不相交。不要把「看起来斜」当成不平行。",
    },
    {
        "from": "pm-g4-geo-n011",
        "to": "pm-g4-geo-n012",
        "type": "easily_confused",
        "note": "平行四边形两组对边都平行；梯形只有一组。",
    },
    {
        "from": "pm-g4-geo-n016",
        "to": "pm-g4-geo-n017",
        "type": "related",
        "note": "先能围成三角形，再按边是否相等分类。",
    },
    {
        "from": "pm-g4-geo-n017",
        "to": "pm-g4-geo-n018",
        "type": "related",
        "note": "按边分类和按角分类是两把尺子，同一个三角形可以同时是等腰直角。",
    },
    {
        "from": "pm-g4-geo-n021",
        "to": "pm-g4-geo-n022",
        "type": "related",
        "note": "三角形面积是等底等高平行四边形的一半。",
    },
    {
        "from": "pm-g4-geo-n021",
        "to": "pm-g4-geo-n024",
        "type": "application",
        "note": "割补前后面积不变，所以等底等高面积相等。",
    },
    {
        "from": "pm-g4-geo-n007",
        "to": "pm-g4-geo-n021",
        "type": "application",
        "note": "高必须垂直于底，作高就是画垂线。",
    },
    {
        "from": "pm-g4-geo-n027",
        "to": "pm-g4-geo-n028",
        "type": "related",
        "note": "会看三视图才能反过来搭。",
    },
    {
        "from": "pm-g4-geo-n029",
        "to": "pm-g4-geo-n030",
        "type": "easily_confused",
        "note": "轴对称是翻折，旋转是绕点转，对应点的轨迹不同。",
    },
    {
        "from": "pm-g4-geo-n015",
        "to": "pm-g4-geo-n011",
        "type": "related",
        "note": "三角形稳定、平行四边形易变形，都是边的连接方式带来的。",
    },
]


QUESTS = [
    quest(
        "pm-g4-geo-n001-explain",
        "pm-g4-geo-n001",
        "三种线比一比",
        "explain",
        10,
        "画出直线、射线、线段，用箭头或端点标清楚，说明哪种可以量长度。",
        "只有线段两个头都在，长度确定。",
    ),
    quest(
        "pm-g4-geo-n002-explain",
        "pm-g4-geo-n002",
        "标出顶点和边",
        "explain",
        10,
        "在三个角上标顶点、边，并说明边是射线而不是线段。",
        "边要够长，但角的大小不靠边的长短。",
    ),
    quest(
        "pm-g4-geo-n003-practice",
        "pm-g4-geo-n003",
        "中心对顶点",
        "practice",
        20,
        "量 6 个角（含锐角钝角），写出度数。其中两个角的边对着内外圈容易读反。",
        "先找 0 刻度靠着哪一条边，再读另一条边。",
        6,
    ),
    quest(
        "pm-g4-geo-n004-practice",
        "pm-g4-geo-n004",
        "画出指定角",
        "practice",
        20,
        "画出 45°、90°、120°、180° 的角，用量角器复查，误差不超过 2°。",
        "先画一条边，再对中心、对 0，找到度数点连起来。",
        4,
    ),
    quest(
        "pm-g4-geo-n005-explain",
        "pm-g4-geo-n005",
        "平角是一条直线",
        "explain",
        10,
        "把两个直角拼成平角，再转一圈说明周角。说出直角、平角、周角的度数关系。",
        "90、180、360 是三个锚点。",
    ),
    quest(
        "pm-g4-geo-n006-practice",
        "pm-g4-geo-n006",
        "按度数贴标签",
        "practice",
        20,
        "给 8 个角贴上锐角/直角/钝角/平角/周角，并写出一个例子的度数范围。",
        "锐角小于 90°，钝角在 90° 和 180° 之间。",
        8,
    ),
    quest(
        "pm-g4-geo-n007-practice",
        "pm-g4-geo-n007",
        "找垂足画垂线",
        "practice",
        20,
        "过直线上一点和直线外一点分别画垂线，标出垂足。",
        "三角板的直角要贴紧已知直线。",
        4,
    ),
    quest(
        "pm-g4-geo-n008-explain",
        "pm-g4-geo-n008",
        "不相交才平行",
        "explain",
        10,
        "用两支铅笔演示平行和相交。说明在纸上（同一平面）怎样判断平行。",
        "延长后仍不相交，并且方向一致。",
    ),
    quest(
        "pm-g4-geo-n009-practice",
        "pm-g4-geo-n009",
        "过一点作线",
        "practice",
        20,
        "过直线外一点作已知直线的垂线和平行线各一条，简述步骤。",
        "平行线常用「平移三角板」的方法保持方向。",
        4,
    ),
    quest(
        "pm-g4-geo-n010-practice",
        "pm-g4-geo-n010",
        "角与线闯关练",
        "practice",
        20,
        "混合：量角、画 70° 角、判断垂直平行、过一点作垂线。",
        "量角对中心，作垂线对直角。",
        8,
    ),
    quest(
        "pm-g4-geo-n010-quiz",
        "pm-g4-geo-n010",
        "角与线小测",
        "mini_quiz",
        30,
        "读量角器、角的分类、垂直平行判断。夹一道内外圈读反的改错。",
        "从 0 那一圈读起。",
        10,
    ),
    quest(
        "pm-g4-geo-boss-angle",
        "pm-g4-geo-n010",
        "关主：角的度量师",
        "boss",
        80,
        "击败关主：①正确量两个角 ②画出一个指定角 ③在图中标出一组垂线和一组平行线。",
        "工具摆对，度数和位置才对。",
        12,
    ),
    quest(
        "pm-g4-geo-n011-explain",
        "pm-g4-geo-n011",
        "拉一拉平行四边形",
        "explain",
        10,
        "拉动平行四边形框架，观察对边是否保持平行、角是否改变，说明它容易变形。",
        "对边平行且相等，角可以变。",
    ),
    quest(
        "pm-g4-geo-n012-explain",
        "pm-g4-geo-n012",
        "只有一组平行",
        "explain",
        10,
        "指出梯形的上底、下底和两腰。翻一个等腰梯形，看看两腰是否相等。",
        "平行的那一组才叫底。",
    ),
    quest(
        "pm-g4-geo-n013-practice",
        "pm-g4-geo-n013",
        "一组还是两组平行",
        "practice",
        20,
        "给 8 个四边形，判断平行四边形、梯形或其他，说出平行边有几组。",
        "先找平行边，再计数。",
        8,
    ),
    quest(
        "pm-g4-geo-n014-practice",
        "pm-g4-geo-n014",
        "家族条件表",
        "practice",
        20,
        "填写：长方形、正方形、平行四边形、梯形各必须满足的边或角条件。",
        "正方形条件最多，梯形只要一组平行。",
        4,
    ),
    quest(
        "pm-g4-geo-n015-explain",
        "pm-g4-geo-n015",
        "拉三角形和四边形",
        "explain",
        10,
        "用吸管和橡皮泥搭一个三角形和一个四边形，拉动比较谁容易变形。",
        "三角形三边固定就定形。",
    ),
    quest(
        "pm-g4-geo-n016-practice",
        "pm-g4-geo-n016",
        "三边能不能围成",
        "practice",
        20,
        "判断 8 组长度（如 2,3,5；4,5,6；1,2,8）能否围成三角形，说明理由。",
        "最短的两边加起来必须大于最长边。",
        8,
    ),
    quest(
        "pm-g4-geo-n017-practice",
        "pm-g4-geo-n017",
        "按边贴标签",
        "practice",
        15,
        "给 6 个三角形按边分类，并指出哪个既是等腰又是等边。",
        "三边相等一定是等腰。",
        6,
    ),
    quest(
        "pm-g4-geo-n018-practice",
        "pm-g4-geo-n018",
        "按角贴标签",
        "practice",
        20,
        "给 6 个三角形按角分类；指出一个等腰直角三角形，说明它同时属于两类。",
        "看最大的那个角：锐、直还是钝。",
        6,
    ),
    quest(
        "pm-g4-geo-n019-practice",
        "pm-g4-geo-n019",
        "三个角加起来",
        "practice",
        20,
        "测量或撕拼验证内角和，再已知两角求第三角，共 6 题。",
        "未知角 = 180° − 两个已知角。",
        6,
    ),
    quest(
        "pm-g4-geo-n020-practice",
        "pm-g4-geo-n020",
        "三角形闯关练",
        "practice",
        20,
        "混合：三边关系、按边按角分类、内角和。夹一道 2+3=5 不能围成的说明。",
        "等于第三边时三条线会「躺平」，围不成面积。",
        8,
    ),
    quest(
        "pm-g4-geo-n020-quiz",
        "pm-g4-geo-n020",
        "三角形小测",
        "mini_quiz",
        30,
        "覆盖稳定性、三边、分类、内角和。夹一道把钝角三角形当成锐角的改错。",
        "有一个钝角就是钝角三角形。",
        8,
    ),
    quest(
        "pm-g4-geo-boss-triangle",
        "pm-g4-geo-n020",
        "关主：三角形与四边形鉴定官",
        "boss",
        80,
        "击败关主：①判断三边能否围成 ②按边和按角各分类一个三角形 ③区分平行四边形与梯形 ④用内角和求一个未知角。",
        "边看能不能围，角看最大那个，四边形看平行组数。",
        12,
    ),
    quest(
        "pm-g4-geo-n021-explain",
        "pm-g4-geo-n021",
        "割补成长方形",
        "explain",
        10,
        "沿平行四边形的高剪开，拼成长方形，说明底和高分别对应长方形的谁。",
        "高要垂直于底，不能斜着量腰。",
    ),
    quest(
        "pm-g4-geo-n021-practice",
        "pm-g4-geo-n021",
        "底乘高",
        "practice",
        20,
        "求 4 个平行四边形面积，图中给出斜边干扰，必须选用垂直的高。",
        "先标底，再找垂直于它的高。",
        4,
    ),
    quest(
        "pm-g4-geo-n022-explain",
        "pm-g4-geo-n022",
        "两个拼一个",
        "explain",
        10,
        "用两个完全一样的三角形拼成平行四边形，说明为什么要除以 2。",
        "一个三角形是拼成后的一半。",
    ),
    quest(
        "pm-g4-geo-n022-practice",
        "pm-g4-geo-n022",
        "底乘高除以2",
        "practice",
        20,
        "求 5 个三角形面积，含直角三角形（两条直角边可当底和高）。",
        "底和高必须互相垂直。",
        5,
    ),
    quest(
        "pm-g4-geo-n023-practice",
        "pm-g4-geo-n023",
        "上底加下底",
        "practice",
        20,
        "求 4 个梯形面积，先标上底、下底和高，再代入公式。",
        "高是两底之间的垂直距离。",
        4,
    ),
    quest(
        "pm-g4-geo-n024-explain",
        "pm-g4-geo-n024",
        "形状不同面积同",
        "explain",
        10,
        "在等底等高的几条形如扇骨的三角形里，说明它们面积为什么相等。",
        "公式只看底和高，不看斜边有多斜。",
    ),
    quest(
        "pm-g4-geo-n025-practice",
        "pm-g4-geo-n025",
        "割补加减",
        "practice",
        20,
        "求 3 个组合图形面积：一个分割、一个补成大长方形再减。",
        "先画辅助线，把不熟悉的变成熟悉的。",
        3,
    ),
    quest(
        "pm-g4-geo-n026-practice",
        "pm-g4-geo-n026",
        "选公式再计算",
        "practice",
        20,
        "给平行四边形、三角形、梯形、组合图形各一，先写公式再求面积。",
        "公式选错，底和高对了也白算。",
        4,
    ),
    quest(
        "pm-g4-geo-n027-practice",
        "pm-g4-geo-n027",
        "看三张图",
        "practice",
        20,
        "为两座小积木选出前面、上面、左面的视图。",
        "上面看层数分布，前面看朝南的面。",
        6,
    ),
    quest(
        "pm-g4-geo-n028-practice",
        "pm-g4-geo-n028",
        "照图搭积木",
        "practice",
        20,
        "根据三视图用 4–8 块正方体搭出立体，核对三个方向。",
        "先搭上面看到的占地，再加层。",
        3,
    ),
    quest(
        "pm-g4-geo-n029-practice",
        "pm-g4-geo-n029",
        "画出对称图形",
        "practice",
        15,
        "在方格纸上画出三角形和「L」形关于给定直线的轴对称图形。软锁节点，可后做。",
        "对应点到对称轴的格数相等、在两侧。",
        2,
    ),
    quest(
        "pm-g4-geo-n030-practice",
        "pm-g4-geo-n030",
        "绕点转90度",
        "practice",
        15,
        "把一个小旗绕格点旋转 90° 和 180° 各一次。软锁节点，可后做。",
        "每个点绕中心转过相同角度。",
        2,
    ),
    quest(
        "pm-g4-geo-n031-practice",
        "pm-g4-geo-n031",
        "测量与图形合练",
        "practice",
        25,
        "混合：量一个角、判断平行垂直、求三角形或梯形面积、选一张三视图。",
        "工具题和公式题分开想，不要互相干扰。",
        10,
    ),
    quest(
        "pm-g4-geo-n031-quiz",
        "pm-g4-geo-n031",
        "合练小测",
        "mini_quiz",
        30,
        "覆盖量角器、四边形分类、三角形内角和、面积公式选对。",
        "高必须垂直；内角和是 180°。",
        10,
    ),
    quest(
        "pm-g4-geo-n032-practice",
        "pm-g4-geo-n032",
        "四年级图形综合练",
        "practice",
        25,
        "题型混合：画角、三边关系、平行四边形与梯形面积、组合图形、三视图。",
        "对回本图已点亮的灯。",
        12,
    ),
    quest(
        "pm-g4-geo-boss-map",
        "pm-g4-geo-n032",
        "关主：四年级图形通关试炼",
        "boss",
        100,
        "最终关主：①量或画一个角 ②区分平行与垂直 ③三边关系或内角和 ④平行四边形或三角形面积（标底和高）⑤一题三视图。全部通过即通关。",
        "通关后记入已通关列表；高与底垂直、量角器内外圈是最常回生的两处。",
        16,
    ),
]


META = {
    "id": "pm-g4-geometry",
    "title": "四年级 · 图形与几何",
    "subject": "数学",
    "stage": "小学",
    "grade": 4,
    "strand": "图形与几何",
    "version": "0.1.0",
    "locale": "zh-CN",
    "start_node_ids": ["pm-g4-geo-n001"],
    "recommended_path_note": "从「直线射线线段」进入：先打通角的度量、垂直平行，再平行四边形梯形与三角形，然后面积公式扩展。三角形稳定性可与角的主线并行。轴对称作图与旋转作图（n029–n030）为软锁支线，不挡终章关主，通关前仍须点亮。",
    "win_condition": {
        "type": "light_all_nodes_and_bosses",
        "required_node_ids": "all",
        "required_boss_quest_ids": [
            "pm-g4-geo-boss-angle",
            "pm-g4-geo-boss-triangle",
            "pm-g4-geo-boss-map",
        ],
        "summary": "点亮全部知识点，并击败三名关主：角的度量师、三角形与四边形鉴定官、地图通关试炼。",
    },
    "content_disclaimer": "知识点与任务为课标/教材目录风格的原创教学大纲与自编提示语，不是任何版本教科书正文或习题的摘录。",
    "description": "小学四年级「图形与几何」地图：角的度量 → 平行四边形与梯形 → 三角形 → 面积公式扩展。与三年级周长面积入门概念衔接，但各自独立通关。",
}


SAMPLE_PROGRESS = {
    "player_id": "demo-learner",
    "display_name": "小明",
    "xp_total": 20,
    "current_map_id": "pm-g4-geometry",
    "cleared_map_ids": [],
    "nodes": {
        "pm-g4-geo-n001": {
            "state": "lit",
            "xp_earned": 10,
            "cleared_quest_ids": ["pm-g4-geo-n001-explain"],
            "updated_at": "2026-09-17T10:00:00Z",
        },
        "pm-g4-geo-n002": {
            "state": "learning",
            "xp_earned": 10,
            "cleared_quest_ids": ["pm-g4-geo-n002-explain"],
            "updated_at": "2026-09-17T10:08:00Z",
        },
    },
}


def main() -> None:
    write_map(OUT, META, NODES, EXTRA_EDGES, QUESTS, SAMPLE_PROGRESS)


if __name__ == "__main__":
    main()
