"""Build Grade 1 Numbers map JSON from a single source of truth.

Run: python3 scripts/_build_grade1_numbers.py
The generated JSON under maps/primary-math/grade-1-numbers/ is the published content.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "maps" / "primary-math" / "grade-1-numbers"

HARD = {"type": "hard_all_prereqs", "allow_teacher_override": False}
SOFT = {"type": "soft_recommended", "allow_teacher_override": True}

MASTERY_CONCEPT = {
    "min_quests_cleared": 1,
    "require_quest_types": ["explain"],
    "review_after_days": 10,
}
MASTERY_SKILL = {
    "min_quests_cleared": 1,
    "min_quiz_accuracy": 0.8,
    "require_quest_types": ["practice"],
    "review_after_days": 7,
}
MASTERY_GATE = {
    "min_quests_cleared": 2,
    "min_quiz_accuracy": 0.85,
    "require_quest_types": ["practice"],
    "review_after_days": 5,
}


def node(
    nid: str,
    title: str,
    difficulty: int,
    prereqs: list[str],
    tags: list[str],
    description: str,
    *,
    unlock: dict | None = None,
    mastery: dict | None = None,
) -> dict:
    return {
        "id": nid,
        "title": title,
        "subject": "数学",
        "stage": "小学",
        "grade": 1,
        "strand": "数与代数",
        "difficulty": difficulty,
        "prerequisites": prereqs,
        "tags": tags,
        "unlock_rule": unlock or HARD,
        "mastery_criteria": mastery or MASTERY_SKILL,
        "description": description,
    }


# Pedagogical spine (人教版/课标风格脉络，自撰短描述，非教材页原文)
NODES = [
    node(
        "pm-g1-n001",
        "数一数（10以内）",
        1,
        [],
        ["count", "ch-start", "within-10"],
        "能手口一致地点数 10 个以内的物体，并说出一共有几个。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-n002",
        "同样多、多、少",
        1,
        ["pm-g1-n001"],
        ["compare", "ch-start", "within-10"],
        "会用一一对应比较两组物体，说出谁多、谁少或同样多。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-n003",
        "认识1～5",
        1,
        ["pm-g1-n001"],
        ["number-sense", "ch-1to5"],
        "认识数字 1 到 5，能把数字、数量和实物对应起来。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-n004",
        "第几：基数与序数",
        1,
        ["pm-g1-n003"],
        ["ordinal", "ch-1to5"],
        "区分「有几个」和「排第几」，会在简单排队情境里指出第几个。",
        unlock=SOFT,
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-n005",
        "5以内数的分与合",
        2,
        ["pm-g1-n003"],
        ["compose", "ch-1to5"],
        "能把 5 以内的数拆成两份，也能把两份合回原来的数。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-n006",
        "认识0",
        1,
        ["pm-g1-n003"],
        ["zero", "ch-1to5"],
        "知道 0 表示没有，也知道它在数数顺序里紧挨着 1。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-n007",
        "5以内加法",
        2,
        ["pm-g1-n005", "pm-g1-n006"],
        ["add", "ch-1to5", "within-5"],
        "能用「合起来」的意思计算 5 以内加法，并写出加法算式。",
    ),
    node(
        "pm-g1-n008",
        "5以内减法",
        2,
        ["pm-g1-n007"],
        ["subtract", "ch-1to5", "within-5"],
        "能用「去掉」的意思计算 5 以内减法，并写出减法算式。",
    ),
    node(
        "pm-g1-n009",
        "认识6～10",
        2,
        ["pm-g1-n003"],
        ["number-sense", "ch-6to10"],
        "认识 6 到 10，能按顺序数、认读和书写这些数字。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-n010",
        "10的分与合",
        2,
        ["pm-g1-n005", "pm-g1-n009"],
        ["compose", "ch-6to10", "make-10"],
        "熟练说出 10 可以分成哪两数、哪两数能合成 10，为凑十做准备。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-n011",
        "10以内加法",
        2,
        ["pm-g1-n007", "pm-g1-n010"],
        ["add", "ch-6to10", "within-10"],
        "能正确计算 10 以内加法，并初步用分与合想得数。",
    ),
    node(
        "pm-g1-n012",
        "10以内减法",
        2,
        ["pm-g1-n008", "pm-g1-n011"],
        ["subtract", "ch-6to10", "within-10"],
        "能正确计算 10 以内减法，会用想加算减检查得数。",
    ),
    node(
        "pm-g1-n013",
        "连加与连减（10以内）",
        3,
        ["pm-g1-n011", "pm-g1-n012"],
        ["chain", "ch-6to10", "within-10"],
        "能从左往右计算 10 以内连加、连减，知道先算前面一步。",
    ),
    node(
        "pm-g1-n014",
        "加减混合（10以内）",
        3,
        ["pm-g1-n013"],
        ["mixed", "ch-6to10", "boss-gate"],
        "能计算 10 以内加减混合式，并在「先合再去」的情境中选对运算。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g1-n015",
        "认识11～20",
        2,
        ["pm-g1-n009"],
        ["number-sense", "ch-11to20"],
        "认识 11 到 20 各数，能数、读、写，并知道 10 后面接着 11。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-n016",
        "十几的组成",
        2,
        ["pm-g1-n010", "pm-g1-n015"],
        ["place-value", "ch-11to20", "teen"],
        "知道十几是 1 个十和几个一合起来的，能用小棒说明组成。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-n017",
        "20以内不进位加法",
        2,
        ["pm-g1-n011", "pm-g1-n016"],
        ["add", "ch-11to20", "no-carry"],
        "计算个位相加不满十的加法，如 12+3，先把几个一加起来。",
    ),
    node(
        "pm-g1-n018",
        "20以内不退位减法",
        2,
        ["pm-g1-n012", "pm-g1-n016"],
        ["subtract", "ch-11to20", "no-borrow"],
        "计算个位够减的减法，如 15−4，从几个一里去掉，十不动。",
    ),
    node(
        "pm-g1-n019",
        "凑十法",
        3,
        ["pm-g1-n010", "pm-g1-n016"],
        ["strategy", "ch-carry", "make-10"],
        "遇到个位相加满十时，会把其中一个数凑成 10，再加剩下的。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-n020",
        "9加几",
        3,
        ["pm-g1-n017", "pm-g1-n019"],
        ["add", "ch-carry", "9-plus"],
        "用凑十法计算 9 加几，体会「9 再凑 1 就成 10」。",
    ),
    node(
        "pm-g1-n021",
        "8、7、6加几",
        3,
        ["pm-g1-n020"],
        ["add", "ch-carry"],
        "把凑十法推广到 8、7、6 加几，个位满十就向十位进 1。",
    ),
    node(
        "pm-g1-n022",
        "20以内进位加法",
        3,
        ["pm-g1-n020", "pm-g1-n021"],
        ["add", "ch-carry", "within-20"],
        "综合计算 20 以内进位加法，能口算并说清怎样凑十。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g1-n023",
        "破十法与想加算减",
        4,
        ["pm-g1-n018", "pm-g1-n022"],
        ["strategy", "ch-borrow"],
        "个位不够减时，会破开 1 个十再减，或用加法想对应的减。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-n024",
        "十几减9",
        4,
        ["pm-g1-n023"],
        ["subtract", "ch-borrow", "minus-9"],
        "计算十几减 9，能把它和「9 加几」对应起来验算。",
    ),
    node(
        "pm-g1-n025",
        "十几减8、7、6",
        4,
        ["pm-g1-n024"],
        ["subtract", "ch-borrow"],
        "把退位减法推广到减 8、7、6，能选破十或想加算减。",
    ),
    node(
        "pm-g1-n026",
        "20以内退位减法",
        4,
        ["pm-g1-n025"],
        ["subtract", "ch-borrow", "within-20", "boss-gate"],
        "综合计算 20 以内退位减法，并会用加法验算。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g1-n027",
        "加减法的关系",
        3,
        ["pm-g1-n022", "pm-g1-n026"],
        ["relation", "ch-apply"],
        "知道加减互逆：知道两个加数与和，就能写出相关减法。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-n028",
        "解决问题：一共与还剩",
        3,
        ["pm-g1-n014", "pm-g1-n026"],
        ["word-problem", "ch-apply", "application"],
        "在「合起来一共」「去掉还剩」的短故事里，正确选择加或减。",
    ),
    node(
        "pm-g1-n029",
        "整十数（到100）",
        2,
        ["pm-g1-n015"],
        ["tens", "ch-to100"],
        "认识 10、20、…、100，能十个十个地数，知道 10 个十是 100。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-n030",
        "100以内数的读与写",
        3,
        ["pm-g1-n029"],
        ["read-write", "ch-to100"],
        "能读、写 100 以内各数，避免「二十五」写成 205 这类位数错误。",
    ),
    node(
        "pm-g1-n031",
        "100以内数的组成",
        3,
        ["pm-g1-n016", "pm-g1-n030"],
        ["place-value", "ch-to100"],
        "能说出一个两位数是几个十和几个一，建立十位、个位观念。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g1-n032",
        "100以内数的大小比较",
        3,
        ["pm-g1-n002", "pm-g1-n031"],
        ["compare", "ch-to100"],
        "会先看十位再看个位比较 100 以内数的大小，并用＞＜＝表示。",
    ),
    node(
        "pm-g1-n033",
        "整十数加、减整十数",
        3,
        ["pm-g1-n011", "pm-g1-n012", "pm-g1-n029"],
        ["add", "subtract", "ch-to100", "tens"],
        "把整十数加减转化成几个十加减，如 30+20 想成 3 个十加 2 个十。",
    ),
    node(
        "pm-g1-n034",
        "两位数加、减一位数（不进退位）",
        3,
        ["pm-g1-n017", "pm-g1-n018", "pm-g1-n031"],
        ["add", "subtract", "ch-to100", "no-carry"],
        "计算个位不进位、不退位的两位数加减一位数，十位保持不变。",
    ),
    node(
        "pm-g1-n035",
        "两位数加、减整十数",
        3,
        ["pm-g1-n033", "pm-g1-n034"],
        ["add", "subtract", "ch-to100"],
        "两位数加减整十数时只动十位、个位不动，能口算并说理。",
    ),
    node(
        "pm-g1-n036",
        "解决问题：比多与比少",
        4,
        ["pm-g1-n028", "pm-g1-n032"],
        ["word-problem", "ch-apply", "compare"],
        "理解「比一个数多几 / 少几」，能从短故事里列出正确算式。",
    ),
    node(
        "pm-g1-n037",
        "20以内加减口算熟练",
        4,
        ["pm-g1-n022", "pm-g1-n026"],
        ["fluency", "within-20", "ch-apply"],
        "20 以内加减能较熟练口算，并自觉用互逆关系验算。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g1-n038",
        "数与运算入门综合",
        5,
        ["pm-g1-n027", "pm-g1-n035", "pm-g1-n036", "pm-g1-n037"],
        ["synthesis", "ch-final", "boss-gate"],
        "综合运用一年级数的认识、组成、比较与 20 以内及整十加减解决问题。",
        mastery=MASTERY_GATE,
    ),
]


EXTRA_EDGES = [
    {
        "from": "pm-g1-n007",
        "to": "pm-g1-n008",
        "type": "related",
        "note": "加与减成对出现，宜对照着学。",
    },
    {
        "from": "pm-g1-n011",
        "to": "pm-g1-n012",
        "type": "related",
        "note": "10 以内加减对照练习。",
    },
    {
        "from": "pm-g1-n003",
        "to": "pm-g1-n004",
        "type": "related",
        "note": "认识数量之后再学「第几」。",
    },
    {
        "from": "pm-g1-n017",
        "to": "pm-g1-n020",
        "type": "easily_confused",
        "note": "不进位与进位都是加法，是否凑十容易混。",
    },
    {
        "from": "pm-g1-n020",
        "to": "pm-g1-n024",
        "type": "easily_confused",
        "note": "9 加几与十几减 9 是一对，容易算反。",
    },
    {
        "from": "pm-g1-n022",
        "to": "pm-g1-n026",
        "type": "easily_confused",
        "note": "进位加与退位减都动到「十」，方向相反。",
    },
    {
        "from": "pm-g1-n028",
        "to": "pm-g1-n036",
        "type": "easily_confused",
        "note": "「一共」与「比多比少」都像应用题，数量关系不同。",
    },
    {
        "from": "pm-g1-n016",
        "to": "pm-g1-n031",
        "type": "related",
        "note": "十几组成是两位数组成的缩影。",
    },
    {
        "from": "pm-g1-n002",
        "to": "pm-g1-n032",
        "type": "related",
        "note": "同样多/多/少是符号比较的前身。",
    },
    {
        "from": "pm-g1-n011",
        "to": "pm-g1-n028",
        "type": "application",
        "note": "把 10 以内加法用到「一共」问题。",
    },
    {
        "from": "pm-g1-n012",
        "to": "pm-g1-n028",
        "type": "application",
        "note": "把减法用到「还剩」问题。",
    },
    {
        "from": "pm-g1-n027",
        "to": "pm-g1-n037",
        "type": "application",
        "note": "用互逆关系给口算验算。",
    },
    {
        "from": "pm-g1-n032",
        "to": "pm-g1-n036",
        "type": "application",
        "note": "比较大小支撑「比多比少」问题。",
    },
]


def quest(qid: str, node_id: str, title: str, qtype: str, xp: int, prompt: str, hint: str, items: int | None = None) -> dict:
    q = {
        "id": qid,
        "node_id": node_id,
        "title": title,
        "type": qtype,
        "xp": xp,
        "prompt": prompt,
        "success_hint": hint,
    }
    if items is not None:
        q["items_suggested"] = items
    return q


QUESTS = [
    quest("pm-g1-n001-explain", "pm-g1-n001", "边指边数", "explain", 10,
          "任选桌上不超过 10 件物品，边指边数，最后大声说「一共有几个」。",
          "手指、口说、眼睛看同一件物品。"),
    quest("pm-g1-n002-explain", "pm-g1-n002", "一对一比一比", "explain", 10,
          "摆两排物品，用一一对应说明谁多、谁少，或同样多。",
          "多出来的没有「朋友」配对。"),
    quest("pm-g1-n003-explain", "pm-g1-n003", "数字找朋友", "explain", 10,
          "看到 1～5 的数字，拿出同样多的小圆片，再说出这个数。",
          "数字、数量、实物要能对上。"),
    quest("pm-g1-n003-practice", "pm-g1-n003", "认读1～5", "practice", 15,
          "打乱顺序出示数字卡片 1～5，正确认读并按从小到大排好。",
          "先找到最小的 1，再一个一个往后排。", 8),
    quest("pm-g1-n004-explain", "pm-g1-n004", "有几个和第几", "explain", 10,
          "五个小朋友排队。说清「一共有 5 人」和「从左数第 3 个是谁」有什么不同。",
          "「有几个」问总数，「第几」问位置。"),
    quest("pm-g1-n005-explain", "pm-g1-n005", "5可以怎么分", "explain", 10,
          "用 5 根小棒分成两堆，至少说出三种分法，再说怎样合回去。",
          "一边说「几和几」，一边把两堆再合在一起。"),
    quest("pm-g1-n005-practice", "pm-g1-n005", "分与合卡片", "practice", 15,
          "完成 5 以内分与合：如 4 可以分成 1 和 □。",
          "两份加起来要回到原来的数。", 8),
    quest("pm-g1-n006-explain", "pm-g1-n006", "没有就是0", "explain", 10,
          "盘子里原来有 2 块糖，吃完了。用 0 说明现在有几块，并指出 0 在 1 的前面。",
          "0 既表示没有，也是一个数。"),
    quest("pm-g1-n007-explain", "pm-g1-n007", "合起来用加法", "explain", 10,
          "左边 2 个、右边 3 个，用手势表示合起来，并写出加法算式。",
          "加号表示把两部分合在一起。"),
    quest("pm-g1-n007-practice", "pm-g1-n007", "5以内加法练习", "practice", 20,
          "口算一组 5 以内加法，如 2+2、1+4、0+5。",
          "想分与合，或接着数。", 10),
    quest("pm-g1-n008-explain", "pm-g1-n008", "去掉用减法", "explain", 10,
          "有 5 个桃子，吃掉 2 个，用「去掉」说明还剩几个，并写出减法算式。",
          "减号表示从总数里去掉一部分。"),
    quest("pm-g1-n008-practice", "pm-g1-n008", "5以内减法练习", "practice", 20,
          "口算一组 5 以内减法，如 5−1、4−0、3−3。",
          "可以用对应的加法想得数。", 10),
    quest("pm-g1-n008-quiz", "pm-g1-n008", "5以内加减小测", "mini_quiz", 25,
          "混合出现 5 以内加减，看算式选对运算并算出得数。",
          "先看是合起来还是去掉。", 8),
    quest("pm-g1-n009-explain", "pm-g1-n009", "接着数到10", "explain", 10,
          "从 1 数到 10，再倒着数回 1，指出 6、7、8、9、10 各是多少个小棒。",
          "10 要用一捆（10 根）来表示更清楚。"),
    quest("pm-g1-n010-explain", "pm-g1-n010", "10的好朋友", "explain", 10,
          "说出 10 的分与合（1 和 9、2 和 8…），并说明为什么以后常要用到「凑十」。",
          "两数合起来是 10，就是一对好朋友。"),
    quest("pm-g1-n010-practice", "pm-g1-n010", "凑十对对碰", "practice", 20,
          "给出一个 10 以内的数，迅速说出再加几是 10。",
          "想 10 的分与合。", 10),
    quest("pm-g1-n011-practice", "pm-g1-n011", "10以内加法练习", "practice", 20,
          "口算 10 以内加法，包含加 0 和得数是 10 的题。",
          "得数不要超过 10。", 12),
    quest("pm-g1-n012-practice", "pm-g1-n012", "10以内减法练习", "practice", 20,
          "口算 10 以内减法，并用加法验算其中两题。",
          "减数和差加起来应等于被减数。", 12),
    quest("pm-g1-n013-explain", "pm-g1-n013", "先算哪一步", "explain", 10,
          "用「先放进 2 个，再放进 3 个」说明 2+3+1 要先算前面的加法。",
          "连加连减都从左边开始，一步一步算。"),
    quest("pm-g1-n013-practice", "pm-g1-n013", "连加连减练习", "practice", 20,
          "计算若干 10 以内连加、连减式，写出中间一步的得数。",
          "可以在第一步下面标出小得数。", 8),
    quest("pm-g1-n014-practice", "pm-g1-n014", "加减混合练习", "practice", 20,
          "计算 10 以内加减混合，如 6+2−3。先判断每一步是加还是减。",
          "仍然从左往右。", 8),
    quest("pm-g1-n014-quiz", "pm-g1-n014", "10以内混合小测", "mini_quiz", 30,
          "既有口算也有「先来了几个、又走了几个」的短故事。",
          "故事里的「又来」多半用加，「走了」多半用减。", 10),
    quest("pm-g1-boss-10", "pm-g1-n014", "关主：十以内加减大闯关", "boss", 80,
          "闯过三关：①10 的分与合抢答 ②10 以内加减口算 ③一个「一共/还剩」短故事。全部通过才算击败关主。",
          "分与合熟练了，口算和应用题都会轻松很多。", 15),
    quest("pm-g1-n015-explain", "pm-g1-n015", "数到20", "explain", 10,
          "从 10 接着数到 20，指出 11、15、20，并正确书写这几个数。",
          "10 后面是 11，不是「101」。"),
    quest("pm-g1-n016-explain", "pm-g1-n016", "一个十和几个一", "explain", 10,
          "用 1 捆小棒（10 根）加几根零散小棒表示一个十几，说出它的组成。",
          "左边一捆是十，右边几根是一。"),
    quest("pm-g1-n016-practice", "pm-g1-n016", "十几组成练习", "practice", 15,
          "说出 11～19 各是几个十和几个一，并写出如 13=10+3。",
          "十几里一定有 1 个十。", 9),
    quest("pm-g1-n017-practice", "pm-g1-n017", "不进位加法练习", "practice", 20,
          "计算个位相加不满十的题，如 12+4、10+7、16+2。",
          "只把几个一加起来，十先不动。", 10),
    quest("pm-g1-n018-practice", "pm-g1-n018", "不退位减法练习", "practice", 20,
          "计算个位够减的题，如 18−3、15−5、12−2。",
          "个位够减就不用破十。", 10),
    quest("pm-g1-n019-explain", "pm-g1-n019", "怎样凑成10", "explain", 10,
          "用小棒说明 9+5：先从 5 里拿出 1 给 9 凑成 10，再加剩下的 4。",
          "先凑十，再加剩下的部分。"),
    quest("pm-g1-n020-practice", "pm-g1-n020", "9加几练习", "practice", 20,
          "口算 9+2 到 9+9，每题用一句话说出凑十过程。",
          "9 再要 1 个就变成 10。", 8),
    quest("pm-g1-n021-practice", "pm-g1-n021", "8、7、6加几练习", "practice", 20,
          "口算 8、7、6 加几（得数在 20 以内），标明凑了几成十。",
          "8 凑 2，7 凑 3，6 凑 4。", 12),
    quest("pm-g1-n022-practice", "pm-g1-n022", "进位加法综合练", "practice", 20,
          "混合 9、8、7、6 加几以及 5 加几，全部为 20 以内进位加法。",
          "先看个位够不够十。", 12),
    quest("pm-g1-n022-quiz", "pm-g1-n022", "进位加法小测", "mini_quiz", 30,
          "判断哪些加法要进位，再计算。夹一道「9 加几」与「12+3」的对比。",
          "不满十不进位，满十才凑十。", 10),
    quest("pm-g1-n023-explain", "pm-g1-n023", "个位不够减怎么办", "explain", 10,
          "用小棒说明 13−5：打开一捆十，变成 10 和 3，再减 5。或用「5 加几等于 13」来想。",
          "破十和想加算减都可以，选自己更清楚的一种。"),
    quest("pm-g1-n024-practice", "pm-g1-n024", "十几减9练习", "practice", 20,
          "口算 11−9 到 18−9，并用对应的 9 加几验算两题。",
          "减 9 常常想「再加 1 就是减 10」。", 8),
    quest("pm-g1-n025-practice", "pm-g1-n025", "十几减8、7、6练习", "practice", 20,
          "口算十几减 8、7、6，每类至少 3 题。",
          "可以先想加算减：减数 + 差 = 被减数。", 12),
    quest("pm-g1-n026-practice", "pm-g1-n026", "退位减法综合练", "practice", 20,
          "混合 20 以内退位减法，并指出哪几题个位本来就够减（干扰项）。",
          "先看个位够不够减。", 12),
    quest("pm-g1-n026-quiz", "pm-g1-n026", "退位减法小测", "mini_quiz", 30,
          "进位加、退位减混排，要先判断类型再计算。",
          "加往「满十」走，减往「破十」走。", 10),
    quest("pm-g1-boss-20", "pm-g1-n026", "关主：二十以内进退位", "boss", 80,
          "击败关主条件：①说出凑十或破十过程 ②正确完成进位加与退位减各 5 题 ③用加减互逆验算 1 题。",
          "这一关之后，20 以内计算就打通了。", 15),
    quest("pm-g1-n027-explain", "pm-g1-n027", "加减是一对好朋友", "explain", 10,
          "由 8+6=14 写出两道相关减法，并说明为什么得数互相「认识」。",
          "和减去一个加数，得到另一个加数。"),
    quest("pm-g1-n028-practice", "pm-g1-n028", "一共还是还剩", "practice", 20,
          "读三则短故事：来了几个 / 走了几个 / 合在一起，选择加或减并列式。",
          "「一共、合起来」用加；「还剩、去掉、吃了」用减。", 6),
    quest("pm-g1-n029-explain", "pm-g1-n029", "十个十个地数", "explain", 10,
          "把 10 根小棒捆成一捆，数十捆到 100，说出 40、70、100 各是几十。",
          "整十数的十位上是几，就有几个十。"),
    quest("pm-g1-n030-practice", "pm-g1-n030", "读一读写一写", "practice", 20,
          "听数写数、看数读数（100 以内），特别注意 13、30、100。",
          "13 是 1 个十和 3 个一；30 是 3 个十。", 10),
    quest("pm-g1-n031-explain", "pm-g1-n031", "几个十几个一", "explain", 10,
          "任意说一个两位数，用「几个十、几个一」说明它的组成，并对照 十几 的组成。",
          "十位上的数字表示几个十。"),
    quest("pm-g1-n032-practice", "pm-g1-n032", "比大小", "practice", 20,
          "比较 100 以内两个数的大小，先比十位再比个位，填 ＞＜＝。",
          "十位大的数就大；十位相同再比个位。", 10),
    quest("pm-g1-n033-practice", "pm-g1-n033", "整十加减", "practice", 20,
          "计算 20+30、50−10、100−40 等，用「几个十」来想。",
          "只算十位上的数，个位都是 0。", 8),
    quest("pm-g1-n034-practice", "pm-g1-n034", "两位数加减一位数", "practice", 20,
          "计算不进位、不退位的两位数加减一位数，如 34+5、48−2。",
          "个位算个位，十位先原样写下来。", 10),
    quest("pm-g1-n035-practice", "pm-g1-n035", "加减整十数", "practice", 20,
          "计算 45+20、67−30 等，说清哪一位发生了变化。",
          "加减整十数时个位不变。", 8),
    quest("pm-g1-n036-explain", "pm-g1-n036", "多几少几是什么意思", "explain", 10,
          "小明有 8 支笔，小红比他多 3 支。用图或学具说明「多 3 支」该怎样算。",
          "比一个数多几，就在这个数上再加几。"),
    quest("pm-g1-n036-practice", "pm-g1-n036", "比多比少练习", "practice", 20,
          "完成「比多」「比少」短故事各两则，并列式计算。",
          "先找到「以谁为标准」，再决定加还是减。", 4),
    quest("pm-g1-n037-practice", "pm-g1-n037", "口算小跑", "practice", 20,
          "限时口算 20 以内加减混合，错题用互逆关系当场验算。",
          "又快又对才算熟练，不要只图快。", 16),
    quest("pm-g1-n037-quiz", "pm-g1-n037", "口算过关小测", "mini_quiz", 30,
          "20 以内加减混排，正确率达到掌握标准才算过关。",
          "遇到进退位先在心里想凑十或破十。", 12),
    quest("pm-g1-n038-practice", "pm-g1-n038", "地图综合练", "practice", 25,
          "题型混合：读数写数、比较大小、20 以内进退位、整十加减、比多比少故事。",
          "先判断这题在考哪一个已点亮的知识点。", 12),
    quest("pm-g1-boss-map", "pm-g1-n038", "关主：一年级数与运算通关试炼", "boss", 100,
          "最终关主：①正确读写并比较两个两位数 ②20 以内进退位各 4 题 ③整十加减 2 题 ④「还剩」与「比多」故事各 1 则。全部通过即通关本地图。",
          "通关后这张地图记入已通关列表，节点保持点亮，过一段时间会邀请复习。", 16),
]


META = {
    "id": "pm-g1-numbers",
    "title": "一年级 · 数与运算入门",
    "subject": "数学",
    "stage": "小学",
    "grade": 1,
    "strand": "数与代数",
    "version": "0.1.0",
    "locale": "zh-CN",
    "start_node_ids": ["pm-g1-n001"],
    "recommended_path_note": "从「数一数」进入，先打通 10 以内，再 20 以内进退位，最后衔接 100 以内数与整十加减。序数（n004）为软锁支线。",
    "win_condition": {
        "type": "light_all_nodes_and_bosses",
        "required_node_ids": "all",
        "required_boss_quest_ids": ["pm-g1-boss-10", "pm-g1-boss-20", "pm-g1-boss-map"],
        "summary": "点亮全部知识点，并击败三名关主：十以内加减、二十以内进退位、地图通关试炼。",
    },
    "content_disclaimer": "知识点与任务为课标/教材目录风格的原创教学大纲与自编提示语，不是任何版本教科书正文或习题的摘录。",
    "description": "小学一年级「数与代数」入门地图：10 以内认识与加减 → 20 以内进退位 → 100 以内数的认识与简单加减。适合作为点亮知识点 RPG 的第一张可通关样例。",
}


SAMPLE_PROGRESS = {
    "player_id": "demo-learner",
    "display_name": "小明",
    "xp_total": 35,
    "current_map_id": "pm-g1-numbers",
    "cleared_map_ids": [],
    "nodes": {
        "pm-g1-n001": {
            "state": "lit",
            "xp_earned": 10,
            "cleared_quest_ids": ["pm-g1-n001-explain"],
            "updated_at": "2026-09-16T10:00:00Z",
        },
        "pm-g1-n002": {
            "state": "available",
            "xp_earned": 0,
            "cleared_quest_ids": [],
            "updated_at": "2026-09-16T10:00:00Z",
        },
        "pm-g1-n003": {
            "state": "learning",
            "xp_earned": 10,
            "cleared_quest_ids": ["pm-g1-n003-explain"],
            "updated_at": "2026-09-16T10:05:00Z",
        },
    },
}


def prereq_edges(nodes: list[dict]) -> list[dict]:
    edges = []
    for n in nodes:
        for src in n["prerequisites"]:
            edges.append(
                {
                    "from": src,
                    "to": n["id"],
                    "type": "prerequisite",
                    "note": f"{src} 需先于 {n['id']}",
                }
            )
    return edges


def dump(path: Path, data) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    edges = prereq_edges(NODES) + EXTRA_EDGES
    dump(OUT / "nodes.json", {"map_id": META["id"], "nodes": NODES})
    dump(OUT / "edges.json", {"map_id": META["id"], "edges": edges})
    dump(OUT / "quests.json", {"map_id": META["id"], "quests": QUESTS})
    dump(OUT / "map.meta.json", META)
    dump(OUT / "player-progress.sample.json", SAMPLE_PROGRESS)


if __name__ == "__main__":
    main()
