"""Build Grade 3 Geometry map JSON from a single source of truth.

Run: python3 scripts/_build_grade3_geometry.py

Pedagogical spine (课标/人教脉络风格，自撰短描述，非教材页原文):
  四边形再认识（长方形、正方形、平行四边形初步）
  → 周长（量一周、长方形正方形周长）
  → 面积入门（面积单位、长方形正方形面积）
  → 平移、旋转初步与轴对称判断。
观察物体（前面上面左面）为软锁支线。
本图自洽，不引用低年级或数与运算节点 id。
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _geo_common import (
    MASTERY_CONCEPT,
    MASTERY_GATE,
    ROOT,
    SOFT,
    node as _node,
    quest,
    write_map,
)

OUT = ROOT / "maps" / "primary-math" / "grade-3-geometry"
G = 3


def node(nid, title, difficulty, prereqs, tags, description, *, unlock=None, mastery=None):
    return _node(
        nid, title, G, difficulty, prereqs, tags, description, unlock=unlock, mastery=mastery
    )


NODES = [
    node(
        "pm-g3-geo-n001",
        "四边形有四条边",
        1,
        [],
        ["quad", "ch-quad"],
        "能指出四边形有四条边、四个角，并把明显不是四边形的图形排除出去。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g3-geo-n002",
        "长方形再认识",
        2,
        ["pm-g3-geo-n001"],
        ["quad", "ch-quad", "rectangle"],
        "能说明长方形对边相等、四个角是直角，并在方格纸上指出它的长和宽。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g3-geo-n003",
        "正方形再认识",
        2,
        ["pm-g3-geo-n002"],
        ["quad", "ch-quad", "square"],
        "能说明正方形四边相等、四个角是直角，它是特殊的长方形。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g3-geo-n004",
        "平行四边形长什么样",
        2,
        ["pm-g3-geo-n001"],
        ["quad", "ch-quad", "parallelogram"],
        "能辨认平行四边形：两组对边分别平行（看起来对边一样长、一样斜），角不一定是直角。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g3-geo-n005",
        "四边形家族",
        3,
        ["pm-g3-geo-n003", "pm-g3-geo-n004"],
        ["quad", "ch-quad", "classify"],
        "能把长方形、正方形、平行四边形放进四边形大家族里，并说出谁更「特殊」。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g3-geo-n006",
        "什么是周长",
        2,
        ["pm-g3-geo-n005"],
        ["perimeter", "ch-peri"],
        "知道周长是封闭图形一周的长度，能用绳子围一圈再拉开来理解。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g3-geo-n007",
        "量一周有多长",
        2,
        ["pm-g3-geo-n006"],
        ["perimeter", "ch-peri", "measure"],
        "能分段量出各边长度再相加，得到不规则或规则图形的周长。",
    ),
    node(
        "pm-g3-geo-n008",
        "长方形的周长",
        3,
        ["pm-g3-geo-n007", "pm-g3-geo-n002"],
        ["perimeter", "ch-peri", "rectangle"],
        "能用「长+宽+长+宽」或「（长+宽）×2」求长方形周长，并说明两种算法一样。",
    ),
    node(
        "pm-g3-geo-n009",
        "正方形的周长",
        3,
        ["pm-g3-geo-n008", "pm-g3-geo-n003"],
        ["perimeter", "ch-peri", "square"],
        "能用「边长×4」求正方形周长，并与长方形周长公式对照。",
    ),
    node(
        "pm-g3-geo-n010",
        "周长公式为什么",
        3,
        ["pm-g3-geo-n009"],
        ["perimeter", "ch-peri", "formula"],
        "能用自己的话说清：对边相等所以可以先加一组邻边再乘 2，正方形四边相等所以乘 4。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g3-geo-n011",
        "周长实际问题",
        3,
        ["pm-g3-geo-n010"],
        ["perimeter", "ch-peri", "application"],
        "能解决围篱笆、镜框边、跑道一圈等「求一周有多长」的短故事。",
    ),
    node(
        "pm-g3-geo-n012",
        "组合图形的周长",
        4,
        ["pm-g3-geo-n011"],
        ["perimeter", "ch-peri", "composite"],
        "能看出拼在一起的图形，外轮廓哪些边还在、哪些边被挡住不再算进周长。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g3-geo-n013",
        "周长综合",
        4,
        ["pm-g3-geo-n012"],
        ["perimeter", "ch-peri", "boss-gate"],
        "能在规则、组合与实际问题中正确求周长，不把中间的公共边重复加进去。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g3-geo-n014",
        "面的大小",
        2,
        ["pm-g3-geo-n013"],
        ["area", "ch-area"],
        "知道面积表示面的大小，能直观比较两张纸谁覆盖的地方更大。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g3-geo-n015",
        "平方厘米",
        2,
        ["pm-g3-geo-n014"],
        ["area", "ch-area", "unit"],
        "认识 1 平方厘米：边长 1 厘米的正方形的面积，用来量较小的面。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g3-geo-n016",
        "平方米与平方分米",
        3,
        ["pm-g3-geo-n015"],
        ["area", "ch-area", "unit"],
        "认识平方分米、平方米，能判断量手帕、课桌面、教室地面各用哪个单位更合适。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g3-geo-n017",
        "用面积单位铺一铺",
        3,
        ["pm-g3-geo-n016"],
        ["area", "ch-area", "measure"],
        "能用面积单位小正方形铺满图形，数出大约有多少格，就是大约多少面积单位。",
    ),
    node(
        "pm-g3-geo-n018",
        "长方形的面积",
        3,
        ["pm-g3-geo-n017"],
        ["area", "ch-area", "rectangle"],
        "能发现长方形每行有几个格、有几行，面积 = 长 × 宽（单位是面积单位）。",
    ),
    node(
        "pm-g3-geo-n019",
        "正方形的面积",
        3,
        ["pm-g3-geo-n018"],
        ["area", "ch-area", "square"],
        "能用「边长 × 边长」求正方形面积，并与长方形面积公式对照。",
    ),
    node(
        "pm-g3-geo-n020",
        "面积和周长不要混",
        4,
        ["pm-g3-geo-n019", "pm-g3-geo-n013"],
        ["area", "perimeter", "ch-area"],
        "能区分周长是「边走一圈」、面积是「面有多大」；同样的周长，面积不一定一样。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g3-geo-n021",
        "面积实际问题",
        3,
        ["pm-g3-geo-n020"],
        ["area", "ch-area", "application"],
        "能解决铺地砖、给长方形纸求面积等短故事，注意单位要用平方。",
    ),
    node(
        "pm-g3-geo-n022",
        "面积入门综合",
        4,
        ["pm-g3-geo-n021"],
        ["area", "ch-area", "boss-gate"],
        "能选择面积单位、求长方形正方形面积，并在易混题里指出谁在问周长、谁在问面积。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g3-geo-n023",
        "平移现象",
        2,
        ["pm-g3-geo-n005"],
        ["motion", "ch-motion", "translation"],
        "能从电梯、平移门感受图形整体移动、方向和大小不变。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g3-geo-n024",
        "方格纸上平移",
        3,
        ["pm-g3-geo-n023"],
        ["motion", "ch-motion", "translation"],
        "能在方格纸上把简单图形按「向右 3 格、向上 2 格」平移，并画出平移后的图形。",
    ),
    node(
        "pm-g3-geo-n025",
        "旋转现象",
        2,
        ["pm-g3-geo-n023"],
        ["motion", "ch-motion", "rotation"],
        "能从钟面指针、旋转木马感受图形绕一点转动；大小不变，方向会变。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g3-geo-n026",
        "轴对称图形判断",
        3,
        ["pm-g3-geo-n005"],
        ["motion", "ch-motion", "symmetry"],
        "能判断简单平面图形是不是轴对称图形，并画出一条对称轴。",
    ),
    node(
        "pm-g3-geo-n027",
        "图形的运动综合",
        3,
        ["pm-g3-geo-n024", "pm-g3-geo-n025", "pm-g3-geo-n026"],
        ["motion", "ch-motion"],
        "能分辨一道题是平移、旋转还是轴对称，不把「翻过来」说成「滑过去」。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g3-geo-n028",
        "从前面上面左面看",
        3,
        ["pm-g3-geo-n005"],
        ["view", "ch-view"],
        "能辨认简单物体从前面、上面、左面看到的形状；为四年级观察物体做铺垫。",
        unlock=SOFT,
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g3-geo-n029",
        "周长面积易混专练",
        4,
        ["pm-g3-geo-n020"],
        ["area", "perimeter", "ch-end"],
        "能在成对题目里先判断问的是周长还是面积，再选择加边还是长乘宽。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g3-geo-n030",
        "四边形周长面积合练",
        4,
        ["pm-g3-geo-n022", "pm-g3-geo-n027"],
        ["mixed", "ch-end"],
        "能在同一张综合练习里完成四边形辨认、周长、面积和简单平移。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g3-geo-n031",
        "三年级图形通关",
        5,
        ["pm-g3-geo-n030"],
        ["mixed", "ch-end", "boss-gate"],
        "综合四边形、周长、面积入门与图形运动初步，完成本图收束检查。",
        mastery=MASTERY_GATE,
    ),
]


EXTRA_EDGES = [
    {
        "from": "pm-g3-geo-n002",
        "to": "pm-g3-geo-n004",
        "type": "related",
        "note": "长方形可以看成角是直角的平行四边形。",
    },
    {
        "from": "pm-g3-geo-n003",
        "to": "pm-g3-geo-n004",
        "type": "related",
        "note": "正方形、长方形、平行四边形同属四边形家族。",
    },
    {
        "from": "pm-g3-geo-n008",
        "to": "pm-g3-geo-n009",
        "type": "related",
        "note": "正方形周长是长方形周长在长=宽时的特例。",
    },
    {
        "from": "pm-g3-geo-n011",
        "to": "pm-g3-geo-n012",
        "type": "easily_confused",
        "note": "围一周只算外轮廓；拼起来的公共边不再走第二遍。",
    },
    {
        "from": "pm-g3-geo-n006",
        "to": "pm-g3-geo-n014",
        "type": "easily_confused",
        "note": "周长走边，面积铺面，一个用长度单位，一个用面积单位。",
    },
    {
        "from": "pm-g3-geo-n018",
        "to": "pm-g3-geo-n008",
        "type": "easily_confused",
        "note": "长×宽是面积；周长是（长+宽）×2。公式里都有长和宽，最容易混。",
    },
    {
        "from": "pm-g3-geo-n015",
        "to": "pm-g3-geo-n016",
        "type": "related",
        "note": "面积单位从平方厘米到平方米，和长度单位厘米到米是配套的。",
    },
    {
        "from": "pm-g3-geo-n023",
        "to": "pm-g3-geo-n025",
        "type": "easily_confused",
        "note": "平移不转向，旋转绕一点转；看起来都在动，规则不同。",
    },
    {
        "from": "pm-g3-geo-n025",
        "to": "pm-g3-geo-n026",
        "type": "related",
        "note": "旋转和轴对称都改变方向感，但轴对称是翻折重合。",
    },
    {
        "from": "pm-g3-geo-n024",
        "to": "pm-g3-geo-n011",
        "type": "application",
        "note": "平移后图形大小不变，周长和面积也不变。",
    },
    {
        "from": "pm-g3-geo-n028",
        "to": "pm-g3-geo-n005",
        "type": "related",
        "note": "从不同方向看，四边形的某个面可能变成一条线段。",
    },
    {
        "from": "pm-g3-geo-n017",
        "to": "pm-g3-geo-n018",
        "type": "related",
        "note": "先数格子，再发现「每行几个×几行」就是长乘宽。",
    },
]


QUESTS = [
    quest(
        "pm-g3-geo-n001-explain",
        "pm-g3-geo-n001",
        "数四条边",
        "explain",
        10,
        "从一组图形里指出哪些是四边形，说明你是按「四条边围起来」来判断的。",
        "缺边、五条边、圆形都不是四边形。",
    ),
    quest(
        "pm-g3-geo-n002-explain",
        "pm-g3-geo-n002",
        "长和宽在哪",
        "explain",
        10,
        "在方格纸上的长方形里标出长和宽，并用三角板确认四个角都是直角。",
        "长通常指较长的那组对边。",
    ),
    quest(
        "pm-g3-geo-n003-explain",
        "pm-g3-geo-n003",
        "正方形更特殊",
        "explain",
        10,
        "说明正方形为什么可以算作长方形，但长方形不一定是正方形。",
        "正方形四边相等，长方形只要对边相等。",
    ),
    quest(
        "pm-g3-geo-n004-explain",
        "pm-g3-geo-n004",
        "斜斜的四边形",
        "explain",
        10,
        "指出平行四边形学具或图，拉动它让角变斜，观察对边是不是仍然一样长。",
        "对边平行（一样斜）是它的关键样子。",
    ),
    quest(
        "pm-g3-geo-n005-practice",
        "pm-g3-geo-n005",
        "四边形家族谱",
        "practice",
        20,
        "给 8 个四边形贴标签：正方形 / 长方形（非正方形）/ 平行四边形（非长方形）/ 其他。",
        "先看直角，再看边是否都相等。",
        8,
    ),
    quest(
        "pm-g3-geo-n006-explain",
        "pm-g3-geo-n006",
        "围一周",
        "explain",
        10,
        "用绳子围手帕一圈，拉开绳子说明「这一圈的长」就是周长。",
        "周长是边的总长，不是手帕有多大。",
    ),
    quest(
        "pm-g3-geo-n007-practice",
        "pm-g3-geo-n007",
        "分段量再加",
        "practice",
        20,
        "量一个三角形纸片三边（整厘米），相加得周长；再量一个不规则四边形。",
        "每一段都要对准 0，最后把各边加起来。",
        4,
    ),
    quest(
        "pm-g3-geo-n008-practice",
        "pm-g3-geo-n008",
        "两种周长算法",
        "practice",
        20,
        "对同一个长方形，用四边相加和（长+宽）×2 各算一次，核对得数。",
        "两种算法只是把相同的边合并着加。",
        6,
    ),
    quest(
        "pm-g3-geo-n009-practice",
        "pm-g3-geo-n009",
        "边长乘4",
        "practice",
        20,
        "求边长 6 厘米、8 厘米、1 分米的正方形周长，并说明为什么是乘 4。",
        "四条边一样长，所以乘 4。",
        6,
    ),
    quest(
        "pm-g3-geo-n010-explain",
        "pm-g3-geo-n010",
        "公式从哪来",
        "explain",
        10,
        "用自己的话讲清长方形周长为什么可以写成（长+宽）×2，正方形为什么是边长×4。",
        "先加一组邻边，因为对面还有同样的一组。",
    ),
    quest(
        "pm-g3-geo-n011-practice",
        "pm-g3-geo-n011",
        "篱笆和镜框",
        "practice",
        20,
        "解决两则短故事：给长方形菜地围篱笆；给正方形镜子做一圈木框。注意单位。",
        "问的是「一圈有多长」，用周长。",
        4,
    ),
    quest(
        "pm-g3-geo-n012-practice",
        "pm-g3-geo-n012",
        "公共边不算两遍",
        "practice",
        20,
        "两个长方形拼成「L」形，求外轮廓周长，标出哪几条边被拼进去了。",
        "被挡住的边不再走。",
        4,
    ),
    quest(
        "pm-g3-geo-n013-practice",
        "pm-g3-geo-n013",
        "周长闯关练",
        "practice",
        20,
        "混合：长方形、正方形、三角形、L 形组合。指出其中一题如果把公共边加进去会怎样。",
        "先描外轮廓，再决定加哪些边。",
        8,
    ),
    quest(
        "pm-g3-geo-n013-quiz",
        "pm-g3-geo-n013",
        "周长小测",
        "mini_quiz",
        30,
        "公式、实际问题、组合图形各有，夹一道把面积公式拿来求周长的改错。",
        "周长的单位是长度单位，不是平方。",
        8,
    ),
    quest(
        "pm-g3-geo-boss-perimeter",
        "pm-g3-geo-n013",
        "关主：周长测绘员",
        "boss",
        80,
        "击败关主：①说出周长含义 ②正确求长方形与正方形周长 ③求一个组合图形外轮廓周长。",
        "外轮廓走一遍，公共边不要付第二次钱。",
        12,
    ),
    quest(
        "pm-g3-geo-n014-explain",
        "pm-g3-geo-n014",
        "谁盖住的地方大",
        "explain",
        10,
        "把两张不同的纸叠一叠或铺在桌上，说明「盖住的地方」就是面的大小。",
        "面积看覆盖，不看边走一圈。",
    ),
    quest(
        "pm-g3-geo-n015-explain",
        "pm-g3-geo-n015",
        "1平方厘米",
        "explain",
        10,
        "剪或指出边长 1 厘米的小正方形，说明它的面积是 1 平方厘米。",
        "边长用厘米，面积就要说平方厘米。",
    ),
    quest(
        "pm-g3-geo-n016-practice",
        "pm-g3-geo-n016",
        "选面积单位",
        "practice",
        20,
        "给邮票、课桌面、教室地面、操场选择平方厘米、平方分米或平方米。",
        "面越大，越可能用平方米。",
        6,
    ),
    quest(
        "pm-g3-geo-n017-practice",
        "pm-g3-geo-n017",
        "数格子",
        "practice",
        20,
        "在方格纸上数出 3 个图形大约占几格（半格按半格算），写出面积。",
        "满格算 1，差不多半格算 0.5。",
        6,
    ),
    quest(
        "pm-g3-geo-n018-practice",
        "pm-g3-geo-n018",
        "每行几个乘几行",
        "practice",
        20,
        "求几个长方形面积：先数格子验证，再用长×宽算一遍。",
        "长和宽的单位相同，积的单位是平方。",
        6,
    ),
    quest(
        "pm-g3-geo-n019-practice",
        "pm-g3-geo-n019",
        "边长乘边长",
        "practice",
        20,
        "求边长 4 厘米、7 厘米、1 分米的正方形面积，并写上正确的面积单位。",
        "两个长度相乘，单位变成平方。",
        6,
    ),
    quest(
        "pm-g3-geo-n020-explain",
        "pm-g3-geo-n020",
        "走边还是铺面",
        "explain",
        10,
        "用同一张长方形纸，先求周长再求面积，说明两个得数单位为什么不同、意思有什么不同。",
        "周长用厘米，面积用平方厘米。",
    ),
    quest(
        "pm-g3-geo-n020-practice",
        "pm-g3-geo-n020",
        "周长面积对照",
        "practice",
        20,
        "成对题目：围篱笆 / 铺地砖；再比较两个周长相等、形状不同的图形面积是否一样。",
        "先判断问的是圈还是面。",
        6,
    ),
    quest(
        "pm-g3-geo-n021-practice",
        "pm-g3-geo-n021",
        "铺地砖短故事",
        "practice",
        20,
        "解决两则面积故事：给长方形桌面铺纸；给正方形手帕求面积。提醒写单位。",
        "铺满问的是面积。",
        4,
    ),
    quest(
        "pm-g3-geo-n022-practice",
        "pm-g3-geo-n022",
        "面积闯关练",
        "practice",
        20,
        "混合选单位、长方形正方形面积、与周长对照的易混题。",
        "看到「长×宽」先问：这是在铺面吗？",
        8,
    ),
    quest(
        "pm-g3-geo-n022-quiz",
        "pm-g3-geo-n022",
        "面积入门小测",
        "mini_quiz",
        30,
        "单位、公式、实际问题、周长面积判断各有。夹一道单位漏写「平方」的改错。",
        "面积单位必须带「平方」。",
        10,
    ),
    quest(
        "pm-g3-geo-boss-area",
        "pm-g3-geo-n022",
        "关主：面积铺贴员",
        "boss",
        80,
        "击败关主：①选对面积单位 ②求长方形与正方形面积 ③在一组题里指出哪几题其实在问周长。",
        "先判断圈还是面，再动笔。",
        12,
    ),
    quest(
        "pm-g3-geo-n023-explain",
        "pm-g3-geo-n023",
        "整体滑过去",
        "explain",
        10,
        "看平移门或电梯，说明图案怎样移动、有没有翻转或转动。",
        "平移：位置变，方向和大小不变。",
    ),
    quest(
        "pm-g3-geo-n024-practice",
        "pm-g3-geo-n024",
        "向右3格向上2格",
        "practice",
        20,
        "在方格纸上平移三角形和长方形各一次，标出对应点移动了几格。",
        "每个点移动的格数和方向都要相同。",
        4,
    ),
    quest(
        "pm-g3-geo-n025-explain",
        "pm-g3-geo-n025",
        "绕一点转",
        "explain",
        10,
        "看钟面指针或风车，指出旋转中心，说明转动后形状大小不变、朝向变了。",
        "旋转要说清绕哪一点、转了多少。",
    ),
    quest(
        "pm-g3-geo-n026-practice",
        "pm-g3-geo-n026",
        "对称轴画一画",
        "practice",
        20,
        "判断 6 个图形是不是轴对称，给是的图形画出一条对称轴（正方形可画不止一条）。",
        "对折能重合才有对称轴。",
        6,
    ),
    quest(
        "pm-g3-geo-n027-practice",
        "pm-g3-geo-n027",
        "三种运动辨一辨",
        "practice",
        20,
        "给 6 组「运动前后」的图，判断是平移、旋转还是轴对称（翻折）。",
        "滑、转、翻，先用一个字抓住动作。",
        6,
    ),
    quest(
        "pm-g3-geo-n028-practice",
        "pm-g3-geo-n028",
        "三个方向看积木",
        "practice",
        15,
        "看两层积木，选出前面、上面、左面的视图。本节点为软锁，可先走主线再回来。",
        "上面看的是俯视轮廓。",
        4,
    ),
    quest(
        "pm-g3-geo-n029-practice",
        "pm-g3-geo-n029",
        "先判断再计算",
        "practice",
        20,
        "10 道短题先圈「周长/面积」，再计算其中 6 道。含周长相等面积不同的对照。",
        "圈错了，公式再熟也会算错对象。",
        10,
    ),
    quest(
        "pm-g3-geo-n030-practice",
        "pm-g3-geo-n030",
        "四边形与测量合练",
        "practice",
        25,
        "混合：四边形分类、周长、面积、方格纸平移。",
        "每题先点名这是家族、圈还是面、还是运动。",
        10,
    ),
    quest(
        "pm-g3-geo-n030-quiz",
        "pm-g3-geo-n030",
        "合练小测",
        "mini_quiz",
        30,
        "覆盖四边形、周长公式、面积公式、易混判断和一题平移。",
        "（长+宽）×2 与长×宽不要对调。",
        10,
    ),
    quest(
        "pm-g3-geo-n031-practice",
        "pm-g3-geo-n031",
        "三年级图形综合练",
        "practice",
        25,
        "题型混合：辨认平行四边形、求周长与面积、组合图形外轮廓、平移 3 格。",
        "对回已经点亮的灯再下手。",
        12,
    ),
    quest(
        "pm-g3-geo-boss-map",
        "pm-g3-geo-n031",
        "关主：三年级图形通关试炼",
        "boss",
        100,
        "最终关主：①四边形家族 ②长方形正方形周长 ③长方形正方形面积 ④指出一题是周长还是面积 ⑤完成一次平移。全部通过即通关。",
        "通关后记入已通关列表；周长与面积是本图最容易回生的一对。",
        16,
    ),
]


META = {
    "id": "pm-g3-geometry",
    "title": "三年级 · 图形与几何",
    "subject": "数学",
    "stage": "小学",
    "grade": 3,
    "strand": "图形与几何",
    "version": "0.1.0",
    "locale": "zh-CN",
    "start_node_ids": ["pm-g3-geo-n001"],
    "recommended_path_note": "从「四边形有四条边」进入：先认长方形正方形与平行四边形初步，再打通周长，然后面积入门。平移旋转与轴对称判断可与测量主线并行。观察物体（n028）为软锁支线，不挡终章关主，通关前仍须点亮。",
    "win_condition": {
        "type": "light_all_nodes_and_bosses",
        "required_node_ids": "all",
        "required_boss_quest_ids": [
            "pm-g3-geo-boss-perimeter",
            "pm-g3-geo-boss-area",
            "pm-g3-geo-boss-map",
        ],
        "summary": "点亮全部知识点，并击败三名关主：周长测绘员、面积铺贴员、地图通关试炼。",
    },
    "content_disclaimer": "知识点与任务为课标/教材目录风格的原创教学大纲与自编提示语，不是任何版本教科书正文或习题的摘录。",
    "description": "小学三年级「图形与几何」地图：四边形 → 周长 → 面积入门 → 平移旋转初步。与二年级长度、角、长方形正方形初步概念衔接，但各自独立通关。",
}


SAMPLE_PROGRESS = {
    "player_id": "demo-learner",
    "display_name": "小明",
    "xp_total": 20,
    "current_map_id": "pm-g3-geometry",
    "cleared_map_ids": [],
    "nodes": {
        "pm-g3-geo-n001": {
            "state": "lit",
            "xp_earned": 10,
            "cleared_quest_ids": ["pm-g3-geo-n001-explain"],
            "updated_at": "2026-09-17T10:00:00Z",
        },
        "pm-g3-geo-n002": {
            "state": "learning",
            "xp_earned": 10,
            "cleared_quest_ids": ["pm-g3-geo-n002-explain"],
            "updated_at": "2026-09-17T10:08:00Z",
        },
    },
}


def main() -> None:
    write_map(OUT, META, NODES, EXTRA_EDGES, QUESTS, SAMPLE_PROGRESS)


if __name__ == "__main__":
    main()
