"""Build Grade 3 Numbers map JSON from a single source of truth.

Run: python3 scripts/_build_grade3_numbers.py
The generated JSON under maps/primary-math/grade-3-numbers/ is the published content.

Pedagogical spine (人教版/课标风格脉络，自撰短描述，非教材页原文):
  万以内加减巩固与估算 → 倍的认识 → 多位数乘一位数
  → 一位数除多位数（含余数）与乘除综合
  → 两位数乘两位数入门（与除法主线并行）
  → 分数初步（后半段）→ 小数初步（软锁支线，三年级下/四年级衔接）。
与二年级地图概念衔接（万以内读写与整百整千口算），但节点 id 不跨图引用。
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "maps" / "primary-math" / "grade-3-numbers"

HARD = {"type": "hard_all_prereqs", "allow_teacher_override": False}
SOFT = {"type": "soft_recommended", "allow_teacher_override": True}

MASTERY_CONCEPT = {
    "min_quests_cleared": 1,
    "require_quest_types": ["explain"],
    "review_after_days": 10,
}
MASTERY_SKILL = {
    "min_quests_cleared": 1,
    "min_quiz_accuracy": 0.8,
    "require_quest_types": ["practice"],
    "review_after_days": 7,
}
MASTERY_GATE = {
    "min_quests_cleared": 2,
    "min_quiz_accuracy": 0.85,
    "require_quest_types": ["practice"],
    "review_after_days": 5,
}


def node(
    nid: str,
    title: str,
    difficulty: int,
    prereqs: list[str],
    tags: list[str],
    description: str,
    *,
    unlock: dict | None = None,
    mastery: dict | None = None,
) -> dict:
    return {
        "id": nid,
        "title": title,
        "subject": "数学",
        "stage": "小学",
        "grade": 3,
        "strand": "数与代数",
        "difficulty": difficulty,
        "prerequisites": prereqs,
        "tags": tags,
        "unlock_rule": unlock or HARD,
        "mastery_criteria": mastery or MASTERY_SKILL,
        "description": description,
    }


# --- 38 nodes, teaching order ---
NODES = [
    # A. 万以内加减巩固 / 估算
    node(
        "pm-g3-n001",
        "万以内数位与组成复习",
        1,
        [],
        ["place-value", "ch-addsub", "review"],
        "能指出万以内一个数的千、百、十、个位，并说出各数位上的数表示几个千、几个百等。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g3-n002",
        "万以内加法（不进位）",
        2,
        ["pm-g3-n001"],
        ["add", "ch-addsub", "no-carry"],
        "对齐数位后，每一位都不满十时，能正确计算万以内加法。",
    ),
    node(
        "pm-g3-n003",
        "万以内加法（进位）",
        3,
        ["pm-g3-n002"],
        ["add", "ch-addsub", "carry"],
        "某一位满十时会向前一位进 1，包括连续进位，完成万以内加法。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g3-n004",
        "万以内减法（不退位）",
        2,
        ["pm-g3-n001"],
        ["subtract", "ch-addsub", "no-borrow"],
        "对齐数位后，每一位都够减时，能正确计算万以内减法。",
    ),
    node(
        "pm-g3-n005",
        "万以内减法（退位）",
        4,
        ["pm-g3-n003", "pm-g3-n004"],
        ["subtract", "ch-addsub", "borrow"],
        "某一位不够减时会向前一位借 1 当 10，包括连续退位，并能用加法想一想。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g3-n006",
        "连加连减与加减混合",
        3,
        ["pm-g3-n003", "pm-g3-n005"],
        ["mixed", "chain", "ch-addsub"],
        "能从左往右计算万以内连加、连减和加减混合，并记下中间得数。",
    ),
    node(
        "pm-g3-n007",
        "加减验算",
        3,
        ["pm-g3-n003", "pm-g3-n005"],
        ["check", "ch-addsub"],
        "会用交换加数或「差加减数」的办法验算万以内加减，发现抄错或进退位遗漏。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g3-n008",
        "估算加减得数",
        3,
        ["pm-g3-n003", "pm-g3-n005"],
        ["estimate", "ch-addsub"],
        "能把加数或减数看成接近的整百、整千，先估一估再判断精确得数是否合理。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g3-n009",
        "解决问题：万以内加减",
        3,
        ["pm-g3-n003", "pm-g3-n005"],
        ["word-problem", "ch-addsub", "application"],
        "在「一共、还剩、比多、比少」的短故事里选择加或减，并列万以内算式。",
    ),
    node(
        "pm-g3-n010",
        "万以内加减综合",
        4,
        ["pm-g3-n006", "pm-g3-n007", "pm-g3-n008", "pm-g3-n009"],
        ["fluency", "ch-addsub", "boss-gate"],
        "综合万以内进退位加减、验算、估算和应用题，能独立完成一小节混合练习。",
        mastery=MASTERY_GATE,
    ),
    # B. 倍的认识
    node(
        "pm-g3-n011",
        "倍的意义",
        2,
        ["pm-g3-n010"],
        ["times-as-many", "ch-times", "concept"],
        "知道「几倍」就是几个同样多的一份合起来，能用「几个几」说明倍。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g3-n012",
        "求一个数的几倍",
        3,
        ["pm-g3-n011"],
        ["times-as-many", "ch-times", "multiply"],
        "已知一份是多少、求它的几倍，会用乘法计算。",
    ),
    node(
        "pm-g3-n013",
        "求一个数是另一个数的几倍",
        3,
        ["pm-g3-n012"],
        ["times-as-many", "ch-times", "divide"],
        "比较两个数量时，会用除法求出一个数是另一个数的几倍。",
        mastery=MASTERY_GATE,
    ),
    # C. 多位数乘一位数
    node(
        "pm-g3-n014",
        "口算整十整百乘一位数",
        2,
        ["pm-g3-n010"],
        ["multiply", "ch-mul1", "mental"],
        "能把 30×6、200×4 这类题转化成「几个十、几个百」来口算。",
    ),
    node(
        "pm-g3-n015",
        "两位数乘一位数（不进位）",
        2,
        ["pm-g3-n014"],
        ["multiply", "ch-mul1", "no-carry"],
        "用竖式计算两位数乘一位数，每一位乘完都不满十时能对齐写积。",
    ),
    node(
        "pm-g3-n016",
        "两位数乘一位数（进位）",
        3,
        ["pm-g3-n015"],
        ["multiply", "ch-mul1", "carry"],
        "某一位乘完满十时会向前一位进，完成两位数乘一位数。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g3-n017",
        "三位数乘一位数",
        3,
        ["pm-g3-n016"],
        ["multiply", "ch-mul1"],
        "会用竖式计算三位数乘一位数，包括连续进位。",
    ),
    node(
        "pm-g3-n018",
        "因数中间或末尾有0",
        3,
        ["pm-g3-n017"],
        ["multiply", "ch-mul1", "zero"],
        "乘数中间或末尾有 0 时，积的对应位置要写对，不漏 0、不多 0。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g3-n019",
        "乘法估算",
        3,
        ["pm-g3-n014", "pm-g3-n008"],
        ["estimate", "ch-mul1"],
        "能把多位数看成接近的整十、整百再乘一位数，判断积大概落在哪一带。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g3-n020",
        "用乘法解决问题",
        3,
        ["pm-g3-n012", "pm-g3-n017"],
        ["word-problem", "ch-mul1", "application"],
        "在「每份同样多、求一共」或「求几倍」的短故事里列出乘法算式。",
    ),
    # D. 除数是一位数的除法
    node(
        "pm-g3-n021",
        "口算整十整百除以一位数",
        2,
        ["pm-g3-n014"],
        ["divide", "ch-div1", "mental"],
        "能把 80÷4、600÷3 转化成几个十、几个百来口算。",
    ),
    node(
        "pm-g3-n022",
        "一位数除两位数",
        3,
        ["pm-g3-n021", "pm-g3-n016"],
        ["divide", "ch-div1"],
        "会用竖式计算除数是一位数、被除数是两位数的除法，商写在正确的数位上。",
    ),
    node(
        "pm-g3-n023",
        "一位数除三位数",
        4,
        ["pm-g3-n022", "pm-g3-n017"],
        ["divide", "ch-div1"],
        "会用竖式计算一位数除三位数，从上到下一步一步除，并写出余下的部分。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g3-n024",
        "商中间或末尾有0",
        4,
        ["pm-g3-n023"],
        ["divide", "ch-div1", "zero"],
        "某一位不够商 1 时会在商的这一位写 0，不把 0 漏掉或挪位。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g3-n025",
        "有余数的除法（多位数）",
        4,
        ["pm-g3-n022"],
        ["divide", "ch-div1", "remainder"],
        "除到最后分不完时写出余数，余数必须比除数小，并能用乘加余数验算。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g3-n026",
        "用除法解决问题",
        3,
        ["pm-g3-n013", "pm-g3-n023", "pm-g3-n025"],
        ["word-problem", "ch-div1", "application"],
        "在「平均分、每份几个、能分几份、是几倍」的短故事里列出除法，并处理分不完的情况。",
    ),
    node(
        "pm-g3-n027",
        "乘除综合",
        4,
        ["pm-g3-n018", "pm-g3-n019", "pm-g3-n020", "pm-g3-n024", "pm-g3-n026"],
        ["fluency", "ch-div1", "boss-gate"],
        "综合多位数乘一位数、一位数除多位数、有 0 的积与商、估算和应用题。",
        mastery=MASTERY_GATE,
    ),
    # E. 两位数乘两位数入门（与除法主线并行）
    node(
        "pm-g3-n028",
        "两位数乘整十",
        3,
        ["pm-g3-n016"],
        ["multiply", "ch-mul2", "mental"],
        "会计算两位数乘 10、20、30 等，体会「先乘再在末尾补 0」或分步乘。",
    ),
    node(
        "pm-g3-n029",
        "两位数乘两位数（不进位）",
        3,
        ["pm-g3-n028"],
        ["multiply", "ch-mul2", "no-carry"],
        "会分两层：用个位乘一遍、用十位乘一遍，再把两次积加起来（暂不进位）。",
    ),
    node(
        "pm-g3-n030",
        "两位数乘两位数（进位）入门",
        4,
        ["pm-g3-n029"],
        ["multiply", "ch-mul2", "carry"],
        "每一层相乘若进位，会把进上去的数加对，完成两位数乘两位数的入门竖式。",
        mastery=MASTERY_GATE,
    ),
    # F. 分数初步（后半段）
    node(
        "pm-g3-n031",
        "认识几分之一",
        2,
        ["pm-g3-n027"],
        ["fraction", "ch-frac", "unit-fraction"],
        "把一个物体或一个整体平均分成几份，能指出其中一份是几分之一。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g3-n032",
        "认识几分之几",
        3,
        ["pm-g3-n031"],
        ["fraction", "ch-frac"],
        "平均分之后能指出取了几份，读写几分之几，知道分子、分母各表示什么。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g3-n033",
        "分数的简单比较",
        3,
        ["pm-g3-n032"],
        ["fraction", "ch-frac", "compare"],
        "能比较同分母分数的大小，也能比较分子都是 1 的几分之一的大小。",
    ),
    node(
        "pm-g3-n034",
        "分数与平均分",
        3,
        ["pm-g3-n032"],
        ["fraction", "ch-frac", "application"],
        "在「把一盘、一段、一袋平均分」的短情境里，用分数说出取出的部分。",
    ),
    # G. 小数初步（软锁支线：人教版三年级下常见，系统学习多在四年级）
    node(
        "pm-g3-n035",
        "认识一位小数",
        2,
        ["pm-g3-n033"],
        ["decimal", "ch-dec", "tenths"],
        "知道十分之几可以写成一位小数，能指出小数点左边是整数、右边第一位是十分位。",
        unlock=SOFT,
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g3-n036",
        "小数的读写与大小",
        3,
        ["pm-g3-n035"],
        ["decimal", "ch-dec", "compare"],
        "会读、写一位小数，并比较两个一位小数的大小。",
    ),
    node(
        "pm-g3-n037",
        "一位小数加减入门",
        3,
        ["pm-g3-n036"],
        ["decimal", "ch-dec", "add-sub"],
        "小数点对齐后，能计算简单的一位小数加减（以十分位为主）。",
    ),
    # H. 地图综合（小数为软锁支线，不挡终章关主，通关前仍须点亮）
    node(
        "pm-g3-n038",
        "三年级数与运算综合",
        5,
        ["pm-g3-n010", "pm-g3-n027", "pm-g3-n030", "pm-g3-n034"],
        ["synthesis", "ch-final", "boss-gate"],
        "综合万以内加减与估算、多位数乘除、两位数乘法入门和分数初步。",
        mastery=MASTERY_GATE,
    ),
]


EXTRA_EDGES = [
    {
        "from": "pm-g3-n002",
        "to": "pm-g3-n004",
        "type": "related",
        "note": "不进位加与不退位减都是按数位分别算。",
    },
    {
        "from": "pm-g3-n002",
        "to": "pm-g3-n003",
        "type": "easily_confused",
        "note": "万以内加法是否进位，只看这一位满不满十。",
    },
    {
        "from": "pm-g3-n004",
        "to": "pm-g3-n005",
        "type": "easily_confused",
        "note": "万以内减法是否退位，只看这一位够不够减。",
    },
    {
        "from": "pm-g3-n003",
        "to": "pm-g3-n005",
        "type": "easily_confused",
        "note": "连续进位与连续退位都动到「十」，方向相反。",
    },
    {
        "from": "pm-g3-n007",
        "to": "pm-g3-n008",
        "type": "related",
        "note": "验算查对错，估算先看是否离谱。",
    },
    {
        "from": "pm-g3-n008",
        "to": "pm-g3-n019",
        "type": "related",
        "note": "加减估算的「看成整百整千」同样用在乘法估算。",
    },
    {
        "from": "pm-g3-n011",
        "to": "pm-g3-n014",
        "type": "related",
        "note": "「几个几」既是倍，也是乘法口算的意义。",
    },
    {
        "from": "pm-g3-n012",
        "to": "pm-g3-n013",
        "type": "easily_confused",
        "note": "求几倍用乘；求「是几倍」用除，方向容易反。",
    },
    {
        "from": "pm-g3-n014",
        "to": "pm-g3-n021",
        "type": "related",
        "note": "整十整百乘一位数与除以一位数互为口算伙伴。",
    },
    {
        "from": "pm-g3-n015",
        "to": "pm-g3-n016",
        "type": "easily_confused",
        "note": "乘一位数是否进位，看这一位乘完满不满十。",
    },
    {
        "from": "pm-g3-n018",
        "to": "pm-g3-n024",
        "type": "easily_confused",
        "note": "积里的 0 和商里的 0 来源不同：一个是因数有 0，一个是这一位不够商 1。",
    },
    {
        "from": "pm-g3-n020",
        "to": "pm-g3-n026",
        "type": "easily_confused",
        "note": "「求一共/几倍」用乘，「求每份、份数、是几倍」用除。",
    },
    {
        "from": "pm-g3-n022",
        "to": "pm-g3-n025",
        "type": "easily_confused",
        "note": "正好除尽与有余数，要先看是不是还能再分一份。",
    },
    {
        "from": "pm-g3-n016",
        "to": "pm-g3-n028",
        "type": "related",
        "note": "乘一位数熟练后，再把「乘整十」看成乘 1 再补 0。",
    },
    {
        "from": "pm-g3-n029",
        "to": "pm-g3-n030",
        "type": "easily_confused",
        "note": "两层相乘时，每一层自己也可能进位，不要只加不进。",
    },
    {
        "from": "pm-g3-n026",
        "to": "pm-g3-n031",
        "type": "related",
        "note": "平均分的份数意识，接着用来认识几分之一。",
    },
    {
        "from": "pm-g3-n031",
        "to": "pm-g3-n032",
        "type": "easily_confused",
        "note": "几分之一是取 1 份；几分之几是取了若干份。",
    },
    {
        "from": "pm-g3-n032",
        "to": "pm-g3-n035",
        "type": "easily_confused",
        "note": "十分之几和一位小数表示同一类「十分位上的数」，写法不同。",
    },
    {
        "from": "pm-g3-n001",
        "to": "pm-g3-n035",
        "type": "related",
        "note": "整数数位顺序帮着理解十分位在小数点右边第一位。",
    },
    {
        "from": "pm-g3-n033",
        "to": "pm-g3-n036",
        "type": "related",
        "note": "分数比大小的经验可以对照一位小数比大小。",
    },
    {
        "from": "pm-g3-n003",
        "to": "pm-g3-n009",
        "type": "application",
        "note": "把进位加法用到「一共、比多」问题。",
    },
    {
        "from": "pm-g3-n005",
        "to": "pm-g3-n009",
        "type": "application",
        "note": "把退位减法用到「还剩、比少」问题。",
    },
    {
        "from": "pm-g3-n017",
        "to": "pm-g3-n020",
        "type": "application",
        "note": "三位数乘一位数服务于「每份同样多」的实际问题。",
    },
    {
        "from": "pm-g3-n023",
        "to": "pm-g3-n026",
        "type": "application",
        "note": "一位数除三位数用来解决平均分与求份数。",
    },
    {
        "from": "pm-g3-n032",
        "to": "pm-g3-n034",
        "type": "application",
        "note": "几分之几用到「取出几份」的生活情境。",
    },
    {
        "from": "pm-g3-n019",
        "to": "pm-g3-n027",
        "type": "application",
        "note": "用乘法估算判断乘除综合题的积是否合理。",
    },
    {
        "from": "pm-g3-n030",
        "to": "pm-g3-n038",
        "type": "application",
        "note": "两位数乘法入门进入终章综合。",
    },
]


def quest(
    qid: str,
    node_id: str,
    title: str,
    qtype: str,
    xp: int,
    prompt: str,
    hint: str,
    items: int | None = None,
) -> dict:
    q = {
        "id": qid,
        "node_id": node_id,
        "title": title,
        "type": qtype,
        "xp": xp,
        "prompt": prompt,
        "success_hint": hint,
    }
    if items is not None:
        q["items_suggested"] = items
    return q


QUESTS = [
    # A
    quest(
        "pm-g3-n001-explain",
        "pm-g3-n001",
        "指出千百十个",
        "explain",
        10,
        "任意说一个四位数，指出千位、百位、十位、个位，并说出每一位上的数各表示多少。",
        "从右边起：个、十、百、千。",
    ),
    quest(
        "pm-g3-n001-practice",
        "pm-g3-n001",
        "组成填空",
        "practice",
        15,
        "完成如 4706＝□个千□个百□个十□个一；也能根据「3 个千和 8 个十」写出这个数。",
        "哪一位上是 0，就表示这一位一个单位也没有。",
        8,
    ),
    quest(
        "pm-g3-n002-practice",
        "pm-g3-n002",
        "对齐数位再加",
        "practice",
        20,
        "竖式计算万以内不进位加法，如 3120+456、2503+130、1402+357。",
        "相同数位对齐，从个位加起。",
        8,
    ),
    quest(
        "pm-g3-n003-explain",
        "pm-g3-n003",
        "满十向前一位进1",
        "explain",
        10,
        "用计数器或竖式说明 358+276：个位满十向十位进 1，十位再满十向百位进 1。",
        "哪一位满十，就向前一位进 1。",
    ),
    quest(
        "pm-g3-n003-practice",
        "pm-g3-n003",
        "万以内进位加法练",
        "practice",
        20,
        "竖式计算含一次进位和连续进位的万以内加法，进上去的 1 要写在竖式里。",
        "进上去的 1 不要忘了加到前一位。",
        10,
    ),
    quest(
        "pm-g3-n003-quiz",
        "pm-g3-n003",
        "进位还是不进位",
        "mini_quiz",
        30,
        "混合不进位与进位的万以内加法，先判断类型再计算。",
        "一位一位看，满十才进。",
        8,
    ),
    quest(
        "pm-g3-n004-practice",
        "pm-g3-n004",
        "对齐数位再减",
        "practice",
        20,
        "竖式计算万以内不退位减法，如 5896−1234、4705−300、6580−250。",
        "每一位都够减时，不必向前借。",
        8,
    ),
    quest(
        "pm-g3-n005-explain",
        "pm-g3-n005",
        "不够减就向前借",
        "explain",
        10,
        "说明 402−178：个位不够减向十位借，十位是 0 时要继续向百位借。",
        "哪一位不够减，就向前一位借 1 当 10。",
    ),
    quest(
        "pm-g3-n005-practice",
        "pm-g3-n005",
        "万以内退位减法练",
        "practice",
        20,
        "竖式计算含退位和连续退位的万以内减法，并用加法验算两题。",
        "差加上减数，应当等于被减数。",
        10,
    ),
    quest(
        "pm-g3-n005-quiz",
        "pm-g3-n005",
        "退位还是不退位",
        "mini_quiz",
        30,
        "进位加、退位减混排，要先判断类型再计算。",
        "加看满十，减看够减。",
        10,
    ),
    quest(
        "pm-g3-n006-explain",
        "pm-g3-n006",
        "从左往右一步一步",
        "explain",
        10,
        "用「先运来 1250 箱，又运来 380 箱，运走 460 箱」说明 1250+380−460 要先算哪一步。",
        "连加连减和加减混合都从左边开始。",
    ),
    quest(
        "pm-g3-n006-practice",
        "pm-g3-n006",
        "混合式中间得数",
        "practice",
        20,
        "计算若干万以内连加、连减、加减混合，写出每一步的中间得数。",
        "可以在第一步下面标出小得数。",
        8,
    ),
    quest(
        "pm-g3-n007-explain",
        "pm-g3-n007",
        "怎样知道算对了",
        "explain",
        10,
        "各举一道加法和减法，说出用「交换加数再加一遍」或「差加减数」怎样验算。",
        "加法可以交换加数；减法用差加减数看是否回到被减数。",
    ),
    quest(
        "pm-g3-n007-practice",
        "pm-g3-n007",
        "验算找错",
        "practice",
        20,
        "给几道已算出的万以内加减，用验算判断对错，并把错题改正。",
        "验算对不上，先查数位有没有对齐。",
        6,
    ),
    quest(
        "pm-g3-n008-explain",
        "pm-g3-n008",
        "先看成整百整千",
        "explain",
        10,
        "把 1980+312 看成 2000+300，说明「大约」是在找接近的整百或整千，用来估计得数大概是多少。",
        "估算先看高位，不必先算得完全精确。",
    ),
    quest(
        "pm-g3-n008-practice",
        "pm-g3-n008",
        "估一估是否合理",
        "practice",
        20,
        "给几道万以内加减，先估再算或判断别人的得数是否合理（如 3900+4100 不可能得 800）。",
        "整千相加能很快看出对不对。",
        6,
    ),
    quest(
        "pm-g3-n009-explain",
        "pm-g3-n009",
        "故事里是加还是减",
        "explain",
        10,
        "各举一则「一共」「还剩」「比一个数多几」的短故事（数量在千以上），说明为什么用加或减。",
        "先找到已知的那个数，再看是合起来还是去掉、比较。",
    ),
    quest(
        "pm-g3-n009-practice",
        "pm-g3-n009",
        "万以内加减故事",
        "practice",
        20,
        "完成「一共、还剩、比多、比少」短故事各一则，并列万以内算式计算。",
        "「比多」在标准上再加；「比少」从标准里减。",
        4,
    ),
    quest(
        "pm-g3-n010-practice",
        "pm-g3-n010",
        "万以内加减综合练",
        "practice",
        25,
        "混合竖式进退位、连加连减、验算、估算和一则应用题。",
        "先判断这题在考进位、退位、验算还是选运算。",
        12,
    ),
    quest(
        "pm-g3-n010-quiz",
        "pm-g3-n010",
        "万以内加减小测",
        "mini_quiz",
        30,
        "限时混合检测：连续进位加、连续退位减、一道验算、一道估算、一则比多或还剩故事。",
        "竖式一定对齐数位。",
        10,
    ),
    quest(
        "pm-g3-boss-add",
        "pm-g3-n010",
        "关主：万以内加减大闯关",
        "boss",
        80,
        "击败关主条件：①说出一次连续进位或连续退位的过程 ②正确完成进位加与退位减各 3 题 ③用验算检查一题 ④先估再算或判断一题是否合理 ⑤一则「一共/还剩」短故事列式正确。",
        "这一关之后，万以内加减就打通了。",
        12,
    ),
    # B
    quest(
        "pm-g3-n011-explain",
        "pm-g3-n011",
        "几倍就是几个几",
        "explain",
        10,
        "一盘有 6 颗草莓，三盘是 6 的 3 倍。用「3 个 6」说明「倍」是几个同样多的一份。",
        "几倍就是把这一份同样地取几次。",
    ),
    quest(
        "pm-g3-n012-explain",
        "pm-g3-n012",
        "求几倍用乘法",
        "explain",
        10,
        "一份是 8，求它的 4 倍。说明为什么写成 8×4，并求出得数。",
        "已知一份的数量，求几倍，用乘法。",
    ),
    quest(
        "pm-g3-n012-practice",
        "pm-g3-n012",
        "一个数的几倍",
        "practice",
        20,
        "完成若干「求一个数的几倍」的口算或笔算，夹一则短故事。",
        "先找出「一份是多少」和「是几倍」。",
        8,
    ),
    quest(
        "pm-g3-n013-explain",
        "pm-g3-n013",
        "求是几倍用除法",
        "explain",
        10,
        "红绳 24 厘米，蓝绳 6 厘米。说明「24 是 6 的几倍」为什么用除法，并列出算式。",
        "看一个数里有几个另一个数，就是求倍数。",
    ),
    quest(
        "pm-g3-n013-practice",
        "pm-g3-n013",
        "是几倍还是几倍是多少",
        "practice",
        20,
        "混合「求一个数的几倍」和「求一个数是另一个数的几倍」，先判断用乘还是用除。",
        "已知倍数求数量用乘；已知两个数量求倍数用除。",
        8,
    ),
    quest(
        "pm-g3-n013-quiz",
        "pm-g3-n013",
        "倍的方向小测",
        "mini_quiz",
        25,
        "乘、除混排的「倍」问题，正确率达到掌握标准才过关。",
        "先问：是在求「几倍是多少」，还是在求「是几倍」。",
        8,
    ),
    # C
    quest(
        "pm-g3-n014-explain",
        "pm-g3-n014",
        "几个十几个百",
        "explain",
        10,
        "把 40×7 说成 4 个十乘 7，把 300×5 说成 3 个百乘 5，并口算出结果。",
        "先算前面的数字，再在后面补上原来的 0。",
    ),
    quest(
        "pm-g3-n014-practice",
        "pm-g3-n014",
        "整十整百口算乘",
        "practice",
        20,
        "口算 20×6、70×8、400×3、900×5 等，写出想的过程。",
        "只算有数字的那一位，0 跟着写在后面。",
        10,
    ),
    quest(
        "pm-g3-n015-practice",
        "pm-g3-n015",
        "两位数乘一位数不进位",
        "practice",
        20,
        "竖式计算每一位乘完都不满十的两位数乘一位数，如 23×2、31×3、40×2。",
        "从个位乘起，积写在对应数位下面。",
        8,
    ),
    quest(
        "pm-g3-n016-explain",
        "pm-g3-n016",
        "乘完满十怎么办",
        "explain",
        10,
        "用竖式说明 28×4：个位 8×4=32，写 2 向十位进 3，再算十位。",
        "哪一位乘完满十，就把满了几个十进到前一位。",
    ),
    quest(
        "pm-g3-n016-practice",
        "pm-g3-n016",
        "两位数乘一位数进位练",
        "practice",
        20,
        "竖式计算两位数乘一位数（进位），进上去的数要标在竖式里。",
        "进上去的数要和下一位的积加在一起。",
        10,
    ),
    quest(
        "pm-g3-n016-quiz",
        "pm-g3-n016",
        "乘一位数进位小测",
        "mini_quiz",
        30,
        "混合不进位与进位的两位数乘一位数，先判断再计算。",
        "看这一位乘完满不满十。",
        8,
    ),
    quest(
        "pm-g3-n017-practice",
        "pm-g3-n017",
        "三位数乘一位数练",
        "practice",
        20,
        "竖式计算三位数乘一位数，含连续进位，如 256×3、470×6。",
        "从个位乘到百位，每一位的进位都要加上。",
        8,
    ),
    quest(
        "pm-g3-n018-explain",
        "pm-g3-n018",
        "0乘任何数得0",
        "explain",
        10,
        "比较 205×4 和 250×4：中间的 0 与末尾的 0 在积里各出现在哪一位，并说明为什么。",
        "这一位是 0，乘完这一位就是 0；末尾的 0 可以先记下再补上。",
    ),
    quest(
        "pm-g3-n018-practice",
        "pm-g3-n018",
        "积里的0",
        "practice",
        20,
        "计算因数中间有 0 或末尾有 0 的多位数乘一位数，检查积里的 0 有没有写丢。",
        "中间的 0 不能跳过；末尾有几个 0 积的末尾往往也要有。",
        8,
    ),
    quest(
        "pm-g3-n019-explain",
        "pm-g3-n019",
        "先看成整十再乘",
        "explain",
        10,
        "把 198×4 看成 200×4，说明积大约是 800，用来判断精确计算有没有算飞。",
        "估算先看高位，再乘一位数。",
    ),
    quest(
        "pm-g3-n019-practice",
        "pm-g3-n019",
        "乘法估一估",
        "practice",
        20,
        "给几道多位数乘一位数，先估后算，或判断别人的积是否合理。",
        "198×5 接近 200×5=1000，不可能只有 200 多。",
        6,
    ),
    quest(
        "pm-g3-n020-explain",
        "pm-g3-n020",
        "每份同样多求一共",
        "explain",
        10,
        "每箱 125 本练习本，有 6 箱。用「几个几」或「倍」说明为什么用乘法，并列出算式。",
        "每份同样多，求一共，就用乘法。",
    ),
    quest(
        "pm-g3-n020-practice",
        "pm-g3-n020",
        "乘法故事练习",
        "practice",
        20,
        "完成「每份同样多求一共」和「求几倍」短故事各两则，并列式计算。",
        "先找出「每份几个」和「有几份」。",
        4,
    ),
    # D
    quest(
        "pm-g3-n021-explain",
        "pm-g3-n021",
        "几个十除以几",
        "explain",
        10,
        "把 80÷4 说成 8 个十平均分成 4 份，把 600÷3 说成 6 个百平均分成 3 份。",
        "先算前面的数字，0 再跟上。",
    ),
    quest(
        "pm-g3-n021-practice",
        "pm-g3-n021",
        "整十整百口算除",
        "practice",
        20,
        "口算 60÷3、90÷3、800÷4、400÷2 等，并用乘法验算两题。",
        "商乘除数应当回到被除数。",
        10,
    ),
    quest(
        "pm-g3-n022-explain",
        "pm-g3-n022",
        "商写在哪一位",
        "explain",
        10,
        "用竖式说明 96÷4：先看十位够不够除，商写在十位上，再除个位。",
        "除到哪一位，商就写在哪一位的上面。",
    ),
    quest(
        "pm-g3-n022-practice",
        "pm-g3-n022",
        "一位数除两位数练",
        "practice",
        20,
        "竖式计算除数是一位数、被除数是两位数的除法，商的数位要对齐。",
        "不够除就看下一位，不要把商写错位。",
        8,
    ),
    quest(
        "pm-g3-n023-practice",
        "pm-g3-n023",
        "一位数除三位数练",
        "practice",
        20,
        "竖式计算一位数除三位数，每一步写下乘积和余下的数。",
        "从上到下，除完这一位，余下的数落下来继续除。",
        8,
    ),
    quest(
        "pm-g3-n023-quiz",
        "pm-g3-n023",
        "除法竖式小测",
        "mini_quiz",
        30,
        "混合两位数、三位数被除数的一位数除法，正确率达到掌握标准才过关。",
        "可以用乘法当场验算。",
        8,
    ),
    quest(
        "pm-g3-n024-explain",
        "pm-g3-n024",
        "这一位不够商就写0",
        "explain",
        10,
        "说明 812÷4：百位商 2 之后，十位上余下的数不够商 1，这一位要写 0，再除个位。",
        "不够商 1 的那一位必须写 0，占住数位。",
    ),
    quest(
        "pm-g3-n024-practice",
        "pm-g3-n024",
        "商里的0",
        "practice",
        20,
        "计算商的中间或末尾有 0 的一位数除法，检查 0 有没有写丢。",
        "商少写一个 0，得数会差十倍。",
        8,
    ),
    quest(
        "pm-g3-n025-explain",
        "pm-g3-n025",
        "分不完剩下的叫余数",
        "explain",
        10,
        "把 250 支铅笔装进每盒 6 支的盒子，说明能装满几盒、还剩几支，并写出带余数的除法。",
        "余数一定要比除数小，否则还能再分一份。",
    ),
    quest(
        "pm-g3-n025-practice",
        "pm-g3-n025",
        "有余数除法练习",
        "practice",
        20,
        "计算若干一位数除多位数（有余数），用「商×除数+余数」验算；夹两道正好除尽的题。",
        "先想这一位最多能商几，剩下的就是带到下一位的余数。",
        8,
    ),
    quest(
        "pm-g3-n026-explain",
        "pm-g3-n026",
        "什么时候用除法",
        "explain",
        10,
        "各举一则「平均分成几份求每份」和「每几个一份能分几份」的短故事，并说明分不完时余数表示什么。",
        "已知一共和份数求每份，或已知一共和每份求份数，都用除法。",
    ),
    quest(
        "pm-g3-n026-practice",
        "pm-g3-n026",
        "除法故事练习",
        "practice",
        20,
        "完成平均分、求份数、求倍数故事，并穿插一则该用乘法的干扰故事；至少一则需要余数。",
        "求一共或几倍用乘；求每份、份数或是几倍用除。",
        5,
    ),
    quest(
        "pm-g3-n027-practice",
        "pm-g3-n027",
        "乘除综合练",
        "practice",
        25,
        "混合多位数乘一位数、一位数除多位数、积或商里有 0、有余数、估算和一则应用题。",
        "先判断是求一共、求每份，还是分不完。",
        12,
    ),
    quest(
        "pm-g3-n027-quiz",
        "pm-g3-n027",
        "乘除综合小测",
        "mini_quiz",
        30,
        "乘除混排加 2 道有 0 的积或商、1 道有余数、1 则应用题，正确率达到掌握标准才过关。",
        "可以用乘除互逆当场验算。",
        12,
    ),
    quest(
        "pm-g3-boss-muldiv",
        "pm-g3-n027",
        "关主：多位数乘除大闯关",
        "boss",
        90,
        "击败关主条件：①两位数或三位数乘一位数 3 题（含一题因数有 0）②一位数除多位数 3 题（含一题商有 0）③一道有余数除法（余数小于除数）④先估再算或判断一题积是否合理 ⑤一则用乘或除的短故事。",
        "竖式对齐数位，有 0 的积和商最容易写丢。",
        14,
    ),
    # E
    quest(
        "pm-g3-n028-explain",
        "pm-g3-n028",
        "乘整十可以先乘再补0",
        "explain",
        10,
        "把 24×30 看成 24×3 再在末尾补一个 0，或看成 24 个 30，说明两种想法人一样。",
        "乘整十：先按乘一位数算，再按整十补 0。",
    ),
    quest(
        "pm-g3-n028-practice",
        "pm-g3-n028",
        "两位数乘整十练",
        "practice",
        20,
        "计算 15×10、27×20、36×40 等，写出分步或补 0 的过程。",
        "先乘前面的非零数字，0 写在积的末尾。",
        8,
    ),
    quest(
        "pm-g3-n029-explain",
        "pm-g3-n029",
        "分两层再加起来",
        "explain",
        10,
        "用 12×34 说明：先用个位 4 去乘 12，再用十位 3 去乘 12（积向左错一位），最后把两层加起来。",
        "个位乘的积从个位写起，十位乘的积从十位写起。",
    ),
    quest(
        "pm-g3-n029-practice",
        "pm-g3-n029",
        "两位数乘法不进位",
        "practice",
        20,
        "竖式计算两层相乘暂不进位的两位数乘两位数，检查第二层是否错位。",
        "第二层是用十位去乘，末尾要空出个位（或写 0）。",
        6,
    ),
    quest(
        "pm-g3-n030-practice",
        "pm-g3-n030",
        "两位数乘法进位入门",
        "practice",
        25,
        "竖式计算两位数乘两位数（含进位），每一层的进位只加在这一层里。",
        "两层分别进位，最后再把两层积相加。",
        8,
    ),
    quest(
        "pm-g3-n030-quiz",
        "pm-g3-n030",
        "乘两位数入门小测",
        "mini_quiz",
        30,
        "混合乘整十、不进位与进位的两位数乘法，先标出两层再计算。",
        "先分清哪一层是个位乘、哪一层是十位乘。",
        8,
    ),
    # F
    quest(
        "pm-g3-n031-explain",
        "pm-g3-n031",
        "平均分成几份取一份",
        "explain",
        10,
        "把一张长方形纸对折再对折，指出其中一份是四分之一，并说出分母 4 表示什么。",
        "平均分成几份，一份就是几分之一。",
    ),
    quest(
        "pm-g3-n031-practice",
        "pm-g3-n031",
        "找出几分之一",
        "practice",
        15,
        "在圆形或纸条图上指出 1/2、1/3、1/4，并判断哪一份不是平均分。",
        "不是平均分，就不能用几分之一来表示。",
        6,
    ),
    quest(
        "pm-g3-n032-explain",
        "pm-g3-n032",
        "取了几份就是几分之几",
        "explain",
        10,
        "把一条彩带平均分成 8 段，涂色 3 段，说明这是八分之三，并指出分子、分母。",
        "分母是平均分的份数，分子是取了几份。",
    ),
    quest(
        "pm-g3-n032-practice",
        "pm-g3-n032",
        "读写几分之几",
        "practice",
        20,
        "看图写分数、看分数涂色，夹两道「取了全部」或「一份都没取」的判断。",
        "分子和分母同样大，表示取了整个；分子是 0 表示一份都没取。",
        8,
    ),
    quest(
        "pm-g3-n033-explain",
        "pm-g3-n033",
        "谁更大先看什么",
        "explain",
        10,
        "比较 3/8 和 5/8，再比较 1/2 和 1/4。说明同分母看分子，分子都是 1 时看谁分得更细。",
        "分得份数越多，每一份就越小。",
    ),
    quest(
        "pm-g3-n033-practice",
        "pm-g3-n033",
        "分数比大小",
        "practice",
        20,
        "比较同分母分数、分子是 1 的分数，填＞＜＝，并能在图上说明。",
        "同分母：分子大的反而大；分子是 1：分母大的反而小。",
        8,
    ),
    quest(
        "pm-g3-n034-explain",
        "pm-g3-n034",
        "生活里的几分之几",
        "explain",
        10,
        "一盘饺子平均分成 6 份，吃了 2 份。用分数说出吃了多少，还剩多少。",
        "先确认是不是平均分，再数取了几份。",
    ),
    quest(
        "pm-g3-n034-practice",
        "pm-g3-n034",
        "分数小故事",
        "practice",
        20,
        "完成三则「把一个整体平均分再取出几份」的短情境，写出分数并指出分子分母。",
        "问取出的部分，就写几分之几；问剩下的部分，分子用总份数减去取出的份数。",
        3,
    ),
    # G
    quest(
        "pm-g3-n035-explain",
        "pm-g3-n035",
        "十分之几写成小数",
        "explain",
        10,
        "把 3/10 写成 0.3，指出小数点右边第一位是十分位，并对照米和分米说一说。",
        "一位小数表示十分之几。",
    ),
    quest(
        "pm-g3-n035-practice",
        "pm-g3-n035",
        "分数和小数互相对照",
        "practice",
        15,
        "在 1/10 与 0.1、7/10 与 0.7 之间来回改写，并指出 0.5 是十分之五。",
        "十分位上是几，就是十分之几。",
        8,
    ),
    quest(
        "pm-g3-n036-practice",
        "pm-g3-n036",
        "一位小数读读写写",
        "practice",
        20,
        "读、写一位小数，并比较大小，如 0.4 和 0.8、1.2 和 0.9。",
        "先比整数部分，再比十分位。",
        10,
    ),
    quest(
        "pm-g3-n037-explain",
        "pm-g3-n037",
        "小数点对齐再加减",
        "explain",
        10,
        "用 0.5+0.3、1.2−0.4 说明：小数点对齐就是十分位对十分位，再按整数加减的办法算。",
        "小数点对齐后，从十分位算起。",
    ),
    quest(
        "pm-g3-n037-practice",
        "pm-g3-n037",
        "一位小数加减练",
        "practice",
        20,
        "计算简单的一位小数加减，检查小数点有没有对齐、得数的小数点有没有丢。",
        "得数里的小数点要与加数、减数对齐。",
        8,
    ),
    # H
    quest(
        "pm-g3-n038-practice",
        "pm-g3-n038",
        "地图综合练",
        "practice",
        25,
        "题型混合：万以内进退位加减、乘一位数、一位数除多位数、有余数、两位数乘法入门、分数读写比较、一则估算。",
        "先判断这题在考哪一盏已点亮的灯。",
        12,
    ),
    quest(
        "pm-g3-boss-map",
        "pm-g3-n038",
        "关主：三年级数与运算通关试炼",
        "boss",
        100,
        "最终关主：①万以内进位加、退位减各 1 题 ②三位数乘一位数 1 题 ③一位数除三位数 1 题（可含余数）④两位数乘两位数入门 1 题 ⑤读写并比较两个分数 ⑥用估算判断一道计算是否合理。全部通过即通关本地图。",
        "通关后这张地图记入已通关列表。二年级地图的万以内读写与整百整千口算，和本地图起点概念衔接，但存档仍按图分别计算，暂无跨地图引擎。",
        18,
    ),
]


META = {
    "id": "pm-g3-numbers",
    "title": "三年级 · 数与运算",
    "subject": "数学",
    "stage": "小学",
    "grade": 3,
    "strand": "数与代数",
    "version": "0.1.0",
    "locale": "zh-CN",
    "start_node_ids": ["pm-g3-n001"],
    "recommended_path_note": "从「万以内数位复习」进入：先打通万以内加减与估算，再倍的认识与多位数乘一位数、一位数除多位数（含余数），两位数乘两位数入门可与除法并行，然后分数初步。小数初步（n035）为软锁支线（三年级下/四年级衔接），不挡终章关主，通关前仍须点亮。",
    "win_condition": {
        "type": "light_all_nodes_and_bosses",
        "required_node_ids": "all",
        "required_boss_quest_ids": [
            "pm-g3-boss-add",
            "pm-g3-boss-muldiv",
            "pm-g3-boss-map",
        ],
        "summary": "点亮全部知识点，并击败三名关主：万以内加减、多位数乘除大闯关、地图通关试炼。",
    },
    "content_disclaimer": "知识点与任务为课标/教材目录风格的原创教学大纲与自编提示语，不是任何版本教科书正文或习题的摘录。",
    "description": "小学三年级「数与代数」地图：万以内加减巩固与估算 → 倍 → 多位数乘一位数 → 一位数除多位数 → 两位数乘两位数入门 → 分数初步；小数初步为软锁支线。与二年级地图概念衔接，但各自独立通关。",
}


SAMPLE_PROGRESS = {
    "player_id": "demo-learner",
    "display_name": "小明",
    "xp_total": 25,
    "current_map_id": "pm-g3-numbers",
    "cleared_map_ids": [],
    "nodes": {
        "pm-g3-n001": {
            "state": "lit",
            "xp_earned": 10,
            "cleared_quest_ids": ["pm-g3-n001-explain"],
            "updated_at": "2026-09-17T10:00:00Z",
        },
        "pm-g3-n002": {
            "state": "available",
            "xp_earned": 0,
            "cleared_quest_ids": [],
            "updated_at": "2026-09-17T10:00:00Z",
        },
        "pm-g3-n004": {
            "state": "learning",
            "xp_earned": 20,
            "cleared_quest_ids": ["pm-g3-n004-practice"],
            "updated_at": "2026-09-17T10:08:00Z",
        },
    },
}


def prereq_edges(nodes: list[dict]) -> list[dict]:
    edges = []
    for n in nodes:
        for src in n["prerequisites"]:
            edges.append(
                {
                    "from": src,
                    "to": n["id"],
                    "type": "prerequisite",
                    "note": f"{src} 需先于 {n['id']}",
                }
            )
    return edges


def dump(path: Path, data) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")


def _assert_field_limits() -> None:
    """Fail fast if learner-facing strings exceed schema limits."""
    for n in NODES:
        assert 1 <= len(n["title"]) <= 40, n["title"]
        assert 8 <= len(n["description"]) <= 160, (n["id"], len(n["description"]), n["description"])
    for q in QUESTS:
        assert 1 <= len(q["title"]) <= 40, q["title"]
        assert 4 <= len(q["prompt"]) <= 400, (q["id"], len(q["prompt"]))
        hint = q.get("success_hint") or ""
        assert len(hint) <= 200, (q["id"], len(hint))
    covered = {q["node_id"] for q in QUESTS}
    missing = [n["id"] for n in NODES if n["id"] not in covered]
    assert not missing, f"nodes without quests: {missing}"


def main() -> None:
    _assert_field_limits()
    OUT.mkdir(parents=True, exist_ok=True)
    edges = prereq_edges(NODES) + EXTRA_EDGES
    dump(OUT / "nodes.json", {"map_id": META["id"], "nodes": NODES})
    dump(OUT / "edges.json", {"map_id": META["id"], "edges": edges})
    dump(OUT / "quests.json", {"map_id": META["id"], "quests": QUESTS})
    dump(OUT / "map.meta.json", META)
    dump(OUT / "player-progress.sample.json", SAMPLE_PROGRESS)


if __name__ == "__main__":
    main()
