"""Build Grade 2 Numbers map JSON from a single source of truth.

Run: python3 scripts/_build_grade2_numbers.py
The generated JSON under maps/primary-math/grade-2-numbers/ is the published content.

Pedagogical spine (人教版/课标风格脉络，自撰短描述，非教材页原文):
  100 以内加减巩固 → 表内乘法 → 表内除法（含有余数入门）
  → 同级混合运算与小括号意识 → 万以内数认识与简单估算。
奇数与偶数为软锁支线，不挡口诀主路。
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "maps" / "primary-math" / "grade-2-numbers"

HARD = {"type": "hard_all_prereqs", "allow_teacher_override": False}
SOFT = {"type": "soft_recommended", "allow_teacher_override": True}

MASTERY_CONCEPT = {
    "min_quests_cleared": 1,
    "require_quest_types": ["explain"],
    "review_after_days": 10,
}
MASTERY_SKILL = {
    "min_quests_cleared": 1,
    "min_quiz_accuracy": 0.8,
    "require_quest_types": ["practice"],
    "review_after_days": 7,
}
MASTERY_GATE = {
    "min_quests_cleared": 2,
    "min_quiz_accuracy": 0.85,
    "require_quest_types": ["practice"],
    "review_after_days": 5,
}


def node(
    nid: str,
    title: str,
    difficulty: int,
    prereqs: list[str],
    tags: list[str],
    description: str,
    *,
    unlock: dict | None = None,
    mastery: dict | None = None,
) -> dict:
    return {
        "id": nid,
        "title": title,
        "subject": "数学",
        "stage": "小学",
        "grade": 2,
        "strand": "数与代数",
        "difficulty": difficulty,
        "prerequisites": prereqs,
        "tags": tags,
        "unlock_rule": unlock or HARD,
        "mastery_criteria": mastery or MASTERY_SKILL,
        "description": description,
    }


# --- 39 nodes, teaching order ---
NODES = [
    # A. 100 以内巩固
    node(
        "pm-g2-n001",
        "100以内数的组成复习",
        1,
        [],
        ["place-value", "ch-within-100", "review"],
        "能说出一个两位数是几个十和几个一，为进退位加减对齐数位做准备。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g2-n002",
        "两位数加一位数（进位）",
        2,
        ["pm-g2-n001"],
        ["add", "ch-within-100", "carry"],
        "个位相加满十时，会向十位进 1，正确计算两位数加一位数。",
    ),
    node(
        "pm-g2-n003",
        "两位数减一位数（退位）",
        2,
        ["pm-g2-n001"],
        ["subtract", "ch-within-100", "borrow"],
        "个位不够减时，会向十位借 1 当 10，正确计算两位数减一位数。",
    ),
    node(
        "pm-g2-n004",
        "两位数加两位数（不进位）",
        2,
        ["pm-g2-n001"],
        ["add", "ch-within-100", "no-carry"],
        "个位与十位分别相加且个位不满十时，能对齐数位算出两位数加两位数。",
    ),
    node(
        "pm-g2-n005",
        "两位数加两位数（进位）",
        3,
        ["pm-g2-n002", "pm-g2-n004"],
        ["add", "ch-within-100", "carry"],
        "个位相加满十时，会把进上去的 1 加到十位上，完成两位数加两位数。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g2-n006",
        "两位数减两位数（不退位）",
        2,
        ["pm-g2-n003", "pm-g2-n004"],
        ["subtract", "ch-within-100", "no-borrow"],
        "个位够减时，个位减个位、十位减十位，算出两位数减两位数。",
    ),
    node(
        "pm-g2-n007",
        "两位数减两位数（退位）",
        4,
        ["pm-g2-n003", "pm-g2-n005", "pm-g2-n006"],
        ["subtract", "ch-within-100", "borrow"],
        "个位不够减时会退位，并能用对应的进位加法验算。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g2-n008",
        "连加连减与加减混合",
        3,
        ["pm-g2-n005", "pm-g2-n007"],
        ["mixed", "chain", "ch-within-100"],
        "能从左往右计算 100 以内连加、连减和加减混合，并记下中间得数。",
    ),
    node(
        "pm-g2-n009",
        "解决问题：100以内加减",
        3,
        ["pm-g2-n005", "pm-g2-n007"],
        ["word-problem", "ch-within-100", "application"],
        "在「一共、还剩、比多、比少」的短故事里，正确选择加或减并列式。",
    ),
    node(
        "pm-g2-n010",
        "100以内加减综合",
        4,
        ["pm-g2-n008", "pm-g2-n009"],
        ["fluency", "ch-within-100", "boss-gate"],
        "综合口算与笔算 100 以内进退位加减，并能在应用题里选对运算。",
        mastery=MASTERY_GATE,
    ),
    # B. 表内乘法
    node(
        "pm-g2-n011",
        "相同加数与乘法的意义",
        2,
        ["pm-g2-n010"],
        ["multiply", "ch-times", "same-addend"],
        "知道几个相同的数连加可以用乘法表示，能说出「几个几」。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g2-n012",
        "乘法算式：因数与积",
        2,
        ["pm-g2-n011"],
        ["multiply", "ch-times"],
        "会读写乘法算式，知道乘号两边是因数、结果叫积。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g2-n013",
        "2和5的乘法口诀",
        2,
        ["pm-g2-n012"],
        ["multiply", "ch-times", "table-2-5"],
        "熟记 2、5 的乘法口诀，能根据口诀写出对应算式并求出积。",
    ),
    node(
        "pm-g2-n014",
        "3和4的乘法口诀",
        2,
        ["pm-g2-n013"],
        ["multiply", "ch-times", "table-3-4"],
        "熟记 3、4 的乘法口诀，能口算 3、4 乘一位数。",
    ),
    node(
        "pm-g2-n015",
        "6的乘法口诀",
        3,
        ["pm-g2-n014"],
        ["multiply", "ch-times", "table-6"],
        "熟记 6 的乘法口诀，至此能计算 2～6 乘一位数。",
    ),
    node(
        "pm-g2-n016",
        "7的乘法口诀",
        3,
        ["pm-g2-n015"],
        ["multiply", "ch-times", "table-7"],
        "熟记 7 的乘法口诀，能口算 7 乘一位数。",
    ),
    node(
        "pm-g2-n017",
        "8的乘法口诀",
        3,
        ["pm-g2-n016"],
        ["multiply", "ch-times", "table-8"],
        "熟记 8 的乘法口诀，能口算 8 乘一位数。",
    ),
    node(
        "pm-g2-n018",
        "9的乘法口诀",
        3,
        ["pm-g2-n017"],
        ["multiply", "ch-times", "table-9"],
        "熟记 9 的乘法口诀，能口算 9 乘一位数，并发现积的个位与十位相加常为 9。",
    ),
    node(
        "pm-g2-n019",
        "乘1与乘0",
        2,
        ["pm-g2-n013"],
        ["multiply", "ch-times", "zero-one"],
        "知道任何数乘 1 还是它本身，任何数乘 0 都得 0。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g2-n020",
        "乘法口诀表",
        3,
        ["pm-g2-n018", "pm-g2-n019"],
        ["multiply", "ch-times", "table"],
        "会在口诀表里查找积，体会交换两个因数积不变，并补全缺的口诀。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g2-n021",
        "用乘法解决问题",
        3,
        ["pm-g2-n020"],
        ["word-problem", "ch-times", "application"],
        "在「每份同样多、求一共」的短故事里列出乘法算式。",
    ),
    node(
        "pm-g2-n022",
        "奇数与偶数",
        2,
        ["pm-g2-n013"],
        ["parity", "ch-times"],
        "能判断 100 以内的数是奇数还是偶数，知道偶数能两个两个地数完。",
        unlock=SOFT,
        mastery=MASTERY_CONCEPT,
    ),
    # C. 表内除法
    node(
        "pm-g2-n023",
        "平均分",
        2,
        ["pm-g2-n011"],
        ["divide", "ch-div", "share"],
        "能把一些物品平均分成几份，每份同样多，并说出每份是几个。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g2-n024",
        "除法的意义",
        3,
        ["pm-g2-n012", "pm-g2-n023"],
        ["divide", "ch-div"],
        "知道平均分和「几个几个地分」都可以写成除法，会读写除号、被除数、除数和商。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g2-n025",
        "用2～6的口诀求商",
        3,
        ["pm-g2-n015", "pm-g2-n024"],
        ["divide", "ch-div", "table-2-6"],
        "会想乘法口诀求 2～6 作除数的表内除法的商。",
    ),
    node(
        "pm-g2-n026",
        "用7～9的口诀求商",
        3,
        ["pm-g2-n018", "pm-g2-n024"],
        ["divide", "ch-div", "table-7-9"],
        "会想 7、8、9 的口诀求商，完成表内除法。",
    ),
    node(
        "pm-g2-n027",
        "乘法和除法的关系",
        4,
        ["pm-g2-n021", "pm-g2-n025", "pm-g2-n026"],
        ["relation", "ch-div"],
        "知道乘除互逆：由两个因数与积，能写出相关的除法并用来验算。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g2-n028",
        "用除法解决问题",
        3,
        ["pm-g2-n027"],
        ["word-problem", "ch-div", "application"],
        "在「平均分、每份几个、能分几份」的短故事里列出除法算式。",
    ),
    node(
        "pm-g2-n029",
        "有余数的除法",
        4,
        ["pm-g2-n025"],
        ["divide", "ch-div", "remainder"],
        "知道分不完时商旁边还有余数，余数必须比除数小。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g2-n030",
        "表内乘除综合",
        4,
        ["pm-g2-n027", "pm-g2-n028", "pm-g2-n029"],
        ["fluency", "ch-div", "boss-gate"],
        "综合表内乘除、互逆验算和有余数除法，并在短故事里选对乘或除。",
        mastery=MASTERY_GATE,
    ),
    # D. 混合运算意识
    node(
        "pm-g2-n031",
        "同级两步混合运算",
        4,
        ["pm-g2-n010", "pm-g2-n030"],
        ["mixed", "ch-order"],
        "没有括号时，加减混合或乘除混合都从左往右按顺序算。",
    ),
    node(
        "pm-g2-n032",
        "小括号与运算顺序",
        4,
        ["pm-g2-n031"],
        ["mixed", "ch-order", "parentheses"],
        "有小括号时先算括号里面的，体会括号能改变运算顺序。",
        mastery=MASTERY_GATE,
    ),
    # E. 万以内数与估算
    node(
        "pm-g2-n033",
        "千以内数的认识",
        2,
        ["pm-g2-n001"],
        ["place-value", "ch-to10000", "thousands"],
        "认识 1000 以内各数，知道 10 个一百是一千，能顺着数、倒着数整百。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g2-n034",
        "万以内数的读与写",
        3,
        ["pm-g2-n033"],
        ["read-write", "ch-to10000"],
        "能读、写万以内的数，中间有 0 和末尾有 0 时不多数、不少读。",
    ),
    node(
        "pm-g2-n035",
        "万以内数的组成",
        3,
        ["pm-g2-n034"],
        ["place-value", "ch-to10000"],
        "能说出一个数含有几个千、几个百、几个十和几个一，建立数位顺序。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g2-n036",
        "万以内数的大小比较",
        3,
        ["pm-g2-n035"],
        ["compare", "ch-to10000"],
        "会先看位数、再从高位比起，比较万以内数的大小。",
    ),
    node(
        "pm-g2-n037",
        "整百整千数的加减",
        3,
        ["pm-g2-n010", "pm-g2-n035"],
        ["add", "subtract", "ch-to10000", "mental"],
        "能把整百、整千数的加减转化成几个百或几个千来口算。",
    ),
    node(
        "pm-g2-n038",
        "近似数与简单估算",
        4,
        ["pm-g2-n036", "pm-g2-n037"],
        ["estimate", "ch-to10000"],
        "能把一个数看成与它接近的整十、整百，并用估算判断得数是否合理。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g2-n039",
        "二年级数与运算综合",
        5,
        ["pm-g2-n010", "pm-g2-n030", "pm-g2-n032", "pm-g2-n038"],
        ["synthesis", "ch-final", "boss-gate"],
        "综合 100 以内加减、表内乘除、两步运算顺序、万以内读写比较与简单估算。",
        mastery=MASTERY_GATE,
    ),
]


EXTRA_EDGES = [
    {
        "from": "pm-g2-n002",
        "to": "pm-g2-n003",
        "type": "related",
        "note": "进位加与退位减宜对照着学。",
    },
    {
        "from": "pm-g2-n004",
        "to": "pm-g2-n006",
        "type": "related",
        "note": "不进位加与不退位减都是按数位分别算。",
    },
    {
        "from": "pm-g2-n004",
        "to": "pm-g2-n005",
        "type": "easily_confused",
        "note": "两位数加法是否进位，只看个位满不满十。",
    },
    {
        "from": "pm-g2-n006",
        "to": "pm-g2-n007",
        "type": "easily_confused",
        "note": "两位数减法是否退位，只看个位够不够减。",
    },
    {
        "from": "pm-g2-n005",
        "to": "pm-g2-n007",
        "type": "easily_confused",
        "note": "进位加与退位减都动到「十」，方向相反。",
    },
    {
        "from": "pm-g2-n008",
        "to": "pm-g2-n011",
        "type": "related",
        "note": "连加是认识「几个几」的桥梁。",
    },
    {
        "from": "pm-g2-n011",
        "to": "pm-g2-n023",
        "type": "related",
        "note": "相同加数合起来，与平均分是一对相反的过程。",
    },
    {
        "from": "pm-g2-n013",
        "to": "pm-g2-n022",
        "type": "related",
        "note": "2 的口诀帮着理解偶数是两个两个数完的。",
    },
    {
        "from": "pm-g2-n012",
        "to": "pm-g2-n024",
        "type": "related",
        "note": "乘法算式与除法算式对照着认各部分名称。",
    },
    {
        "from": "pm-g2-n023",
        "to": "pm-g2-n024",
        "type": "easily_confused",
        "note": "平均分和几个几个地分，都写成除法，分的过程不同。",
    },
    {
        "from": "pm-g2-n021",
        "to": "pm-g2-n028",
        "type": "easily_confused",
        "note": "「求一共」用乘，「求每份/份数」用除，容易选反。",
    },
    {
        "from": "pm-g2-n025",
        "to": "pm-g2-n029",
        "type": "easily_confused",
        "note": "正好分完与分不完（有余数）要先判断。",
    },
    {
        "from": "pm-g2-n018",
        "to": "pm-g2-n026",
        "type": "easily_confused",
        "note": "9 的口诀求积与用同一句口诀求商，容易乘除搞反。",
    },
    {
        "from": "pm-g2-n031",
        "to": "pm-g2-n032",
        "type": "easily_confused",
        "note": "没括号从左往右；有括号要先算括号里。",
    },
    {
        "from": "pm-g2-n036",
        "to": "pm-g2-n038",
        "type": "easily_confused",
        "note": "精确比较看每一位；估算只看接近的整十或整百。",
    },
    {
        "from": "pm-g2-n033",
        "to": "pm-g2-n035",
        "type": "related",
        "note": "认识千是万以内组成的台阶。",
    },
    {
        "from": "pm-g2-n005",
        "to": "pm-g2-n009",
        "type": "application",
        "note": "把进位加法用到「一共」问题。",
    },
    {
        "from": "pm-g2-n007",
        "to": "pm-g2-n009",
        "type": "application",
        "note": "把退位减法用到「还剩、比少」问题。",
    },
    {
        "from": "pm-g2-n020",
        "to": "pm-g2-n021",
        "type": "application",
        "note": "口诀表服务于「几个几」的实际问题。",
    },
    {
        "from": "pm-g2-n027",
        "to": "pm-g2-n028",
        "type": "application",
        "note": "用乘除互逆检查应用题列式。",
    },
    {
        "from": "pm-g2-n027",
        "to": "pm-g2-n030",
        "type": "application",
        "note": "互逆关系给表内乘除验算。",
    },
    {
        "from": "pm-g2-n038",
        "to": "pm-g2-n039",
        "type": "application",
        "note": "用估算判断综合题得数是否合理。",
    },
]


def quest(
    qid: str,
    node_id: str,
    title: str,
    qtype: str,
    xp: int,
    prompt: str,
    hint: str,
    items: int | None = None,
) -> dict:
    q = {
        "id": qid,
        "node_id": node_id,
        "title": title,
        "type": qtype,
        "xp": xp,
        "prompt": prompt,
        "success_hint": hint,
    }
    if items is not None:
        q["items_suggested"] = items
    return q


QUESTS = [
    # A
    quest(
        "pm-g2-n001-explain",
        "pm-g2-n001",
        "几个十几个一",
        "explain",
        10,
        "任意说一个两位数，用小棒或方块说明它是几个十和几个一，并指出十位、个位。",
        "十位上的数字表示几个十。",
    ),
    quest(
        "pm-g2-n001-practice",
        "pm-g2-n001",
        "组成填空",
        "practice",
        15,
        "完成如 47＝□个十和□个一；也能根据「3 个十和 8 个一」写出这个数。",
        "先看十位再看个位。",
        8,
    ),
    quest(
        "pm-g2-n002-explain",
        "pm-g2-n002",
        "个位满十怎么办",
        "explain",
        10,
        "用小棒说明 28+5：个位 8+5 满十，把 10 根捆成一捆加到十位。",
        "个位满十，向十位进 1。",
    ),
    quest(
        "pm-g2-n002-practice",
        "pm-g2-n002",
        "两位数加一位数进位练",
        "practice",
        20,
        "口算或竖式计算两位数加一位数（进位），如 36+7、49+8、55+6。",
        "先算个位，满十就进 1。",
        10,
    ),
    quest(
        "pm-g2-n003-explain",
        "pm-g2-n003",
        "个位不够减怎么办",
        "explain",
        10,
        "用小棒说明 32−5：打开一捆十，变成 10 和 2，再减 5。",
        "个位不够减，向十位借 1 当 10。",
    ),
    quest(
        "pm-g2-n003-practice",
        "pm-g2-n003",
        "两位数减一位数退位练",
        "practice",
        20,
        "计算两位数减一位数（退位），如 41−6、50−3、73−9。",
        "先看个位够不够减。",
        10,
    ),
    quest(
        "pm-g2-n004-practice",
        "pm-g2-n004",
        "对齐数位再加",
        "practice",
        20,
        "计算个位不满十的两位数加两位数，如 23+14、40+35、51+26。",
        "个位加个位，十位加十位。",
        8,
    ),
    quest(
        "pm-g2-n005-practice",
        "pm-g2-n005",
        "两位数进位加法练",
        "practice",
        20,
        "竖式计算两位数加两位数（进位），并在个位上标出进上去的 1。",
        "进上去的 1 不要忘了加到十位。",
        10,
    ),
    quest(
        "pm-g2-n005-quiz",
        "pm-g2-n005",
        "进位还是不进位",
        "mini_quiz",
        30,
        "混合不进位与进位的两位数加法，先判断类型再计算。",
        "只看个位相加满不满十。",
        8,
    ),
    quest(
        "pm-g2-n006-practice",
        "pm-g2-n006",
        "对齐数位再减",
        "practice",
        20,
        "计算个位够减的两位数减两位数，如 58−23、90−40、76−15。",
        "个位够减就不用借十。",
        8,
    ),
    quest(
        "pm-g2-n007-practice",
        "pm-g2-n007",
        "两位数退位减法练",
        "practice",
        20,
        "竖式计算两位数减两位数（退位），并用加法验算两题。",
        "差加上减数，应等于被减数。",
        10,
    ),
    quest(
        "pm-g2-n007-quiz",
        "pm-g2-n007",
        "退位还是不退位",
        "mini_quiz",
        30,
        "进位加、退位减混排，要先判断类型再计算。",
        "加看满十，减看够减。",
        10,
    ),
    quest(
        "pm-g2-n008-explain",
        "pm-g2-n008",
        "从左往右一步一步",
        "explain",
        10,
        "用「先来了 24 人，又来 18 人，走了 9 人」说明 24+18−9 要先算哪一步。",
        "连加连减和加减混合都从左边开始。",
    ),
    quest(
        "pm-g2-n008-practice",
        "pm-g2-n008",
        "混合式中间得数",
        "practice",
        20,
        "计算若干 100 以内连加、连减、加减混合，写出每一步的中间得数。",
        "可以在第一步下面标出小得数。",
        8,
    ),
    quest(
        "pm-g2-n009-explain",
        "pm-g2-n009",
        "故事里是加还是减",
        "explain",
        10,
        "各举一则「一共」「还剩」「比一个数多几」的短故事，说明为什么用加或减。",
        "先找到已知的那个数，再看是合起来还是去掉、比较。",
    ),
    quest(
        "pm-g2-n009-practice",
        "pm-g2-n009",
        "100以内加减故事",
        "practice",
        20,
        "完成「一共、还剩、比多、比少」短故事各一则，并列式计算。",
        "「比多」在标准上再加；「比少」从标准里减。",
        4,
    ),
    quest(
        "pm-g2-n010-practice",
        "pm-g2-n010",
        "100以内加减综合练",
        "practice",
        25,
        "混合口算、竖式和应用题：进位加、退位减、连加连减各若干题。",
        "先判断这题在考进位、退位，还是选运算。",
        12,
    ),
    quest(
        "pm-g2-n010-quiz",
        "pm-g2-n010",
        "100以内加减小测",
        "mini_quiz",
        30,
        "限时混合检测：竖式进退位、从左往右混合式、一则比多或还剩故事。",
        "竖式一定对齐个位和十位。",
        10,
    ),
    quest(
        "pm-g2-boss-100",
        "pm-g2-n010",
        "关主：一百以内进退位",
        "boss",
        80,
        "击败关主条件：①说出一次进位或退位的过程 ②正确完成进位加与退位减各 4 题 ③一则「一共/还剩」短故事列式正确。",
        "这一关之后，100 以内加减就打通了。",
        12,
    ),
    # B
    quest(
        "pm-g2-n011-explain",
        "pm-g2-n011",
        "几个几可以写成乘法",
        "explain",
        10,
        "把 2+2+2+2 说成「4 个 2」，并改写成乘法算式，说明乘号在代替相同加数的连加。",
        "相同的加数有几个，乘号前面（或后面）就写几。",
    ),
    quest(
        "pm-g2-n012-explain",
        "pm-g2-n012",
        "因数和积在哪里",
        "explain",
        10,
        "指着 3×5=15，说出哪个是因数、哪个是积，并再写一道「5 个 3」的算式。",
        "乘号两边都是因数，等号后面是积。",
    ),
    quest(
        "pm-g2-n013-practice",
        "pm-g2-n013",
        "二五口诀抢答",
        "practice",
        20,
        "按口诀顺序和打乱顺序各说一遍 2、5 的乘法口诀，并写出对应算式求积。",
        "一五得五、二五一十……顺着背，再用算式检查。",
        12,
    ),
    quest(
        "pm-g2-n014-practice",
        "pm-g2-n014",
        "三四口诀练习",
        "practice",
        20,
        "口算 3、4 乘一位数，缺一句口诀时能自己补出来。",
        "三四十二就是 3×4=12。",
        12,
    ),
    quest(
        "pm-g2-n015-practice",
        "pm-g2-n015",
        "六的口诀练习",
        "practice",
        20,
        "熟背 6 的口诀并口算 6 乘 1 到 6 乘 9；穿插两道 2～5 的复习。",
        "六六三十六，不要说成「三十五」。",
        10,
    ),
    quest(
        "pm-g2-n016-practice",
        "pm-g2-n016",
        "七的口诀练习",
        "practice",
        20,
        "熟背 7 的口诀并口算 7 乘一位数，用「几个 7」检查两题。",
        "七七四十九，可以用 7×6=42 再加 7 来想。",
        9,
    ),
    quest(
        "pm-g2-n017-practice",
        "pm-g2-n017",
        "八的口诀练习",
        "practice",
        20,
        "熟背 8 的口诀并口算 8 乘一位数。",
        "四八三十二、五八四十，相邻两句相差一个 8。",
        9,
    ),
    quest(
        "pm-g2-n018-practice",
        "pm-g2-n018",
        "九的口诀练习",
        "practice",
        20,
        "熟背 9 的口诀；观察积的个位与十位有什么有趣的关系。",
        "一九得九、二九十八……积的两个数字加起来常常是 9。",
        9,
    ),
    quest(
        "pm-g2-n019-explain",
        "pm-g2-n019",
        "乘1和乘0会怎样",
        "explain",
        10,
        "用「5 个 1」「0 个 4」说明任何数乘 1、乘 0 的结果，并各写两道算式。",
        "乘 1 不变，乘 0 得 0。",
    ),
    quest(
        "pm-g2-n020-practice",
        "pm-g2-n020",
        "口诀表找朋友",
        "practice",
        20,
        "在口诀表里查出指定积；再把 4×7 和 7×4 都算一遍，说说积为什么一样。",
        "交换因数，积不变，所以表里可以只记一半。",
        10,
    ),
    quest(
        "pm-g2-n020-quiz",
        "pm-g2-n020",
        "表内乘法小测",
        "mini_quiz",
        30,
        "打乱 2～9 的口诀求积，夹两道乘 0 或乘 1，正确率达到掌握标准才过关。",
        "想不起来时，用相邻口诀加减一个因数。",
        16,
    ),
    quest(
        "pm-g2-n021-explain",
        "pm-g2-n021",
        "每份同样多求一共",
        "explain",
        10,
        "每盒 6 支铅笔，有 4 盒。用「几个几」说明为什么用乘法，并列出算式。",
        "每份同样多，求一共，就用乘法。",
    ),
    quest(
        "pm-g2-n021-practice",
        "pm-g2-n021",
        "乘法故事练习",
        "practice",
        20,
        "完成三则「每份同样多、求一共」的短故事，并列式计算。",
        "先找出「每份几个」和「有几份」。",
        3,
    ),
    quest(
        "pm-g2-n022-explain",
        "pm-g2-n022",
        "两个两个数得完吗",
        "explain",
        10,
        "把 8 颗和 9 颗棋子各两个两个地分，说明哪个能分完、哪个会剩 1，并给偶数、奇数下个自己的定义。",
        "偶数能两个两个数完；奇数会剩下 1 个。",
    ),
    quest(
        "pm-g2-n022-practice",
        "pm-g2-n022",
        "奇偶分类",
        "practice",
        15,
        "把一组 100 以内的数分成奇数、偶数两堆，并指出个位是 0、2、4、6、8 的是偶数。",
        "看个位就能判断奇偶。",
        10,
    ),
    # C
    quest(
        "pm-g2-n023-explain",
        "pm-g2-n023",
        "怎样才叫平均分",
        "explain",
        10,
        "把 12 块糖平均分给 3 人，边分边说「每人同样多」，指出每份是几个。",
        "平均分的每一份要一样多，不能有人多有人少。",
    ),
    quest(
        "pm-g2-n024-explain",
        "pm-g2-n024",
        "除号表示什么",
        "explain",
        10,
        "把「12 平均分成 3 份」和「12 里有几个 3」都写成除法，指出被除数、除数、商。",
        "两种分法都可以用除法，算式里各部分名称要说清。",
    ),
    quest(
        "pm-g2-n025-practice",
        "pm-g2-n025",
        "想口诀求商（2～6）",
        "practice",
        20,
        "计算除数是 2～6 的表内除法，每题说出用的哪一句口诀。",
        "三六十八，所以 18÷6=3，也可以 18÷3=6。",
        12,
    ),
    quest(
        "pm-g2-n025-quiz",
        "pm-g2-n025",
        "2～6求商小测",
        "mini_quiz",
        25,
        "乘法和除法混排（2～6 口诀范围），看算式选对运算并求出得数。",
        "求积想口诀往前背，求商想「几和几得这个数」。",
        10,
    ),
    quest(
        "pm-g2-n026-practice",
        "pm-g2-n026",
        "想口诀求商（7～9）",
        "practice",
        20,
        "计算除数是 7、8、9 的表内除法，并用乘法验算两题。",
        "商乘除数应当等于被除数。",
        12,
    ),
    quest(
        "pm-g2-n027-explain",
        "pm-g2-n027",
        "乘除是一对好朋友",
        "explain",
        10,
        "由 6×7=42 写出两道相关除法，并说明为什么可以用来互相检查。",
        "积除以一个因数，得到另一个因数。",
    ),
    quest(
        "pm-g2-n028-explain",
        "pm-g2-n028",
        "什么时候用除法",
        "explain",
        10,
        "各举一则「平均分成几份、求每份几个」和「每几个一份、能分几份」的短故事。",
        "已知一共和份数求每份，或已知一共和每份求份数，都用除法。",
    ),
    quest(
        "pm-g2-n028-practice",
        "pm-g2-n028",
        "除法故事练习",
        "practice",
        20,
        "完成平均分与「几个几个地分」故事各两则，并列式；穿插一则该用乘法的干扰故事。",
        "求一共用乘；求每份或份数用除。",
        5,
    ),
    quest(
        "pm-g2-n029-explain",
        "pm-g2-n029",
        "分不完剩下的叫余数",
        "explain",
        10,
        "把 13 块糖平均分给 4 人，说明每人几个、还剩几个，并写出带余数的除法。",
        "余数一定要比除数小，否则还能再分一份。",
    ),
    quest(
        "pm-g2-n029-practice",
        "pm-g2-n029",
        "有余数除法练习",
        "practice",
        20,
        "计算若干有余数的除法，检查余数是否小于除数；夹两道正好分完的题。",
        "先想最接近的口诀，剩下的就是余数。",
        8,
    ),
    quest(
        "pm-g2-n030-practice",
        "pm-g2-n030",
        "表内乘除综合练",
        "practice",
        25,
        "混合表内乘法、表内除法、有余数除法和一则「每份同样多」或「平均分」故事。",
        "先判断是求一共、求每份，还是分不完。",
        12,
    ),
    quest(
        "pm-g2-n030-quiz",
        "pm-g2-n030",
        "表内乘除小测",
        "mini_quiz",
        30,
        "乘除混排加 2 道有余数除法、1 则应用题，正确率达到掌握标准才过关。",
        "可以用互逆当场验算。",
        12,
    ),
    quest(
        "pm-g2-boss-times",
        "pm-g2-n030",
        "关主：表内乘除大闯关",
        "boss",
        90,
        "击败关主条件：①背出指定一行口诀 ②表内乘、除各 5 题 ③一道有余数除法（余数小于除数）④一则用乘或除的短故事。",
        "口诀熟了，求积和求商就是同一张表的两种用法。",
        16,
    ),
    # D
    quest(
        "pm-g2-n031-explain",
        "pm-g2-n031",
        "没有括号谁先算",
        "explain",
        10,
        "比较 8+5−3 和 2×6÷3，说明都是同级运算、要从左往右，并算出得数。",
        "加减是一级，乘除是一级；同级就按书写顺序。",
    ),
    quest(
        "pm-g2-n031-practice",
        "pm-g2-n031",
        "从左往右两步算",
        "practice",
        20,
        "计算加减混合、乘除混合各若干题，写出中间得数。",
        "先算左边一步，再把得数带入右边。",
        8,
    ),
    quest(
        "pm-g2-n032-explain",
        "pm-g2-n032",
        "括号能改变顺序",
        "explain",
        10,
        "比较 10−4+2 和 10−(4+2)，说出得数为什么不同，括号让哪一步先算。",
        "看见小括号，先把括号里面算完。",
    ),
    quest(
        "pm-g2-n032-practice",
        "pm-g2-n032",
        "带括号的两步运算",
        "practice",
        20,
        "计算含小括号的两步式，并与去掉括号后的式子对比得数。",
        "括号里算完再和外面运算。",
        8,
    ),
    quest(
        "pm-g2-n032-quiz",
        "pm-g2-n032",
        "运算顺序小测",
        "mini_quiz",
        30,
        "混合「从左往右」和「先算括号」的两步式，先标出第一步再计算。",
        "先找有没有括号。",
        8,
    ),
    # E
    quest(
        "pm-g2-n033-explain",
        "pm-g2-n033",
        "十个百是一千",
        "explain",
        10,
        "用方块或计数器说明 10 个一百是一千，并从 900 数到 1000，再指出 240、1000。",
        "千位上是 1，就是一千。",
    ),
    quest(
        "pm-g2-n034-practice",
        "pm-g2-n034",
        "万以内读一读写一写",
        "practice",
        20,
        "听数写数、看数读数（万以内），特别注意 305、350、3005、1010、10000。",
        "中间的 0 要读出来；末尾的 0 一般不读。",
        10,
    ),
    quest(
        "pm-g2-n035-explain",
        "pm-g2-n035",
        "千百十个对对齐",
        "explain",
        10,
        "说出 2406 是几个千、几个百、几个十、几个一，并对照计数器的数位。",
        "从右边起：个、十、百、千。",
    ),
    quest(
        "pm-g2-n036-practice",
        "pm-g2-n036",
        "万以内比大小",
        "practice",
        20,
        "比较万以内两个数的大小，先看位数再从最高位比起，填＞＜＝。",
        "位数多的更大；位数相同就一位一位比。",
        10,
    ),
    quest(
        "pm-g2-n037-practice",
        "pm-g2-n037",
        "整百整千口算",
        "practice",
        20,
        "计算 300+400、2000+5000、800−300、9000−4000 等，用「几个百、几个千」来想。",
        "只算有数字的那一位，后面的 0 跟着写。",
        8,
    ),
    quest(
        "pm-g2-n038-explain",
        "pm-g2-n038",
        "接近多少就算大约",
        "explain",
        10,
        "把 198 看成 200、把 312 看成 300，说明「大约」是在找接近的整百，并用来估计 198+312 大概是多少。",
        "估算先看高位，不必算得完全精确。",
    ),
    quest(
        "pm-g2-n038-practice",
        "pm-g2-n038",
        "估一估是否合理",
        "practice",
        20,
        "给几道加减，先估再算或判断别人的得数是否合理（如 390+410 不可能得 70）。",
        "整百相加能很快看出对不对。",
        6,
    ),
    quest(
        "pm-g2-n039-practice",
        "pm-g2-n039",
        "地图综合练",
        "practice",
        25,
        "题型混合：100 以内进退位、表内乘除、有余数、带括号两步式、万以内读写比较、一则估算。",
        "先判断这题在考哪一盏已点亮的灯。",
        12,
    ),
    quest(
        "pm-g2-boss-map",
        "pm-g2-n039",
        "关主：二年级数与运算通关试炼",
        "boss",
        100,
        "最终关主：①两位数进位加、退位减各 2 题 ②表内乘、除各 3 题 ③有余数除法 1 题 ④带小括号的两步式 1 题 ⑤读写并比较两个万以内的数 ⑥用估算判断一道加减是否合理。全部通过即通关本地图。",
        "通关后这张地图记入已通关列表。一年级地图的 100 以内与本地图起点概念衔接，但存档仍按图分别计算，暂无跨地图引擎。",
        18,
    ),
]


META = {
    "id": "pm-g2-numbers",
    "title": "二年级 · 数与运算",
    "subject": "数学",
    "stage": "小学",
    "grade": 2,
    "strand": "数与代数",
    "version": "0.1.0",
    "locale": "zh-CN",
    "start_node_ids": ["pm-g2-n001"],
    "recommended_path_note": "从「100以内组成复习」进入：先打通 100 以内进退位加减，再表内乘法、表内除法（含有余数），然后两步混合运算与小括号，最后衔接万以内数与简单估算。奇数与偶数（n022）为软锁支线。",
    "win_condition": {
        "type": "light_all_nodes_and_bosses",
        "required_node_ids": "all",
        "required_boss_quest_ids": [
            "pm-g2-boss-100",
            "pm-g2-boss-times",
            "pm-g2-boss-map",
        ],
        "summary": "点亮全部知识点，并击败三名关主：一百以内进退位、表内乘除大闯关、地图通关试炼。",
    },
    "content_disclaimer": "知识点与任务为课标/教材目录风格的原创教学大纲与自编提示语，不是任何版本教科书正文或习题的摘录。",
    "description": "小学二年级「数与代数」地图：100 以内加减巩固 → 表内乘除入门 → 混合运算意识 → 万以内数认识与简单估算。与一年级地图概念衔接，但各自独立通关。",
}


SAMPLE_PROGRESS = {
    "player_id": "demo-learner",
    "display_name": "小明",
    "xp_total": 25,
    "current_map_id": "pm-g2-numbers",
    "cleared_map_ids": [],
    "nodes": {
        "pm-g2-n001": {
            "state": "lit",
            "xp_earned": 10,
            "cleared_quest_ids": ["pm-g2-n001-explain"],
            "updated_at": "2026-09-16T10:00:00Z",
        },
        "pm-g2-n002": {
            "state": "available",
            "xp_earned": 0,
            "cleared_quest_ids": [],
            "updated_at": "2026-09-16T10:00:00Z",
        },
        "pm-g2-n004": {
            "state": "learning",
            "xp_earned": 20,
            "cleared_quest_ids": ["pm-g2-n004-practice"],
            "updated_at": "2026-09-16T10:08:00Z",
        },
    },
}


def prereq_edges(nodes: list[dict]) -> list[dict]:
    edges = []
    for n in nodes:
        for src in n["prerequisites"]:
            edges.append(
                {
                    "from": src,
                    "to": n["id"],
                    "type": "prerequisite",
                    "note": f"{src} 需先于 {n['id']}",
                }
            )
    return edges


def dump(path: Path, data) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")


def _assert_field_limits() -> None:
    """Fail fast if learner-facing strings exceed schema limits."""
    for n in NODES:
        assert 1 <= len(n["title"]) <= 40, n["title"]
        assert 8 <= len(n["description"]) <= 160, (n["id"], len(n["description"]), n["description"])
    for q in QUESTS:
        assert 1 <= len(q["title"]) <= 40, q["title"]
        assert 4 <= len(q["prompt"]) <= 400, (q["id"], len(q["prompt"]))
        hint = q.get("success_hint") or ""
        assert len(hint) <= 200, (q["id"], len(hint))


def main() -> None:
    _assert_field_limits()
    OUT.mkdir(parents=True, exist_ok=True)
    edges = prereq_edges(NODES) + EXTRA_EDGES
    dump(OUT / "nodes.json", {"map_id": META["id"], "nodes": NODES})
    dump(OUT / "edges.json", {"map_id": META["id"], "edges": edges})
    dump(OUT / "quests.json", {"map_id": META["id"], "quests": QUESTS})
    dump(OUT / "map.meta.json", META)
    dump(OUT / "player-progress.sample.json", SAMPLE_PROGRESS)


if __name__ == "__main__":
    main()
