"""Build Grade 5 Numbers map JSON from a single source of truth.

Run: python3 scripts/_build_grade5_numbers.py
The generated JSON under maps/primary-math/grade-5-numbers/ is the published content.

Pedagogical spine (人教版/课标风格脉络，自撰短描述，非教材页原文):
  小数乘除系统化（本图自洽，承接四年级小数加减 / 乘除入门概念但不引用跨图 id）
  → 因数与倍数、质数合数
  → 分数的意义、约分通分、分数加减
  → 简易方程入门（软锁支线，不挡终章关主）。
与四年级地图概念衔接（小数加减、小数乘除入门软锁），但节点 id 不跨图引用。
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "maps" / "primary-math" / "grade-5-numbers"

HARD = {"type": "hard_all_prereqs", "allow_teacher_override": False}
SOFT = {"type": "soft_recommended", "allow_teacher_override": True}

MASTERY_CONCEPT = {
    "min_quests_cleared": 1,
    "require_quest_types": ["explain"],
    "review_after_days": 10,
}
MASTERY_SKILL = {
    "min_quests_cleared": 1,
    "min_quiz_accuracy": 0.8,
    "require_quest_types": ["practice"],
    "review_after_days": 7,
}
MASTERY_GATE = {
    "min_quests_cleared": 2,
    "min_quiz_accuracy": 0.85,
    "require_quest_types": ["practice"],
    "review_after_days": 5,
}


def node(
    nid: str,
    title: str,
    difficulty: int,
    prereqs: list[str],
    tags: list[str],
    description: str,
    *,
    unlock: dict | None = None,
    mastery: dict | None = None,
) -> dict:
    return {
        "id": nid,
        "title": title,
        "subject": "数学",
        "stage": "小学",
        "grade": 5,
        "strand": "数与代数",
        "difficulty": difficulty,
        "prerequisites": prereqs,
        "tags": tags,
        "unlock_rule": unlock or HARD,
        "mastery_criteria": mastery or MASTERY_SKILL,
        "description": description,
    }


# --- 37 nodes, teaching order ---
NODES = [
    # A. 小数乘除系统化（本图自洽）
    node(
        "pm-g5-n001",
        "小数乘整数",
        2,
        [],
        ["decimal", "ch-dec-mul", "multiply"],
        "能把小数乘整数看成几个相同小数连加，或先按整数相乘再点上小数点。本图从这里系统学习小数乘除。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-n002",
        "积的小数位数",
        3,
        ["pm-g5-n001"],
        ["decimal", "ch-dec-mul", "place-value"],
        "知道两个因数一共有几位小数，积里通常先点几位小数；末尾的 0 可以按小数性质去掉。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-n003",
        "小数乘小数",
        3,
        ["pm-g5-n002"],
        ["decimal", "ch-dec-mul", "multiply"],
        "会计算小数乘小数：先按整数相乘，再按因数一共的小数位数点上积的小数点。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g5-n004",
        "运算律推广到小数",
        3,
        ["pm-g5-n003"],
        ["decimal", "ch-dec-mul", "laws"],
        "知道整数乘法的交换律、结合律、分配律对小数同样适用，并能用来把小数乘法变得更好算。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-n005",
        "积的近似值",
        3,
        ["pm-g5-n003"],
        ["decimal", "ch-dec-mul", "round"],
        "会按「四舍五入」求积的近似值，保留到指定的十分位、百分位或整数位。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-n006",
        "小数乘法解决问题",
        3,
        ["pm-g5-n003"],
        ["word-problem", "ch-dec-mul", "application"],
        "在「每份同样多、求一共」或「求几倍」的小数短故事里列出乘法算式，并能先估一估。",
    ),
    node(
        "pm-g5-n007",
        "小数除以整数",
        3,
        ["pm-g5-n003"],
        ["decimal", "ch-dec-div", "divide"],
        "会计算小数除以整数：商的小数点与被除数对齐；整数部分不够除时商的整数部分写 0。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g5-n008",
        "一个数除以小数",
        4,
        ["pm-g5-n007"],
        ["decimal", "ch-dec-div", "divide"],
        "除数是小数时，能把除数和被除数的小数点同时向右移动同样位数，转化成除数是整数再除。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g5-n009",
        "商的近似值",
        3,
        ["pm-g5-n008"],
        ["decimal", "ch-dec-div", "round"],
        "除不尽时会根据需要多除一位，再用四舍五入求商的近似值。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-n010",
        "循环小数初步",
        3,
        ["pm-g5-n008"],
        ["decimal", "ch-dec-div", "repeating"],
        "知道有限小数和循环小数，能用循环节上面加小圆点的办法表示循环小数。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-n011",
        "小数四则混合运算",
        4,
        ["pm-g5-n004", "pm-g5-n008"],
        ["decimal", "ch-dec-div", "mixed"],
        "能按先乘除后加减、有括号先算括号的顺序，完成含小数的四则混合运算。",
    ),
    node(
        "pm-g5-n012",
        "小数乘除综合",
        4,
        ["pm-g5-n005", "pm-g5-n006", "pm-g5-n009", "pm-g5-n010", "pm-g5-n011"],
        ["fluency", "ch-dec-div", "boss-gate"],
        "综合小数乘小数、除数是小数、积与商的近似值、循环小数和混合运算。",
        mastery=MASTERY_GATE,
    ),
    # B. 因数与倍数（可与分数线衔接，本图放在小数关主之后）
    node(
        "pm-g5-n013",
        "因数的意义",
        2,
        ["pm-g5-n012"],
        ["factor", "ch-factor", "concept"],
        "在整数乘法里，知道两个乘数都是积的因数；能找出一个数的全部因数。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-n014",
        "倍数的意义",
        2,
        ["pm-g5-n012"],
        ["multiple", "ch-factor", "concept"],
        "知道如果 a×b＝c，那么 c 是 a 的倍数，也是 b 的倍数；能找出一个数的若干个倍数。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-n015",
        "2、5、3的倍数特征",
        3,
        ["pm-g5-n014"],
        ["multiple", "ch-factor", "divisibility"],
        "能根据个位是不是 0、2、4、6、8 判断 2 的倍数，个位是 0 或 5 判断 5 的倍数，各位数字之和判断 3 的倍数。",
    ),
    node(
        "pm-g5-n016",
        "质数与合数",
        3,
        ["pm-g5-n013"],
        ["prime", "ch-factor", "concept"],
        "知道质数只有 1 和它本身两个因数，合数还有别的因数；1 既不是质数也不是合数。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-n017",
        "分解质因数入门",
        3,
        ["pm-g5-n016"],
        ["prime", "ch-factor", "factorize"],
        "能把一个合数写成几个质数相乘的形式，并用短除法做入门练习。",
    ),
    node(
        "pm-g5-n018",
        "最大公因数",
        4,
        ["pm-g5-n013", "pm-g5-n017"],
        ["gcd", "ch-factor"],
        "能找出两个数的公因数，并指出其中最大的一个；会用短除法求最大公因数。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g5-n019",
        "最小公倍数",
        4,
        ["pm-g5-n014", "pm-g5-n017"],
        ["lcm", "ch-factor"],
        "能找出两个数的公倍数，并指出其中最小的一个；会用短除法求最小公倍数。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g5-n020",
        "因数倍数综合",
        4,
        ["pm-g5-n015", "pm-g5-n018", "pm-g5-n019"],
        ["fluency", "ch-factor"],
        "综合判断倍数特征、找出因数、分辨质数合数、求最大公因数和最小公倍数。",
        mastery=MASTERY_GATE,
    ),
    # C. 分数的意义、约分通分
    node(
        "pm-g5-n021",
        "分数与除法",
        2,
        ["pm-g5-n020"],
        ["fraction", "ch-frac", "concept"],
        "知道分数可以表示「把单位 1 平均分成若干份取几份」，也可以表示两个整数相除的商。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-n022",
        "真分数假分数带分数",
        3,
        ["pm-g5-n021"],
        ["fraction", "ch-frac", "improper"],
        "能区分真分数、假分数，并把假分数与整数或带分数互相改写。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-n023",
        "分数的基本性质",
        3,
        ["pm-g5-n022"],
        ["fraction", "ch-frac", "property"],
        "知道分数的分子和分母同时乘或除以一个不为 0 的数，分数的大小不变。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-n024",
        "约分",
        3,
        ["pm-g5-n023"],
        ["fraction", "ch-frac", "reduce"],
        "能用最大公因数把分数化成最简分数，并说明约分前后大小相等。",
    ),
    node(
        "pm-g5-n025",
        "通分",
        4,
        ["pm-g5-n023"],
        ["fraction", "ch-frac", "common-denom"],
        "能用最小公倍数找出几个分数的公分母，把它们化成同分母分数再比较或计算。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g5-n026",
        "分数与小数互化",
        3,
        ["pm-g5-n023"],
        ["fraction", "ch-frac", "decimal"],
        "能把分母是 10、100 或能化成这些数的分数写成小数，也能把有限小数写成分数并约分。",
    ),
    # D. 分数加减
    node(
        "pm-g5-n027",
        "同分母分数加减",
        3,
        ["pm-g5-n022"],
        ["fraction", "ch-frac-ops", "add-sub"],
        "同分母分数相加减，分母不变、分子相加减；得数能约分的要约成最简分数。",
    ),
    node(
        "pm-g5-n028",
        "异分母分数加减",
        4,
        ["pm-g5-n025", "pm-g5-n027"],
        ["fraction", "ch-frac-ops", "add-sub"],
        "异分母分数相加减，先通分再按同分母的办法算，并养成约分的习惯。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g5-n029",
        "分数加减混合运算",
        4,
        ["pm-g5-n024", "pm-g5-n028"],
        ["fraction", "ch-frac-ops", "mixed"],
        "能计算含真分数、带分数的加减混合，需要时先把带分数化成假分数，最后约分。",
    ),
    node(
        "pm-g5-n030",
        "分数加减解决问题",
        3,
        ["pm-g5-n028"],
        ["word-problem", "ch-frac-ops", "application"],
        "在「一共、还剩、比多比少」的短故事里，用分数加减列出算式并求出最简结果。",
    ),
    node(
        "pm-g5-n031",
        "分数加减综合",
        4,
        ["pm-g5-n026", "pm-g5-n029", "pm-g5-n030"],
        ["fluency", "ch-frac-ops", "boss-gate"],
        "综合分数意义、约分通分、异分母加减、互化和应用题。",
        mastery=MASTERY_GATE,
    ),
    # E. 简易方程入门（软锁支线，不挡终章关主）
    node(
        "pm-g5-n032",
        "用字母表示数",
        2,
        ["pm-g5-n012"],
        ["algebra", "ch-eq", "letter"],
        "能用字母表示运算定律、常见数量关系和未知的数，体会字母可以代表许多数。",
        unlock=SOFT,
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-n033",
        "方程的意义",
        2,
        ["pm-g5-n032"],
        ["algebra", "ch-eq", "concept"],
        "知道含有未知数的等式叫做方程，能判断哪些式子是方程，哪些只是等式或算式。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-n034",
        "等式的性质",
        3,
        ["pm-g5-n033"],
        ["algebra", "ch-eq", "property"],
        "知道等式两边同时加、减同一个数，或同时乘、除以一个不为 0 的数，等式仍然成立。",
        mastery=MASTERY_CONCEPT,
    ),
    node(
        "pm-g5-n035",
        "解简易方程",
        4,
        ["pm-g5-n034"],
        ["algebra", "ch-eq", "solve"],
        "能用等式的性质解 x±a＝b、ax＝b、ax±b＝c 这样的简易方程，并检验得数。",
        mastery=MASTERY_GATE,
    ),
    node(
        "pm-g5-n036",
        "列方程解决问题入门",
        4,
        ["pm-g5-n035"],
        ["algebra", "ch-eq", "application"],
        "能在简单数量关系里设未知数、列方程、求解并回看是否符合题意。",
    ),
    # F. 地图综合（方程为软锁，不挡终章关主，通关前仍须点亮）
    node(
        "pm-g5-n037",
        "五年级数与运算综合",
        5,
        ["pm-g5-n012", "pm-g5-n020", "pm-g5-n031"],
        ["synthesis", "ch-final", "boss-gate"],
        "综合小数乘除、因数倍数、分数意义与约分通分、分数加减。方程支线不挡本关，通关前仍须点亮。",
        mastery=MASTERY_GATE,
    ),
]


EXTRA_EDGES = [
    {
        "from": "pm-g5-n001",
        "to": "pm-g5-n002",
        "type": "easily_confused",
        "note": "先按整数乘只是中间步骤；积的小数点要按因数一共有几位小数来点。",
    },
    {
        "from": "pm-g5-n002",
        "to": "pm-g5-n003",
        "type": "related",
        "note": "小数乘小数仍然用「因数一共几位小数，积就先点几位」。",
    },
    {
        "from": "pm-g5-n003",
        "to": "pm-g5-n007",
        "type": "easily_confused",
        "note": "乘法看因数的小数位数点积；除法里商的小数点要与被除数对齐。",
    },
    {
        "from": "pm-g5-n007",
        "to": "pm-g5-n008",
        "type": "easily_confused",
        "note": "除数是小数时，被除数和除数要同时扩大相同倍数，不能只移动一边。",
    },
    {
        "from": "pm-g5-n005",
        "to": "pm-g5-n009",
        "type": "related",
        "note": "积的近似值和商的近似值都用四舍五入，先看题目要保留到哪一位。",
    },
    {
        "from": "pm-g5-n009",
        "to": "pm-g5-n010",
        "type": "easily_confused",
        "note": "求近似值是四舍五入截取；循环小数是除不尽时用循环节表示精确商。",
    },
    {
        "from": "pm-g5-n004",
        "to": "pm-g5-n011",
        "type": "application",
        "note": "运算律可以让小数混合运算先凑整，再按顺序算。",
    },
    {
        "from": "pm-g5-n006",
        "to": "pm-g5-n012",
        "type": "application",
        "note": "小数乘法故事进入乘除综合关。",
    },
    {
        "from": "pm-g5-n013",
        "to": "pm-g5-n014",
        "type": "easily_confused",
        "note": "因数是「谁乘谁得到它」；倍数是「它是谁的几倍」，方向不要说反。",
    },
    {
        "from": "pm-g5-n013",
        "to": "pm-g5-n016",
        "type": "related",
        "note": "看一个数有几个因数，就能分辨它是质数还是合数。",
    },
    {
        "from": "pm-g5-n016",
        "to": "pm-g5-n017",
        "type": "related",
        "note": "分解质因数就是把合数拆成质数相乘。",
    },
    {
        "from": "pm-g5-n018",
        "to": "pm-g5-n019",
        "type": "easily_confused",
        "note": "最大公因数不会比两个数中较小的那个大；最小公倍数不会比它们中较大的那个小。",
    },
    {
        "from": "pm-g5-n018",
        "to": "pm-g5-n024",
        "type": "application",
        "note": "约分时要找分子分母的最大公因数。",
    },
    {
        "from": "pm-g5-n019",
        "to": "pm-g5-n025",
        "type": "application",
        "note": "通分时常取分母的最小公倍数作公分母。",
    },
    {
        "from": "pm-g5-n021",
        "to": "pm-g5-n026",
        "type": "related",
        "note": "分数表示整数相除的商，所以可以和小数互相改写。",
    },
    {
        "from": "pm-g5-n023",
        "to": "pm-g5-n024",
        "type": "easily_confused",
        "note": "基本性质是「同时乘或除以同一个不为 0 的数」；约分是用它化成最简。",
    },
    {
        "from": "pm-g5-n024",
        "to": "pm-g5-n025",
        "type": "easily_confused",
        "note": "约分是缩小分子分母；通分是扩大分子分母，使分母相同。",
    },
    {
        "from": "pm-g5-n027",
        "to": "pm-g5-n028",
        "type": "easily_confused",
        "note": "同分母直接加减分子；异分母必须先通分，不能分母、分子分别加减。",
    },
    {
        "from": "pm-g5-n012",
        "to": "pm-g5-n026",
        "type": "related",
        "note": "小数乘除里见过的有限小数，这里再和分数对照着写。",
    },
    {
        "from": "pm-g5-n028",
        "to": "pm-g5-n030",
        "type": "application",
        "note": "异分母加减用到「一共、还剩」的分数故事。",
    },
    {
        "from": "pm-g5-n033",
        "to": "pm-g5-n034",
        "type": "related",
        "note": "方程是特殊的等式，解方程靠的是等式两边同加同减、同乘同除。",
    },
    {
        "from": "pm-g5-n035",
        "to": "pm-g5-n036",
        "type": "application",
        "note": "会解方程之后，才能在短故事里设未知数并列方程。",
    },
    {
        "from": "pm-g5-n032",
        "to": "pm-g5-n004",
        "type": "related",
        "note": "用字母表示运算律，和「运算律推广到小数」说的是同一件事。",
    },
    {
        "from": "pm-g5-n031",
        "to": "pm-g5-n037",
        "type": "application",
        "note": "分数加减进入终章综合。",
    },
]


def quest(
    qid: str,
    node_id: str,
    title: str,
    qtype: str,
    xp: int,
    prompt: str,
    hint: str,
    items: int | None = None,
) -> dict:
    q = {
        "id": qid,
        "node_id": node_id,
        "title": title,
        "type": qtype,
        "xp": xp,
        "prompt": prompt,
        "success_hint": hint,
    }
    if items is not None:
        q["items_suggested"] = items
    return q


QUESTS = [
    # A
    quest(
        "pm-g5-n001-explain",
        "pm-g5-n001",
        "几个相同的小数",
        "explain",
        10,
        "把 1.2×3 看成 1.2+1.2+1.2，或先算 12×3 再点上小数点。说明积里为什么有一位小数。本图从这里系统学习，不依赖其他地图节点。",
        "小数乘整数：可以先当整数乘，再看因数一共有几位小数。",
    ),
    quest(
        "pm-g5-n001-practice",
        "pm-g5-n001",
        "小数乘整数练",
        "practice",
        20,
        "计算一位或两位小数乘一位整数，如 0.4×5、1.3×4、2.05×6，并说出积的小数点点在哪里。",
        "因数里一共有几位小数，积里通常也先点几位，末尾的 0 可以再去掉。",
        8,
    ),
    quest(
        "pm-g5-n002-explain",
        "pm-g5-n002",
        "因数有几位积就先点几位",
        "explain",
        10,
        "用 0.12×5 说明：0.12 有两位小数，5 没有小数，积先点两位得到 0.60，再去掉末尾 0 写成 0.6。",
        "点完小数点后，末尾的 0 可以按小数性质去掉，中间的 0 不能去。",
    ),
    quest(
        "pm-g5-n002-practice",
        "pm-g5-n002",
        "先点小数点再化简",
        "practice",
        20,
        "给几道小数乘整数，先说出积应有几位小数，再计算；夹两道积末尾有 0 的题。",
        "先点位，再看末尾 0 能不能去掉。",
        8,
    ),
    quest(
        "pm-g5-n003-explain",
        "pm-g5-n003",
        "两个小数相乘",
        "explain",
        10,
        "用 1.2×0.4 说明：先算 12×4＝48，因数一共有两位小数，积是 0.48。积比两个因数都小，是因为都小于 1。",
        "小于 1 的小数相乘，积会更小，这是正常的。",
    ),
    quest(
        "pm-g5-n003-practice",
        "pm-g5-n003",
        "小数乘小数练",
        "practice",
        25,
        "计算小数乘小数，含一位乘一位、一位乘两位，检查积的小数位数和末尾 0。",
        "先当整数乘，再按因数小数位数的和点小数点。",
        8,
    ),
    quest(
        "pm-g5-n003-quiz",
        "pm-g5-n003",
        "小数乘法小测",
        "mini_quiz",
        30,
        "混合小数乘整数、小数乘小数，夹积末尾有 0、积比因数小的情况，正确率达到掌握标准才过关。",
        "积比因数小，常常是因为有一个因数小于 1。",
        8,
    ),
    quest(
        "pm-g5-n004-explain",
        "pm-g5-n004",
        "小数也能用运算律",
        "explain",
        10,
        "用 0.25×3.6×4 说明：可以先算 0.25×4＝1，再乘 3.6。指出交换律、结合律对小数同样成立。",
        "先乘能得到整数或整十的那两个因数。",
    ),
    quest(
        "pm-g5-n004-practice",
        "pm-g5-n004",
        "小数运算律练",
        "practice",
        20,
        "用交换、结合或分配使小数乘法更好算，如 0.125×8×2.4、(1.2+0.8)×3.5。",
        "分配律：和乘一个数，可以拆开分别乘再加。",
        6,
    ),
    quest(
        "pm-g5-n005-explain",
        "pm-g5-n005",
        "积保留到哪一位",
        "explain",
        10,
        "计算 3.14×2.6 后，说明怎样保留到十分位、百分位。指出「约」是近似值，和精确积不一定相等。",
        "看要保留的那一位的下一位，满 5 向前入，不满 5 舍去。",
    ),
    quest(
        "pm-g5-n005-practice",
        "pm-g5-n005",
        "求积的近似值",
        "practice",
        20,
        "先算出小数乘法的积，再按要求保留到整数位、十分位或百分位；夹一道只要精确积的对比题。",
        "题目没说「约」或「保留」，就不要四舍五入。",
        6,
    ),
    quest(
        "pm-g5-n006-explain",
        "pm-g5-n006",
        "每份是小数求一共",
        "explain",
        10,
        "每千克 12.5 元，买 3.2 千克。用「每份同样多、求一共」说明为什么用乘法，并先估大约多少元。",
        "先找出「每份是多少」和「有几份」，两数都可以是小数。",
    ),
    quest(
        "pm-g5-n006-practice",
        "pm-g5-n006",
        "小数乘法故事",
        "practice",
        20,
        "完成「每份同样多求一共」和「求一个数的几倍」小数短故事，并列式计算；其中一则先估再算。",
        "估算时可把小数看成接近的整数或一位小数。",
        4,
    ),
    quest(
        "pm-g5-n007-explain",
        "pm-g5-n007",
        "商的小数点对齐",
        "explain",
        10,
        "用 1.2÷3＝0.4 说明：竖式里商的小数点要和被除数的小数点对齐。整数部分不够除时先商 0。",
        "除到小数部分，先在商上点好小数点，再继续往下除。",
    ),
    quest(
        "pm-g5-n007-practice",
        "pm-g5-n007",
        "小数除以整数练",
        "practice",
        20,
        "计算小数除以整数，如 2.8÷4、0.9÷3、6.45÷5，检查商的小数点；夹一道整数部分不够除的题。",
        "不够除就商 0，不要把小数点丢掉。",
        8,
    ),
    quest(
        "pm-g5-n008-explain",
        "pm-g5-n008",
        "同时扩大变成除以整数",
        "explain",
        10,
        "把 3.6÷0.4 看成 36÷4：除数、被除数的小数点都向右移一位。说明两边扩大相同倍数，商不变。",
        "除数变成整数后，再按小数除以整数来算。",
    ),
    quest(
        "pm-g5-n008-practice",
        "pm-g5-n008",
        "除数是小数练",
        "practice",
        25,
        "计算一个数除以小数，含被除数位数不够要补 0 的情况，如 2.4÷0.12、1.8÷0.5。",
        "移动位数以除数为准，被除数位数不够就在末尾补 0。",
        8,
    ),
    quest(
        "pm-g5-n008-quiz",
        "pm-g5-n008",
        "小数除法小测",
        "mini_quiz",
        30,
        "混合小数除以整数、除数是小数，正确率达到掌握标准才过关。",
        "先问：除数是不是整数？不是就先同时移动小数点。",
        8,
    ),
    quest(
        "pm-g5-n009-explain",
        "pm-g5-n009",
        "除不尽就多除一位",
        "explain",
        10,
        "计算 2÷3，说明要保留到百分位时须除到千分位再四舍五入。指出这是近似商。",
        "想保留到哪一位，就多除出下一位来决定入还是舍。",
    ),
    quest(
        "pm-g5-n009-practice",
        "pm-g5-n009",
        "求商的近似值",
        "practice",
        20,
        "给几道除不尽的小数除法，按要求保留到十分位或百分位；夹一道除得尽的对比题。",
        "除得尽就写精确商，不要硬四舍五入。",
        6,
    ),
    quest(
        "pm-g5-n010-explain",
        "pm-g5-n010",
        "循环节上面加点",
        "explain",
        10,
        "用 1÷3＝0.333… 说明循环小数，并写成 0.3 上面加一点。再指出 0.25 是有限小数，除得尽。",
        "从哪几位开始循环，就在循环节的首尾数字上加小圆点。",
    ),
    quest(
        "pm-g5-n010-practice",
        "pm-g5-n010",
        "认出循环小数",
        "practice",
        15,
        "判断几道除法的商是有限小数还是循环小数，并把循环小数用循环节表示。",
        "同一数字或同一组数字不断重复，就是循环。",
        6,
    ),
    quest(
        "pm-g5-n011-practice",
        "pm-g5-n011",
        "小数混合运算练",
        "practice",
        25,
        "计算含小数加减乘除、小括号的混合运算，写出每一步的中间得数；可选用运算律简便的一题。",
        "没有括号先乘除后加减；同级从左往右。",
        6,
    ),
    quest(
        "pm-g5-n012-practice",
        "pm-g5-n012",
        "小数乘除综合练",
        "practice",
        25,
        "混合小数乘小数、除数是小数、积或商的近似值、循环小数、一则混合运算和一则应用题。",
        "先判断这题要精确得数，还是近似值，还是在讲循环。",
        12,
    ),
    quest(
        "pm-g5-n012-quiz",
        "pm-g5-n012",
        "小数乘除小测",
        "mini_quiz",
        30,
        "乘除混排加 1 道近似值、1 道除数是小数、1 道混合运算，正确率达到掌握标准才过关。",
        "点错一位小数点，得数会差十倍，可先估数量级。",
        10,
    ),
    quest(
        "pm-g5-boss-decimal",
        "pm-g5-n012",
        "关主：小数乘除大闯关",
        "boss",
        90,
        "击败关主条件：①小数乘小数 1 题 ②小数除以整数 1 题 ③除数是小数 1 题 ④求积或商的近似值 1 题 ⑤一道小数四则混合 ⑥一则用乘或除的短故事。",
        "先对齐小数点或按位数点积，除数是小数要两边一起扩大。",
        12,
    ),
    # B
    quest(
        "pm-g5-n013-explain",
        "pm-g5-n013",
        "谁乘谁得到它",
        "explain",
        10,
        "因为 3×4＝12，所以 3 和 4 都是 12 的因数。说出 12 的全部因数，并说明 1 和它本身一定是因数。",
        "成对出现：1 和 12、2 和 6、3 和 4。",
    ),
    quest(
        "pm-g5-n013-practice",
        "pm-g5-n013",
        "找出全部因数",
        "practice",
        20,
        "写出若干数（如 18、20、7、1）的全部因数，并指出哪个数的因数只有两个。",
        "从小到大试除，试到平方根附近就可以成对写完。",
        6,
    ),
    quest(
        "pm-g5-n014-explain",
        "pm-g5-n014",
        "它是谁的几倍",
        "explain",
        10,
        "因为 3×4＝12，所以 12 是 3 的倍数，也是 4 的倍数。说出 3 的前几个倍数，并说明倍数有无数个。",
        "0 是任何自然数的倍数；一个数的倍数里最小的非 0 倍数是它本身。",
    ),
    quest(
        "pm-g5-n014-practice",
        "pm-g5-n014",
        "写出若干倍数",
        "practice",
        20,
        "写出 4、5、8 的前几个倍数；判断 36 是不是 6 的倍数、是不是 8 的倍数。",
        "看能不能整除：能整除就是倍数。",
        8,
    ),
    quest(
        "pm-g5-n015-explain",
        "pm-g5-n015",
        "看个位、看各位之和",
        "explain",
        10,
        "说明：个位是偶数就是 2 的倍数；个位是 0 或 5 就是 5 的倍数；各位数字加起来是 3 的倍数，它就是 3 的倍数。",
        "2 和 5 看个位就够；3 要看各位数字的和。",
    ),
    quest(
        "pm-g5-n015-practice",
        "pm-g5-n015",
        "判断倍数特征",
        "practice",
        20,
        "判断一些数是不是 2、5、3 的倍数，夹「既是 2 又是 5 的倍数」和「只是 3 的倍数」。",
        "既是 2 又是 5 的倍数，个位一定是 0。",
        10,
    ),
    quest(
        "pm-g5-n016-explain",
        "pm-g5-n016",
        "因数只有两个还是更多",
        "explain",
        10,
        "比较 7 和 8：7 只有 1 和 7 两个因数，是质数；8 还有 2、4，是合数。特别说明 1 为什么两个都不是。",
        "质数：两个因数；合数：两个以上因数；1：只有一个因数。",
    ),
    quest(
        "pm-g5-n016-practice",
        "pm-g5-n016",
        "圈出质数合数",
        "practice",
        20,
        "在 1 到 20 里区分质数、合数和 1；再判断 21、29、1、9 各是什么。",
        "先看 2、3、5、7 能不能整除，能整除且不是它本身就是合数。",
        10,
    ),
    quest(
        "pm-g5-n017-explain",
        "pm-g5-n017",
        "拆成质数相乘",
        "explain",
        10,
        "用短除法把 12 写成 2×2×3，把 18 写成 2×3×3。说明每一层除以的都是质数。",
        "每次都用最小的质数去除，直到商是质数。",
    ),
    quest(
        "pm-g5-n017-practice",
        "pm-g5-n017",
        "分解质因数练",
        "practice",
        20,
        "把若干合数分解质因数，写成相乘的形式；夹一个质数说明它本身已经是质因数。",
        "质数不必再分解。",
        6,
    ),
    quest(
        "pm-g5-n018-explain",
        "pm-g5-n018",
        "公共的因数里最大的",
        "explain",
        10,
        "找出 12 和 18 的全部公因数，指出最大公因数是 6。再用短除法验一次。",
        "公因数是两边都有的因数；最大的那一个叫最大公因数。",
    ),
    quest(
        "pm-g5-n018-practice",
        "pm-g5-n018",
        "求最大公因数",
        "practice",
        25,
        "求几组数的最大公因数，含互质（最大公因数是 1）的一组。",
        "互质不一定都是质数，只要没有 1 以外的公因数。",
        6,
    ),
    quest(
        "pm-g5-n019-explain",
        "pm-g5-n019",
        "公共的倍数里最小的",
        "explain",
        10,
        "写出 4 和 6 的若干公倍数，指出最小公倍数是 12。再用短除法验一次。",
        "公倍数有无数个；其中最小的那个叫最小公倍数。",
    ),
    quest(
        "pm-g5-n019-practice",
        "pm-g5-n019",
        "求最小公倍数",
        "practice",
        25,
        "求几组数的最小公倍数，含两个数互质（最小公倍数等于两数之积）的一组。",
        "互质时，最小公倍数就是两数相乘。",
        6,
    ),
    quest(
        "pm-g5-n020-practice",
        "pm-g5-n020",
        "因数倍数综合练",
        "practice",
        25,
        "混合：写出因数、判断倍数特征、圈质数合数、求最大公因数和最小公倍数。",
        "先分清题目要的是因数、倍数、质数，还是公因数/公倍数。",
        10,
    ),
    quest(
        "pm-g5-n020-quiz",
        "pm-g5-n020",
        "因数倍数小测",
        "mini_quiz",
        30,
        "特征判断、质数合数、最大公因数、最小公倍数各至少一题，正确率达到掌握标准才过关。",
        "1 既不是质数也不是合数，不要漏看。",
        8,
    ),
    # C
    quest(
        "pm-g5-n021-explain",
        "pm-g5-n021",
        "平均分也可以写成除法",
        "explain",
        10,
        "把一张纸平均分成 5 份取 2 份，是 2/5；也可以说 2÷5＝2/5。指出分数线和除号是一家。",
        "分母是平均分的份数，分子是取的份数；也等于分子除以分母。",
    ),
    quest(
        "pm-g5-n021-practice",
        "pm-g5-n021",
        "分数和除法对照",
        "practice",
        15,
        "在「平均分取几份」的图和「两个整数相除」之间来回写分数，如 3÷4＝3/4。",
        "除号可以写成分数线。",
        8,
    ),
    quest(
        "pm-g5-n022-explain",
        "pm-g5-n022",
        "分子分母谁大谁小",
        "explain",
        10,
        "说明真分数小于 1，假分数大于或等于 1。把 7/4 写成 1 又 3/4，把 2 又 1/3 写成 7/3。",
        "带分数＝整数部分 + 真分数部分；假分数分子≥分母。",
    ),
    quest(
        "pm-g5-n022-practice",
        "pm-g5-n022",
        "真假带分数改写",
        "practice",
        20,
        "判断真分数、假分数，并完成假分数与带分数、整数的互相改写。",
        "假分数化带分数：分子除以分母，商是整数部分，余数是新分子。",
        8,
    ),
    quest(
        "pm-g5-n023-explain",
        "pm-g5-n023",
        "同时乘除大小不变",
        "explain",
        10,
        "用涂色图说明 1/2＝2/4＝3/6：分子分母同时乘 2 或 3，大小不变。再说明不能乘 0。",
        "0 不能做除数，也不能让分母变成 0。",
    ),
    quest(
        "pm-g5-n023-practice",
        "pm-g5-n023",
        "写出相等的分数",
        "practice",
        20,
        "根据分数的基本性质填空，写出与 2/3、3/4 相等的分数；判断哪一步乘错或除错。",
        "分子分母必须乘（或除以）同一个不为 0 的数。",
        8,
    ),
    quest(
        "pm-g5-n024-explain",
        "pm-g5-n024",
        "化成最简分数",
        "explain",
        10,
        "把 12/18 的分子分母同时除以最大公因数 6，得到 2/3。说明最简分数的分子分母互质。",
        "能一次除以最大公因数，就不必一次次约。",
    ),
    quest(
        "pm-g5-n024-practice",
        "pm-g5-n024",
        "约分练",
        "practice",
        20,
        "把若干分数约成最简分数，含已经是最简的一题作对比。",
        "约完后检查分子分母还能不能再同时除以同一个数。",
        8,
    ),
    quest(
        "pm-g5-n025-explain",
        "pm-g5-n025",
        "分母变得相同",
        "explain",
        10,
        "比较 1/2 和 1/3：取 2 和 3 的最小公倍数 6 作公分母，写成 3/6 和 2/6。说明通分后大小不变。",
        "公分母通常取分母的最小公倍数，分子要跟着扩大同样倍数。",
    ),
    quest(
        "pm-g5-n025-practice",
        "pm-g5-n025",
        "通分再比大小",
        "practice",
        25,
        "把几组异分母分数通分，并比较大小；夹一道已经同分母的对比题。",
        "先求分母的最小公倍数，再把每个分数化成这个分母。",
        6,
    ),
    quest(
        "pm-g5-n025-quiz",
        "pm-g5-n025",
        "约分通分小测",
        "mini_quiz",
        30,
        "约分、通分、用通分比大小各至少两题，正确率达到掌握标准才过关。",
        "约分是除，通分是乘，方向不要反。",
        8,
    ),
    quest(
        "pm-g5-n026-explain",
        "pm-g5-n026",
        "十分之几就是一位小数",
        "explain",
        10,
        "说明 3/10＝0.3、7/100＝0.07；再把 0.25 写成 25/100 并约成 1/4。分母不是 10、100 时可以先通分或去除。",
        "有限小数都能写成分母是 10、100、1000… 的分数。",
    ),
    quest(
        "pm-g5-n026-practice",
        "pm-g5-n026",
        "分数小数互化练",
        "practice",
        20,
        "分数改小数、小数改分数并约分；夹一道分母是 4、5、8 的分数。",
        "分母是 4、5、8 时，可先化成 10、100 再写小数，或直接除。",
        8,
    ),
    # D
    quest(
        "pm-g5-n027-explain",
        "pm-g5-n027",
        "分母不变分子加减",
        "explain",
        10,
        "用 2/5+1/5＝3/5 说明：同样大的一份，取 2 份再取 1 份就是 3 份。3/5−1/5 同理。",
        "同分母：只加减分子，分母照抄；能约分要约。",
    ),
    quest(
        "pm-g5-n027-practice",
        "pm-g5-n027",
        "同分母加减练",
        "practice",
        20,
        "计算同分母分数加减，含得数需要约分、得数是假分数要化带分数的情况。",
        "最后看一眼：能不能约分，是不是大于 1。",
        8,
    ),
    quest(
        "pm-g5-n028-explain",
        "pm-g5-n028",
        "先通分再加减",
        "explain",
        10,
        "计算 1/2+1/3：先通分成 3/6+2/6＝5/6。强调不能把分母相加当新分母。",
        "异分母必须先变成同样大的一份，才能把份数加起来。",
    ),
    quest(
        "pm-g5-n028-practice",
        "pm-g5-n028",
        "异分母加减练",
        "practice",
        25,
        "计算异分母分数加减，含带分数入门一题；得数要约分成最简。",
        "带分数可先化成假分数，或整数部分与分数部分分开算。",
        8,
    ),
    quest(
        "pm-g5-n028-quiz",
        "pm-g5-n028",
        "分数加减小测",
        "mini_quiz",
        30,
        "混合同分母、异分母、需要约分的加减，正确率达到掌握标准才过关。",
        "先看分母是否相同，不同就先通分。",
        8,
    ),
    quest(
        "pm-g5-n029-practice",
        "pm-g5-n029",
        "分数加减混合练",
        "practice",
        25,
        "计算含真分数、带分数的加减混合，从左往右或先算括号，最后约分。",
        "带分数化假分数后，分母不同仍要通分。",
        6,
    ),
    quest(
        "pm-g5-n030-explain",
        "pm-g5-n030",
        "故事里的分数加减",
        "explain",
        10,
        "一段路先走了 1/3，又走了 1/6。说明「一共走了几分之几」用加法，还剩几分之几用减法（把这段路看作单位 1）。",
        "先找到单位 1，再看是合起来还是去掉、比较。",
    ),
    quest(
        "pm-g5-n030-practice",
        "pm-g5-n030",
        "分数加减故事",
        "practice",
        20,
        "完成「一共、还剩、比多」的分数短情境各一则，并列式求出最简结果。",
        "结果是假分数时，看题目要不要写成带分数。",
        4,
    ),
    quest(
        "pm-g5-n031-practice",
        "pm-g5-n031",
        "分数加减综合练",
        "practice",
        25,
        "混合：真假带分数改写、约分通分、异分母加减、分数小数互化、一则应用题。",
        "先判断这题在考哪一盏已点亮的灯。",
        12,
    ),
    quest(
        "pm-g5-n031-quiz",
        "pm-g5-n031",
        "分数加减综合小测",
        "mini_quiz",
        30,
        "约分或通分、异分母加减、互化、应用题各至少一题，正确率达到掌握标准才过关。",
        "得数记得约分；互化时分母要对准 10、100。",
        10,
    ),
    quest(
        "pm-g5-boss-fraction",
        "pm-g5-n031",
        "关主：分数加减大闯关",
        "boss",
        90,
        "击败关主条件：①假分数与带分数互化 1 题 ②约分 1 题 ③通分后比较或计算 1 题 ④异分母加减 2 题 ⑤分数与小数互化 1 题 ⑥一则分数加减短故事。",
        "通分用最小公倍数，算完要约成最简。",
        12,
    ),
    # E
    quest(
        "pm-g5-n032-explain",
        "pm-g5-n032",
        "字母可以代表许多数",
        "explain",
        10,
        "用 a+b＝b+a 表示加法交换律；用 3x 表示 3 个 x 相加。说明字母在不同问题里可以代表不同的数。",
        "字母表示数，数字和字母相乘常常把数字写在前面，乘号可省略。",
    ),
    quest(
        "pm-g5-n032-practice",
        "pm-g5-n032",
        "用字母写一写",
        "practice",
        15,
        "用字母表示运算律、正方形周长、或「比某个数多 5」；并指出 2a 表示什么。",
        "2a 就是 2×a；a×a 可以写成 a²，本图入门阶段会读即可。",
        6,
    ),
    quest(
        "pm-g5-n033-explain",
        "pm-g5-n033",
        "含未知数的等式",
        "explain",
        10,
        "判断 3+5＝8、x+5＝8、x+5 哪个是方程：必须既是等式，又含有未知数。",
        "算式没有等号，不是方程；等式里没有未知数，也不是方程。",
    ),
    quest(
        "pm-g5-n033-practice",
        "pm-g5-n033",
        "哪些是方程",
        "practice",
        15,
        "从一组式子里挑出方程，并说明其余为什么不是。",
        "看两样：有没有等号，有没有未知数。",
        8,
    ),
    quest(
        "pm-g5-n034-explain",
        "pm-g5-n034",
        "两边同时变等式仍成立",
        "explain",
        10,
        "天平两边同样重，两边同时加 2 或同时乘 3，仍然平衡。对应到等式：两边同时加、减、乘、除（除数不为 0），等式仍成立。",
        "只能两边做同样的运算；除数、乘数都不能是 0。",
    ),
    quest(
        "pm-g5-n034-practice",
        "pm-g5-n034",
        "等式性质练",
        "practice",
        20,
        "根据等式的性质填空或判断对错，如 从 a＝b 得到 a+3＝b+3、a÷2＝b÷2。",
        "两边必须同时、同样地变。",
        6,
    ),
    quest(
        "pm-g5-n035-explain",
        "pm-g5-n035",
        "让未知数单独在一边",
        "explain",
        10,
        "解 x+8＝20：两边减 8，得 x＝12。解 3x＝12：两边除以 3。解 2x+5＝13：先两边减 5，再除以 2。最后代回去检验。",
        "目标是把未知数单独留在等号一边。",
    ),
    quest(
        "pm-g5-n035-practice",
        "pm-g5-n035",
        "解简易方程练",
        "practice",
        25,
        "解 x±a＝b、ax＝b、ax±b＝c 各若干题，并至少检验两题。",
        "有加减先去掉加减，再去掉未知数前面的乘数。",
        8,
    ),
    quest(
        "pm-g5-n035-quiz",
        "pm-g5-n035",
        "解方程小测",
        "mini_quiz",
        30,
        "混合三类简易方程，正确率达到掌握标准才过关；其中至少一题要写出检验。",
        "把得数代入原方程，左右两边要相等。",
        8,
    ),
    quest(
        "pm-g5-n036-explain",
        "pm-g5-n036",
        "设未知数列方程",
        "explain",
        10,
        "一个数的 3 倍少 4 等于 11。设这个数是 x，列出 3x−4＝11，解出后再用原话检查。",
        "先用一句话写出数量关系，再换成带 x 的等式。",
    ),
    quest(
        "pm-g5-n036-practice",
        "pm-g5-n036",
        "列方程入门故事",
        "practice",
        20,
        "完成「比一个数多、少」「一个数的几倍」短故事，设未知数、列方程、求解并回看题意。",
        "求出来的数要符合题目里的单位和实际情况。",
        4,
    ),
    # F
    quest(
        "pm-g5-n037-practice",
        "pm-g5-n037",
        "地图综合练",
        "practice",
        25,
        "题型混合：小数乘除、积或商的近似值、因数或倍数特征、最大公因数或最小公倍数、约分通分、异分母加减。",
        "先判断这题在考哪一盏已点亮的灯。",
        12,
    ),
    quest(
        "pm-g5-boss-map",
        "pm-g5-n037",
        "关主：五年级数与运算通关试炼",
        "boss",
        100,
        "最终关主：①小数乘或除 1 题 ②求近似值或识别循环小数 1 题 ③因数倍数或质数合数 1 题 ④最大公因数或最小公倍数 1 题 ⑤约分或通分 1 题 ⑥异分母加减 1 题。全部通过即通关本地图。",
        "通关后这张地图记入已通关列表。四年级的小数加减与乘除入门和本地图起点在概念上衔接，但存档仍按图分别计算，暂无跨地图引擎。",
        16,
    ),
]


META = {
    "id": "pm-g5-numbers",
    "title": "五年级 · 数与运算",
    "subject": "数学",
    "stage": "小学",
    "grade": 5,
    "strand": "数与代数",
    "version": "0.1.0",
    "locale": "zh-CN",
    "start_node_ids": ["pm-g5-n001"],
    "recommended_path_note": "从「小数乘整数」进入：先打通小数乘除（含积与商的近似值、循环小数、混合运算），再因数倍数与质数合数，然后分数意义、约分通分与分数加减。简易方程（n032）为软锁支线，不挡终章关主，通关前仍须点亮。",
    "win_condition": {
        "type": "light_all_nodes_and_bosses",
        "required_node_ids": "all",
        "required_boss_quest_ids": [
            "pm-g5-boss-decimal",
            "pm-g5-boss-fraction",
            "pm-g5-boss-map",
        ],
        "summary": "点亮全部知识点，并击败三名关主：小数乘除、分数加减、地图通关试炼。",
    },
    "content_disclaimer": "知识点与任务为课标/教材目录风格的原创教学大纲与自编提示语，不是任何版本教科书正文或习题的摘录。",
    "description": "小学五年级「数与代数」地图：小数乘除 → 因数倍数 → 分数意义与加减；简易方程为软锁支线。与四年级地图概念衔接，但各自独立通关。",
}


SAMPLE_PROGRESS = {
    "player_id": "demo-learner",
    "display_name": "小明",
    "xp_total": 20,
    "current_map_id": "pm-g5-numbers",
    "cleared_map_ids": [],
    "nodes": {
        "pm-g5-n001": {
            "state": "lit",
            "xp_earned": 10,
            "cleared_quest_ids": ["pm-g5-n001-explain"],
            "updated_at": "2026-09-17T10:00:00Z",
        },
        "pm-g5-n002": {
            "state": "learning",
            "xp_earned": 10,
            "cleared_quest_ids": ["pm-g5-n002-explain"],
            "updated_at": "2026-09-17T10:08:00Z",
        },
    },
}


def prereq_edges(nodes: list[dict]) -> list[dict]:
    edges = []
    for n in nodes:
        for src in n["prerequisites"]:
            edges.append(
                {
                    "from": src,
                    "to": n["id"],
                    "type": "prerequisite",
                    "note": f"{src} 需先于 {n['id']}",
                }
            )
    return edges


def dump(path: Path, data) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")


def _assert_field_limits() -> None:
    """Fail fast if learner-facing strings exceed schema limits."""
    for n in NODES:
        assert 1 <= len(n["title"]) <= 40, n["title"]
        assert 8 <= len(n["description"]) <= 160, (n["id"], len(n["description"]), n["description"])
    for q in QUESTS:
        assert 1 <= len(q["title"]) <= 40, q["title"]
        assert 4 <= len(q["prompt"]) <= 400, (q["id"], len(q["prompt"]))
        hint = q.get("success_hint") or ""
        assert len(hint) <= 200, (q["id"], len(hint))
    for e in EXTRA_EDGES:
        note = e.get("note") or ""
        assert len(note) <= 120, (e["from"], e["to"], len(note), note)
    covered = {q["node_id"] for q in QUESTS}
    missing = [n["id"] for n in NODES if n["id"] not in covered]
    assert not missing, f"nodes without quests: {missing}"


def main() -> None:
    _assert_field_limits()
    OUT.mkdir(parents=True, exist_ok=True)
    edges = prereq_edges(NODES) + EXTRA_EDGES
    dump(OUT / "nodes.json", {"map_id": META["id"], "nodes": NODES})
    dump(OUT / "edges.json", {"map_id": META["id"], "edges": edges})
    dump(OUT / "quests.json", {"map_id": META["id"], "quests": QUESTS})
    dump(OUT / "map.meta.json", META)
    dump(OUT / "player-progress.sample.json", SAMPLE_PROGRESS)


if __name__ == "__main__":
    main()
